### ISSUE TITLE
EnoughDataToQuery not functional?

### ISSUE THREAD

**Issue by jbienzms** [Azure/azure-spatial-anchors-samples#10]
**AzureSpatialAnchorsDemoWrapper** provides a property called **EnoughDataToCreate**. This property looks at the **SessionStatusIndicator** of **RecommendedForCreate** and checks to make sure it's above 1.0. This is a great indicator that enough data has been gathered to successfully create an anchor.

Under the covers, **SessionStatusIndicators** are filled in during **CloudSpatialAnchorSession_SessionUpdated**. However, the only two values that are captured in that handler are **args.Status.ReadyForCreateProgress** and **args.Status.RecommendedForCreateProgress**.

There does not appear to be any field exposed in **SessionUpdatedEventArgs** that describes how prepared the system is to execute a query. And it does not appear that **AzureSpatialAnchorsDemoWrapper.EnoughDataToQuery** provides a meaningful value.

Should the application wait for any particular condition before attempting to execute a query? Or if a query can be executed at any time, should the **EnoughDataToQuery** property just be removed?

**Comment by vriveras** [comment]
Thank you for your feedback. Yes this property is not needed anymore in the samples. The next version of the sample already address this.
