### ISSUE TITLE
[Question] offline working

### ISSUE THREAD

**Issue by KSemenenko** [Azure/azure-spatial-anchors-samples#101]
Does it work offline?
Does it work with bad gps communication?

**Comment by pjar-msft** [comment]
Azure Spatial Anchors does not work offline.   If you would like to post this as a feedback @ [Azure Spatial Anchors Feedback](https://feedback.azure.com/forums/919252-azure-spatial-anchors), this will allow the community to upvote and for the product team to include into their plans.

GPS can be [supplemented with WiFi and Bluetooth sensor data](https://docs.microsoft.com/en-us/azure/spatial-anchors/concepts/coarse-reloc); some platforms like HoloLens don't use GPS at all.

**Comment by efsjouw** [comment]
Could you somehow work around this by using the WorldAnchorManager located class in the SDK/Experimental? You could set this to persistent and then save a world anchor on the position of the found asa anchor, so you will at least have to locate it once before going offline.

**Comment by craigktreasure** [comment]
@pjar-msft is right. The product does not work offline at this time. Providing feedback or upvoting an existing request at the feedback link would be the right thing to do.

As for the question about bad GPS data, i'm not sure what you mean by "bad gps communication". You can refer to the documentation for [Coarse Relocalization](https://docs.microsoft.com/azure/spatial-anchors/concepts/coarse-reloc) to understand how GPS data is used when using the Coarse relocalization feature.
