### ISSUE TITLE
Ability to know when an anchor is created/deleted outside of app

### ISSUE THREAD

**Issue by kforshier** [Azure/azure-spatial-anchors-samples#102]
Is there anyway to know when an anchor has been created/updated/deleted outside of the app that is doing it? For example, if device A creates an anchor, how do I let device B know about it? Do I need to roll my own solution or is there something provided? I've tried searching around the monitoring capabilities in azure, but it doesn't seem like spatial anchor accounts are included in those, or have any alerts associated to them.

**Comment by julianparismorgan** [comment]
You'll need to write your own service to handle this. As an example, you can check out this tutorial on how to use CosmosDB with Azure Spatial Anchors. You'll then need to add some more logic to call to other clients with a notification that a new anchor has been created. 

https://docs.microsoft.com/en-us/azure/spatial-anchors/tutorials/tutorial-share-anchors-across-devices?tabs=VS%2CAndroid
