### ISSUE TITLE
Unity for iOS: Missing/Wrong Bluetooth Purpose String

### ISSUE THREAD

**Issue by TobiasPott** [Azure/azure-spatial-anchors-samples#104]
Hi there,

I'm currently developing an application using the version 2.0 of the ASA SDK for Unity and faced a minor issue when I tried to upload it to the AppStoreConnect website to distribute it using Testflight.

During processing of my uploaded application package Apple found an issue regarding the bluetooth purpose string which was embedded into the app.
The notification I recieved was the following:

> ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSBluetoothPeripheralUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more 

As our app is based on the example project and still contains the "InjectPermissionsBuildProcessing.cs" script a purpose for bluetooth is added by the post build script. Obviously something is required as the coarse localisation feature can use bluetooth. 

At first I thought sth different was wrong as I remembered the post build script to add the description for bluetooth and I wasn't aware that there was a different one required for detecting bluetooth peripherals (e.g. token). 
I'm not that into the latest changes and it could be possible that the requirement and the usage description stated in the message from Apple is fairly new but unless I added it, Apple won't allow me to upload the application and reject any binary.

Thus said, this is not an technical issue with the SDK or the service but a request regarding the examples to include setting the "NSBluetoothPeripheralUsageDescription" value on post build processing.
I'm not sure whether the "NSBluetoothAlwaysUsageDescription" is still required when the above is added, but I have no indication that it can be left out.

My current solution is simply adding another line to the build post processing script.
```        
/// <summary>
/// Adds the "Bluetooth Always Usage Description" property to Info.
/// </
/// <param name="buildOutputPath">Build output path.</
private static void AddBluetoothUsageDescription(string 
{
#if UNITY_IOS
            string infoPlistPath = Path.Combine(buildOutputPath, "Info.plist");
            var propertyList = new PlistDocument();
            propertyList.ReadFromFile(infoPlistPath);
            propertyList.root.SetString(
                "NSBluetoothAlwaysUsageDescription",
                "This application uses bluetooth to find nearby beacons.");
// following line was added
            propertyList.root.SetString(
                "NSBluetoothPeripheralUsageDescription",
                "This application uses bluetooth to find nearby beacons.");
            propertyList.WriteToFile(infoPlistPath);
#endif 
}
```

I think an additional hint on this would be helpful or an addition to the script in the samples so people know what might be required.

Best Regards

**Comment by julianparismorgan** [comment]
Hi @TobiasPott, thanks for letting us know! We're looking into this, and will let you know when we have updates (internal issue #24655317).

**Comment by TobiasPott** [comment]
Hi @julianparismorgan 
thank you very much for your response, looking forward to your updates.

**Comment by vincentfretin** [comment]
SDK 2.2.0 seems to have included NSBluetoothPeripheralUsageDescription
https://github.com/Azure/azure-spatial-anchors-samples/commit/975594023dbbe5b065cde766787ba7ff3f05329d#diff-e28e973db1f1ba052e16bc91b8b5b387R169
