### ISSUE TITLE
Releases should have migration instructions for breaking changes

### ISSUE THREAD

**Issue by chrisfromwork** [Azure/azure-spatial-anchors-samples#105]
Releases thus far seem to have done a good job of calling out what breaking changes have occurred; however, its unclear how to fix things to consume these breaking changes. It would be appreciated if future releases could call out what needs to be done to consume breaking changes.

**Comment by craigktreasure** [comment]
Good know. Thanks for the suggestion! We'll try to be better about that in the future.
