### ISSUE TITLE
Java initialization freezes / runs indefinitely for Android (8.1)

### ISSUE THREAD

**Issue by rafek** [Azure/azure-spatial-anchors-samples#106]
I'm on Android 8.1 and I successfully run Android sample on my phone. Started implementing my solution using ASA 2.0 and on both HL1 and iOS platforms everything worked as expected but for Android the app fails silently on:

```java
if (!javaInitialized)
{
    // Create a TaskCompletionSource that we can use to know when
    // the Java plugin has completed initialization on the Android
    // thread.
    TaskCompletionSource<bool> pluginInit = new TaskCompletionSource<bool>();

    // Make sure ARCore is running. This code must be executed
    // on a Java thread provided by Android.
    AndroidHelper.Instance.DispatchUiThread(unityActivity =>
    {
        // Create the plugin
        using (AndroidJavaClass cloudServices = new AndroidJavaClass("com.microsoft.CloudServices"))
        {
            // Initialize the plugin
            cloudServices.CallStatic("initialize", unityActivity);

            // Update static variable to say that the plugin has been initialized
            javaInitialized = true;

            // Set the task completion source so the CreateSession method can
            // continue back on the Unity thread.
            pluginInit.SetResult(true);
        }
    });

    // Wait for the plugin to complete initialization on the
    // Java thread.
    await pluginInit.Task;
}
```

and `CreateSessionAsync` never ends (neither fails nor succeeds). I've created a simple app that is pretty straightforward but presents the issue: https://github.com/rafek/AzureSpatialAnchors

With VS debugger attached to the app running on a phone, it just hangs after hitting that part of code.

Described issue also happened once while running the sample code.

It's similar to #71

**Comment by julianparismorgan** [comment]
Hi @rafek, thanks for letting us know! We're looking into this and will update you when we know more.

**Comment by h2hjastermereel** [comment]
Same issue here.  Unity 2019.3.x , Spacial Anchors 2.2.0, Android 9, Samsung 9+ (SM-G965W).  After setting break points in SpacialAnchorManager at:

``
                        cloudServices.CallStatic("initialize", unityActivity);
``

It never returns (JavaInitialized is always = false).  This is after clicking the "Next Step" button on the screen "Create Cloud Spatial Anchor Session for query".

**Comment by msftradford** [comment]
Hello @rafek, are you still able to reproduce this issue? I'd like to dig-in a bit more to our internal logs, so please make note of the time period (with timezone) when the issue occurs. Please note that as of ASA SDK 2.4, the service began general availability. Also, starting in February 2021, ASA SDK 2.7 will become the minimum version.
