### ISSUE TITLE
AR session is null - not handled properly

### ISSUE THREAD

**Issue by anton-khoryukov-zf** [Azure/azure-spatial-anchors-samples#108]
**Android Java SDK**
The method `setSession` of the class `CloudSpatialAnchorSession` does not throw an exception / error when the given parameter `Session` is null (AR session not ready).

In the Android Java SDK example this can happen in the function `initializeSession()` (`this.cloudSession.setSession(sceneView.getSession());`) and lead to the following behavior:
- `SessionUpdatedEvent `of the class `CloudSpatialAnchorSession` will not be fired
- Numerous log messages: _OnArFrameAvailable - CreatePlatformAnchor() did not return a Platform Anchor, so the session is likely stopping.  Ignoring this frame. Error Message: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.ar.core.Anchor com.google.ar.core.Session.createAnchor(com.google.ar.core.Pose)' on a null object reference_

**Comment by Alberto-Vega-MSFT** [comment]
@craigktreasure @RamonArguelles  Would you please help?

**Comment by darax** [comment]
I believe this issue is closed and was reopened accidentally.

**Comment by craigktreasure** [comment]
I don't think so. It was opened from the Docs side and we asked them to open the issue over here instead. It's not resolved.

**Comment by RamonArguelles** [comment]
Hi @anton-khoryukov-zf, thanks for reporting! I've filed an internal issue (#26089016) for this so that we can take a look at it.

**Comment by pamistel** [comment]
Hi 
Thanks for reporting this. We have recently updated the Android Tutorial and have addressed this issue.

https://docs.microsoft.com/en-us/azure/spatial-anchors/tutorials/tutorial-new-android-app?tabs=azure-portal
