### ISSUE TITLE
SpatialAnchorManager should expose properties in order to be configurable at runtime

### ISSUE THREAD

**Issue by chrisfromwork** [Azure/azure-spatial-anchors-samples#109]
We have some stale logic related to ASA in another Microsoft MR project that we are currently looking to update: https://github.com/microsoft/MixedReality-SpectatorView/blob/master/src/SpectatorView.Unity/Assets/SpatialAlignment.ASA/Scripts/SpatialAlignment/SpatialAnchorsCoordinateService.cs

It's a bit unclear whether we should write custom calls to create/manage CloudSpatialAnchorSessions or if we should rely on SpatialAnchorManager for session management. For our current logic flow, we need to be able to dynamically create/destroy this logic as needed. We also need to configure ASA credentials at runtime compared to hard coding before. Right now, it seems like the suggested ASA mechanism for setting things up in Unity requires declaring items in the Unity inspectator through serialized fields in SpatialAnchorManager. Ideally, these properties could be configured at runtime through getter/setters or protected properties. Right now all of these properties are private preventing creating a custom child class or calling to update these values. https://github.com/Azure/azure-spatial-anchors-samples/blob/c90cb42c5f6cb452c7cff4e97fe4284c7a17502b/Unity/Assets/AzureSpatialAnchors.SDK/Scripts/SpatialAnchorManager.cs#L81

**Comment by vincentfretin** [comment]
In SDK 2.2.0 you have SpatialAnchorsAccountId and SpatialAnchorsAccountKey getter/setter properties now.
I needed to dynamically set the credentials. I do it like this, In Unity editor I disabled the script "Spatial Anchor Manager" in my AzureSpatialAnchors gameobject and in my code I do this:
```
CloudManager.SpatialAnchorsAccountId = "xxxxxx";
CloudManager.SpatialAnchorsAccountKey = "yyyyyyy";
CloudManager.enabled = true;
await CloudManager.CreateSessionAsync();
...
```
It works fine like this.

**Comment by darax** [comment]
Yes, I'm pretty sure he did that actual work. :)

**Comment by chrisfromwork** [comment]
Thanks for confirming!
