### ISSUE TITLE
Xamarin.Android: LocateAnchorStatus is not an enum

### ISSUE THREAD

**Issue by dotMorten** [Azure/azure-spatial-anchors-samples#110]
There appears to be an issue with the binding for Android, as it's not correctly being shown as an enum as it is in iOS, but is instead a set of static values:

iOS definition:
![image](https://user-images.githubusercontent.com/1378165/70949862-caf8ec80-2013-11ea-8f75-adc61d4f74fc.png)

Android definition:
![image](https://user-images.githubusercontent.com/1378165/70949877-d4825480-2013-11ea-953f-a823a4ee7d77.png)

This makes it trickier to write reusable code. For instance a switch on the status works in iOS but not in Android:
```cs
    switch (status)
    {
        case LocateAnchorStatus.AlreadyTracked: // Compiler error CS0150: A constant value is expected
             break;
    }
```

There's quite a lot of these odd inconsistencies all over (for instance event arguments on android are accessed below an extra `args` property, so on iOS where it's `e.Status` on Android it's `e.Args.Status`.
It's fine that things are different when the underlying platform is different (like ARKit vs ARCore objects), but when things are the same, it would be nice with a consistent API.

**Comment by julianparismorgan** [comment]
Hi @dotMorten, thanks for letting us know! We're looking into this. RE. your note on odd inconsistencies, we really appreciate you taking the time to report these inconsistencies and help us fix them, so please continue to do so :)

**Comment by dotMorten** [comment]
@Varnauld was this addressed? I don’t see a PR linked

**Comment by Varnauld** [comment]
hi @dotMorten ! Apologies, I was closing out older items (this one was two years old) - here's the link to our latest release https://github.com/Azure/azure-spatial-anchors-samples/releases/tag/v2.12.0 

if you have some time, would love to chat more with you 1:1 !

**Comment by dotMorten** [comment]
Thanks for the link. So is that a yes that the mapping was fixed and it is now an enum on Android too?
