### ISSUE TITLE
Compatibility with ARFoundation 3.0

### ISSUE THREAD

**Issue by somepablo** [Azure/azure-spatial-anchors-samples#111]
Hi,

Some of our apps use both Spatial Anchors and other AR features. However, because Spatial Anchors requires ARFoundation 2, we are somehow limited to new ARFoundation features and fixes.

Are you planning to upgrade Azure Anchors SDK to support ARFoundation 3.0? Is there any workaround to use ARFoundation 3 with the current Anchors SDK?

Thanks

**Comment by softwarengineer2** [comment]
I tried it with ARFoundation 3.1.0. They just set their manifest.json to 2.1. You can simply upgrade it with Package Manager (Window/Package Manager) or directly updating manifest.json (Unity\Packages\manifest.json) to this

```
{
  "dependencies": {
    "com.unity.2d.sprite": "1.0.0",
    "com.unity.2d.tilemap": "1.0.0",
    "com.unity.ads": "2.0.8",
    "com.unity.analytics": "3.3.4",
    "com.unity.collab-proxy": "1.2.16",
    "com.unity.ext.nunit": "1.0.0",
    "com.unity.ide.rider": "1.1.4",
    "com.unity.ide.vscode": "1.1.3",
    "com.unity.purchasing": "2.0.6",
    "com.unity.test-framework": "1.1.9",
    "com.unity.textmeshpro": "2.0.1",
    "com.unity.timeline": "1.2.9",
    "com.unity.ugui": "1.0.0",
    "com.unity.xr.arcore": "3.1.0-preview.2",
    "com.unity.xr.arfoundation": "3.1.0-preview.3",
    "com.unity.xr.arkit": "3.1.0-preview.2",
    "com.unity.xr.legacyinputhelpers": "2.0.2",
    "com.unity.xr.windowsmr.metro": "4.0.0",
    "com.unity.modules.ai": "1.0.0",
    "com.unity.modules.androidjni": "1.0.0",
    "com.unity.modules.animation": "1.0.0",
    "com.unity.modules.assetbundle": "1.0.0",
    "com.unity.modules.audio": "1.0.0",
    "com.unity.modules.cloth": "1.0.0",
    "com.unity.modules.director": "1.0.0",
    "com.unity.modules.imageconversion": "1.0.0",
    "com.unity.modules.imgui": "1.0.0",
    "com.unity.modules.jsonserialize": "1.0.0",
    "com.unity.modules.particlesystem": "1.0.0",
    "com.unity.modules.physics": "1.0.0",
    "com.unity.modules.physics2d": "1.0.0",
    "com.unity.modules.screencapture": "1.0.0",
    "com.unity.modules.terrain": "1.0.0",
    "com.unity.modules.terrainphysics": "1.0.0",
    "com.unity.modules.tilemap": "1.0.0",
    "com.unity.modules.ui": "1.0.0",
    "com.unity.modules.uielements": "1.0.0",
    "com.unity.modules.umbra": "1.0.0",
    "com.unity.modules.unityanalytics": "1.0.0",
    "com.unity.modules.unitywebrequest": "1.0.0",
    "com.unity.modules.unitywebrequestassetbundle": "1.0.0",
    "com.unity.modules.unitywebrequestaudio": "1.0.0",
    "com.unity.modules.unitywebrequesttexture": "1.0.0",
    "com.unity.modules.unitywebrequestwww": "1.0.0",
    "com.unity.modules.vehicles": "1.0.0",
    "com.unity.modules.video": "1.0.0",
    "com.unity.modules.vr": "1.0.0",
    "com.unity.modules.wind": "1.0.0",
    "com.unity.modules.xr": "1.0.0"
    }
}
```

**Comment by somepablo** [comment]
You are right, it works with ARFoundation 3.1. However we had to manually modify some code of Anchors SDK because the ARFoundation upgrade include some break changes wrt version 2.2.

**Comment by darax** [comment]
I tend to use the latest ARFoundation (3.x) when testing even though our official support is 2.x. The name change from ARReferencePoint*** to ARAnchor*** is going to make supporting both 2.x and 3.x at the same time a bit tricky.  My instinct is to leave ARReferencePoint*** and keep the project manifest pointed at 2.x.  This will allow Unity to update the scripts if the user chooses to move to the newer ARFoundation.

**Comment by rogueyoshi** [comment]
Is full support for 3.x on the horizon? There's a lot to be gained, but I'm not interested in upgrading ARFoundation if it means breaking changes in new versions of Azure Spatial Anchors...

**Comment by rogueyoshi** [comment]
I have some insight for this. The AR Foundation 3.1.X preview package will automatically update all project scripts to use the correct references (but not ARF 3.0.X). You can save yourself a lot of time by upgrading to the preview package rather than the release. [This should be safe as the patch notes mostly only feature bugfixes and backwards compatibility fixes.](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.1/changelog/CHANGELOG.html)

**Comment by craigktreasure** [comment]
Hey everyone. We're closing this in favor of #149 where you'll find more information about our support for ARFoundation 3 and Unity 2019.3. Thanks!
