### ISSUE TITLE
CloudToNative() does not work with localized anchors 

### ISSUE THREAD

**Issue by FSchmidNT** [Azure/azure-spatial-anchors-samples#113]
When I locate an anchor created in another session and try to save the identifier of my Cloud Spatial Anchor in the CloudNativeAnchor component of my anchor, it does not work. Apparently the reference is not created because I have an " Object reference not set..." error. However, if I want to add the Cloud Spatial Anchor to a newly created anchor in the session, it works fine. 

For my app I use the DemoScriptBase script from the example:
`GameObject nextObject = SpawnNewAnchoredObject(anchorPose.position, anchorPose.rotation, currentCloudAnchor);`
`nextObject.GetComponent<CloudNativeAnchor>().CloudToNative(currentCloudAnchor);`

This works:
`currentCloudAnchor.Identifier;`

This is not working:
`nextObject.GetComponent<CloudNativeAnchor>().CloudAnchor.Identifier;`

I would be very grateful for help.

**Comment by darax** [comment]
Hi @FSchmidNT, just saw this.  After reviewing the code, I think there is a bug in the ASA SDK.  You can try this patch:
In file Assets\AzureSpatialAnchors.SDK\Scripts\CloudNativeAnchor.cs
Find the function CloudToNative (around line 70):
public void CloudToNative(CloudSpatialAnchor cloudAnchor)
        {
            // Validate
            if (cloudAnchor == null) { throw new ArgumentNullException(nameof(cloudAnchor)); }

            // Apply and store updated native anchor
            nativeAnchor = gameObject.ApplyCloudAnchor(cloudAnchor);
        }

and after 
// Apply and store updated native anchor
            nativeAnchor = gameObject.ApplyCloudAnchor(cloudAnchor);
add:
this.cloudAnchor = cloudAnchor;

so the function looks like:
 public void CloudToNative(CloudSpatialAnchor cloudAnchor)
        {
            // Validate
            if (cloudAnchor == null) { throw new ArgumentNullException(nameof(cloudAnchor)); }

            // Apply and store updated native anchor
            nativeAnchor = gameObject.ApplyCloudAnchor(cloudAnchor);
            this.cloudAnchor = cloudAnchor;
        }

**Comment by rogueyoshi** [comment]
Did you make a pull request for this yet? If not, I'll do it.

**Comment by rogueyoshi** [comment]
> Hi @FSchmidNT, just saw this. After reviewing the code, I think there is a bug in the ASA SDK. You can try this patch:
> In file Assets\AzureSpatialAnchors.SDK\Scripts\CloudNativeAnchor.cs
> Find the function CloudToNative (around line 70):
> 
> ```
>         public void CloudToNative(CloudSpatialAnchor cloudAnchor)
>         {
>             // Validate
>             if (cloudAnchor == null) { throw new ArgumentNullException(nameof(cloudAnchor)); }
> 
>             // Apply and store updated native anchor
>             nativeAnchor = gameObject.ApplyCloudAnchor(cloudAnchor);
>         }
> ```
> 
> and after
> 
> ```
> // Apply and store updated native anchor
> nativeAnchor = gameObject.ApplyCloudAnchor(cloudAnchor);
> ```
> 
> add:
> `this.cloudAnchor = cloudAnchor;`
> 
> so the function looks like:
> 
> ```
>         public void CloudToNative(CloudSpatialAnchor cloudAnchor)
>         {
>             // Validate
>             if (cloudAnchor == null) { throw new ArgumentNullException(nameof(cloudAnchor)); }
> 
>             // Apply and store updated native anchor
>             nativeAnchor = gameObject.ApplyCloudAnchor(cloudAnchor);
>             this.cloudAnchor = cloudAnchor;
>         }
> ```

Did you make a pull request for this yet? If not, I'll do it.

**Comment by pandakub** [comment]
I Just want to report that I also encountered this exact same bug.

**Comment by FSchmidNT** [comment]
Sorry for the late answer, in my case the fix worked great. 
For your information, I just tried the new version (2.2) and noticed that the bug is still not fixed. 
Thanks for the help.

**Comment by RamonArguelles** [comment]
Hi @FSchmidNT, thanks for reporting! I've filed an internal issue (#26089424) for this so that we can take a look at it. It is indeed a bug in the ASA SDK, hence why we aren't opening a pull request to change the sample code: the code snippet above is just a workaround while we fix the real underlying issue in the SDK.

**Comment by anders-lundgren** [comment]
Any updates on this? The workaround does the job but would be great to have the long term fix for this!

**Comment by craigktreasure** [comment]
This was fixed last month and should be available in 2.4.0. Please move to 2.4.0 to get the fix.
