### ISSUE TITLE
Migrate to Unity 2019.3

### ISSUE THREAD

**Issue by SpencerIO** [Azure/azure-spatial-anchors-samples#116]
When I migrate the Unity project to 2019.3 I am getting CS0506 override issues in the com.unity.xr.arsubsystems@2.2.0-preview.3
![Screen Shot 2020-01-08 at 4 56 43 PM](https://user-images.githubusercontent.com/5199953/72028607-01eba800-3238-11ea-831e-c97f7603ad25.png)

I am specifically looking to use the new feature in 2019.3 to use Unity as a library

**Comment by skypu3** [comment]
I had same issue too. How can we fix it ?

**Comment by softwarengineer2** [comment]
You just need to upgrade the some of the packages to the latest from package manager (On top menu Window>Package Manager).

Or you can simply use my manifest.json (Unity\Packages\manifest.json)

`{
  "dependencies": {
    "com.unity.2d.sprite": "1.0.0",
    "com.unity.2d.tilemap": "1.0.0",
    "com.unity.ads": "2.0.8",
    "com.unity.analytics": "3.3.4",
    "com.unity.collab-proxy": "1.2.16",
    "com.unity.ext.nunit": "1.0.0",
    "com.unity.ide.rider": "1.1.4",
    "com.unity.ide.vscode": "1.1.3",
    "com.unity.purchasing": "2.0.6",
    "com.unity.test-framework": "1.1.9",
    "com.unity.textmeshpro": "2.0.1",
    "com.unity.timeline": "1.2.9",
    "com.unity.ugui": "1.0.0",
    "com.unity.xr.arcore": "3.1.0-preview.2",
    "com.unity.xr.arfoundation": "3.1.0-preview.3",
    "com.unity.xr.arkit": "3.1.0-preview.2",
    "com.unity.xr.legacyinputhelpers": "2.0.2",
    "com.unity.xr.windowsmr.metro": "4.0.0",
    "com.unity.modules.ai": "1.0.0",
    "com.unity.modules.androidjni": "1.0.0",
    "com.unity.modules.animation": "1.0.0",
    "com.unity.modules.assetbundle": "1.0.0",
    "com.unity.modules.audio": "1.0.0",
    "com.unity.modules.cloth": "1.0.0",
    "com.unity.modules.director": "1.0.0",
    "com.unity.modules.imageconversion": "1.0.0",
    "com.unity.modules.imgui": "1.0.0",
    "com.unity.modules.jsonserialize": "1.0.0",
    "com.unity.modules.particlesystem": "1.0.0",
    "com.unity.modules.physics": "1.0.0",
    "com.unity.modules.physics2d": "1.0.0",
    "com.unity.modules.screencapture": "1.0.0",
    "com.unity.modules.terrain": "1.0.0",
    "com.unity.modules.terrainphysics": "1.0.0",
    "com.unity.modules.tilemap": "1.0.0",
    "com.unity.modules.ui": "1.0.0",
    "com.unity.modules.uielements": "1.0.0",
    "com.unity.modules.umbra": "1.0.0",
    "com.unity.modules.unityanalytics": "1.0.0",
    "com.unity.modules.unitywebrequest": "1.0.0",
    "com.unity.modules.unitywebrequestassetbundle": "1.0.0",
    "com.unity.modules.unitywebrequestaudio": "1.0.0",
    "com.unity.modules.unitywebrequesttexture": "1.0.0",
    "com.unity.modules.unitywebrequestwww": "1.0.0",
    "com.unity.modules.vehicles": "1.0.0",
    "com.unity.modules.video": "1.0.0",
    "com.unity.modules.vr": "1.0.0",
    "com.unity.modules.wind": "1.0.0",
    "com.unity.modules.xr": "1.0.0"
  }
}
`

**Comment by SpencerIO** [comment]
Great, thank you. Once you have the iOS project published remember to change your podfile as per the other issue I mentioned. You can keep your version of spacial anchors in the podfile
