### ISSUE TITLE
Error when opening SharingService solution

### ISSUE THREAD

**Issue by Okke234** [Azure/azure-spatial-anchors-samples#12]
Hello! I'm quite new to C#, Unity, Hololens development etc. I've been trying to figure out how the company i'm interning for can use Azure spatial anchors for holograms to make the office more interesting when showing guests around. (Have them put on a Hololens or quickly deploy and app on their phones)

The [Unity Hololens quickstart](https://docs.microsoft.com/nl-nl/azure/spatial-anchors/quickstarts/get-started-unity-hololens) went swimmingly, but when i started working through the [tutorial](https://docs.microsoft.com/en-us/azure/spatial-anchors/tutorials/tutorial-share-anchors-across-devices) i very quickly got stuck.
I opened the SharingService project like the tutorial told me to and was greeted with an error message. 

![image](https://user-images.githubusercontent.com/33544581/55166668-d6e40c00-516f-11e9-83c8-d6a3d5957279.png)

The output window displayed the following:
`D:\Unity Projects\Spatial anchors\Sharing\SharingServiceSample\SharingService.csproj : error  : Project file is incomplete. Expected imports are missing.`

I made sure nothing was wrong with my files and ended up re-cloning just to be sure; didn't solve the issue.
I repaired Visual Studio 2017, also just to be sure and again this didn't solve it.
This leads me to believe something's wrong with the .csproj file? (Or it is just a me-problem as per usual).

Thanks in advance for the help and i hope this helps you out aswell.

**Comment by valthec** [comment]
I had same problem and delete (or rename) global.json located in main forlder was enough to fix it. Hope it helps.

**Comment by vriveras** [comment]
The sample is using a global.json and this has some rules that it [follows](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json#matching-rules). You can make sure you match this version to what you have available or update your version locally for the .netcore project.

**Comment by sarahboxbear** [comment]
Thanks @valthec and @vrviveras for the answer and @Okke234 for reporting: I had the very same issue when following the tutorial.

**Comment by ctheodorak** [comment]
Where is the global.json flle located cause  cant find it?
