### ISSUE TITLE
iOS saving/recalling of anchors with incorrect AnchorPose

### ISSUE THREAD

**Issue by lokedward** [Azure/azure-spatial-anchors-samples#120]
Hi, I'm running the latest samples ASA 2.1.1 on Unity 2019.2.17 with an iPhone 8 and I am encountering a bug when saving and recalling anchors on my device. 

When I create an anchor and place it, I can see the demo object on the surface but when it finishes the Saving step my anchor the cube & attached text mesh jumps to where my device is and that seems to be the saved location when I recall the anchor it spawns where my device is and not where I placed the cube on the surface. In my xcode console I only see a suspicious `"exception causing failure: File with depth file name not available"` message but nothing else. 

Any insights would be greatly appreciated.

**Comment by makihiro** [comment]
same here. is there any insights?
