### ISSUE TITLE
Unity throwing errors on Android regarding unexpected serialization size mismatch

### ISSUE THREAD

**Issue by rogueyoshi** [Azure/azure-spatial-anchors-samples#123]
Is this error safe? It's happening on an unmodified build of the demo app, though it seems to be working regardless.

> 02/04 16:28:39.156 7984 8072 Error Unity: A scripted object (probably UnityEngine.XR.WSA.SpatialMappingCollider?) has a different serialization layout when loading. (Read 32 bytes but expected 100 bytes)
02/04 16:28:39.156 7984 8072 Error Unity: Did you #ifdef UNITY_EDITOR a section of your serialized properties in any of your scripts?
02/04 16:28:39.156 7984 8072 Error Unity:  
02/04 16:28:39.156 7984 8072 Error Unity: (Filename: ./Runtime/Serialize/SerializedFile.cpp Line: 2012)
02/04 16:28:39.156 7984 8072 Error Unity:

**Comment by mschofie** [comment]
That doesn't appear to be an Azure Spatial Anchors issue - the UnityEngine.XR.WSA.SpatialMappingCollider is part of Unity's XR framework.
