### ISSUE TITLE
AnchorLocateStrategy not behaving the same way on HoloLens 1 and HoloLens 2 devices

### ISSUE THREAD

**Issue by Daniel-Tamborra** [Azure/azure-spatial-anchors-samples#128]
When creating a **CloudSpatialAnchorWatcher** we set the Strategy parameter on AnchorLocateStrategy to **"AnyStrategy"** and provide a list of Identifiers, meaning we search for multiple anchors with a single watcher.

We have multiple anchors placed and on HoloLens 1 it locates and places all of them correctly. On HoloLens 2 however it finds the nearest anchor correctly but places the rest of the anchors on position 0,0,0 in Unity Space (Where the app was launched) This is a major issue.

It does not matter whether these anchors are created on HoloLens 1 or HoloLens 2. The HoloLens 1 will locate them correctly but the HoloLens 2 (using the same settings) will only locate the nearest anchor correctly.

If we set LocateStrategy to Relationship it does not work either.

**Comment by Merichbier** [comment]
I'm experiencing the same problem. Furthermore, using several watchers (one after another), Hololens 2 locate the first on correctly but then the next ones are all badly located

**Comment by RamonArguelles** [comment]
Hi @Daniel-Tamborra and @Merichbier. Thanks a lot for reporting this issue. We just discovered, and fixed, and bug in our Azure Spatial Anchors service, that may have been the reason behind the issue you described. Could you try your scenario again, and let us know if it's indeed fixed for you? Thanks!

**Comment by Merichbier** [comment]
Hi @RamonArguelles,
Updated ASA from 2.2.0 to 2.2.1 this morning and tested. I'm happy to confirm that you did fix it
