### ISSUE TITLE
Store Cloud Anchor Locally

### ISSUE THREAD

**Issue by paul-bonnel-fr** [Azure/azure-spatial-anchors-samples#13]
Hello everyone,
I cannot figure out how to save the C# object : `CloudSpatialAnchor` locally, so it can be persistent and save into the local Unity cache...
Is there is a way to store the anchor locally instead of sending it to the cloud ? Any tought about this ? 

Thank you

**Comment by robinjongen** [comment]
No solution but keep an eye out to the unity forum. A similar question has been asked over there.

[Feedback azure spatial anchors](https://feedback.azure.com/forums/919252-azure-spatial-anchors/suggestions/36946621-storing-spatial-anchors-to-the-edge-and-not-cloud)

**Comment by vriveras** [comment]
Today we do not support storing anchors locally you need to have an active connection to the service to be able to store and recall anchors.

We are currently collecting feedback for new features please log your feedback [here](https://feedback.azure.com/forums/919252-azure-spatial-anchors)
