### ISSUE TITLE
Unable to save anchors[Service unavailable EU?] - IOS

### ISSUE THREAD

**Issue by Nanoodle** [Azure/azure-spatial-anchors-samples#134]
Hello,

Starting Thursday 20th, we've been unable to save any anchors. During the process, after scanning, it will hang on "saving" after which an error will be displayed (likely due to service timeout?). Functionality returns intermittently. We are facing the same issues today.

We've:
- Rolled back without positive result
- Tried a fully functional previous build still on the device
- Tried refreshing the primary key
- Tried the ASA Samples app without changes other than the account info

I'll add the XCode log for the samples app run in case it helps. 
A team member has also found a post on MSDN [Post](https://social.msdn.microsoft.com/Forums/en-US/706bce77-3b78-4204-a1fc-63304f02911f/spatial-anchor-service-doesnt-work-for-4-hours?forum=WAVirtualMachinesVirtualNetwork) with a similar report, though they were using the Hololens, based in Germany.

Near the end of the log (p22) we run into:
"service unavailable or unspecified error found
Microsoft.Azure.SpatialAnchors.Unity.Examples.DemoScriptBase:CloudManager_Error(Object, SessionErrorEventArgs)
Microsoft.Azure.SpatialAnchors.SessionErrorDelegate:Invoke(Object, SessionErrorEventArgs)
Microsoft.Azure.SpatialAnchors.SessionErrorDelegate:Invoke(Object, SessionErrorEventArgs)
Microsoft.Azure.SpatialAnchors.<>c__DisplayClass82_0:<CreateAnchorAsync>b__0()"

Followed by a "cloudspatial exception" and "Failed to save anchor Microsoft.Azure.SpatialAnchors.CloudSpatialException"

[SamplesDebug.docx](https://github.com/Azure/azure-spatial-anchors-samples/files/4230138/SamplesDebug.docx)

Please let me know if I need to provide more/other information or if there is something specific we should try.

**Comment by vincentfretin** [comment]
Hi, you have similar timeout issues like mine #132 I was having yesterday in France. At some hours it worked, and some other hours it didn't.

**Comment by weinanshen** [comment]
Hi, we are investigating it and will get back to you. Thanks!

**Comment by Nanoodle** [comment]
Hey Vincent, 
yes I saw the issue and thought it was similar. I decided to log a separate issue because yours seemed more geared to changing the feedback to the dev/user about the timeouts. 

When operational was the service still particularly slow for you? As opposed to previous usage?
At the moment it is functional again on our side, wifi is quite slow but on 4G it is fine. Did you per chance have any test cases of 4G vs wifi back then?

Thanks Weinanshen.

**Comment by vincentfretin** [comment]
I first tested the SDK two weeks ago, and I was already having timeout issues. The first time I tested the app I got a stacktrace. :) When the service is operational, on 4g or wifi, saving an anchor takes 2-4s I think.

**Comment by RamonArguelles** [comment]
Hi @Nanoodle & @vincentfretin, thanks a lot for reporting this problem. Could you confirm if you are still hitting it? We've recently fixed some issues on our Azure Spatial Anchor service that may have been related. Thanks!

**Comment by vincentfretin** [comment]
Hi @RamonArguelles , I'm not currently working on the project anymore, so I won't be able to confirm it.

**Comment by Nanoodle** [comment]
It has been a while since any such occurrence, but a large part of the focus is currently elsewhere so the usage of anchors has been low and thus there's also not been much opportunity to hit this issue. It was very "temperamental" in the first place after all.

I will keep you informed, whether I hit it or if after an increase in usage over time, I haven't.

Thanks for the update.

**Comment by RamonArguelles** [comment]
Ok, thanks @vincentfretin and @Nanoodle! I'll close this issue for now, since we do believe it is now fixed on our side. That said, if you ever happen to hit it again, please feel free to either reopen, or open a brand new issue, so that we can take a look. Thanks!
