### ISSUE TITLE
Connecting Sessions

### ISSUE THREAD

**Issue by FSchmidNT** [Azure/azure-spatial-anchors-samples#135]
Hi, 

we are in the process of developing a navigation that works with Spatial Anchors alone. The whole thing works surprisingly well, but unfortunately only for a few anchors and only if they were created in the same session. We would like to apply this to large areas and have the following questions: 

- If one anchor is found, all other anchors created in the same session are also found directly. This requires that you have created all anchors in one session or that you search for anchors until at least one anchor from each session is found. Is there a way to connect sessions together or to continue placing anchors after restarting the app with a previously used session?

- Will it be possible to locate more than 35 anchors at once in the future?

I would appreciate your help

**Comment by darax** [comment]
Hi @FSchmidNT 
You've done your homework on how to connect anchors in Azure Spatial Anchors. :) Connecting sessions between app launches isn't a behavior that we've implemented. I can't comment on what the future might bring, connecting sessions and flexibility in configuring the watcher are both good requests for us to keep on the list of future improvements. 

Thanks!

**Comment by RamonArguelles** [comment]
As @darax mentioned, thanks for the feedback, @FSchmidNT. I filed an internal feature request (#26121770) for this so that we can track it.

**Comment by Varnauld** [comment]
Hello,
I closed this item as this was originally submitted close to two years ago. Our latest release is available [here](https://github.com/Azure/azure-spatial-anchors-samples/releases/tag/v2.12.0) – please re-open this item should you have further feedback for the team.
Alternatively, if you have any ideas or requests for new features or capabilities, or should you wish to upvote an existing idea, please visit our [Feedback hub](https://feedback.azure.com/d365community/forum/f47d9b25-0725-ec11-b6e6-000d3a4f07b8)

Thank you
