### ISSUE TITLE
Unity iOS build fail issue with latest spatial anchor 2.2.0 and Unity 2019.3.2f1

### ISSUE THREAD

**Issue by skypu3** [Azure/azure-spatial-anchors-samples#137]
Hi All,

I used the Azure spatial anchor with version 2.2.0, and ARFoundation 3.0.1 packages.
I can successfully build app into Android without any issues, however I can't build app into iOS.
I follow the guide to install spatial anchor with pod, and compile it then showed up following issues:
Undefined symbols for architecture arm64:
  "_ssc_cloud_spatial_anchor_session_set_log_level", referenced from:
      _CloudSpatialAnchorSession_set_LogLevel

![截圖 2020-02-24 下午4 12 38](https://user-images.githubusercontent.com/70039/75136743-8af36b80-5720-11ea-818d-a5eb35221cb1.png)

Does anyone know about the issue ?

**Comment by skypu3** [comment]
BTW my unity version is 2019.3.2f1

**Comment by JeanVACCA** [comment]
I have experienced the same issue, to fix it you have to change the podfile
to target the UnityFramework instead of the Unity-iPhone project. It
results with a successful build but after that the app crashed at startup
and i haven't manage to fix this issue, so I advise you to rollback to
Unity 2019.2.x

**Comment by skypu3** [comment]
Oh, because I would like to have Library feature from Unity 2019.3, so I need to stay with this version.

**Comment by Nanoodle** [comment]
Hey guys,

I'd noticed the same with 2019.3.x. We put off the switch to that new version of Unity but a way I found to get around it, at the time, is to: 

[In the XCode Workspace]
- Click on UnityFramework under Targets  
- Bottom of the Frameworks & Libraries press the + button
- Add other- Add files  
- Direct it through all the Azure folders in the Pods folder for your Build folder until you get to the AzureSpatialAnchors exec 
- Select the exec & press open 
-> It should now be added to the Framework&Libraries list

Unsure if it's a situational fix so no guarantees & it's obviously not optimal, but it might get you through the hurdle as a quickfix.

**Comment by JeanVACCA** [comment]
Hey, Thanks for the tips. Unfortunately i still get the same error but i finally managed to make it work with this config 
<img width="627" alt="Capture d'écran 2020-02-25 11 02 28" src="https://user-images.githubusercontent.com/20737779/75236915-cba1c200-57be-11ea-8401-2098ca361d2f.png">

Hope this will help

**Comment by craigktreasure** [comment]
Thanks for the discussion everyone. I love the community effort here. Please see the #149 for further information on Unity 2019.3.

**Comment by faizan1990** [comment]
Where did you get the `AzureSpatialAnchors.framework` and `UnityFramework.framework` from? All I see in my Frameworks, Libraries, and Embedded Content is this:

<img width="546" alt="Screen Shot 2020-04-20 at 4 57 15 pm" src="https://user-images.githubusercontent.com/13532645/79722823-19065f80-8328-11ea-977d-c9b675127fbe.png">

Unity Version: 2019.1.14
XCode Version: 11.3
