### ISSUE TITLE
ARReferencePoint count keeps increasing during a session

### ISSUE THREAD

**Issue by vincentfretin** [Azure/azure-spatial-anchors-samples#140]
- On an app inspired from BasicDemo where I can add several anchors
- Android Samsung S8 and iPad 2018 6th gen
- Unity 2019.2.20f1
- all ARFoundation packages 2.2.0-preview.6
- ASA SDK 2.2.0

ARReferencePoint count (referencePointManager.trackables.count) keeps increasing during a session each time a new watcher detects a previously located anchor. Is this a normal behavior?

Here is an example of what I do during a session:
- starting a session is creating a new ARReferencePoint right away (for the camera it seems, recreated every 8 meters when the user move)
- start watcher with identifiers=[1]
2 ARReferencePoint created when anchor identifier 1 is located (Located event fired and I spawn a cube with CloudNativeAnchor component)
Is this normal that it creates two native anchors? One is the cube's parent, the other one has no child and is at the same position.
- stop watcher
- start watcher with identifiers=[1,2]  (1 and 2 are connected)
anchor 2 located event fired
2 ARReferencePoint created for the newly located anchor 2 and 1 ARReferencePoint created again for anchor 1 that was previously located
- stop watcher
- start watcher identifiers=[1]
near anchor 1, 1 ARReferencePoint created
- stop watcher
- start watcher identifiers=[1,2]
near anchor 2, 2 ARReferencePoint created (for anchor 1 and anchor 2)

Should I keep track myself of located anchors identifiers and not put them again in the watcher identifiers list?
Is this normal that it creates two native anchors when a cloud anchor is located for the first time?
Is this normal that it creates again a ARReferencePoint when a new watcher redetects a previously located anchor?

**Comment by msftradford** [comment]
Hi @vincentfretin, thanks for the questions. I've started an internal search (#30612339) to get you answers to your questions. Please be aware that starting in February 2021, [the minimum version for ASA SDK will be 2.7](https://github.com/Azure/azure-spatial-anchors-samples/releases/tag/v2.7.0).

**Comment by vincentfretin** [comment]
Hi @msftradford Thanks for the reply. If your internal search leads to a real issue that will be fixed, great! The project where I wanted to use ASA SDK is currently in stand by due to the pandemic, so I'm not currently working on it, but I'll be sure to update the SDK if I work on it again.

**Comment by msftradford** [comment]
@vincentfretin, understood. we'll leave this open and follow-up with our findings in case other folks end up having similar questions.

**Comment by msftradford** [comment]
Closing this issue as [ARReferencePointManager has been deprecated](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/api/UnityEngine.XR.ARFoundation.ARReferencePointManager.html) in favor of ARAnchorManager.
