### ISSUE TITLE
Unity Editor run Error

### ISSUE THREAD

**Issue by Mlt123** [Azure/azure-spatial-anchors-samples#141]
DllNotFoundException: azurespatialanchorsndk

**Comment by Mlt123** [comment]
I can package to an Android device，but when I click the go button on the first screen ，He will fall back

**Comment by JeanVACCA** [comment]
have you tried that ?
[image: image.png]

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Mlt123** [comment]
i change a device ，that is ok ？   Why does n’t the device support arccore work?

**Comment by rononiwu** [comment]
@Mlt123 can you please confirm a few things for me
1. Changing the device solved the issue for you? 
2. What specific device make and model did you start with ?
3. What specific device make and model did you switch to?

**Comment by Mlt123** [comment]
1.yes,i change a device that is ok.
2.HUAWEI MediaPad M5 lite 10,  Android8.0 not ok
3.huawei nova 5,Android 10.0  is ok

**Comment by craigktreasure** [comment]
Per the issue title, we don't currently support running Azure Spatial Anchors in the Unity Editor. Sorry about the confusion.

**Comment by RamonArguelles** [comment]
Sorry @Mlt123, @craigktreasure is correct: we don't support running Azure Spatial Anchors within the Unity Editor. You need to deploy the code to an actual device and run from there.
