### ISSUE TITLE
access denied to spatial anchor exporter ensure your os build is up to date and the spatialperception capability is set

### ISSUE THREAD

**Issue by Mlt123** [Azure/azure-spatial-anchors-samples#143]
How should i modify

**Comment by rononiwu** [comment]
> How should i modify

@Mlt123 Can you please confirm what version of the SDK you are running?

**Comment by Mlt123** [comment]
> > How should i modify
> 
> @Mlt123 Can you please confirm what version of the SDK you are running?
HoloLens Windows version	17134.111.x86fre.rs4_release_svc_prod1.180605-2350 
unity build  windows10SDK=>10.0.18362.0

**Comment by rononiwu** [comment]
> How should i modify

Hey @Mlt123 Can you please confirm what version of our SDK you are running?

**Comment by rononiwu** [comment]
> How should i modify
> 
> Hey @Mlt123 Can you please confirm what version of our SDK you are running?

Also @Mlt123 can you please let me know what your device is and what OS Build your device running?

**Comment by darax** [comment]
@Mlt123, you need to update the OS on your HoloLens to RS5.  You should be able to do so through settings/update and security and check for updates. For more information go here: https://docs.microsoft.com/en-us/hololens/hololens-update-hololens
