### ISSUE TITLE
Using Coarse Relocalization + IDs on Watchers

### ISSUE THREAD

**Issue by rogueyoshi** [Azure/azure-spatial-anchors-samples#145]
What's the best practice for this? Suppose I want to get nearby anchors with the sensor data, but also simultaneously get the anchors which were made in a session without sensor data. If we run two watchers, we get a concurrency error. Should we daisy chain the second instead from the LocateAnchorsCompleted event?

**Comment by Merichbier** [comment]
I guess that could be a solution. What we made is a queue in which we add the locate criterias and since only one watcher can run we wait it to finish to start the next one.

**Comment by julianparismorgan** [comment]
Hi @rogueyoshi, this isn't currently supported today, but we are thinking about supporting multiple watchers or expanding what you can do with locate criteria! @Merichbier's suggestion seems reasonable as a workaround.

**Comment by tomkrikorian** [comment]
I'm using the same workaround as @Merichbier. 
Multiple watchers or more identifiers would be amazing @julianparismorgan !

**Comment by julianparismorgan** [comment]
If you could post it as a suggestion to our UserVoice, that would be great! https://feedback.azure.com/forums/919252-azure-spatial-anchors

**Comment by tomkrikorian** [comment]
Done :)

Here is the link to the suggestion : https://feedback.azure.com/forums/919252-azure-spatial-anchors/suggestions/40207366-multiple-watchers-and-or-more-watcher-options
