### ISSUE TITLE
Scripts compile issue

### ISSUE THREAD

**Issue by nipundavid** [Azure/azure-spatial-anchors-samples#147]
Hi,

All I did was open the project in Unity3D 2019.3.2, and it threw a bunch of scripts errors.

`Library\PackageCache\com.unity.xr.arsubsystems@2.2.0-preview.3\Runtime\ImageTrackingSubsystem\XRImageTrackingSubsystem.cs(57,30): error CS0506: 'XRImageTrackingSubsystem.Destroy()': cannot override inherited member 'Subsystem.Destroy()' because it is not marked virtual, abstract, or override

[Screenshot attached.]

![Git_SA_GIT](https://user-images.githubusercontent.com/2108309/77089550-f7197480-6a2b-11ea-9a26-280115e1fc73.PNG)

**Comment by craigktreasure** [comment]
Please see #149.
