### ISSUE TITLE
CocoaPods could not find compatible versions for pod "AzureSpatialAnchors" (SDK Version 2.2.1)

### ISSUE THREAD

**Issue by FelixRoh** [Azure/azure-spatial-anchors-samples#148]
Starting a iOs build with installing pods ("pod install --repo-update") I get following message:
```
[!] CocoaPods could not find compatible versions for pod "AzureSpatialAnchors":
  In Podfile:
    AzureSpatialAnchors (= 2.2.1)

None of your spec sources contain a spec satisfying the dependency: `AzureSpatialAnchors (= 2.2.1)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

```

**Comment by ThomasNigro** [comment]
Getting the same issue here.

**Comment by craigktreasure** [comment]
Seems we might have an issue with our CocoaPods deployment. We're investigating and will report back. Stick with 2.2.0 for now.

**Comment by craigktreasure** [comment]
Hey everyone. Really sorry about that. We've fixed the publishing issue. You can now run `pod install --repo-update` to install Azure Spatial Anchors 2.2.1.
