### ISSUE TITLE
Assertion failed on expression: 'm_FrameIndexGfxThread != m_FrameAddIndex'

### ISSUE THREAD

**Issue by jelmerS2** [Azure/azure-spatial-anchors-samples#15]
I get the following errors on every frame when playing a scene in the editor
Assertion failed on expression: 'm_FrameIndexGfxThread != m_FrameAddIndex'
Assertion failed on expression: 'IsMatrixValid(matrix)'

this is with the "cameraparent" prefab from the spatial anchors sample project

target: UWP (Hololens)
unity: 2018.3.10

**Comment by vriveras** [comment]
We currently do not support playing directly on the unity editor. The API requires access to the hardware on the devices to be able to process frames in the application and analyse the environment.
