### ISSUE TITLE
iOS/Swift sample always get a fail

### ISSUE THREAD

**Issue by mrsniperz** [Azure/azure-spatial-anchors-samples#152]
![image](https://user-images.githubusercontent.com/35944209/78670135-e44ddd80-790f-11ea-8560-127ec2422ecd.png)
I have tried all three buttons,every time when i get 100% also get a "Creation Fail".
I have checked the ID and KEY.

**Comment by julianparismorgan** [comment]
HI @mrsniperz , it looks like your haven't set the uri correctly. In the string, I see that it says "...azure.com/Accounts/**Setme**/spatialanchors?...". Can you double check that you set the Account ID and Account Key?
