### ISSUE TITLE
shooting 11 errors on opening.

### ISSUE THREAD

**Issue by midopooler** [Azure/azure-spatial-anchors-samples#153]
BELOW IS THE CONSOLE LOG 
2.0.2 (location: C:\Users\Pulkit\Desktop\AR SDKs\azure-spatial-anchors-samples\Unity\Library\PackageCache\com.unity.xr.legacyinputhelpers@2.0.2)
com.unity.xr.windowsmr.metro@4.0.0 (location: C:\Users\Pulkit\Desktop\AR SDKs\azure-spatial-anchors-samples\Unity\Library\PackageCache\com.unity.xr.windowsmr.metro@4.0.0)
com.unity.ext.nunit@1.0.0 (location: C:\Users\Pulkit\Desktop\AR SDKs\azure-spatial-anchors-samples\Unity\Library\PackageCache\com.unity.ext.nunit@1.0.0)
com.unity.xr.arsubsystems@2.2.0-preview.3 (location: C:\Users\Pulkit\Desktop\AR SDKs\azure-spatial-anchors-samples\Unity\Library\PackageCache\com.unity.xr.arsubsystems@2.2.0-preview.3)
com.unity.subsystemregistration@1.0.5 (location: C:\Users\Pulkit\Desktop\AR SDKs\azure-spatial-anchors-samples\Unity\Library\PackageCache\com.unity.subsystemregistration@1.0.5)
Built-in packages:
com.unity.2d.sprite@1.0.0 (location: C:\Program Files\Unity\Hub\Editor\2019.3.0f5\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.2d.sprite)
com.unity.2d.tilemap@1.0.0 (location: C:\Program Files\Unity\Hub\Editor\2019.3.0f5\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.2d.tilemap)
com.unity.ugui@1.0.0 (location: C:\Program Files\Unity\Hub\Editor\2019.3.0f5\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.ugui)
com.unity.modules.ai@1.0.0 (location: C:\Program Files\Unity\Hub\Editor\2019.3.0f5\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.ai)
com.unity.modules.androidjni@1.0.0 (location: C:\Program Files\Unity\Hub\Editor\2019.3.0f5\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.androidjni)
com.unity.modules.animation@1.0.0 (location: C:\Program Files\Unity\Hub\Editor\2019.3.0f5\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.animation)
com.unity.modules.assetbundle@1.0.0 (location: C:\Program Files\Unity\Hub\Editor\2019.3.0f5\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.assetbundle)
com.unity.modules.audio@1.0.0 (location: C:\Program Files\Unity\Hub\Editor\2019.3.0f5\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.audio)
com.unity.modules.cloth@1.0.0 (location: C:\Program Files\Unity\Hub\Editor\2019.3.0f5\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.cloth)
com.unity.modules.director@1.0.0 (location: C:\Program Files\Unity\Hub\Editor\2019.3.0f5\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.director)
com.unity.modules.imageconversion@1.0.0 (location: C:\Program Files\Unity\Hub\Editor\2019.3.0f5\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.imageconversion)
com.unity.modules.imgui@1.0.0 (location: C:\Program Files\Unity\Hub\Editor\2019.3.0f5\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.imgui)
com.unity.modules.jsonserialize@1.0.0 (location: C:\Program Files\Unity\Hub\Editor\2019.3.0f5\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.jsonserialize)
com.unity.modules.particlesystem@1.0.0 (location: C:\Program Files\Unity\Hub\Editor\2019.3.0f5\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.particlesystem)
com.unity.modules.physics@1.0.0 (location: C:\Program Files\Unity\Hub\Editor\2019.3.0f5\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.physics)
com.unity.modules.physics2d@1.0.0 (location: C:\Program Files\Unity\Hub\Editor\2019.3.0f5\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.physics2d)
com.unity.modules.screencapture@1.0.0 (location: C:\Program Files\Unity\Hub\Editor\2019.3.0f5\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.screencapture)
com.unity.modules.terrain@1.0.0 (location: C:\Program Files\Unity\Hub\Editor\2019.3.0f5\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.terrain)
com.unity.modules.terrainphysics@1.0.0 (location: C:\Program Files\Unity\Hub\Editor\2019.3.0f5\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.terrainphysics)
com.unity.modules.tilemap@1.0.0 (location: C:\Program Files\Unity\Hub\Editor\2019.3.0f5\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.tilemap)
com.unity.modules.ui@1.0.0 (location: C:\Program Files\Unity\Hub\Editor\2019.3.0f5\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.ui)
com.unity.modules.uielements@1.0.0 (location: C:\Program Files\Unity\Hub\Editor\2019.3.0f5\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.uielements)
com.unity.modules.umbra@1.0.0 (location: C:\Program Files\Unity\Hub\Editor\2019.3.0f5\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.umbra)
com.unity.modules.unityanalytics@1.0.0 (location: C:\Program Files\Unity\Hub\Editor\2019.3.0f5\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.unityanalytics)
com.unity.modules.unitywebrequest@1.0.0 (location: C:\Program Files\Unity\Hub\Editor\2019.3.0f5\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.unitywebrequest)
com.unity.modules.unitywebrequestassetbundle@1.0.0 (location: C:\Program Files\Unity\Hub\Editor\2019.3.0f5\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.unitywebrequestassetbundle)
com.unity.modules.unitywebrequestaudio@1.0.0 (location: C:\Program Files\Unity\Hub\Editor\2019.3.0f5\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.unitywebrequestaudio)
com.unity.modules.unitywebrequesttexture@1.0.0 (location: C:\Program Files\Unity\Hub\Editor\2019.3.0f5\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.unitywebrequesttexture)
com.unity.modules.unitywebrequestwww@1.0.0 (location: C:\Program Files\Unity\Hub\Editor\2019.3.0f5\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.unitywebrequestwww)
com.unity.modules.vehicles@1.0.0 (location: C:\Program Files\Unity\Hub\Editor\2019.3.0f5\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.vehicles)
com.unity.modules.video@1.0.0 (location: C:\Program Files\Unity\Hub\Editor\2019.3.0f5\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.video)
com.unity.modules.vr@1.0.0 (location: C:\Program Files\Unity\Hub\Editor\2019.3.0f5\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.vr)
com.unity.modules.wind@1.0.0 (location: C:\Program Files\Unity\Hub\Editor\2019.3.0f5\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.wind)
com.unity.modules.xr@1.0.0 (location: C:\Program Files\Unity\Hub\Editor\2019.3.0f5\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.xr)
com.unity.modules.subsystems@1.0.0 (location: C:\Program Files\Unity\Hub\Editor\2019.3.0f5\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.subsystems)

[Subsystems] No new subsystems found in resolved package list.
[Package Manager] Done registering packages in 0.01s seconds
Refreshing native plugins compatible for Editor in 0.06 ms, found 0 plugins.
Preloading 0 native plugins for Editor in 0.00 ms.
IsTimeToCheckForNewEditor: Update time 1586332283 current 1586379225
Initialize engine version: 2019.3.0f5 (44796c9d3c2c)
[Subsystems] Discovering subsystems at path C:/Program Files/Unity/Hub/Editor/2019.3.0f5/Editor/Data/Resources/UnitySubsystems
[Subsystems] Discovering subsystems at path C:/Users/Pulkit/Desktop/AR SDKs/azure-spatial-anchors-samples/Unity/Assets
GfxDevice: creating device client; threaded=1
Direct3D:
Version: Direct3D 11.0 [level 11.1]
Renderer: NVIDIA GeForce GTX 1050 (ID=0x1c8d)
Vendor:
VRAM: 1987 MB
Driver: 23.21.13.8816
[EnlightenBakeManager] m_Clear = false;
Initialize mono

**Comment by julianparismorgan** [comment]
Hi @midopooler, thanks for letting us know! A things for us to better help you:
- I can't tell what the errors are from above, what are they? _Having trouble without color / explicit error messages_.
- Are these Unity Editor errors? Or runtime errors? 
- What platform are your trying to run?
