### ISSUE TITLE
"no suitable image found" by iOS's ADAL

### ISSUE THREAD

**Issue by BASB-Ichikawa** [Azure/azure-spatial-anchors-samples#158]
I've been executing a sample project (iOS) on Mac and Xcode.
the app deploy on iPhone 8 (v 13.3).
But the app has an error below, when the app start.

Can anyone do any advice?

--------------------------------
dyld: Library not loaded: @rpath/ADAL.framework/ADAL
  Referenced from: /private/var/containers/Bundle/Application/774C8738-B08D-4210-A93A-EC0AA7F3B253/SampleSwift.app/SampleSwift
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/774C8738-B08D-4210-A93A-EC0AA7F3B253/SampleSwift.app/Frameworks/ADAL.framework/ADAL: code signature invalid for '/private/var/containers/Bundle/Application/774C8738-B08D-4210-A93A-EC0AA7F3B253/SampleSwift.app/Frameworks/ADAL.framework/ADAL'

	/private/var/containers/Bundle/Application/774C8738-B08D-4210-A93A-EC0AA7F3B253/SampleSwift.app/Frameworks/ADAL.framework/ADAL: code signature invalid for '/private/var/containers/Bundle/Application/774C8738-B08D-4210-A93A-EC0AA7F3B253/SampleSwift.app/Frameworks/ADAL.framework/ADAL'

	/private/var/containers/Bundle/Application/774C8738-B08D-4210-A93A-EC0AA7F3B253/SampleSwift.app/Frameworks/ADAL.framework/ADAL: stat() failed with errno=1
	/private/var/containers/Bundle/Application/774C8738-B08D-4210-A93A-EC0AA7F3B253/SampleSwift.app/Frameworks/ADAL.framework/ADAL: code signature invalid for '/private/var/containers/Bundle/Application/774C8738-B08D-4210-A93A-EC0AA7F3B253/SampleSwift.app/Frameworks/ADAL.framework/ADAL'

	/private/var/containers/Bundle/Application/774C8738-B08D-4210-A93A-EC0AA7F3B253/SampleSwift.app/Frameworks/ADAL.framework/ADAL: stat() failed with errno=1

**Comment by darax** [comment]
how have your configured signing? Do you have a paid developer account with apple, and is the device you are testing on registered?
