### ISSUE TITLE
InvalidOperationException when trying to create an anchor

### ISSUE THREAD

**Issue by tomkrikorian** [Azure/azure-spatial-anchors-samples#159]
I'm running into this exception a lot when trying to create an anchor : 

`04-17 19:18:28.615 20082 20110 E Unity   : ASAScanner (Opuscope.Core.Environment.ASAAnchorScanner):OnSaveCloudAnchorFailed: Failed to save anchor : System.InvalidOperationException: . Request CV: . Response CV: .
04-17 19:18:28.615 20082 20110 E Unity   :   at Microsoft.Azure.SpatialAnchors.NativeLibraryHelpers.CheckStatus (System.IntPtr handle, Microsoft.Azure.SpatialAnchors.status value) [0x00000] in <00000000000000000000000000000000>:0
04-17 19:18:28.615 20082 20110 E Unity   :   at Microsoft.Azure.SpatialAnchors.CloudSpatialAnchorSession+<>c__DisplayClass82_0.<CreateAnchorAsync>b__0 () [0x00000] in <00000000000000000000000000000000>:0
04-17 19:18:28.615 20082 20110 E Unity   :   at System.Action.Invoke () [0x00000] in <00000000000000000000000000000000>:0
04-17 19:18:28.615 20082 20110 E Unity   :   at System.Threading.Tasks.Task.Execute () [0x00000] in <00000000000000000000000000000000>:0
04-17 19:18:28.615 20082 20110 E Unity   :   at System.Threading.ContextCallback.Invoke (System.Object state) [0x00000] in <00000000000000000000000000000000>:0
04-17 19:18:28.615 20082 20110 E Unity   :   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000]`

**Comment by darax** [comment]
this is a hint that something bad happened before we actually started talking to the cloud. Request CV: . Response CV: 

can you post a log with more context?  Are you waiting for the readinesstocreate from SessionUpdated to be >= 1?

**Comment by tomkrikorian** [comment]
I'm waiting for ReadyToCreate to be true and to have enough progress (>1).
I tried again today and i can't reproduce the issue. It comes and go so it makes me think it comes from the cloud service. I'll try to have more log next time it happens.

**Comment by RamonArguelles** [comment]
Thanks @tomkrikorian. Logs will be useful if you hit this again. One possibility is that you may be having Internet Connectivity issues. Or it could be related to https://github.com/Azure/azure-spatial-anchors-samples/issues/127: the value returned by RecommendedForCreateProgress can go up and down as you are scanning your environment, depending on many factors, including the speed in which your device is moving. If you are waiting to have enough progress (>1) before calling CreateAnchorAsync, but your device keeps moving before the call completes, RecommendedForCreateProgress could drop down and cause a failure. In any case, logs will be able to shed light in here. Closing the issue for now, but feel free to reopen if you hit again and you have logs. Thanks!
