### ISSUE TITLE
Cloud Spatial Exception : Azure Spatial Anchor

### ISSUE THREAD

**Issue by avisingh91** [Azure/azure-spatial-anchors-samples#162]
Hi,

### Specs & Environment

Unity3d 2019.1.1.f
Andorid One Plus 6
Azure Spatial Anchor download from this repo.

### Log File .
[LogFile.txt](https://github.com/Azure/azure-spatial-anchors-samples/files/4504903/LogFile.txt)

### Error Scenario 

- When im trying to save local spatial anchor to cloud in "AzureSpatialAnchorsBasicDemo" Scene

Please let me know. How to resolve the issue.Thanks

**Comment by MarcinKulwicki** [comment]
I have the same Issue unresolved. You can look there https://github.com/Azure/azure-spatial-anchors-samples/issues/155
Apparently someone succeeded resolve this error and my issue was closed but not mine. If you will find the solution please leave solution

**Comment by darax** [comment]
Apparently I cursed the issue by resolving Marcin's issue, the fix made last week was temporary and the issue resurfaced over the weekend.  Service team has implemented a complete fix now.
 @avisingh91 @MarcinKulwicki give it another shot. 
Marcin, if you are still having trouble, go ahead and reopen your issue.

**Comment by avisingh91** [comment]
> Apparently I cursed the issue by resolving Marcin's issue, the fix made last week was temporary and the issue resurfaced over the weekend. Service team has implemented a complete fix now.
> @avisingh91 @MarcinKulwicki give it another shot.
> Marcin, if you are still having trouble, go ahead and reopen your issue.

Thanks for the reply. Provided there is no update in the repo, i assume the fix is done on the back-end side. Hence, i made a build and run it one the mobile, and the error is still the same..

**Comment by MarcinKulwicki** [comment]
Now is everything all right. Thanks for resolved the problem.

1) I have Unity 2019.3.0f6 and instruction https://github.com/Azure/azure-spatial-anchors-samples/issues/149
2) Regenerated Access Key (Primary Key)
3) Set up this key for all scenes and resources

And it start working :)

After this i remove Api key from not usable scenes ale leave only in resources and AzureSpatialAnchorsBasicDemo. Still work

**Comment by avisingh91** [comment]
Yes. It is fixed. Thanks @MarcinKulwicki  @darax  for the help.
