### ISSUE TITLE
CreateAnchorAsync succeeds with empty anchor ID after 30s

### ISSUE THREAD

**Issue by motionsmith** [Azure/azure-spatial-anchors-samples#163]
Hello,

I'm seeing a problem when I await `CreateAnchorAsync` on a poor network connection (consistently repros using XCode's poor network simulator). After about 30-45 seconds the task completes without an exception or an `AnchorManager.Error` event. However, the resulting `CloudSpatialAnchor.Identifer` value is an empty string `""`, so the anchor is unusable. The CancellationToken was not triggered.

```
try
            {
                var watch = System.Diagnostics.Stopwatch.StartNew();
                op.SaveStatus = AnchorSaveStatus.Uploading;
                await ASA.CreateAnchorAsync(cloudAnchor, cts.Token);
                watch.Stop();
                var elapsedMs = watch.ElapsedMilliseconds;
                var elapsedSecs = TimeSpan.FromMilliseconds(elapsedMs).TotalSeconds;
                var result = cts.IsCancellationRequested ? "cancelled" : "completed";
                op.SaveStatus = AnchorSaveStatus.Saved;
                Log.AddLog($"Upload {result} in {elapsedSecs.ToString("F1")}s; ASA ID {cloudAnchor.Identifier}");
            }
            catch (Exception ex)
            {
                op.SaveStatus = AnchorSaveStatus.Failed;
                Log.AddLog($"Save failed at CreateAnchorAsync: {ex.Message}");
            }
```

**Comment by motionsmith** [comment]
If I retry the CreateAnchorAsync() request (provide the same CloudSpatialAnchor pointer), the request can subsequently succeed if the network connection improves.

**Comment by motionsmith** [comment]
The ultimate thing this is preventing me from doing is creating anchors on a cellular (LTE) connection. My download speed are decent (1.6 Mbps) but I don't know what my upload speeds are, but I bet they are bad. If I could just create the anchor, it may be subsequently findable on a cellular connection.

**Comment by RamonArguelles** [comment]
Hi @motionsmith, thanks a lot for reporting. I've filed an internal issue (#26123177) for this so that we can take a look at it.

**Comment by Varnauld** [comment]
Hello,
I closed this item as this was originally submitted close to two years ago. Our latest release is available [here](https://github.com/Azure/azure-spatial-anchors-samples/releases/tag/v2.12.0) – please re-open this item should you have further feedback for the team.
Alternatively, if you have any ideas or requests for new features or capabilities, or should you wish to upvote an existing idea, please visit our [Feedback hub](https://feedback.azure.com/d365community/forum/f47d9b25-0725-ec11-b6e6-000d3a4f07b8)

Thank you
