### ISSUE TITLE
connecting app to Azure Cosmos DB

### ISSUE THREAD

**Issue by lilfrimmy19** [Azure/azure-spatial-anchors-samples#165]
I was following the persistent sharing tutorial and I followed the steps in creating a Cosmos DB and  I added the connection string to the .json file in the Sharing Services folder, but when I create an anchor, it does not show up in the database account I created. Is it possible that I am missing a step?

**Comment by mschofie** [comment]
Unfortunately, I think this is the wrong place to ask Cosmos DB questions; we're not really that familiar with it. The Sharing Service is provided as an example of what can be possible in sharing Azure Spatial Anchors - how you store and share the id's on the back-end is up to you.
