### ISSUE TITLE
Multiple Error

### ISSUE THREAD

**Issue by InitusJames** [Azure/azure-spatial-anchors-samples#166]
Cloned GIT, opened with Unity 2019.3.12f1

Multiple Errors (11) similar to the following.

Library\PackageCache\com.unity.xr.arsubsystems@2.2.0-preview.3\Runtime\ObjectTrackingSubsystem\XRObjectTrackingSubsystem.cs(121,37): error CS0506: 'XRObjectTrackingSubsystem.Destroy()': cannot override inherited member 'Subsystem.Destroy()' because it is not marked virtual, abstract, or override

**Comment by craigktreasure** [comment]
Please see #149.
