### ISSUE TITLE
Move your device to capture more environment data, (canvas) stuck at 0%

### ISSUE THREAD

**Issue by midopooler** [Azure/azure-spatial-anchors-samples#167]
Hi, I tried running it on my pocophone. i did put the right API keys 
But the ARReferencePoint counter is stuck at 0%
How can I tackle this?

**Comment by shivaylamba** [comment]
Hi @midopooler You can try to look at this documentation : https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@2.2/manual/reference-point-manager.html

**Comment by midopooler** [comment]
![WhatsApp Image 2020-05-12 at 7 03 13 PM](https://user-images.githubusercontent.com/43686606/81698477-a9494780-9483-11ea-99ee-75aeb0da7ba7.jpeg)
Actually this is the issue I'm facing here. It is not capturing my environment even after considerable amount of scanning. It's stuck at 0%.

**Comment by shivaylamba** [comment]
Oh okay, this seems to be a strange issue. @midopooler

**Comment by shivaylamba** [comment]
@vriveras Could you help

**Comment by darax** [comment]
Hi @midopooler could you set the ASA logging level in the scene you are testing to all, and share the logging output?

**Comment by midopooler** [comment]
Hi @darax , could you please help me explaining the term ASA logging level? provided that google search didnt helped me much.

**Comment by darax** [comment]
hey @midopooler,
Sorry, I should have made a screen shot. 
In unity
- Go to Assets\AzureSpatialAnchors.Examplse\Scenes and open the AzureSpatialAnchorsBasicDemo scene
- In the Hierarchy select the 'AzureSpatialAnchors' game object.
- In the Inspector, in the SpatialAnchorManager script, change the logging level from Warning to All.
![image](https://user-images.githubusercontent.com/15933792/83191769-6cb75600-a0e9-11ea-823a-07a093ce09b2.png)

then run the app on your device.  After the app starts, keep the device plugged into USB, and in the console tab switch from 'Editor' to AndroidPlayer on 127.0.0.1
![image](https://user-images.githubusercontent.com/15933792/83191944-a7b98980-a0e9-11ea-845d-c0bb19599e52.png)

if you do that all of our debug logging should show up in the unity console.   You can right click on the 'Console' tab itself to get the option to 'show editor log' which might be a more convenient way to get the logging data.
