### ISSUE TITLE
Delete an anchor by id without CloudSpatialAnchor / AnchorWatcher

### ISSUE THREAD

**Issue by tomkrikorian** [Azure/azure-spatial-anchors-samples#168]
Hello,

My use case is as follow : 
App A & App B use the same set of spatial anchors, if App A deletes an anchor i want to be able to tell App B to delete that anchor next time it's launched but without going through an AnchorWatcher / CloudSpatialAnchor.

Maybe i missed something but it seems not possible at the moment. Is there a way or is it planned to be able to delete an Anchor by providing an id and not going through the CloudSpatialAnchor object ?

Thanks !

**Comment by julianparismorgan** [comment]
Hey @tomkrikorian, to do this you'll want to first get the `CloudSpatialAnchor` object by calling `CloudSpatialAnchorSession.getAnchorPropertiesAsync(String identifier)`. Then you'll be able to call `CloudSpatialAnchorSession.deleteAnchorAsync(CloudSpatialAnchor anchor)`. This chain effectively lets you use the ID to delete the anchor. Let us know if this doesn't solve your issue!

https://docs.microsoft.com/en-us/java/api/com.microsoft.azure.spatialanchors.cloudspatialanchorsession.getanchorpropertiesasync#com_microsoft_azure_spatialanchors_CloudSpatialAnchorSession_getAnchorPropertiesAsync_final_String_

**Comment by tomkrikorian** [comment]
damn, can't believe i missed this. Thanks @julianparismorgan !
Do you think an API could be provided to delete anchors so we can cleanup anchors outside the SDK ?

**Comment by julianparismorgan** [comment]
No problem! For a suggestion like that, it would be awesome if you can post it to our UserVoice. We aren't super active on there, but we do watch it :) https://feedback.azure.com/forums/919252-azure-spatial-anchors

I'm going to close this if okay with you.

**Comment by tomkrikorian** [comment]
You can find the suggestion here : 
https://feedback.azure.com/forums/919252-azure-spatial-anchors/suggestions/40403953-delete-an-anchor-through-an-api-or-the-sdk-using-o
Thanks for your help, you can close my ticket 👍
