### ISSUE TITLE
UpdateAnchorPropertiesAsync not funtional

### ISSUE THREAD

**Issue by joelmaca96** [Azure/azure-spatial-anchors-samples#17]
When creating new properties for an anchor or updating existing ones, the app crashes without throwing any exception or error.

**Comment by vriveras** [comment]
Can you enable verbose logging on the SDK to get more details on what is going on. 

You can follow this article to enable [logging](https://docs.microsoft.com/en-us/azure/spatial-anchors/concepts/logging-diagnostics#configuration-of-log-messages)

**Comment by joelmaca96** [comment]
Sorry, I have fixed the error, I was trying to update the anchor with an invalid ID.

Thank you for your help.
