### ISSUE TITLE
Unable to delete some anchors

### ISSUE THREAD

**Issue by PeppyBjorn** [Azure/azure-spatial-anchors-samples#170]
I am having problems with some Anchors that cannot be deleted. They seem to be tied to a location but also for some reason is always detected very quickly and are placed incorrectly.

I walk to the site, search for anchors near device, almost immediatly these anchors get located (and placed haphazardly often ontop of me or 10meters away), then if I get all anchors nearby (including these) and delete them all. Other anchors are deleted correctly but when I start the watcher again it still finds these problematic anchors.

Is there some way to just purge all anchors on Azure portal?

(I have tried to bypass cache, reinstall uninstall app, tested different devices, removed all entries on Cosmos DB)

**Comment by weinanshen** [comment]
Hi @PeppyBjorn, currently it's not supported to delete anchors on Azure portal. You can upvote [here](https://feedback.azure.com/forums/919252-azure-spatial-anchors/suggestions/37107037-show-a-list-of-all-the-created-anchors-in-a-webpag) as feature request, if you haven't done it yet.

To investigate your issue further, could you provide the Anchor Ids of the problematic anchors, and
request/response CVs when deleting these anchors? You can find the CVs in the log.

Thanks!

**Comment by olenkapolak** [comment]
@PeppyBjorn any chance you would be willing to sync up about this issue? Been encountering and getting frustrated by similar issues and would love to talk to you about it olenka@Moetsi.com
