### ISSUE TITLE
Azure Spatial Anchors failing to save  

### ISSUE THREAD

**Issue by milligan21** [Azure/azure-spatial-anchors-samples#172]
Arghhhhhhhhh So.. I am using the sample from here for using and placing ASA on my phone ( android ) and everything... EVERYTHING works.. apart from the one thing that I need to work which is the placing of an anchor within Azure so that it is in the cloud. It is the local shared section of the example that I am trying to work out. If someone has this already completed on android and wants to share it with me .. that would be great :D "failed to store the anchor key using `https:PROJECT NAME / api/anchors"

I am new to Unity and have followed the instructions as best I could... this has me stumped! HELPPPPPPPPPPPP please :D

**Comment by SirisDracken** [comment]
I am not new to Unity, and I also cannot get this to work.

I have gone through the steps three times now, and it just fails to upload every time giving me the message: "Failed to store the anchor key using https://<app_name>.azurewebsites.net/api/anchors"

I removed my actual app name web address from this but I just cannot get it to work.  I have been trying for about three days now.

**Comment by milligan21** [comment]
Thought it was just me.. :D I am also on day 3 of this.. about to admit defeat!!!

**Comment by SirisDracken** [comment]
Yeah quite frustrating, I work at MS, I am escalating this issue right now.  I will let you know what I find out!

**Comment by milligan21** [comment]
Ah .. I used to work there also :D I am sure if i tried to escalate it they would ignore me ahahh The guy I was in touch with int eh US seems to have it figured out so.. if he finds something I missed then I will let you know !! He also said the instructions are a nightmare to figure out.

**Comment by julianparismorgan** [comment]
Hey @milligan21, a few questions:
- Are you able to get the Basic and Nearby demos working? 
- If it's the Shared demo that is not working, are you able to see your Swagger page successfully? I.e. [like here](https://docs.microsoft.com/en-us/azure/spatial-anchors/tutorials/tutorial-share-anchors-across-devices?tabs=VS%2CUnity#create-and-publish-the-web-app).
- Just to be certain, have you set the account id, account key, and SpatialAnchorSamplesConfig? Like [detailed here](https://docs.microsoft.com/en-us/azure/spatial-anchors/tutorials/tutorial-share-anchors-across-devices?tabs=VS%2CUnity#configure-the-account-identifier-and-key).
- Do you have device logs you could share? I am curious if it saving the CloudSpatialAnchor to ASA that is failing, or if it is saving the identifier to the web app that is failing.

@SirisDracken, would love to know the same from you, but you can also message me on Teams to speed up the conversation loop.

**Comment by SirisDracken** [comment]
Nope, I am unable to see the Swagger page.

**Comment by craigktreasure** [comment]
Hey everyone. It's not clear to me which instructions you're following and where exactly you're getting stuck. Are you following the instructions [here](https://docs.microsoft.com/en-us/azure/spatial-anchors/tutorials/tutorial-share-anchors-across-devices?tabs=VS%2CAndroid)?

It _sounds_ like you've got anchors being saved into Azure Spatial Anchors, but you're not able to persist the anchor Ids into your own Azure service to be shared with "others." Is that right? Are you able to check if anchors are being saved in your service using Swagger or by calling the `api/anchors/last` endpoint on your service?

**Comment by craigktreasure** [comment]
When publishing your Sharing Service to Azure, were you able to view your service in the web browser? See the screenshot [here](https://docs.microsoft.com/en-us/azure/spatial-anchors/tutorials/tutorial-share-anchors-across-devices?tabs=VS%2CAndroid#create-a-resource-group) for an example. Sounds like we need to get your Sharing Service running correctly.

**Comment by SirisDracken** [comment]
yep those are the exact instructions I followed
I am currently working directly with one of your peers, I think we should be able to solve it, and I will post the resolution here.

**Comment by SirisDracken** [comment]
No I am not able to see that screen shot when going to my URL, so there must be a step I missed in there, we are trying to figure that out now.

**Comment by milligan21** [comment]
Are you following the instructions here? YES
Ids into your own Azure service to be shared with "others." Is that right? YES
See the screenshot here for an example: I got that screen but didnt know what to do with it :D if i was supposed to enter something into swagger? No idea

**Comment by SirisDracken** [comment]
ok, we got mine to work, but I am a bit confused.

In Visual Studio after going through the Create and Publish steps, it takes you to a "sharing service" tab to show your all of your Publish settings.  I ended up hitting publish a second time, and this time it worked.  However I still have to manually go to 
"https://<myappname>.azurewebsites.net/swagger/index.html#/"

Going to "https://<myappname>.azurewebsites.net" does not automatically redirect me to that.

**Comment by craigktreasure** [comment]
@milligan21 Is your issue something similar perhaps?

**Comment by milligan21** [comment]
well its late here so i will see tomorrow..... I was doing mine in  visual studio code... I have 0 ideas about coding haha Dont even know where the publish button is :D

**Comment by milligan21** [comment]
@craigktreasure The answer is..... no.. still doesnt work for me. I can publish and all that .. add my url with teh /api/anchors at the end but still fails to save to the cloud. I can get it to work with someone elses URL but that was just as a test. So.. no idea

**Comment by milligan21** [comment]
I have another problem.. where I put a large enough scene in and when I locate it it does stay anchored.... it follows me when i walk! stupid

**Comment by milligan21** [comment]
> ok, we got mine to work, but I am a bit confused.
> 
> In Visual Studio after going through the Create and Publish steps, it takes you to a "sharing service" tab to show your all of your Publish settings. I ended up hitting publish a second time, and this time it worked. However I still have to manually go to
> "https://.azurewebsites.net/swagger/index.html#/"
> 
> Going to "https://.azurewebsites.net" does not automatically redirect me to that.

Yours is working now? :O Send me that guy to sort mine out

**Comment by SirisDracken** [comment]
Sorry, was out yesterday.  All we did was go over what I had done in the tutorial, and then I just said, well lets just hit publish again, and then it worked.  It is good to note that I wasnt even getting the Swagger page to come up, but that is resolved now.

Can you go through the steps with Visual Studio 2019 and see if that works for you?

**Comment by milligan21** [comment]
Oh thats ok :D I figured it out.. with the help of some guy who had it working in America ... The issue I was having was that the .NET 2.2 wasnt allowing the publish to work. So.... i downloaded VS2019 and published the shared service from there a few hours ago and now.. works!!! Unreal hahah was so close but yet so far.. happy now.. apart from my model following me.... No idea how to prevent that. Smaller models dont but I have a large scene and when I spawn it in AR it doesnt stay where i put it. More researching now...... Thanks for getting back to me :)

**Comment by SirisDracken** [comment]
oh great!  yeah that seems to be about the same issue I was having.  I am glad you got it working!  Good luck on the rest of your project!

**Comment by milligan21** [comment]
Same to you :) I am also glad.. that the nightmare is over on that section hahah

**Comment by weinanshen** [comment]
Hi @milligan21, great to see it's working for you! Please open a new issue if you still have the anchor not anchored problem. I'll close this one for now. Thanks!
