### ISSUE TITLE
CreateSessionAsync don't initialize Java class on release build, only on debug - Unity as an export

### ISSUE THREAD

**Issue by ericloureiro** [Azure/azure-spatial-anchors-samples#173]
I'm working with Azure Spatial Anchors in Unity as an export to an Android Flutter project.

Running debug build everything works as expected. 
However, a release build don't pass Java initialization - utillizing CreateSessionAsync method in SpatialAnchorManager.cs from SDK.
I don't get errors neither do crashes: The application continuous to play but without using ASA.

Plugin used to integrate Unity to Flutter:
https://github.com/Glartek/flutter-unity

Currently using the following buildTypes:
```
debug 
{
            debuggable true
}
release 
{
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-unity.txt', 'proguard-user.txt'
}
profile 
{
            matchingFallbacks = ['release']
}
```

My proguard-unity file:
```
-keep class bitter.jnibridge.* { *; }
-keep class com.unity3d.player.* { *; }
-keep interface com.unity3d.player.IUnityPlayerLifecycleEvents { *; }
-keep class org.fmod.* { *; }
-keep class com.google.androidgamesdk.ChoreographerCallback { *; }
-keep class com.google.androidgamesdk.SwappyDisplayManager { *; }
```

My proguard-user file:
```
-keep class com.glartek.flutter_unity.FlutterUnityPlugin { *; }
-keep class com.google.android.gms.common.api.GoogleApiClient { *; }
-keep class com.google.android.gms.common.api.GoogleApiClient$Builder { *; }
-keep class com.google.android.gms.common.api.GoogleApiClient$ConnectionCallbacks { *; }
-keep class com.google.android.gms.common.api.GoogleApiClient$OnConnectionFailedListener { *; }
-keep class com.google.android.gms.location.LocationServices { *; }
-keep class com.google.android.gms.location.LocationListener { *; }
-keep class com.google.android.gms.location.LocationRequest { *; }
```

I tried as a possible solution to add the Java class to my proguard-user file like: 
`-keep class com.microsoft.CloudServices { *; }`
or even
`-keep class com.microsoft.azure.spatialanchors { *; }`
 but then the application crashs and give me this generic error:
```
"UnityMain" prio=10 tid=16 Native
  at com.unity3d.player.UnityPlayer.nativeRender(Native method)
  at com.unity3d.player.UnityPlayer.access$300(unavailable:-1)
  at com.unity3d.player.UnityPlayer$e$1.handleMessage(unavailable:-1)
  at com.unity3d.player.UnityPlayer$e.run(unavailable:-1)
"UnityMain" prio=10 tid=18 Native
  at com.unity3d.player.UnityPlayer$e.run(unavailable:-1)
```

**PS**: I found the need to use minify/proguard because I was getting the two following errors - (thats a ARCore thing and not the focus of the problem, just to illustrate why I have to use minify/proguard): 
```
E/ARCore-LocationProvider: Exception during FLP api client construction: com.google.android.gms.common.api.GoogleApiClient
    java.lang.ClassNotFoundException: com.google.android.gms.common.api.GoogleApiClient
E/ARCore-LocationProvider: Can't find FLP class: com.google.android.gms.location.LocationServices
    java.lang.ClassNotFoundException: com.google.android.gms.location.LocationServices
```
This only happens in release too and even after adding implementation of those classes and their dependencies in build.gradle. After several research on Google the solution i came to was to use minify and add them in the proguard-user as above.

**Comment by marcotuna** [comment]
I'm having the same exact problem. Any solutions for this?

**Comment by msftradford** [comment]
Hi @ericloureiro, thanks for reaching out. I'm going to open an internal investigation (#30614582) to check this out. Have you been able to reproduce the issue with ASA SDK 2.7? As a reminder, starting in February 2021, [ASA SDK 2.7 will become the minimum version](https://github.com/Azure/azure-spatial-anchors-samples/releases/tag/v2.7.0).

**Comment by ericloureiro** [comment]
Hello @msftradford, thanks for your information!

Yes, unfortunately, I was able to reproduce the same issue with ASA 2.7.0 (previously reported on ASA 2.4.0)

Additional information:
1. ARCore error mentioned before is not happening with Unity 2019 .4.10f1 and ARFoundation/ARCore 4.0.8, so there is no need to use minify/proguard anymore;
2. Running `flutter run --release` works like a charm and also builds an APK that works on our devices too. Building with `flutter build apk` will not allow ASA services to be initialized. 

The workaround found by our team is to build an APK with `--no-shrink` flag enabled, this drawbacks us with a little additional weight in our application.

**Comment by msftradford** [comment]
@ericloureiro great to hear that you've discovered a workaround. I'm not familiar with the R8 optimizations that could be affecting ASA during the shrink, but it may just be removing some untraceable code. Are you still experiencing application crashes when proguarding the ASA-related and Unity-related classes?

**Comment by ericloureiro** [comment]
Proguarding ASA and Unity related classes are not crashing the application right now with ASA 2.7.0 and Flutter 1.20.4. 

What still happening is that the java initialization does not pass through `using (AndroidJavaClass cloudServices = new AndroidJavaClass("com.microsoft.CloudServices"))`

I'm not familiar with builds shrink optimizations neither, but as I could check, building for `arm_64` and `arm_7` gets the job done. 
I strongly guess that the problem is when these optimizations are done to `x86` builds.

If more information is needed, feel free to contact me.

**Comment by Varnauld** [comment]
Hello,
I closed this item as this was originally submitted close to two years ago. Our latest release is available [here](https://github.com/Azure/azure-spatial-anchors-samples/releases/tag/v2.12.0) – please re-open this item should you have further feedback for the team.
Alternatively, if you have any ideas or requests for new features or capabilities, or should you wish to upvote an existing idea, please visit our [Feedback hub](https://feedback.azure.com/d365community/forum/f47d9b25-0725-ec11-b6e6-000d3a4f07b8)

Thank you
