### ISSUE TITLE
Invalid GeoLocation data from PlatformLocationProvider on HoloLens 

### ISSUE THREAD

**Issue by anders-lundgren** [Azure/azure-spatial-anchors-samples#174]
I'm trying to create cross platform spatial anchors (HoloLens, iOS and Android) and would like to use a HoloLens for anchor creation. 
The plan is to use Coarse Relocation to get anchor candidates for the application. 
The application is intended for indoor use, so only inferred positioning will be possible on all platforms. 
This works reasonably well across iOS <-> Android, and also across UWP <-> Android. 
However, anchors do not seem to be discoverable between iOS and UWP (HoloLens).

When inspecting the anchor properties, all platforms claim that they can provide GeoLocation, and I find that the PlatformLocationProvider do provide correct location estimates on iOS and Android, but fails to produce sensible readings on HoloLens. 
This appears to occur when reading location data using ssc_cloud_spatial_anchor_session_get_location_provider(). 

The location data seems very odd, but not arbitrary, for instance, in one location, HoloLens consistently places the user at 180, 0, -6335440 (long-lat-altitude):
![image](https://user-images.githubusercontent.com/5128590/82488759-bea41e80-9ae0-11ea-81bd-87be222cac37.png)

Is there a way to get the PlatformLocationProvider to provide proper WGS coordinates on HoloLens, using inferred positioning like on the other platforms?

**Comment by bucurb** [comment]
Sorry, we do not support geo-location on Hololens. The device itself does not come with GPS hardware and the estimated GPS coordinates are just too imprecise. Hololens only supports Wi-Fi and BLE beacons for coarse relocalization. Android supports geo-location on top of Wi-Fi and BLE, while iOS only supports geo-location and BLE. For indoor use it seems like your best bet is deploying BLE beacons and using those instead - if you want a solution that is supported on all 3 devices.

**Comment by anders-lundgren** [comment]
Hi, okay, thanks, this is very interesting! I understand the rationale but I'm not sure I think the conclusion is valid in all cases. 
Case in point, the "Edge" web browser in HoloLens actually provides geo-location using inference (I'm assuming IP address in combination with Wi-fi and/or Bluetooth fingerprints). It is actually highly accurate, in my brief trials it can pinpoint my location within 20-50m, well within similar ranges that for instance Google or Apple can achieve. Is there any chance this will change in the future? Can I elect to "bring my own" georeferencing data ie using the Edge positioning data in my app when creating anchors on the HoloLens?

**Comment by jelmer3000** [comment]
Hey, did you ever find a solution for this? 
Or how can one provide GPS coordinates to Azure Spatial Anchors? IN the worst case scenario, I could type in GPS coordinates on the HL2 when creating anchors...
