### ISSUE TITLE
Anchor not getting saved in Cloud

### ISSUE THREAD

**Issue by PawanKotak** [Azure/azure-spatial-anchors-samples#176]
I have used the code provided in sample for SampleXamrin.Android. On saving anchor message is getting display saving cloud anchor but not able to see anchor created in my Azure Spatial Anchor Resource.

**Comment by chwarr** [comment]
There's currently no listing of anchors in the Azure Portal, if that's where you were looking at your ASA resource. (There are some [feature requests](https://feedback.azure.com/forums/919252-azure-spatial-anchors) in this area. If you see any that look useful to use, please vote for them.)

If you were trying to see the anchor somewhere else, can you talk more about the steps you're using?
