### ISSUE TITLE
Saving the Anchor in the Cloud throws Error

### ISSUE THREAD

**Issue by Bimod** [Azure/azure-spatial-anchors-samples#177]
Hello, im using the sample Scene for Android. Unfortunatly the apps throws some errors and does not save the Anchor into the cloud. I can place the anchor but after scanning it and reaching the 100% the app shows an error. Attached some of the errors that are shown. 
![Screenshot_20200527_213406_com microsoft azure spatialanchors examples unity helloar](https://user-images.githubusercontent.com/65503589/83065186-549cf380-a063-11ea-8bc1-bd8ab56dce5a.jpg)

**Comment by darax** [comment]
It might be useful to get the logging messages from the Unity Console. You can switch to the android player after starting the app.

![image](https://user-images.githubusercontent.com/15933792/83192309-30d0c080-a0ea-11ea-973d-99933938359e.png)

BTW, your screen shot is interesting... did you scrub your camera output for privacy or is it actually not there?

**Comment by Bimod** [comment]
Attached the log from the Console. I just block the camera for privacy reasons (my room is a mess). the camera output works. 
![log_AzureAnchorDemo](https://user-images.githubusercontent.com/65503589/83332489-c1023780-a29b-11ea-882a-77a7dc929c11.png)

**Comment by darax** [comment]
Thanks @Bimod,

It looks like Unity isn't finding the DLL, so there's some sort of issue building.  Since you are on 2020, you might try the instructions for 2019.3 here: https://github.com/Azure/azure-spatial-anchors-samples/issues/149.

**Comment by Bimod** [comment]
Since I am using th ARFoundation and ARCore 4.0.0 Packages, the scripts got updated and replaced already. Also the Android gradle script is updated with the correct Version number

**Comment by darax** [comment]
I got 2020.1 installed. I let Unity update the sample project from 2019.3 to 2020.1. I was surprised, but it mostly just worked.  I do need to figure out how to get arfoundation 4.0 to show up as an option in the package manager so I can be closer to your environment. You might try arfoundation 3.1, in case arfoundation 4.0 has broken a dependency our library relied upon.

**Comment by Bimod** [comment]
Sorry for the late reply. So i tried it again with Unity Version 2020.1. and ARFoundation 3.1.3 as well as ARCore 3.1.3 and still get shown an error message in the application and editor. Please find attached.
![log_AzureAnchorDemo2](https://user-images.githubusercontent.com/65503589/83975407-1b327680-a8f4-11ea-9734-a544ecf87dd5.png)

**Comment by darax** [comment]
are you using Unity Remote?

**Comment by Bimod** [comment]
yes i tried also the Unity Remote. But since the error comes directly after pressing play, Unity Remote never starts the actual game. The editor stops the playmode directly after pressing play. With the error message shown in the previous comment

**Comment by darax** [comment]
The next step might be to export the project to android studio and build from android studio.

**Comment by darax** [comment]
do you see a message like this:
<i>AndroidPlayer(ADB@127.0.0.1:34999)</i> Failed to load native plugin: Unable to load library /lib/arm/libazurespatialanchorsndk.so', error 'java.lang.UnsatisfiedLinkError: dlopen failed: library "libarcore_sdk_c.so" not found'?  

I just hit this. My phone has updated and I just updated android studio.

**Comment by darax** [comment]
Can you check to see if you have the ARCore plugin provider enabled? I'm not sure what might have unchecked that box in my project, but it was unchecked.  

![image](https://user-images.githubusercontent.com/15933792/84329264-20ccce00-ab39-11ea-83fd-882d31ef0000.png)

Also, if you dir /s *.so from the 'temp' folder in the unity project, you should see that libarcore_sdk_c.so is sitting next to libazurespatialanchorsndk.so
![image](https://user-images.githubusercontent.com/15933792/84329385-71442b80-ab39-11ea-9f5a-4022231d5f43.png)

**Comment by Bimod** [comment]
Hey,
i build the app withAndroid Studio and it worked actually. I could save the anchor and reload it. 
I also check the temp folder and i see the libarcore_sdk_c.so.
![libarcore_sdk](https://user-images.githubusercontent.com/65503589/84705165-4738a200-af5b-11ea-8840-4acc631344f5.png)

**Comment by craigktreasure** [comment]
@Bimod, is this issue resolved with @darax's suggestion?
