### ISSUE TITLE
Anchors get mixed up in indoor locations despite good wi-fi coverage

### ISSUE THREAD

**Issue by anders-lundgren** [Azure/azure-spatial-anchors-samples#179]
We're seeing some inconsistent behaviour in some of our client spaces, where certain anchors seem to get mixed up (ASA returning both anchor A and O, when in either location A or O: 
![image](https://user-images.githubusercontent.com/5128590/83395967-7dbeda80-a3fb-11ea-941a-9289227e8560.png)

This can be consistently reproduced using our own app as well as the example app in this repo). I'm not sure if this could be similar to the "spatial wormhole" behaviour you're mentioning in the docs when BLE beacons are misconfigured (https://docs.microsoft.com/sv-se/azure/spatial-anchors/concepts/coarse-reloc?tabs=csharp#enabling-bluetooth-beacons) ? No BLE beacons are deployed on these sites, however. 
I've checked the Wi-fi AP configuration, and it turns out that the client employs virtual access points, that is, the same SSID:s are present over each site, however, it is assigned to unique BSSID:s and each access point is on its separate channel. 
Is there a known limitation for using ASA in sites with multiple AP:s using the same SSID:s, or is there some potential misconfiguration on the Wi-fi network that we should be on the lookout for?

**Comment by darax** [comment]
For iOS, I believe using wifi for coarse reloc is very limited unless you have a certificate from apple that allows you to [enable Access Wifi Information.](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_networking_wifi-info)  

How physically far apart are these two locations? Are they visually similar?

**Comment by anders-lundgren** [comment]
I *think* the coarse reloc is working since I get all 15 anchors when querying using coarse reloc. Still learning my way around ASA so could be mistaken how things work, but it appears it's the next step, when the "watcher" is trying to match anchors, when it somehow consistently confuses two spots. The two spots in question are visually distinct to the naked eye, although they do have some visual features in common, such as the shape and size of crates on the floor, some visual signs etc. 
Is there a way to put more strict requirements on watchers before they are allowed to declare a match, to avoid false positives? Or is this some kind of warping/folding/wormholing of the spatial representation of the area?

**Comment by darax** [comment]
Coarse reloc is probably working, but it is relying on GPS signal indoors. 

This sounds like a possible wormhole.  If you can, there is a diagnostics API that will save the images we use to locate the spatial anchors so we can understand the issue better.  It is a little work to setup.  it is documented here: https://docs.microsoft.com/en-us/azure/spatial-anchors/concepts/logging-diagnostics

If you can do this, capture a log from both locations.  In the code snippet showing how to submit a diagnostics bundle a 'path' is created. That path contains a guid that we can use to access the logs on our end. Record that path somehow. On iOS I think you can monitor the Debug.logs through the xcode device console, but I'm not well versed on iOS.  If not, you can write to the file system and enable https://developer.apple.com/documentation/bundleresources/information_property_list/uifilesharingenabled in your xcode project.  
Then attach this script to a GameObject in the scene:
[DebugFileLogger.zip](https://github.com/Azure/azure-spatial-anchors-samples/files/4718979/DebugFileLogger.zip) 

PM me the paths and I'll work with the team to see what's going on.

**Comment by anders-lundgren** [comment]
Thank you @darax . I added the code for capturing images and sent these to the provided endpoint, unfortunately it turns out I didn't capture the actual path in the log file. I have sent you an email with the RespCV of the SubmitDiagnosticsAsync() request, in the hope there is a way this can be used at your end to retrieve the logs instead of the paths? Otherwise let me know and I'll run more tests and capture the proper path.

**Comment by anders-lundgren** [comment]
Update: we decided to run another series of tests in the same space again today, so I now have what I believe are correct (local) paths that contain a GUID in the filename. Have emailed you the paths and some screenshots @darax.

**Comment by msftradford** [comment]
Hi @anders-lundgren, it looks like some work on this issue may have been taken offline. I'm going to go ahead to close the issue, but feel free to re-open if we have more digging to do. thanks!
