### ISSUE TITLE
Appcrash in locationProvider after saving 3 anchors in one session with Coarse Relocation

### ISSUE THREAD

**Issue by anders-lundgren** [Azure/azure-spatial-anchors-samples#182]
I consistently experience app crashes when attempting to save multiple anchors in a single session, using a locationProvider with Wifi, BLE and Location Services. I can replicate the behaviour on Android, iOS, and UWP (x86). 

The reason that I'm trying to save multiple anchors in a single session is that I'm preparing a large space, approximately 5000 sqm, and the anchors are quite far apart, 10-20m. I'm also storing approximately 1 kB of AppProperties data along with each anchor. 

I have traced the error on iOS to appear around this line: 

![image](https://user-images.githubusercontent.com/5128590/83808371-f3090480-a6b4-11ea-9d71-84b04b892fc0.png)

The error message on iOS is as follows:
![image](https://user-images.githubusercontent.com/5128590/83808510-32375580-a6b5-11ea-896f-1012affac6c7.png)

Furthermore, I have noticed that if I query the locationProvider for status updates, the app usually crashes after saving the second anchor. 

I have tried to ensure that all Unity methods are called from the main thread, assuiming that all processing of ASA callbacks happen in background threads. 

I even rewrote the multiple anchor behaviour into the sample demo app "Coarse Reloc" in this repo, with the same result.

Using the latest version of ASA (2.2.1) and compatible versions of ARKit and ARCore. Unity 2019.2.17.

**Comment by anders-lundgren** [comment]
> Hi @anders-lundgren. I intended to forward this post to a co worker last week and failed to follow through. I've reread the issue and I'll try to reproduce it myself. I have a question about multiple-anchors. Are you creating these anchors sequentially or in parallel? I'm going to assume sequentially for my first repro attempt.

Hi @darax , thanks a lot! I am creating the anchors sequentially, but in a single session.

**Comment by darax** [comment]
Great.  I tried, and did not hit a repro.  I still need to add polling of the location provider for status updates to see if that preturbs something.  I also don't have quite as spacious an environment.

here's how I changed the coarse reloc sample to place multiple anchors:
`int anchorsPlaced = 0;

        protected override async Task OnSaveCloudAnchorSuccessfulAsync()
        {
            await base.OnSaveCloudAnchorSuccessfulAsync();

            Debug.Log("Anchor created, yay!");

            // Sanity check that the object is still where we expect
            Pose anchorPose = Pose.identity;

#if UNITY_ANDROID || UNITY_IOS
            anchorPose = currentCloudAnchor.GetPose();
#endif
            // HoloLens: The position will be set based on the unityARUserAnchor that was located.

            SpawnOrMoveCurrentAnchoredObject(anchorPose.position, anchorPose.rotation);
            
            anchorsPlaced++;
            if (anchorsPlaced > 5)
            {
                currentAppState = AppState.DemoStepStopSession;
            }
            else
            {
                spawnedObject = null;
                currentCloudAnchor = null;
                enableAdvancingOnSelect = true;
                currentAppState = AppState.DemoStepCreateLocalAnchor;
            }
        }`

**Comment by anders-lundgren** [comment]
Ok, yes, if you have the opportunity, please try adding a watcher using NearDeviceCriteria as I find that it is only then that this behaviour is triggered.

**Comment by pabusse** [comment]
Hi @anders-lundgren,

We believe we have identified the issue and a fix will be included in the next SDK release.

In the meantime, you should be able to avoid the crash by saving a reference to the newly constructed PlatformLocationProvider in a member variable and using that to access the sensor status instead of session.LocationProvider.

Let me know if you still experience any crashes after making sure your code is not reading the LocationProvider property of the session anywhere, and I will be happy to dig in further.

**Comment by craigktreasure** [comment]
Thanks @pabusse! I'm going to close this since @pabusse has provided a workaround. The underlying issue should be fixed in our next release. @anders-lundgren, feel free to reopen the issue if you have further related issues.
