### ISSUE TITLE
400 response from spatial anchors service when querying from HoloLens 1

### ISSUE THREAD

**Issue by anders-lundgren** [Azure/azure-spatial-anchors-samples#183]
I'm scanning a large space (~5000 sqm) using HoloLens 1 to place spatial anchors. The process mostly works well, but occasionally I receive a 400 response from the spatial anchors service. After this, the only remedy I've been able to find is to reboot the HoloLens, after which the queries start working again. 
Since the space is large, I'm wondering if this may be related to the spatial mesh exceeding some maximum size?

**Comment by chwarr** [comment]
Do you have any RespCV values in your logs that you can share? We can use those values to figure out the details of the 400 response. (A [CV (correlation vector)](https://github.com/Microsoft/CorrelationVector) is a base64 encoded GUID with some counters attached to it. It doesn't contain any sensitive content, so feel free to post them here.)

**Comment by anders-lundgren** [comment]
Request
tpNwai6xRt6kH9eXO/EYIQ.
Response
tpnwai6xRt6kH9eXO/EYIQ and 
bg86FhyMi0av5SH7XfF5ZQ.0
at
NativeLibraryHelpers.CheckStatus

Read from HL1 screenshot, I hope I got the values correct:
![image](https://user-images.githubusercontent.com/5128590/83855485-6d1ea500-a718-11ea-8b1b-83f72f50f66d.png)

**Comment by anders-lundgren** [comment]
Additional observations after today's testing using HoloLens 2 instead of HoloLens 1. 
The same error message appears, but this time I noted two things: 
1. The spatial mapping in HL2 stops working in the holographic shell after the app crashes. (starts working again after a reboot of the HL2). This does not happen on HL1. 
2. I am running a concurrent session on an Android device, with a watcher attached to the same anchor account. When I receive the 400 error on HoloLens, I immediately after receive a "Service Unavailable" error on the Android device. 

I notice there are some indication of memory corruption on HL2 after running the app for some time (have seen similar issues before). The text on top should say "Saving...":
![image](https://user-images.githubusercontent.com/5128590/83874720-3b1c3b80-a736-11ea-8ec9-9478b994f76b.png)

Both the HoloLens and the Android phone are connected over a portable wifi tether (second phone with 4G/LTE), not sure if that matters. I have tested using it for regular browsing during these tests to verify it was working correctly. 

Some more RespCVs:
i+U5WxyVRX+NxYpHR+577w
ZUZfwiJX6U2Py7LpNoGskA.0.
![image](https://user-images.githubusercontent.com/5128590/83874389-a9143300-a735-11ea-8077-80c760e98984.png)

OXicLN06ScWRWTxWMBlvDQ.
ZGwPgrGkxkKtIKSf0PpfvA.0.
![image](https://user-images.githubusercontent.com/5128590/83874553-f690a000-a735-11ea-8fda-f8ab32f93ab5.png)

**Comment by chwarr** [comment]
Thanks for the details. I was able to find the requests and see the 400 Bad Request responses. Another person on the Spatial Anchors team is going to need to look at these to figure out what's going on, as it's from a component that I don't work with on a regular basis. I've sent them the details. Their weekend has already started, so please give them a few days to respond.

**Comment by chwarr** [comment]
We think we have a fix for this. We're validating it before deploying it.

**Comment by chwarr** [comment]
We've deployed an initial server-side fix for this. Please try again and let us know if you still see 400s.

**Comment by anders-lundgren** [comment]
I have tried again, in a smaller space, only 1500 sqm or so, and no 400s. Unfortunately, the service still failed four times over the run of two hours, this time the exception appears to be something in the local DLL not parsing the response properly, since the exception data address references were all 0x0.

**Comment by chwarr** [comment]
Good to hear that the 400s are gone. For the other exceptions, do you have logs & stack traces you can share here?

FYI, @pabusse, who's been fixing a few bugs in this area in the past couple of days.
