### ISSUE TITLE
Unable to authenticate towards ASA account in West Europe

### ISSUE THREAD

**Issue by anders-lundgren** [Azure/azure-spatial-anchors-samples#184]
I created a new ASA account in the new West Europe region. 

When attempting to authenticate using the API key, the app fails with status ApplicationNotAuthenticated. 

Is there a base URL for the different regions that we need to apply before authenticating? 

Using version 2.2.1 of the SDK, and Unity 2019.2.17.

**Comment by pabusse** [comment]
Hi Anders,

You will need to set the AccountDomain property of the session to the value displayed in the Azure Portal. For the West Europe region, this should be westeurope.mixedreality.azure.com.

**Comment by anders-lundgren** [comment]
Thanks, that was it! I understand multi region support is a brand new feature, I think it would be great to add a note about this in the docs for the spatial anchors samples tutorial!

**Comment by ICSmibauer** [comment]
Ok, I changed to AccountDomain to EastUS2 and now it seems to work. But therefore Photon Unity stops working for me... Both Hololens are in ther own room. Very frustrating at all...

**Comment by anders-lundgren** [comment]
Are you following the HoloLens 2 tutorial for spatial anchors? I found that it creates random rooms and if you restart within 10 minutes the devices get placed in different rooms... Quick solution/workaround is to quit the app on all devices, wait 10+ mins and try again, but I rewrote the example to create a persistent room instead which worked much better.

**Comment by ICSmibauer** [comment]
Yes I did. It works now, after changing Unity back to 3.15 and AR Foundation to 2.1.8.

Could you explain how you rewrote the example to create a presistant room? Thanks!
