### ISSUE TITLE
Problem with the ASA Quickstart on Hololens 2

### ISSUE THREAD

**Issue by Baesm** [Azure/azure-spatial-anchors-samples#186]
On using this guide (https://docs.microsoft.com/de-de/azure/spatial-anchors/quickstarts/get-started-unity-hololens) I am able to deploy the appication, but as soon as the anchors are getting uploaded to the cloud, the app throws an error. 

The Error in the app states: 
`Error: Serivce unavailable or unspecified error found`

Unity Version 2019.1.10f1
Visual Studio 2019 16.5.5

I have tried the typical fixing methods from trying a new network to reset access keys in Azure. In the logs there seems to be an underlying issue to it. 

Extended logs from Visual Studio can be found here:
[ASAQuickstart.log](https://github.com/Azure/azure-spatial-anchors-samples/files/4792884/ASAQuickstart.log)

**Comment by craigktreasure** [comment]
Hey @Baesm, are you still able to repro this? I am not able to reproduce this issue on the Basic Demo when using Unity 2019.2.21f1. It could have been a transient issue. Please try again using the version of Unity you were using. If you're still having issues, you might try a newer build of Unity. If you continue to have issues, please let us know.

**Comment by Baesm** [comment]
A newer Version of unity fixed this problem!
