### ISSUE TITLE
Authentication issues due to missing account domain

### ISSUE THREAD

**Issue by kaysabelle** [Azure/azure-spatial-anchors-samples#189]
We've recently made some changes to configuring account information. If you're running into an issue where the application could not authenticate, ensure that you are providing the correct account domain. This can be found in the Azure Portal when viewing your Spatial Anchors Account resource:

![image](https://user-images.githubusercontent.com/5252186/85067172-1a57db00-b165-11ea-9f0c-11cca90c4afd.png)

You'll need to provide this account domain in your CloudSpatialAnchorSession configuration.

We've updated our documentation to reflect this change:

[Unity/HoloLens](https://docs.microsoft.com/en-us/azure/spatial-anchors/quickstarts/get-started-unity-hololens#configure-the-account-identifier-and-key)
[Unity/Android](https://docs.microsoft.com/en-us/azure/spatial-anchors/quickstarts/get-started-unity-android#configure-account-identifier-and-key)
[Unity/iOS](https://docs.microsoft.com/en-us/azure/spatial-anchors/quickstarts/get-started-unity-ios#configure-account-identifier-and-key)
[HoloLens](https://docs.microsoft.com/en-us/azure/spatial-anchors/quickstarts/get-started-hololens#configure-account-identifier-and-key)
[Android](https://docs.microsoft.com/en-us/azure/spatial-anchors/quickstarts/get-started-unity-android#configure-account-identifier-and-key)
[iOS](https://docs.microsoft.com/en-us/azure/spatial-anchors/quickstarts/get-started-unity-ios#configure-account-identifier-and-key)

**Comment by unrealmitch** [comment]
Sovled in this pull request (just Unity): #196

**Comment by craigktreasure** [comment]
This was resolved in the [2.4.0](https://github.com/Azure/azure-spatial-anchors-samples/releases/tag/v2.4.0) release.
