### ISSUE TITLE
Creation failed

### ISSUE THREAD

**Issue by masaldana2** [Azure/azure-spatial-anchors-samples#19]
exception causing failure: std::exception

I implemented the keys and run it successfully, 
but When i try to save the anchor of the cube it fails. 
xcode 10.1 
ipad 2017

**Comment by vriveras** [comment]
@masaldana2 , Can you share the logs of the application when it fails?

**Comment by Alberto-Vega-MSFT** [comment]
@masaldana2 any updates on this?

**Comment by vriveras** [comment]
Closing issue no response
