### ISSUE TITLE
Cannot create the neighborhood anchor

### ISSUE THREAD

**Issue by christopheryang90** [Azure/azure-spatial-anchors-samples#190]
`AndroidPlayer(Google_Pixel_3a_XL@192.168.1.210) [MobileNeighborhoodManager::CreateAtCurrentLocation] Cannot create the neighborhood anchor since no frame has been provided so far.`

I'm getting this error on my spatial anchor app today, it was working fine just yesterday.
I did also get a messages about "too many requests coming from your account, your account will now be throttled" a few days ago, but now that message is gone now and the only error i get is the above one.

Is this due to the amount of usage from my account? I have merely created about a dozen  or so anchors mostly in my room. Not sure why my account is marked as having high usage. Let me know if it would help to provide my anchor account details. 

Thanks for looking into this for me!

**Comment by chwarr** [comment]
Throttling occurs based on the number of requests to the service (e.g., anchor creations attempts, getting anchor properties, locating anchors) and is measured in minutes, not days. Throttling that happened a few days ago will not affect anything today, nor will the total number of anchors you have created.

E.g., if you're throttled one minute, wait for a minute, and try again. If you get throttled again, check the app logic to see if it's creating a lot of watchers, or requesting a lot of anchor properties, or creating a lot of anchors.

I work on the service, and I don't have enough experience to help with the error you've reported. One of my colleagues who better understands the client-side frame collection will need to help you. They should be able to get to this within a couple of days.

**Comment by craigktreasure** [comment]
@christpheryang90 Are you still having issues on your Android app?

**Comment by christopheryang90** [comment]
It went away after sometime, perhaps something related to restarting my phone or a phone software update. Thanks!
