### ISSUE TITLE
Getting Exception While Executing

### ISSUE THREAD

**Issue by nishant199** [Azure/azure-spatial-anchors-samples#192]
I tried to run the Unity3D basic demo (code build from master Azure Spatial Anchor Sample) on Unity3D Android (Samsung S9 Android Version 8.0),But  got an exception when saving anchors to cloud.

![Screenshot_20200622-211903_HelloAR U3D](https://user-images.githubusercontent.com/26568894/85767749-f46aa180-b735-11ea-9612-9811d776a5c6.jpg)

**Comment by craigktreasure** [comment]
Hey @nishant199. Can you provide information about the version of Unity you're building with?

**Comment by craigktreasure** [comment]
Also, are you still able to reproduce this?

**Comment by nishant199** [comment]
> Hey @nishant199. Can you provide information about the version of Unity you're building with?

I am Using Unity3D 2019.2.0f1

**Comment by nishant199** [comment]
> Also, are you still able to reproduce this?

Yes.. Still getting

**Comment by SatishBoddu-MSFT** [comment]
@nishant199 Could you please confirm if this issue is resolved from your side or if you need further help in this matter, so that we can close the same thread on [Microsoft Q&A.](https://docs.microsoft.com/en-us/answers/questions/39912/index.html)
