### ISSUE TITLE
ServerError when saving anchors

### ISSUE THREAD

**Issue by tomkrikorian** [Azure/azure-spatial-anchors-samples#193]
Hi,
I'm getting a lot of server error when saving multiple anchors. (not using the sample btw, using the SDK in our app).
When i save the first anchor, it goes usually fine but then i cannot save more anchors during the session. Most of them return a ServerError code like this : 

`OnSaveCloudAnchorFailed: Failed to save anchor : System.Exception: Cloud spatial exception error code is ServerError with Message  [ Request is 2vBHxxhIQ/O8fkrFdOd4Bg and Response is  ] ---> Microsoft.Azure.SpatialAnchors.CloudSpatialException`

Same code worked fine last week, are there issues with the Azure Spatial Anchors service ?

**Comment by craigktreasure** [comment]
Hey @tomkrikorian. Sorry to hear you're having issues like this. Please let me know if you can still reproduce this issue. If so, we'll escalate and take a look. Thanks!

**Comment by tomkrikorian** [comment]
Reproduced the issue multiple times. Same logs as the one from my first comment. Seems to happen a lot when on a Wifi connexion.

**Comment by craigktreasure** [comment]
What platform are you using? Android, iOS, HoloLens (1 or 2), Unity (iOS\Android\HoloLens)?

**Comment by tomkrikorian** [comment]
Test was done on Android (Unity) but we're using all platforms. I'll be able to test on all platforms next week to try and reproduce the issue again.

**Comment by craigktreasure** [comment]
What version of Unity?

**Comment by tomkrikorian** [comment]
Unity 2019.2.21f1

**Comment by craigktreasure** [comment]
Hey @tomkrikorian. Would you mind trying with ASA 2.4.0 using Unity 2019.4? We just released a new build today. We've experienced a lot of bugs in the older Unity 2019 builds and many are fixed in Unity 2019.4. I'm curious if you still have the issue in a more recent release.

**Comment by tomkrikorian** [comment]
Hey @craigktreasure :
I'll try to update our App to use 2.4.0 in the coming month and get back to you on this. :)

**Comment by tomkrikorian** [comment]
I updated to 2.4.0, now i don't get the ServerError but NotEnoughSpatialData :
`Cloud Spatial Anchor Session found Error : Not enough Neighborhood Spatial Data was available to complete the desired create or update operation  with Error Code NotEnoughSpatialData`

i do wait for `spatialAnchorManager.IsReadyForCreate && spatialAnchorManager.SessionStatus.ReadyForCreateProgress > 1` before calling CreateAnchorAsync

I'm currently trying on Android with Unity 2019.4.8f1 (ARFoundation 4.1 & ARCore 4.1 packages)

**Comment by kaysabelle** [comment]
Hi @tomkrikorian, glad to hear it's working after an update to 2.4.0. I'm going to close this issue now.
