### ISSUE TITLE
Cannot set expiration time of more than 7 days

### ISSUE THREAD

**Issue by avi4gravity** [Azure/azure-spatial-anchors-samples#194]
Not sure if this is supported, but when we set the cloud anchor expiration to be 1 year (which is needed for our business case), we have not been able to resolve our anchors after 7 days.

Anything specific that needs to be done to support cloud spatial anchors for more than 7 days.

Platform: iOS

**Comment by craigktreasure** [comment]
Hey @avi4gravity. Thanks for reporting your issue. First thing to double check is that you're setting the expiration value properly (you've probably done this, but please double check). Also, just to clarify, are you using Unity iOS or native iOS?

**Comment by avi4gravity** [comment]
was a problem on my end...subclass was overriding the expiration time

**Comment by qazqaz12378** [comment]
How to set permanent storage without automatic expiration
