### ISSUE TITLE
[Bug] AnchorLocated event is not invoked from unity main thread.

### ISSUE THREAD

**Issue by rubit0** [Azure/azure-spatial-anchors-samples#195]
The AnchorLocated event from SpatialAnchorsManager is not invoked from the unity main thread which forces the callback handler to be wrapped by UnityDispatcher. See same issue here: https://github.com/Azure/azure-spatial-anchors-samples/issues/150

To be a good Unity citizen, all events must be invoked on the Unity main thread, this is an expected behavior from third party libraries.

**Comment by craigktreasure** [comment]
Thanks @rubit0. We don't currently guarantee the thread the callback is made on. This is something we want to fix in the future to, as you said, be good Unity citizens. It's certainly on our backlog.

Thanks!
