### ISSUE TITLE
Remote debugger failing from incompatible deployment target

### ISSUE THREAD

**Issue by WalkerNoviqu** [Azure/azure-spatial-anchors-samples#198]
Hello, I am currently going through Microsoft's tutorial on spatial anchors and am receiving this error when trying to remotely deploy the sample app to my hololens first gen. When I try to update the OS on the hololens, I'm told I have the latest version. I'm using Unity 2019.1.10. Any help would be appreciated, thank you.

![Screenshot (12)](https://user-images.githubusercontent.com/68605454/88077211-9f595a00-cb40-11ea-887e-6f83d8d5d042.png)

**Comment by kaysabelle** [comment]
Hi @WalkerNoviqu,

Sorry to hear you're having issues. 

First, you should add the IP address of your HoloLens under "Machine Name" in the debugger settings of the HelloARU3D project:

![image](https://user-images.githubusercontent.com/5252186/88091703-48ee1a80-cb44-11ea-882b-7a04f1a48ff7.png)


After adding the IP address in the project debugger settings, try deploying again and see if that works for you.

Alternatively, if remote deployment is still not working after this, you can plug your device in and deploy over USB using the "Device" deployment target.

Please let us know if you can still reproduce the issue after trying the above solutions.

**Comment by WalkerNoviqu** [comment]
Hello, I did already set the Machine Name, and I tried to launch over Device and I get the same error for incompatible deployment target. I see the more info needed tag was added, what more information would you like?

**Comment by kaysabelle** [comment]
Another thing to check - can you make sure that "HoloLens" is selected as the target device in the Build Settings window when building in Unity?

![image](https://user-images.githubusercontent.com/5252186/88228862-a6f22f00-cc24-11ea-82c6-629ea65edddd.png)

**Comment by WalkerNoviqu** [comment]
It is, every menu option that the tutorial asked to change was changed

**Comment by kaysabelle** [comment]
Understood. Can you make sure that your Minimum Platform Version is set to 10.0.10240.0 and let me know if that works?

I was able to get the same error message on my own machine setup. This happens when setting the Minimum Platform Version to something higher than the HoloLens OS version. I've filed a bug for us to update the documentation to make these instructions more explicit (internal bug #27864880).

**Comment by WalkerNoviqu** [comment]
Ok, I checked and it was correctly set to minimum version 10.0.10240.0. I re built the application and ran into the same error. Does it need to be set in visual studio as well?
![Screenshot (31)](https://user-images.githubusercontent.com/68605454/88302077-073bac00-cccb-11ea-9774-b7730e2b9d98.png)
![Screenshot (33)](https://user-images.githubusercontent.com/68605454/88302082-09056f80-cccb-11ea-9d96-aaf928c0ede5.png)

**Comment by kaysabelle** [comment]
Yes, please double-check in Visual Studio that the minimum platform target is set to 10.0.10240.0 in the General project settings as well:

![image](https://user-images.githubusercontent.com/5252186/88419142-75e73b00-cd99-11ea-8f13-3c8b8b17995c.png)
