### ISSUE TITLE
Cannot Save Created Anchor

### ISSUE THREAD

**Issue by DrScatman** [Azure/azure-spatial-anchors-samples#199]
**When I attempt to save a cloud anchor my device crashes with no error message**

Are Azure Spatial Anchors East US 2 servers down? When I go to my resource group some things are failing to load in, such as my access keys are all blank??

When looking at the charts anchor creation events seem to have stopped working entirely at 12:00 pm today (7/31/2020)

**Screenshots**

![image](https://user-images.githubusercontent.com/49825641/89080715-a873d380-d357-11ea-8f41-60104e77d372.png)
![image](https://user-images.githubusercontent.com/49825641/89080790-de18bc80-d357-11ea-8f59-89e73a1cede7.png)

**Development information (please complete the following information)**

 - OS: Windows
 - Development Platform\Version: Unity 2019.2.17f1
 - Azure Spatial Anchors SDK version: 2.2.1

**AR Device information (please complete the following information):**

 - Device: iPhone 8
 - OS: iOS 13

**Comment by chwarr** [comment]
The Azure Spatial Anchors services in East US 2 experienced network connectivity failures from approximately 2020-07-31 22:00Z to 23:00Z. These failures caused issues like those you reported.

This underlying issue has been fixed, and we are performing an analysis to understand what we can change to reduce the likelihood and impact of issues like this in the future.
