### ISSUE TITLE
Android build issue in Unity

### ISSUE THREAD

**Issue by roelkok** [Azure/azure-spatial-anchors-samples#20]
When I use the `AzureSpatialAnchors.unitypackage` the following section in `mainTemplate.gradle` gives me a build error.

```
maven {
  url 'https://microsoft.pkgs.visualstudio.com/_packaging/Analog.SpatialServices/maven/v1'
    credentials {
      username "VSTS"
      // Put the access token VSTS provides in your gradle.properties as "azureArtifactsGradleAccessToken=<AccessToken>"
      password System.getenv("AZURE_ARTIFACTS_ENV_ACCESS_TOKEN") ?: "${azureArtifactsGradleAccessToken}"
    }
}
```

If I remove it, the build will complete successfully. I also noticed that this section is absent in the source from the repo.

**Comment by vriveras** [comment]
@roelkok , There was a problem with the publish Unity package this has been fixed now. You can re-import the package and this problem should be fixed

**Comment by Alberto-Vega-MSFT** [comment]
@roelkok Was your issue resolved?

**Comment by roelkok** [comment]
I just imported the most recent unity package in my project and I can confirm it now builds successfully.
