### ISSUE TITLE
Unclearness about the pricing

### ISSUE THREAD

**Issue by FelixRoh** [Azure/azure-spatial-anchors-samples#200]
Hey Guys,
I saw that you changed the official ASA pricing site.
- Begining of the last week you wrote 10000 for free by month.
- Last Thuresday evening you changed it "... Spatial Anchors locate requests will remain free of charge until further notice.".

The new pricing sounds good. My problem is the remark "further notice" because in the moment we are in the go live phase of a customer project and we have to be sure about the pricing. Maybe you can bring up a bit of clearness about this topic.

Feel free to contact me direct via mail (see Profil).

**Comment by craigktreasure** [comment]
@vriveras to see if he can offer some clarity.

**Comment by vriveras** [comment]
Hi @FelixRoh, 

We are doing a final revision in the pricing before we start charging in the next few months. Please look for another email from us and updates on the pricing page in the coming month announcing this. 

To summarize ASA will charge by anchors queried as stipulated in the previews email and we will announce the specific tiers pricing in the [product page](https://azure.microsoft.com/en-us/pricing/details/spatial-anchors/). 

Thanks, 
Vicente

**Comment by FelixRoh** [comment]
Hi Vicente,
thanks for the replay. Hopefully I got the right mail Adresse. If yes you will find my answer in your in box.

Best,
Felix
