### ISSUE TITLE
Suggestion : Update to Windows XR Plugin for next version.

### ISSUE THREAD

**Issue by tomkrikorian** [Azure/azure-spatial-anchors-samples#201]
SDK 2.4.0 has been updated but still relies on the old XR system of unity with the WindowsMR package (https://docs.unity3d.com/Packages/com.unity.xr.windowsmr.metro@4.2/manual/index.html).
This package will be unusable in 2020.1 and so will the ASA SDK. Next update of your SDK should use the the new Windows XR Plugin (https://docs.unity3d.com/Packages/com.unity.xr.windowsmr@4.0/manual/index.html) to allow projects that need to use the new XR plugin to be be able to use ASA SDK.

I opened a ticket on your suggestion platform for this :
[https://feedback.azure.com/forums/919252-azure-spatial-anchors/suggestions/41095288-update-unity-sdk-to-use-new-xr-plugin-instead-of-w](https://feedback.azure.com/forums/919252-azure-spatial-anchors/suggestions/41095288-update-unity-sdk-to-use-new-xr-plugin-instead-of-w)

**Comment by craigktreasure** [comment]
Yes. We're aware of this and may resolve it in an upcoming release.
