### ISSUE TITLE
I got exception when update SDK version from 2.2.1 into 2.4.0 on iOS

### ISSUE THREAD

**Issue by skypu3** [Azure/azure-spatial-anchors-samples#203]
Hi,

I got the issues when updating SDK, however 2.2.1 version is fine
My Unity version is 2019.4.2f1
ARFoundation is preview.2 4 - 4.1.0

ARSession not yet available (SessionInitializing, will complete initialization when session is running
LogException @ /Users/runner/work/1/s/SpatialServices/API/src/iOS/ARKitPlatformSession.mm:18, SpatialServices::ARKitPlatformSession::ARKitPlatformSession(ssc_platform_session_handle) : Assertion failed: m_platformSessionHandle != nullptr
CallStack:
ReposeStackWalker is not supported on this platform :-(
2020-08-09 16:22:00.630185+0800 test[33940:5446520] exception causing failure: LogException @ /Users/runner/work/1/s/SpatialServices/API/src/iOS/ARKitPlatformSession.mm:18, SpatialServices::ARKitPlatformSession::ARKitPlatformSession(ssc_platform_session_handle) : Assertion failed: m_platformSessionHandle != nullptr
CallStack:

**Comment by skypu3** [comment]
The issue also was happened on ARFoundation 3.1.x

ARSession not yet available (SessionInitializing, will complete initialization when session is running
Microsoft.Azure.SpatialAnchors.Unity.SpatialAnchorManager:<ResetSessionAsync>b__48_0()
System.Net.Http.Headers.HttpHeaders:SetValue(String, T, Func`2)
Microsoft.Azure.SpatialAnchors.Unity.SpatialAnchorManager:CreateSessionAsync()
Argo.Cloud.Anchor.App.<>c__DisplayClass23_0:<OnCloudAnchorLocated>b__0()
System.Net.Http.Headers.HttpHeaders:SetValue(String, T, Func`2)
Argo.Cloud.Anchor.App.SpatialAnchorsScript:AdvanceDemoAsync()
Argo.Cloud.Anchor.App.<>c__DisplayClass68_0:<CloudManager_Error>b__0()
System.Net.Http.Headers.HttpHeaders:SetValue(String, T, Func`2)
Argo.Cloud.Anchor.App.AnchorScriptBase:AdvanceDemo()
Argo.Cloud.Anchor.App.AnchorScriptBase:GetScanPlanesStatus()
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

LogException @ /Users/runner/work/1/s/SpatialServices/API/src/iOS/ARKitPlatformSession.mm:18, SpatialServices::ARKitPlatformSession::ARKitPlatformSession(ssc_platform_session_handle) : Assertion failed: m_platformSessionHandle != nullptr

**Comment by skypu3** [comment]
The issue might is to call `CloudManager.CreateSessionAsync()` when app starting, however the sample code didn't have this issue because `CloudManager.CreateSessionAsync()` is called by button (next button)
So, the issue is happened occasionally, and timing conflict on ARSession states changed.

Does everyone have idea about how to resolve ?

**Comment by craigktreasure** [comment]
@darax and @mschofie to take a look at this one.

**Comment by darax** [comment]
Hi @skypu3, 
I think what is happening here is ARFoundation hasn't yet created the platform's AR Session.  ASA needs to get a raw pointer to the underlying platform session in order to do work.

try adding something like this to your unity script, in place of calling 'start' immediately:
```
SpatialAnchorManager spatialAnchorManager;
bool startedAsa = false;

 void Start()
        {
            spatialAnchorManager = FindObjectOfType<SpatialAnchorManager>();
   
            if (ARSession.state == ARSessionState.SessionTracking)
            {
                StartASA();
            }
            else
            {
                ARSession.stateChanged += ARSession_stateChanged;
            }
        }

        private async void StartASA()
        {
            startedAsa = true;
            await spatialAnchorManager.CreateSessionAsync();
            await spatialAnchorManager.StartSessionAsync();
        }

        private async void ARSession_stateChanged(ARSessionStateChangedEventArgs obj)
        {
            Debug.Log($"ar session {obj.state}");
            if (obj.state == ARSessionState.SessionTracking && !startedAsa)
            {
                StartASA();
            }
        }
```

**Comment by ephb** [comment]
I ran into the same exception and making sure the ARSession is tracking similar to what @darax suggested fixed the issue for me.
