### ISSUE TITLE
Can't locate previous anchor

### ISSUE THREAD

**Issue by WalkerNoviqu** [Azure/azure-spatial-anchors-samples#206]
Hello, I'm currently learning to use spatial anchors in unity using microsoft's tutorial (https://docs.microsoft.com/en-us/azure/spatial-anchors/tutorials/tutorial-new-unity-hololens-app?tabs=UnityPackage), and can successfully create and upload spatial anchors. However, I'm confused on how I'm supposed to locate them after closing and reopening the app? The spheres I created previously don't appear when restarting the app.

**Comment by craigktreasure** [comment]
Hey @WalkerNoviqu. Glad to hear you were able to create anchors. You'll need to persist your anchor ids somewhere after saving them. You'll use those anchor ids to [recall](https://docs.microsoft.com/en-us/azure/spatial-anchors/how-tos/create-locate-anchors-unity#locate-a-cloud-spatial-anchor) spatial anchors in another session. You can find more information [here](https://docs.microsoft.com/en-us/azure/spatial-anchors/tutorials/tutorial-share-anchors-across-devices?tabs=VS%2CAndroid).
