### ISSUE TITLE
Android ARCore 64-bit only on 64-bit devices - Unity sample does not work out-of-the-box anymore

### ISSUE THREAD

**Issue by reneschulte** [Azure/azure-spatial-anchors-samples#207]
In August Google removed support for 32-bit-only apps on 64-bit devices running Android 10 (API level 29) and later.
Details here: https://developers.google.com/ar/64bit

Therefore the sample will crash on any recent Android device (like my Samsung S20 5G I have here).

Do solve it you need to include 64-bit in the APK which requires Unity IL2CPP as shown below. 
Maybe this could be made the default Player Setting in the samples?

These setting make it work again: 
![image](https://user-images.githubusercontent.com/7439129/90146529-6f892500-dd81-11ea-92ad-abd7f32b8b2b.png)

**Comment by mschofie** [comment]
Thanks for the heads-up, @reneschulte. We'll try out your recommendation and if everything looks good include it in the next release.

**Comment by craigktreasure** [comment]
This was fixed in 2.5.0.
