### ISSUE TITLE
Anchor positioning

### ISSUE THREAD

**Issue by bng00** [Azure/azure-spatial-anchors-samples#210]
Hi, I am new to mixed reality and I am currently developing an application on Hololens 2 where I place many anchors in a large outdoor area and users move to each anchor to complete a task and I have the following questions regarding anchors positioning.

I noticed that when I create a watcher (Wifi Coarse Relocalization) to find anchors, every anchor connected in the session will load up. The anchors nearby are usually in their correct position, but the anchors further away have a much noticeable deviation. As I move around, sometimes the anchors correct itself, but other times it does not. There are also some occasions when the anchors are totally out of place at the point of creating a watcher.

1) What difference does the MRTK setting (Room, World) affects anchor positioning in a large outdoor area?

2) Are anchors saved in multiple sessions and single session have any difference in terms of positioning?

3) Is there a way to just load nearby anchors using NearAnchorCriteria in the radius ONLY and subsequently find more anchors as I move?

Thanks
Using HL2, Unity 2019.4.8, ASA 2.4

**Comment by mschofie** [comment]
1. I'm not familiar with the "MRTK setting". Azure Spatial Anchors works both indoors and outdoors, and is not affected by MRTK.
2. Regarding anchors saved in multiple sessions vs. a single session; Anchors created within a single session will have anchor relationships associated between them - see [the documentation ](https://docs.microsoft.com/en-us/azure/spatial-anchors/concepts/anchor-relationships-way-finding) for more details. If you've found an anchor, then then subsequently create an anchor, then those anchors will have relationships created between them.
3. Yes. You should be able to find anchors close to you using, say, NearDeviceCriteria, then as you move closer to a specific anchor you can request anchors near that specific anchor by using the NearAnchorCriteria. The NearAnchorCriteria queries across anchor relationships, that I mentioned in the answer to your second question.
