### ISSUE TITLE
Southeast Asia Resource Location - "Resource not found"

### ISSUE THREAD

**Issue by DrScatman** [Azure/azure-spatial-anchors-samples#211]
**Description**

Southeast Asia (SEA) resource location not displaying data:

- ![image](https://user-images.githubusercontent.com/49825641/91750200-b30ccd00-eb90-11ea-955f-c42ce049b674.png)

**Steps to reproduce the issue**

0. Go to Microsoft Azure Portal
1. Search "Spatial Anchor Accounts"
2. Click "Add"
3. Select "Southeast Asia" for "Location"
4. Create
5. View newly created resource "Metrics"

**Expected behavior**

Working Metrics.

**Additional Information**

I am able to create and locate anchors when using this resource. It is seemingly just an error with the metrics.

**Comment by craigktreasure** [comment]
@chwarr Any ides or suggestions?

**Comment by chwarr** [comment]
I can reproduce this problem. It looks like this region and Korea Central have a misconfiguration in their metrics setup. The Azure Spatial Anchor team is about to start a three day weekend. I've created an internal-to-Microsoft ticket to have someone investigate this next week.

(For Microsoft people, you can find the internal ticket by searching for this GitHub issue's URL, `https://github.com/Azure/azure-spatial-anchors-samples/issues/211`, in our incident tracking system.)

**Comment by chwarr** [comment]
We have fixed the misconfiguration. Metrics are now visible for the two affected regions going forward. We are unable to populate historical metrics.
