### ISSUE TITLE
AzureSpatialAnchorsLocalSharedDemo Anchor expired

### ISSUE THREAD

**Issue by zihexu5** [Azure/azure-spatial-anchors-samples#213]
Unity version:  2019.4.4f1
Azure spatial anchor: latest
Description:
when trying with AzureSpatialAnchorsLocalSharedDemo scene, the anchor created expired less than one day, and in code the anchor expiration time is set to 7 days. It is however not clear for me where the expiration time get overrided or the anchors get deleted somewhere in other classes.

**Comment by craigktreasure** [comment]
Can you please provide more information?

**Development information (please complete the following information)**

 - OS: [e.g. Windows\macOS\Linux]
 - Development Platform\Version: [e.g. Xcode 11.5, Android Studio 3.6.3, Visual Studio 2019, Unity 2019.2.12f1]
 - Azure Spatial Anchors SDK version: [e.g. `2.2.1`]

**Comment by zihexu5** [comment]
Development information
OS: Windows
Development Platform\Version: [e.g. Visual Studio 2019, Unity 2019.4.4f1]
Azure Spatial Anchors SDK version: [e.g. 2.5.0]

**Comment by mschofie** [comment]
The anchors shouldn't be deleted until the expiration hits. Can you share the logs of a repro so we can correlate to what the service sees? Thanks!
