### ISSUE TITLE
Unity: ARCore, ARKit plugins shouldn't be dependencies of Spatial Anchors SDK Core

### ISSUE THREAD

**Issue by marns** [Azure/azure-spatial-anchors-samples#214]
Unity: ARCore, ARKit plugins shouldn't be dependencies of Spatial Anchors SDK Core

There are separate iOS, Android packages for Azure Spatial Anchors SDK already, but their XR Plugins are dependencies of the main SDK Core. This forces those dependencies into projects for other platforms.

**Comment by kaysabelle** [comment]
Hi @marns, thanks for your suggestion. We're looking into this (internal issue #29378850) and will update you with progress.

**Comment by kaysabelle** [comment]
Hello @marns, we've fixed this in 2.6.0.
