### ISSUE TITLE
There is a problem during testing the Azure Spatial Anchors sample of hololens2

### ISSUE THREAD

**Issue by varunitestudio** [Azure/azure-spatial-anchors-samples#215]
Asure-spatial-anchors-samples-master downloaded AzureSpatialAnchorsLocalSharedDemo.Checking Scene.

Account id, key, and domain were all entered, and BaseSharingUrl was also entered. https://xxx.azurewebsites.net/api/anchors

![image](https://user-images.githubusercontent.com/48979208/93412337-eca33f00-f8d7-11ea-8aad-df15c4da6c7b.png)

However, if you build on Hololens2 and share after Save, problems arise.

enter image description here
![image](https://user-images.githubusercontent.com/48979208/93412490-355af800-f8d8-11ea-8812-3fa16f647f0b.png)

Error code : "value does not fall within the expected range retrieve last anchor key"

I'm using Unity3D 2019.3.0f6, Visual Studio 2019

enter image description here
![image](https://user-images.githubusercontent.com/48979208/93412517-43a91400-f8d8-11ea-93de-9c626ee98638.png)

Please tell me the problem.

**Comment by darax** [comment]
Hi @varunitestudio,  I've also responded in https://github.com/Azure/azure-spatial-anchors-samples/issues/217, including a possible workaround. I'm not able to reproduce the issue. Another user is having the same issue. I'm curious what region/language you have your HoloLens device set to use.

**Comment by varunitestudio** [comment]
The region is set to Korea and the language is also Korean.

**Comment by craigktreasure** [comment]
Have you tried @darax's solution from #217?

From #217:

One more thing to try would be to update AnchorExchanger StoreAnchorKey by replacing

```csharp
var response = await client.PostAsync(baseAddress, new StringContent(anchorKey));
```

with

```csharp
var response = await client.PostAsync($"{baseAddress}/key?anchorKey={anchorKey}", new StringContent(""));
```
