### ISSUE TITLE
Spatial Anchors on Unity 2020.1.6

### ISSUE THREAD

**Issue by BartJV** [Azure/azure-spatial-anchors-samples#219]
**Description**

Spatial Anchors 2.6, Unity 2020.1.6, a null pointer crashes the application at
// System.IntPtr UnityEngine.XR.WSA.WorldAnchor::GetNativeSpatialAnchorPtr()

This seems to relate to the new XR SDK that Unity has switched to.

**Steps to reproduce the issue**

Opened the example application in 2020.1.6, and installed Windows XR
call CloudNativeAnchor::NativeToCloud, or gameObject.FindNativeAnchor() once loaded on the Hololens.

**Development information (please complete the following information)**

 - Windows 10
 - Development Platform: Unity 2020.1.6
 - Azure Spatial Anchors SDK version: 2.6

**AR Device information (please complete the following information):**

 - Device: Hololens 2

**Comment by EricVoll** [comment]
I have the exact same issue. Only difference is my Unity version: 2019.4.10f1

**Comment by EricVoll** [comment]
The method `SpatialAnchorExtensions::GetPointer(this NativeAnchor anchor) : IntPtr` uses a deprecated method `GetNativeSpatialAnchroPtr()`, which (according to the method's description) is not working with Windows XR Plugins.

**Comment by craigktreasure** [comment]
This is a known issue with the XR plugin and is basically what's blocking us from supporting Unity 2020 right now. For that reason, we don't support Unity 2020 and can only recommend Unity 2019 LTS.

**Comment by msftradford** [comment]
This issue has been addressed as a part of the ASA SDK 2.9.0 release. With SDK 2.9.0, Unity 2020 and the Unity XR Plug-in Framework are now supported. The release notes are [here](https://github.com/Azure/azure-spatial-anchors-samples/releases/tag/v2.9.0).

**Comment by JoSharon** [comment]
> This issue has been addressed as a part of the ASA SDK 2.9.0 release. With SDK 2.9.0, Unity 2020 and the Unity XR Plug-in Framework are now supported. The release notes are [here](https://github.com/Azure/azure-spatial-anchors-samples/releases/tag/v2.9.0).

@msftradford Hi, do you know how to solve this issue with SDK 2.9.0, Unity 2020 and the Unity XR Plug-in?

Code: localCloudAnchor.LocalAnchor = theObject.FindNativeAnchor().GetPointer();
Error: Cannot implicitly convert type 'System.Threading.Tasks.Task<System.IntPtr>' to 'System.IntPtr'

Code: gameObject.GetComponent<UnityEngine.XR.WSA.WorldAnchor>().SetNativeSpatialAnchorPtr(currentCloudAnchor.LocalAnchor);
Error:The type or namespace name 'WorldAnchor' does not exist in the namespace 'UnityEngine.XR.WSA' (are you missing an assembly reference?)

**Comment by msftradford** [comment]
Hello @JoSharon thanks for reaching out! It appears that you are following the MRTK tutorial [here](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-asa-02). That tutorial has not yet been updated for Unity 2020, so you'll need to follow the [prerequisite instructions](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-asa-01#prerequisites) and target Unity 2019 and ASA SDK 2.7.1. If you have additional issues with a docs page/tutorial, please use the "submit feedback" link at the bottom of the specific page. We hope to have the tutorial updated for Unity 2020 soon.

**Comment by AlecReZ** [comment]
Hello, I use Unity2020.3.x(LTS). Have the same problem.

Assets\MRTK.Tutorials.AzureSpatialAnchors\Scripts\AnchorModuleScript.cs(128,40): error CS0029: Cannot implicitly convert type 'System.Threading.Tasks.Task<System.IntPtr>' to 'System.IntPtr'.

Assets\MRTK.Tutorials.AzureSpatialAnchors\Scripts\AnchorModuleScript.cs(390,64): error CS0234: The type or namespace name 'WorldAnchor' does not exist in the namespace 'UnityEngine.XR.WSA' (are you missing an assembly reference?)

Will the problem be solved in 2020
