### ISSUE TITLE
What is the issue with IL2CPP on HoloLens?

### ISSUE THREAD

**Issue by motionsmith** [Azure/azure-spatial-anchors-samples#22]
In your [documentation](https://github.com/Azure/azure-spatial-anchors-samples/blob/master/Unity/Assets/AzureSpatialAnchorsPlugin/AzureSpatialAnchorsUnityPluginReadme.md#known-issues-for-hololens), it says 

> There is an additional issue on the il2cpp scripting backend case that renders the library unusable in this release.

We need to use IL2CPP for this project (Unity has deprecated the other option and MRTK requires IL2CPP). Can you provide more detail about what is the problem that makes this library unusable? This will help us know how we should move forward.

Thank you for your help! We can't wait to use this new technology.

**Comment by vriveras** [comment]
@motionsmith , sorry for the confusion that section of the readme can be remove now. It should all be working in IL2CPP. I will address the change in the documentation.

**Comment by motionsmith** [comment]
Thanks!
