### ISSUE TITLE
Azure Spatial Anchors Unity example Basic Demo crashes on HoloLens2

### ISSUE THREAD

**Issue by ajaydharankm** [Azure/azure-spatial-anchors-samples#221]
Hi

I am running the Azure spatial anchor Basic Demo example Unity application on HoloLens2. I run the Basic Demo example for creating anchor, save, and look for the created anchors. I repeated the same process, continuously on the same app session. After a few attempts(maybe 6-7 but this varies), the app crashes and I couldn't find much info on the UnityPlayer.log file apart from the State change. Sometimes I could reproduce this issue during the first attempt during the "Looking for Anchor" stage. I am not able to find a specific pattern to reproduce this issue consistently. Any idea about this crash issue?

Azure Spatial Anchor SDK version: 2.6.0
Unity Editor: 2019.4.1f1
Unity Player log from Hololens2: [UnityPlayer-Azurespatialanchor-basicdemo.log](https://github.com/Azure/azure-spatial-anchors-samples/files/5404243/UnityPlayer-Azurespatialanchor-basicdemo.log)

**Comment by DominicBoettger** [comment]
Same here. As soon as the CloudNativeAnchor component is attached to the gameobject the application crashes.

**Comment by msftradford** [comment]
Hi @ajaydharankm, thanks for letting us know! We're looking into this and will update you with progress. Thanks!

**Comment by msftradford** [comment]
Hi @DominicBoettger, would you mind creating a new issue? Please include any relevant information like your ASA SDK version number, Unity Editor version, and your XR Plug-in provider. Thanks!

**Comment by raymondpols** [comment]
Same issue here. Any progress on this or workarounds available to get spatial anchors work on HoloLens 2?

**Comment by msftradford** [comment]
Hi @raymondpols! As we discussed [here](https://github.com/Azure/azure-spatial-anchors-samples/issues/212), ASA does provide support for HoloLens 2 with Unity 2019.4. If you are experiencing an issue with HL2 and Unity 2019.4, can you please file a separate issue. Thanks!

**Comment by msftradford** [comment]
@ajaydharankm, are you familiar with how to provide [feedback from the HoloLens](https://docs.microsoft.com/en-us/hololens/hololens-feedback)? If you are still experiencing this issue, can you attempt to replicate it and then file feedback using those instructions?

**Comment by msft-shshankar** [comment]
Hi all, we identified an ARM32 specific OS bug that was causing these issues and have pushed out a mitigation in the latest 2.7.2 Hotfix (and the OS fix will be arriving eventually in future Windows updates). This hotfix should fix these issues.
