### ISSUE TITLE
Android Platform Build Error when using ASA ver2.60

### ISSUE THREAD

**Issue by tianliang0314** [Azure/azure-spatial-anchors-samples#224]
I follow the tutorial [](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-asa-05),and when i build it ,there are some exceptions
![image](https://user-images.githubusercontent.com/13743806/96977447-acc31d80-154f-11eb-86aa-fbe57e18ccaa.png)
how and i fix it?

**Comment by rubit0** [comment]
Follow these steps:

1. Go to **Player Settings** and open the **Android** section
2. Open **Publishing Settings** section
3. Enable the option "Custom Main Gradle Template"

You build should now work. Please note that your error is not related to ASA.

**Comment by tianliang0314** [comment]
@rubit0 I've checked this option, and I found that it was already on。
 checked this option, and I found that it was already on
![image](https://user-images.githubusercontent.com/13743806/97124510-55999480-176b-11eb-9fd3-30e356fe8ab1.png)
this is where the exception occured

**Comment by tianliang0314** [comment]
@rubit0 I just delete the MainTemplate.Gradle flie in plugins folder and enable the option **"Custom Main Gradle Template"** again to regenerate the MainTemplate.Gradle file, and when i build it, there are more less errors than before.
MainTemplate.Gradle
![image](https://user-images.githubusercontent.com/13743806/97127599-035d7100-1775-11eb-9165-e4faa90a5a5f.png)

**Comment by kaysabelle** [comment]
Hi @tianliang0314, after you're created the custom mainTemplate.gradle file, you'll need to open it in a text editor and add the following lines to the `dependencies` section.

```gradle
    implementation('com.squareup.okhttp3:okhttp:[3.11.0]')
    implementation('com.microsoft.appcenter:appcenter-analytics:[1.10.0]')
```

See the official documentation here for more info (scroll down to **Android only: Configure the mainTemplate.gradle file**):
https://docs.microsoft.com/azure/spatial-anchors/how-tos/setup-unity-project?tabs=UPMPackage

**Comment by tianliang0314** [comment]
@kaysabelle Thanks a lot
