### ISSUE TITLE
Finding existing anchors when app starts

### ISSUE THREAD

**Issue by AscentXR** [Azure/azure-spatial-anchors-samples#225]
Please help!   I have a unity app for hololens2 using mrtk and mrtk spatial anchor prefabs.   I can create and locate spatial anchors consistently on multiple devices...but every time the app restarts I have to start a azure session, get id from network and place the object ( x8 objects and 10 headsets). Do you know how I can start the app and have it place the anchors? I have saved them to disc so they should be able to pull locations from there.

**Comment by msftradford** [comment]
Hi @AscentXR, can you tell us how you are saving anchors/uploading them before the session ends?
