### ISSUE TITLE
Error message when I try to run the Quickstart App on Hololens 2

### ISSUE THREAD

**Issue by teycron** [Azure/azure-spatial-anchors-samples#226]
Hi,

when I try to run the Quickstart app on the Hololens 2, I get the message "Access denied to spatial anchor exporter. Ensure your OS build is up to date and the spatialperception capability is set.".
The SpatialPerception capability is enabled in Unity and in the VisualStudio manifest.

Hololens 2 OS build: 19041.1124
Windows 10 SDK: 10.0.19041.0

Does anyone know this problem and how to solve it?

Thanks in advance for the help

**Comment by msftradford** [comment]
Hello @teycron, thanks for reaching out! I noticed that you are running the latest HL2 build. Would you mind running the HL2 DirectX app to see if that works? I want to make sure that there wasn't some kind of regression in 19041.1124.

**Comment by teycron** [comment]
It was my fault.
I found the solution by myself.
I had to enable the Shared Experiences on the HL2. It can be found in Settings -> System -> Shared Experiences.
