### ISSUE TITLE
Failed to save anchor. Failed to create anchor.

### ISSUE THREAD

**Issue by lingo100** [Azure/azure-spatial-anchors-samples#229]
I run xamarin sample with "Coarse Reloc" and everything worked fine with Azure Spatial Anchors 2.6 SDK.
I can create and see objects later in the watcher with 2.6, but after forced to upgrade to 2.7, it no longer works.
I get this error message when I want to create anchor: "Failed to save anchor. Failed to create anchor." Why?
Do we need to do any change on the server side?

**Comment by msftradford** [comment]
Hey @lingo100, thanks for reaching out! Can you let me know the device and OS to which you are deploying the sample?

**Comment by lingo100** [comment]
Hi msftradford, 
Thanks for asking. I found it is just my Azure account trial period ends.
It works again after I did account upgrade.
Close this issue.
