### ISSUE TITLE
DllNotFoundException: AzureSpatialAnchors

### ISSUE THREAD

**Issue by motionsmith** [Azure/azure-spatial-anchors-samples#23]
I am building a HoloLens/Unity project. I am running into the same issue as [this person](https://github.com/Azure/azure-spatial-anchors-samples/issues/4) because I cannot start from your sample project.

I have copied over all the assets from the AzureSpatialAnchorsPlugin folder in the sample. After pressing play, I get this error at runtime...
```
DllNotFoundException: AzureSpatialAnchors
```
...which appears after I create an `AnchorLocateCriteria` instance in my implementation. The `AnchorLocateCriteria ` constructor is trying to access the native plugin. That made me realize, I don't actually know where the DLL is (indeed, it is not found). Usually for Unity samples of Azure services, there is a DLL file included in the sample project, or they ask us to download it from NuGet or something.

Where is the `Microsoft.Azure.SpatialAnchors` library?

My code seemingly compiles successfully because it looks like the SpatialAnchors library has been wrapped, and the wrapper has the same namespace.

**Comment by vriveras** [comment]
@motionsmith , The SDK doesn't support running the project in the editor the platform needs the devices sensors to be able to run. When you add the unity package there is a post build step that configures the NuGet for the library automatically. Once you do the real build it will get downloaded and it should work.

**Comment by motionsmith** [comment]
Thanks! That'll help me keep moving forward.

**Comment by gamedev2492** [comment]
@vriveras I have run the demo scene on the Android device and I have updated SDK and NDK and still I have got the error. Do we have any solution for this?

**Comment by efonsecab** [comment]
Is there going to be any real solution to this?
One of the basic aspects of Unity is being able to work from the editor itself when developing.
