### ISSUE TITLE
Missing step-by-step documentation for adding missing framework AzureSpatialAnchors on iOS

### ISSUE THREAD

**Issue by oyvind-soroy** [Azure/azure-spatial-anchors-samples#231]
I have looked around all over now but can only find documentation for earlier versions of ASA. I am on 2.7.0 but what I can find is for 2.4.0 and unfortunately it does not seem to match as the folders are not the same in the Assets anymore.

I cannot for the life of me figure out how to get the framework in as there seems to be some missing steps to this that is not clearly explained and updated and in one single step-by-step guide that I can find. 

**Steps to reproduce the issue**

1. Open project in Unity 2019.4.16f1
2. Choose iOS build platform
3. Build and Run
4. (CocoaPods...?)
4. Click "Play" in Xcode
5. "Framework not found AzureSpatialAnchors"

**Screenshot**

https://pbs.twimg.com/media/Ep4bwfDXcAA6CsJ?format=jpg&name=large

This shows how it is set up now after trying to do the CocoaPods-stuff from a whole lot of different online documentation. It says 2.4.0 but I have tried every possible version number from 2.7.0 and down and nothing works.

**Expected behavior**

https://miro.medium.com/max/1200/0*O_0t-47OpEdQkp-h.png

**Development information (please complete the following information)**

 - OS: Latest macOS Catalina
 - Development Platform\Version: Xcode 12.3, Unity 2019.4.16f1
 - Azure Spatial Anchors SDK version: 2.7.0

**AR Device information (please complete the following information):**

Not relevant as I cannot even get to this stage as the build fails.

**Additional context**

Why must this be so difficult. Please explain like I am a little kid that needs spoon-feeding. I have spent the whole day trying to go through documentation and uninstalling/installing and updating and nothing has worked.

**Comment by msftradford** [comment]
Thanks for reaching out @oyvind-soroy. We are constantly looking to improve our documentation and appreciate the feedback. Are [these](https://docs.microsoft.com/en-us/azure/spatial-anchors/quickstarts/get-started-unity-ios) the instructions that you have been following? At what step in the process did you start to notice differences?

**Comment by oyvind-soroy** [comment]
The difference comes from not knowing how to find the missing framework that is mentioned in the screenshot. The quickstart does not help with that, and I have tried all the other options I can find online as well as I saw I was not alone in having this issue, but none of it worked.

**Comment by msftradford** [comment]
Thanks @oyvind-soroy. I want to make sure that we are on the same page so that I can help. Are you having an issue deploying the ASA Unity sample app (called Unity-iPhone, as in your screenshot) or are you having trouble including the ASA framework in a different app? If you are unable to deploy the sample app, can you please use ASA 2.7.0 and verify that you have an entry in your XCode project navigator under Unity-iPhone->Frameworks->com.microsoft.azure.spatial-anchors-sdk.ios->Plugins->iOS->AzureSpatialAnchors.framework. Please also verify that the manifest.json in your Packages directory has the following entries:

```
  "scopedRegistries": [
    {
      "name": "Azure Mixed Reality Services",
      "url": "https://api.bintray.com/npm/microsoft/AzureMixedReality-NPM",
      "scopes": [
        "com.microsoft.azure.spatial-anchors-sdk"
      ]
    }
  ],
  "dependencies": {
    "com.microsoft.azure.spatial-anchors-sdk.android": "2.7.0",
    "com.microsoft.azure.spatial-anchors-sdk.ios": "2.7.0",
    "com.microsoft.azure.spatial-anchors-sdk.windows": "2.7.0",...
```

**Comment by oyvind-soroy** [comment]
This is what it says inside the manifest.json:
`  "scopedRegistries": [
    {
      "name": "Azure Mixed Reality Services",
      "url": "https://api.bintray.com/npm/microsoft/AzureMixedReality-NPM",
      "scopes": [
        "com.microsoft.azure.spatial-anchors-sdk"
      ]
    }
  ],
  "dependencies": {
    "com.microsoft.azure.spatial-anchors-sdk.android": "2.7.0",
    "com.microsoft.azure.spatial-anchors-sdk.ios": "2.7.0",
    "com.microsoft.azure.spatial-anchors-sdk.windows": "2.7.0",`

**Comment by msftradford** [comment]
Thanks @oyvind-soroy. Do let us know what you find on the Mac side. I just went through the [Unity/iOS quickstart](https://docs.microsoft.com/en-us/azure/spatial-anchors/quickstarts/get-started-unity-ios?tabs=azure-portal) (ASA SDK 2.7.0, XCode 12.2, Unity 2019.4.16f1) and was unfortunately not able reproduce an issue related to cocoapods.

**Comment by oyvind-soroy** [comment]
I can do a screen capture to show the process? I have tried reimporting into Unity, build from a new project, but I am still only getting "Framework not found AzureSpatialAnchors" in XCode when I try to build for the devices I have.

**Comment by ephb** [comment]
@msftradford CocoaPods are not used in ASA SDK anymore so you will not be able to reproduce this. Earlier versions used CocoaPods instead of the unity package manager to fetch the framework decency when building. The original issue description seems to be based on an older guide. 

@oyvind-soroy please check inside the 'Frameworks' folder of the XCode project Unity generates. There should be a folder named 'com.microsoft.azure.spatial-anchors-sdk.ios' but I suspect this is missing in your build.

This is basically the same as @msftradford earlier advice:
> If you are unable to deploy the sample app, can you please use ASA 2.7.0 and verify that you have an entry in your XCode project navigator under Unity-iPhone->Frameworks->com.microsoft.azure.spatial-anchors-sdk.ios->Plugins->iOS->AzureSpatialAnchors.framework

Since your manifest.json is correct it seems that something is preventing the package manager form actually downloading the framework, maybe a firewall?

**Comment by oyvind-soroy** [comment]
I can check the firewall issue, I did not think of that.

**Comment by ephb** [comment]
You should check if the framework is present after building first I, might be wrong in my assumption.

**Comment by Varnauld** [comment]
Hello,
I closed this item as this was originally submitted close to two years ago. Our latest release is available [here](https://github.com/Azure/azure-spatial-anchors-samples/releases/tag/v2.12.0) – please re-open this item should you have further feedback for the team.
Alternatively, if you have any ideas or requests for new features or capabilities, or should you wish to upvote an existing idea, please visit our [Feedback hub](https://feedback.azure.com/d365community/forum/f47d9b25-0725-ec11-b6e6-000d3a4f07b8)

Thank you

**Comment by Varnauld** [comment]
Hello,
I closed this item as this was originally submitted close to two years ago. Our latest release is available [here](https://github.com/Azure/azure-spatial-anchors-samples/releases/tag/v2.12.0) – please re-open this item should you have further feedback for the team.
Alternatively, if you have any ideas or requests for new features or capabilities, or should you wish to upvote an existing idea, please visit our [Feedback hub](https://feedback.azure.com/d365community/forum/f47d9b25-0725-ec11-b6e6-000d3a4f07b8)

Thank you
