### ISSUE TITLE
ASA crashes on HoloLens after creating anchor

### ISSUE THREAD

**Issue by rfurmaniak** [Azure/azure-spatial-anchors-samples#236]
**Description**

After creating a spatial anchor on HoloLens 2, application will crash. Crashes seem to be non deterministic, however, it seems that it does occur after 10th use (as in known issues in the release notes) and then it happens every time. Restarting the app does not help. Sometimes reinstalling the app does not help either. It seems that resetting the device to factory settings helps, but only for another few tries.
I have attached two scripts that I'm using for the ASA creation. WorldAnchorContainer calls AzureSpatialManager at the start of the app (after some initial animation disappears) using CreateSceneAnchor method.

I am attaching crash dump here:
https://drive.google.com/file/d/1pRNYOQBlYhDQda0q6_8DNSQqq3WH2isT/view?usp=sharing
(can be opened using WinDbg)

**Steps to reproduce the issue**

1. Add CloudNativeAnchor to object
2. StartSessionAsync
3. Call NativeToCloud on created native anchor
4. Wait until anchor is ready to create
5. Call CreateAnchorAsync 
6. StopSession after anchor is created
7. Quit application
8.  Restart the application few times
9. The app will crash when anchor is being created or few seconds afterwards

**Expected behavior**

The application should not crash, no matter how many times spatial anchor is created

**Development information (please complete the following information)**

 - OS: HoloLens 2 Windows 10 Holographic (multiple versions of OS tried, including Insider Preview)
 - Development Platform\Version: Visual Studio 2019 Enterprise, Unity 2019.4.16f1 (occurs on 2019.4.0f1 too)
 - Azure Spatial Anchors SDK version: 2.7.0, 2.7.1

**AR Device information (please complete the following information):**

 - Device: HoloLens 2
 - OS: Windows 10 Holographic 19041.1402 (happened on other versions too)

**Additional context**

Application ,that my company is working on, greatly relies on spatial anchors. Our last production version was created using 2.3.0 and thus its support will end soon. We are trying to migrate to 2.7.1 but this crash is totally blocking our development.  
I have gathered several crash dumps and they all point towards ASA. I have tried to pinpoint a specific scenario which causes the crash but could not find it. 
I have disabled SDK logging as specified in known issues, but it did not help.
In our application we are calling StopSession after the anchor is created and uploaded to the cloud. However, it seems that removing this method helps with the issue, but produces the crash when trying to locate another spatial anchor afterwards (to replace the current one) all the time. However, we did not have time to further test this behavior.
Initially, I thought that using UniTask is an issue here, but removing it altogether did not help.

[AzureSpatialAnchorManager.txt](https://github.com/Azure/azure-spatial-anchors-samples/files/5881731/AzureSpatialAnchorManager.txt)
[WorldAnchorContainer.txt](https://github.com/Azure/azure-spatial-anchors-samples/files/5881732/WorldAnchorContainer.txt)

**Comment by msftradford** [comment]
Thanks for reaching out @rfurmaniak! I have created an internal issue (#31495405) to help track this. We'll keep you updated.

**Comment by msftradford** [comment]
@rfurmaniak, can you tell us the solution platform (ARM64 etc) that you are using?

**Comment by rfurmaniak** [comment]
@msftradford the platform is ARM32, built with Unity with IL2CPP. 

I will post the log as soon as I get it.

**Comment by rfurmaniak** [comment]
It seems that upgrading to 2.7.2 fixes the issue. I was not able to reproduce the crash with this version. We will be performing intense tests tomorrow, after that I can confirm it 100%

**Comment by msftradford** [comment]
That is great news! Please keep us updated with your testing.

**Comment by rfurmaniak** [comment]
Coming back with the update - everything regarding anchors works in 2.7.2 - we were not able to reproduce any crashes whatsoever. Very big thanks :)

**Comment by msftradford** [comment]
Great to hear @rfurmaniak! I'm going to go ahead and close the issue.
