### ISSUE TITLE
Why Do I need MRTK to use azure spatial anchors on android or ios

### ISSUE THREAD

**Issue by rjtshrm** [Azure/azure-spatial-anchors-samples#237]
Why do I need to set up MRTK for ar foundation camera to use azure spatial anchors on android or ios.  I created a scene with just ar foundation camera and integrated azure spatial anchors with it. I do not get any errors and, also it can seen that CloudSpatialAnchorSession is scanning the environment successfully.  Although, I have not updated the anchors to the cloud. But, is it mandatory to set up mrtk to use azure spatial anchors on android.

**Comment by msftradford** [comment]
Thanks for reaching out @rjtshrm! The [Mixed Reality Toolkit (MRTK)](https://github.com/microsoft/MixedRealityToolkit-Unity) is not required to use Azure Spatial Anchors. You may have noticed that none of our sample apps use MRTK but they still have full ASA functionality. Let us know if you have additional questions. Thanks!
