### ISSUE TITLE
CloudManager.SessionStatus.RecommendedForCreateProgress never gets above 0.

### ISSUE THREAD

**Issue by HendrickSamuel** [Azure/azure-spatial-anchors-samples#238]
Hi, I'm using the **SpatialAnchorManager ** Class provided in the demo with **Unity 2019.4.19f1**
Once the session is created and started, I'm checking for the RecommendedForCreateProgress value but it doesn't get Updated event tho I receive the **SessionUpdated **Event. 

```csharp
protected virtual async Task SaveCurrentObjectAnchorToCloudAsync(GameObject spawnedObject)
    {
        CloudNativeAnchor cna = spawnedObject.GetComponent<CloudNativeAnchor>();

        // If the cloud portion of the anchor hasn't been created yet, create it
        if (cna.CloudAnchor == null) { cna.NativeToCloud(); }

        // Get the cloud portion of the anchor
        CloudSpatialAnchor cloudAnchor = cna.CloudAnchor;

        while (!CloudManager.IsReadyForCreate)
        {
            await Task.Delay(330);
            float createProgress = CloudManager.SessionStatus.RecommendedForCreateProgress;
            feedBack.text = $"Move your device to capture more environment data: {createProgress}";
        }
        bool success = false;

        feedBack.text = "Saving...";

        try
        {
            await CloudManager.CreateAnchorAsync(cloudAnchor);
            var currentCloudAnchor = cloudAnchor;
            success = currentCloudAnchor != null;

            if (success && !isErrorActive)
            {
                await OnSaveCloudAnchorSuccessfulAsync();
            }
            else
            {
                OnSaveCloudAnchorFailed(new Exception("Failed to save, but no exception was thrown."));
            }
        }
        catch (Exception ex)
        {
            OnSaveCloudAnchorFailed(ex);
        }
    }
```

**Comment by tomkrikorian** [comment]
Hi,
I'm currently using Unity 2019.4.18f1 and yesterday one of our user got stuck on the anchor creation (Progress stuck at 0) and i think our issue might be tied to yours. 
Basically it get stucks on !(CloudManager.IsReadyForCreate) since CloudManager.SessionStatus.RecommendedForCreateProgress never updates. Could not reproduce the issue today sadly on my android.

**Comment by pamistel** [comment]
Hi, Happy to help out here @tomkrikorian @HendrickSamuel 

1. Were you able to successfully run the ASA samples and see that RecommendedForCreateProgress was getting updated?
2. What SDK version are you using? 
3. What Device Platform are you using? (@tomkrikorian you mentioned you don't have this issue on Android)

**Comment by HendrickSamuel** [comment]
Hi, 
Yes, the demo worked flawlessly for me.
Then I started recreating my own script that would juste save and recover an Anchor from scratch following this link: https://docs.microsoft.com/en-us/azure/spatial-anchors/how-tos/create-locate-anchors-unity 

But quickly went back. I'm stuck trying to modify the actual samples.

- should I upload where I'm stuck and share you a link ? 

And my project is setup to export for the Android plateform.

**Comment by tomkrikorian** [comment]
Hi @pamistel :
1. I'm not using the samples but our own implementation but this code is pretty much the same though : 
`        while (!CloudManager.IsReadyForCreate)
        {
            await Task.Delay(330);
            float createProgress = CloudManager.SessionStatus.RecommendedForCreateProgress;
            feedBack.text = $"Move your device to capture more environment data: {createProgress}";
        }
`
2. Using last SDK 2.7.2 
3. We're using iOS / HL2 / Android. Relocalization issues happen from time to time for our users and ourselves. We can't reproduce the issue for now on our devices so we think it might have been a connection issue ?

**Comment by TheDrDisco** [comment]
I had this issue too. But I was an idiot who forgot to set the AR camera tag to Main Camera so the anchor manager was never receiving any frames to process. Hopefully that helps someone out.
