### ISSUE TITLE
Unity  Building for iOS on Windows 

### ISSUE THREAD

**Issue by RibinMTC** [Azure/azure-spatial-anchors-samples#242]
Dear devs,

Is it possible to build the sample for iOS with Unity on a Windows machine and afterwards export the Xcode project to a Mac? I tried to build for iOS with Unity on Windows, but I received the following error during the builid process: _FileNotFoundException: Packages\com.microsoft.azure.spatial-anchors-sdk.ios\Plugins\iOS\AzureSpatialAnchors.framework\Headers\AzureSpatialAnchorsLibrary.h.meta does not exist_

Best,

Ribin

**Comment by msftradford** [comment]
Hi @RibinMTC, thanks for reaching out! It is possible to create the sample XCode project for iOS with Unity on a Windows machine. Please make sure that you include all of the necessary Unity packages, including ASA SDK for iOS, this should resolve your issue. One gotcha that you might see when you attempt to build via XCode on a MacOS machine has to do with permissions of MapFileParser.sh. If you see an error in XCode related to this file, you may need to make it executable (chmod +x MapFileParser.sh). Let us know if you have additional questions. Thanks!

**Comment by RibinMTC** [comment]
Thanks for the suggestion. The package you mentioned was already in the sample project, but for some reason, I had to remove that package and manually add ASA SDK for iOS to Unity. Afterwards, the build worked.

**Comment by msftradford** [comment]
Glad to hear this is resolved. Closing the issue for now.
