### ISSUE TITLE
Accuracy of Anchor Localization with a LiDAR sensor

### ISSUE THREAD

**Issue by RibinMTC** [Azure/azure-spatial-anchors-samples#243]
Dear devs,

Does the anchor localization accuracy increase, when creating and localizing spatial anchors using a LiDAR enabled device (like the iPad Pro or the iPhone 12 Pro)? I'm assuming that the point clouds will be denser since it gets additional information from the LiDAR sensor and therefore the detection accuracy is improved? I'm developing on Unity with Arkit 3.1.

Best,

Ribin

**Comment by msftradford** [comment]
Thanks @RibinMTC for the question! As depth sensors become more readily available we are exploring opportunities to take advantage of platform-specific hardware. If you would like to see support added for new sensors in your platform of choice, please provide that feedback [here](https://feedback.azure.com/forums/919252-azure-spatial-anchors). Thanks!

**Comment by RibinMTC** [comment]
Hi,

So that means currently ASA does not take the additional depth information into account when creating and localizing anchors? I assumed that since ASA depends on the underlying information provided by Arkit, it would take the depth information into account.

**Comment by msftradford** [comment]
@RibinMTC, that is correct. You can think of the underlying geometric representation of the environment in ASA as being independent from the geometric representation used by the platform-specific tracker (ARKit, ARCore, etc).
