### ISSUE TITLE
InvalidOperationException Row stride needs to be the same as width

### ISSUE THREAD

**Issue by jimm98y** [Azure/azure-spatial-anchors-samples#244]
**Description**

We get an error in the sample when running it on "Samsung Galaxy Tab A7" in each captured frame:
2021/02/26 16:17:05.361 25787 25816 Error Unity InvalidOperationException: Row stride needs to be the same as width. Request CV: . Response CV: .
2021/02/26 16:17:05.361 25787 25816 Error Unity   at Microsoft.Azure.SpatialAnchors.NativeLibraryHelpers.CheckStatus (System.IntPtr handle, Microsoft.Azure.SpatialAnchors.status value) [0x00131] in C:\Users\lukasv\Downloads\azure-spatial-anchors-samples-master\Unity\Library\PackageCache\com.microsoft.azure.spatial-anchors-sdk.android@2.7.2\Runtime\AzureSpatialAnchorsBridge_Android.cs:182 
2021/02/26 16:17:05.361 25787 25816 Error Unity   at Microsoft.Azure.SpatialAnchors.CloudSpatialAnchorSession.ProcessFrame (System.IntPtr frame) [0x00001] in C:\Users\lukasv\Downloads\azure-spatial-anchors-samples-master\Unity\Library\PackageCache\com.microsoft.azure.spatial-anchors-sdk.android@2.7.2\Runtime\AzureSpatialAnchorsBridge_Android.cs:2570 
2021/02/26 16:17:05.361 25787 25816 Error Unity   at Microsoft.Azure.SpatialAnchors.Unity.SpatialAnchorManager.ProcessLatestFrame () [0x000a5] in C:\Users\lukasv\Downloads\azure-spatial-anchors-samples-master\Unity\Library\PackageCache\com.microsoft.azure.spatial-anchors-sdk.core@2.7.2\Runtime\Scripts\SpatialAnchorManager.

**Steps to reproduce the issue**

1. Run the sample app on Galaxy Tab A7
2. Start "basic" demo
3. Place an anchor
4. See errors in the log, scanning progress remains on 0%, no way to advance the demo

**Expected behavior**

Scanning progress should reach 100%, anchor should be saved to the cloud.

**Screenshots**

**Development information (please complete the following information)**

 - OS: Windows
 - Development Platform\Version: Visual Studio 2019, Unity 2019.4.13f1
 - Azure Spatial Anchors SDK version: 2.7.2

**AR Device information (please complete the following information):**

 - Device: Samsung Galaxy Tab A7
 - OS: Android 10

**Additional context**

The demo app works fine on Google Pixel, so the issue seems to be related to the HW.

**Comment by msftradford** [comment]
Hi @jimm98y, thanks for brining this to our attention! I've filed an internal item (#31909699) to track this issue. We'll provide updates here as soon as we can.

**Comment by laurencecliffe** [comment]
Hi @jimm98y - did you ever get this issue resolved. I'm having the exact same problem with a Motorola g(50) https://github.com/Azure/azure-spatial-anchors-samples/issues/306 - works fine on a Google Pixel 4 and the iOS build is fine too. But I'm having the exact same issue as you on the Motorola (though I'm using the Azure Spatial Anchors SDK version: 2.10.2). a ticket has been logged, though I'm a little concerned that you logged this back in February and there's still no fix...
