### ISSUE TITLE
Visualize the point cloud utilised by ASA

### ISSUE THREAD

**Issue by RibinMTC** [Azure/azure-spatial-anchors-samples#245]
Dear devs,

Is there a possibility to visualize the generated point cloud of ASA for a Unity application running on Android and iOS devices? Specifically, I want to view the point clouds when generating and localizing an anchor. In the docs, I  have found the Diagnostics option, which stores keyframes. Is it possible to access and view these images generated by diagnostics? If no, is there another option?

Best,

Ribin

**Comment by msftradford** [comment]
Hi @RibinMTC, thanks for the question. It is not possible for the user to access the underlying geometric representation. Please consider adding this idea to [the list of ASA suggestions](https://feedback.azure.com/forums/919252-azure-spatial-anchors) or upvoting existing suggestions for visibility. Thanks!

**Comment by RibinMTC** [comment]
Thanks, I upvoted an existing idea. This feature would be really helpful for testing purposes.
