### ISSUE TITLE
Failed to find all the neighbors (Unity - Android)

### ISSUE THREAD

**Issue by bardsodal** [Azure/azure-spatial-anchors-samples#247]
We are having issues while testing the AzureSpatialAnchorsNearbyDemo. We are building from the Unity project to both iOS, Android and HoloLens 2. We can find the neighboring anchors just fine on iOS and HoloLens 2 using the NearbyDemo scene, however it seems not to work on any Android device we have tested it on. We have tested it on four different Android phones, all with ARCore enabled, with Android 8.1 through 10 (as for operating systems). We can find anchors just fine using the normal methods (passing in the anchor ID to the Watcher query), however when we pass in an existing anchor to search for nearby, it times out giving the "Failed to find all the neighbors. Try again".

We are using Unity 2019.4.21f1 and ARFoundation/ARCore/ARKit 3.1.3. 
EDIT: We have also tried using older Unity versions:
- 2019.4.9f1 (last update before the scene was changed on github)
- 2019.4.161 (last update before 2.7.2 packages were added)

Samsung Galaxy s8 (Android 9)
![Screenshot_20210310-145052_Wayfinder](https://user-images.githubusercontent.com/72917687/110761692-53cefa00-8250-11eb-9de2-bdd9a8fdb7d9.jpg) 

Xiaomi Mi 9 (Android 10)
![Screenshot_2021-03-11-09-48-15-999_com Wayfinder](https://user-images.githubusercontent.com/72917687/110761695-54679080-8250-11eb-9b95-734f2059b89d.jpg)

**Comment by pamistel** [comment]
Hi @bardsodal 
We have recently updated the docs to include a page about [Anchor Locate Strategy ](https://docs.microsoft.com/en-us/azure/spatial-anchors/concepts/anchor-locate-strategy).

Can you tell me the exact Anchor Query you are using? I.e. what properties you define in AnchorLocateCriteria

**Comment by bardsodal** [comment]
Hi @pamistel, 

Thanks for the quick response.

We are using the sample app, so if this was a known bug that will be fixed, that is fantastic. 

Here are the answers to your other questions (not sure if they are relevant since we are using the sample app):
We are using the Anchor Query that is used by default which just sends in the CloudSpatialAnchor from one of the anchors we have created as part of the demo scene (as well as the distance to search for anchors). We have not changed the script so the full context can be seen in the AzureSpatialAnchorsNearbyDemoScript.cs from line 345 and onwards.

We were just testing this feature when we realized that the functionality only seemed to work on iOS and HoloLens at the moment, so we wanted to check if this was a known bug, and when it would be fixed. We will potentially need it for a project down the line, in a few months or so, so hopefully it is fixed by then. For the time being we can just work with iOS and HoloLens.

Thanks again!

**Comment by pamistel** [comment]
Hi @bardsodal 

Were you able to try this with the updated 2.8.1

**Comment by bardsodal** [comment]
We are currently testing the new update, and it looks promising so far.

**Comment by bardsodal** [comment]
We have tested it thoroughly now. It is working perfectly! Thanks dev team for quick update!
