### ISSUE TITLE
Unity ARFoundation -- Setting (CloudAnchorSession.Session =ARSession.subsystem.nativePtr) crashes on iOS

### ISSUE THREAD

**Issue by shawmakesmusic** [Azure/azure-spatial-anchors-samples#25]
We're working on an ARFoundation integration.

On Android- we're still working to get progress updates, but everything is successfully initialized. We construct a new CloudAnchorSession and assign the native session pointer from ARFoundation's ARSession class. So far so good! On iOS, however, setting the session to our ARSession.subsystem.nativePtr crashes with no exceptions or logs, right when it hits the CheckStatus native plugin handler. Pointer isn't null.

Given how we're building our app and sharing planes across devices, ARFoundation means not having to code everything twice for iOS and Android, and it's kinda the only way forward. It's also hugely desired by the entire Unity AR community, so figuring this out ASAP would really help with adoption :)

Something I noticed -- using the ARKit/Core packages from download crashes ARFoundation (it's expecting the packages from Unity Package Manager), while using the ARKit/Core packages from the Unity Package Manager just might not be compatible with the Azure Spatial Anchors.

**Comment by vriveras** [comment]
@shawmakesmusic, we do not support ARFoundation in the current version of the SDK. We have it in the pipeline of features but you cannot use it today.

**Comment by ThomasNigro** [comment]
Hello @vriveras. Do you have a (very rough) estimate of when the ARFoundation support will be released? More like 1 month or 6?

Thank you! :)

**Comment by shawmakesmusic** [comment]
> @shawmakesmusic, we do not support ARFoundation in the current version of the SDK. We have it in the pipeline of features but you cannot use it today.

So, doing the monthly check in. Since this was posted, Unity officially deprecated the old ARKit/Core plugins and brought ARFoundation up to the latest versions of each under the hood.

As such, and with all the great new ARKit 3 features in the beta, we have finally hit a threshold where we can build cross platform and the only thing holding us back is that ASA doesn't support Unity's preferred AR solution.

If you guys are seeing low adoption numbers, well, Unity drives 80-90% of all the mobile apps out there, and ASA is currently not up to par. I know maybe 4-5 pretty serious developers who would hop on board tomorrow if you supported ARFoundation. I'm literally in the process of switching over to Google Cloud Anchors, which I'm not happy with, but at least I can get it to jive with ARF, I'd love to not have to do that.

**Comment by vriveras** [comment]
@shawmakesmusic,  We are currently working on ARFoundation It will be part of the SDK supported platforms.

**Comment by shawmakesmusic** [comment]
Checking back in. Any updates, or a rough ETA? Ya'll gonna be at SIGGRAPH?

**Comment by craigktreasure** [comment]
Azure Spatial Anchors 1.3.0 now supports ARFoundation.
