### ISSUE TITLE
2.9.0 Windows package has a missing dependency

### ISSUE THREAD

**Issue by Connor-Kerwin** [Azure/azure-spatial-anchors-samples#251]
When importing ASA 2.9.0, the windows package doesn't specify that it depends on WindowsMR, resulting in build failure for UWP. It requires a manual import of the dependency through the package manager. Is this intentional?

**Comment by polinenibharat** [comment]
Hi Connor, thanks for letting us know! We're looking into this (internal issue #32246076) and will update you with progress. Thanks!

**Comment by polinenibharat** [comment]
Hi Conner, you do indeed need that package. We are working on a fix for a next release.

**Comment by MehranAzimi-msft** [comment]
[ASA SDK 2.10](https://github.com/Azure/azure-spatial-anchors-samples/releases) was released a few days ago which adds support for Mixed Reality OpenXR plugin (com.microsoft.mixedreality.openxr) along the Windows XR plugin (com.unity.xr.windowsmr). This means as a developer you can choose the XR configuration you use in Unity by including either of these packages. Please see [Setting up your XR configuration - Mixed Reality ](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/xr-project-setup?tabs=openxr) and [Choosing a Unity version and XR plugin](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/choosing-unity-version). For the Mixed Reality OpenXR plugin, we recommend version 1.0.0 or later, and for the Windows XR plugin, we recommend version 4.5.0 or later.

As per this change, we did not add the dependency discussed here, and intentionally left that choice to app developers to choose the XR plugin they wish to use.
