### ISSUE TITLE
Can I load Anchor at once?

### ISSUE THREAD

**Issue by varunitestudio** [Azure/azure-spatial-anchors-samples#255]
We are currently testing how many Anchors can be loaded at a time.

So far, we've tested 35 Anchors and checked that objects are loaded.

However, problems occur from 36.

Usually, OnAnchorLocated occurs when Anchor is found, but 36 calls are not made.

Is there a limited number of calls at once?

 Note Sample: MRTK.HoloLens2.Unity.Tutorials.Assets.AzureSpatialAnchors.2.4.0.unitypackage

 - OS: Windows
 - Development Platform\Version: Visual Studio 2019, Unity 2019.4.7f1
 - Azure Spatial Anchors SDK version: 2.8.1

**AR Device information (please complete the following information):**

 - Device: HoloLens2
 - OS: ARM

**Comment by varunitestudio** [comment]
The relevant information was confirmed.
The AnchorLocateCriteria Class contains content.
 - Indicates the CloudSpatialAnchor identifiers to locate. Maximum limit of 35 anchors per watcher.

**Comment by varunitestudio** [comment]
Then what should I do if the number of Anchor is over 35?

**Comment by Merichbier** [comment]
You can always load the anchors in chunk : create several watchers. But as only one watcher can run, you will need some logic to queue them. We also implemented some kind of watcher switching in case not all anchors are found quickly in the running watcher.

**Comment by VipulKakkad-MSFT** [comment]
That's exactly right - the limit of number of anchors per watcher is documented [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.spatialanchors.anchorlocatecriteria?view=spatialanchors-dotnet#properties).
If trying to locate more than that number of anchors, you'll have to manage multiple watchers.

**Comment by varunitestudio** [comment]
If there are more than 35 Anchors, we found all 35 Anchors, and then created a new Watcher to find the next Anchor.

There's a problem here.
If you don't find one Anchor in the middle of finding 35, you can't find the next Anchor.

Dear "Merichbier" If you can't find all Anchor, what should you do with implementing Watchdog Transition?

**Comment by Merichbier** [comment]
The idea is basically the same as in an OS where there is context switching. You can find all the information by googling it. As a short description, the idea is to let the watcher run for some time and then switch with another.

**Comment by VipulKakkad-MSFT** [comment]
Another option to consider: it might be possible to use the same anchor for multiple hologram that are close together, if the scene can be decomposed into multiple spatially contiguous chunks.
This could help reduce the number of anchors being located, so the limit of anchors per watcher is not hit..
