### ISSUE TITLE
Azure Spatial Anchors

### ISSUE THREAD

**Issue by skynard** [Azure/azure-spatial-anchors-samples#256]
Having trouble running the Quickstart tutorial for Azure Spatial Anchorts

When I build in Unity, I get Missing script issues : Script attached to 'Sphere' in scene '' is missing or no valid script is attached. UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&) and Script attached to '_PlaneThatCallsIntoPlugin' in scene '' is missing or no valid script is attached. UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&) –

**Steps to reproduce the issue**

It did occur with the sample app.  

1. Followed the guidelines for the Quickstart tutorial for ASA in Unity for iOS.  
2. Got everything installed 
3. Created my ASA account , loaded licenses, 
4. When creating build, I got the bugs created above.  

**Expected behavior**

Build complete 

**Screenshots**
<img width="846" alt="Screen Shot 2021-04-09 at 5 38 09 AM" src="https://user-images.githubusercontent.com/66785029/114490157-354e7c80-9bc9-11eb-93ac-6ac9fd525a7d.png">

**Development information (please complete the following information)**

 - OS: Mac
 - Development Platform\Version: Xcode version 12.4, Unity 2021.1.1f1, ASA version 2.9

**AR Device information (please complete the following information):**

 - Device: iPhone 11 Pro max
 - OS: Ios 14.4

The MRTK with spatial anchors tutorial for iOS looks better for what we want to achieve.  Should I start with the "Azure Spatial Anchors for Android and iOS" instead?

**Comment by msftradford** [comment]
Thanks for bringing this to our attention @skynard. [ASA SDK 2.9.0 is currently only supported in Unity 2020.3 (LTS)](https://docs.microsoft.com/en-us/azure/spatial-anchors/how-tos/setup-unity-project?tabs=unity-package-web-ui#project-requirements). Do you run into the same issue when building with Unity 2020.3?

**Comment by skynard** [comment]
No. Now I can get the app to run on the phone.  When i hit run demo app,
the whole screen turns black.  The ui is working fine but camera is not.  I
had to add the camera to the scene  because i couldnt find a unity project
in my git download.  I just loaded all the scenes in my unity build

**Comment by msftradford** [comment]
@skynard thanks for the feedback. Glad to hear the app is running now. Let's figure out why the Unity project was missing from the git download. Is [this](https://docs.microsoft.com/en-us/azure/spatial-anchors/quickstarts/get-started-unity-ios) the tutorial that you are following? After you clone the repo and import the ASA SDK packages, is there a _Unity_ folder? What happens when you attempt to add that folder in the Projects tab of Unity Hub?

**Comment by skynard** [comment]
Yes there is a Unity Folder.  Same Tutorial.  So I need to add the folder
in the projects tab of the Unity Hub.  Ok.  Sorry for the ignorance.  So I
must add the ASA sdk after I open the project correct?  Then I should be
able to run the sample project. ?

**Comment by msftradford** [comment]
No worries! Yes, you'll open the project and then follow [these instructions](https://docs.microsoft.com/en-us/azure/spatial-anchors/how-tos/setup-unity-project?tabs=unity-package-web-ui#download-asa-packages) to use Unity's package manager to sideload the ASA SDK Core package and the ASA SDK iOS package. After that, you can continue following the quickstart instructions to build and deploy the sample project.

**Comment by skynard** [comment]
I am using Unity 2020.3 (LTS). I can use ASA sdk 2.10.0 yes? or stay with
2.9.0

**Comment by skynard** [comment]
Nevermind.  You already said to use 2.9

**Comment by skynard** [comment]
I would like to use Unity to attach sound files to the azure anchors when I
get them set up properly.  Would I find tutorials that would help integrate
that.  I am familiar with sound in unity.  Just not the integration with
Azure.

**Comment by skynard** [comment]
Do I use the "azure - spatial- anchors-samples" or
"AzureSpatialAnchors.Examples"

**Comment by skynard** [comment]
its the samles one

**Comment by skynard** [comment]
I see the package manager already has the Azure Spatial Anchors SDK for iOS
loaded.  Do I just side load the core sdk?

**Comment by skynard** [comment]
Everything worked.  Thank you.

**Comment by skynard** [comment]
Having trouble with the tutorial for Azure spatial anchor tutorial. Sorry
to be a pest on the weekend. Trying to add the script

   - Assign the ParentAnchor object to the None (Object) field
   - From the No Function dropdown, select AnchorModuleScript >
StartAzureSession
   () to set this function as the action to be executed when the event is
   triggered


for some reason  when I add the ParentAnchor in the Object field, it is a
cube prefab icon and not a script icon.  Also the "No Function" dropdown
does not contain the "AnchorModuleScript"  Its in my assets folder but I
cant add to the dropdown.  any advice would be helpful.  Maybe I this can
only be run through Hololense?
