### ISSUE TITLE
Need more operations when setting up sample project

### ISSUE THREAD

**Issue by drumath2237** [Azure/azure-spatial-anchors-samples#257]
**Description**

Hi. 👋 

Lacking some information about setting up Azure Spatial Anchors SDK, there are some errors when open the Unity sample project and thus we cannot build any further.
It seemed that it is necessary to refer to the ["Configuring Azure Spatial Anchors in a Unity project"](https://docs.microsoft.com/en-us/azure/spatial-anchors/how-tos/setup-unity-project?tabs=unity-package-web-ui) page in [Quickstart](https://docs.microsoft.com/en-us/azure/spatial-anchors/quickstarts/get-started-unity-android?tabs=azure-portal) in a document.

By the way, I have another idea to configure the SDK.
I used Unity Package Manager to define scoped registry and change `manifest.json`.
This way, it is needless to set up more configurations when we open the project. Please check [my fork's commit](https://github.com/Azure/azure-spatial-anchors-samples/compare/master...drumath2237:master).

**Steps to reproduce the issue**

1. Open this Unity project
2. Errors occur in console and cannot build

**Expected behavior**

No errors occur.

**Screenshots**

![image](https://user-images.githubusercontent.com/11372210/115140944-c2d01780-a074-11eb-9801-4c33faec3930.png)
![image](https://user-images.githubusercontent.com/11372210/115140955-de3b2280-a074-11eb-8b51-875cb7df3e62.png)

**Development information (please complete the following information)**

 - OS: Windows 10 Home
 - Development Platform\Version: Unity 2020.2.7f1
 - Azure Spatial Anchors SDK version: `2.9.0`

**AR Device information (please complete the following information):**

 - Device: [e.g. iPhone 12, Samsung S20]
 - OS: [e.g. iOS 14.4, Android 11]

**Additional context**

**Comment by gllebede** [comment]
@drumath2237 Thanks for the feedback!
I'll look into it.

**Comment by gllebede** [comment]
I’ve tried your branch, but I don’t see any build failures. Although my Unity version is slightly newer, and I’ve only tried Android build so far. Did get the “Open this Unity project” reference as a reference to your branch correctly?

**Comment by gllebede** [comment]
As you can see at this commit the registry been removed from the file:
https://github.com/Azure/azure-spatial-anchors-samples/commit/e852b60da8eefcca3673e11fdad854bfccc44b36#diff-9b89002cc901a67e416fe3a195ee5e75b0c74eea5a2902d12447196da4d4c559

Unfortunately, we can’t provide this functionality anymore. But there is an alternative.
To simplify the set up process there is new [Welcome to the Mixed Reality Feature Tool](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/welcome-to-mr-feature-tool) available.

![image](https://user-images.githubusercontent.com/36988895/115469131-f73a0400-a22b-11eb-8e3c-a95c60d1c57a.png)

**Comment by oafolabi-msft** [comment]
@drumath2237 , would you say we can close this issue?

**Comment by drumath2237** [comment]
Yes you can.
I'm sorry for not being able to reply clearly.
Thank you.
