### ISSUE TITLE
ASA and iOS tutorial

### ISSUE THREAD

**Issue by skynard** [Azure/azure-spatial-anchors-samples#258]
Having trouble with the tutorial for Azure spatial anchor tutorial. Sorry
to be a pest on the weekend. Trying to add the script

   - Assign the ParentAnchor object to the None (Object) field
   - From the No Function dropdown, select AnchorModuleScript >
StartAzureSession
   () to set this function as the action to be executed when the event is
   triggered

for some reason  when I add the ParentAnchor in the Object field, it is a
cube prefab icon and not a script icon.  Also the "No Function" dropdown
does not contain the "AnchorModuleScript"  Its in my assets folder but I
cant add to the dropdown.  any advice would be helpful.  Maybe I this can
only be run through Hololense?

1. Load tutorial for ASA

Looks like its missing some scripts.  I am trying to deploy on iOS..  

<img width="1777" alt="Screen Shot 2021-04-18 at 10 04 05 PM" src="https://user-images.githubusercontent.com/66785029/115299258-6c65e600-a113-11eb-9e44-ad7570f1c319.png">

 - OS: Mac
 - Xcode 12.4, Big Sur, Visual Studio 2019, Unity 2019.4.0 LTS
 - Azure Spatial Anchors SDK version: 2.10.0

**AR Device information (please complete the following information):**

 - Device: IPHONE 11
 - OS: 14.4

**Comment by skynard** [comment]
<img width="405" alt="Screen Shot 2021-04-19 at 3 14 55 PM" src="https://user-images.githubusercontent.com/66785029/115310494-c28e5580-a122-11eb-9cb9-5eef7d5a7efa.png">

My window looks slightly different than the tutorial.  The interactable script is present in my setup.  In the tutorial I am following it is not.  I can't seem to add the anchorModuleScript anywhere.

**Comment by skynard** [comment]
My ParentAnchor has a prefab cube instead of a script when I drag and drop to the None (object) field

**Comment by gllebede** [comment]
We are aware of the issue. An update to the tutorial is in progress. I’m sorry for inconvenience.

**Comment by skynard** [comment]
Oh my.  I thought is was my mistake.  Lots of time trying to remedy.
Lolol.  Let me know

**Comment by skynard** [comment]
Do you know when the issue will be fixed?

**Comment by gllebede** [comment]
Unfortunately I can't give an estimation at the moment.

**Comment by gllebede** [comment]
@skynard maybe we can look into this in a meanwhile. I don't think the issue is iOS specific, isn't it?

**Comment by skynard** [comment]
Have no idea.  I am a hack.  I can barely figure out the first tutorial

**Comment by veeruby-developer** [comment]
@skynard we will try to help you on this issue, 

we Just verified with Mac OS, Unity 2019.4.22f, MRTK Version 2.6.1 and ASA version 2.7.2 every thing is correct have attached a screenshot for reference.
![image](https://user-images.githubusercontent.com/61759322/116684702-e24d3580-a9ce-11eb-8b8a-6f932c5d2f3b.png)

Please also let us know what is the MRTK and ASA version you are using, because in the in the description you have mentioned ASA 2.10.0 which is not released yet.
please try again by importing all the project Assets and let us know.

**Comment by skynard** [comment]
So if this is all correct, I will be able to use the anchormodulescript.cs
and add it to the parent anchor in order to run the tutorial for azure
spatial anchors sample project?

**Comment by skynard** [comment]
and then build to xcode?

**Comment by veeruby-developer** [comment]
@skynard Yes.
but you don't need to add anchormodulescript.cs to parent anchor, it has already been added in the Tutorial package [MRTK.HoloLens2.Unity.Tutorials.Assets.AzureSpatialAnchors.2.5.3.unitypackage](https://github.com/microsoft/MixedRealityLearning/releases/download/azure-spatial-anchors-v2.5.3/MRTK.HoloLens2.Unity.Tutorials.Assets.AzureSpatialAnchors.2.5.3.unitypackage) if you click on the Parent Anchor you can see that anchormodulescript.cs has already been attached to it.

**Comment by skynard** [comment]
This can be deployed on an ios device?

**Comment by veeruby-developer** [comment]
@ skynard yes.

**Comment by skynard** [comment]
Thanks for the help

**Comment by skynard** [comment]
It needs to be 2019.4.22f?  2019.4.24f won't work?

**Comment by veeruby-developer** [comment]
we have tested with 2019.4.22, but i think any 2019 LTS version would work

**Comment by skynard** [comment]
Got the tutorial to work.  Pretty cool stuff.  Getting an error in the
debug window.  says "need an enabled aranchormanger in the scene". I can
set the anchor but cant
Says spatial anchor manager improperly configured.

**Comment by veeruby-developer** [comment]
please provide us more details at what stage you are getting this Error, also please provide below details.
Unity Version
ASA Version
also please confirm weather you are using XRSDK or Legacy XR ?

**Comment by skynard** [comment]
Unity 2019.4.22.f1
asa version  2.7.2
ar foundation 3.1.3
arkit 3.1.3
I didn't load xr plugin management.  I guess I should?  Do I need to start
from scratch if that is the case and rebuild everything again?

The error happens when running the app.  I can move the cube and set its
anchor.  I cant find anchor.

**Comment by veeruby-developer** [comment]
Yes you should have set up the XR plugin management  first as it says in the tutorial
![image](https://user-images.githubusercontent.com/61759322/117033080-aba15300-ad1f-11eb-9ed0-4b3f5e11dd0c.png)
you don't need to do it from scratch you can add it now.
please make sure that you use Legacy XR.

**Comment by skynard** [comment]
It says xr Legacy Input helpers is loaded as well as xr plugin management
is loaded.  is XR Legacy Input Helpers not the correct package?

**Comment by skynard** [comment]
This is the debug window when hitting create anchor button

**Comment by veeruby-developer** [comment]
may be packages of both  XR plugin management(XRSDK) and Legacy XR have been installed and there is conflict due to this.
don't use XRSDK, please redo the tutorial only with Legacy XR as per the instruction in the Tutorial.

**Comment by skynard** [comment]
Should I reinstall everything or just remove xr and legacy and then
reinstall?  I forgot to ask if its ok to work on a mac to create all this.

**Comment by veeruby-developer** [comment]
if you are sure that all packages related to XRPlugin management has been removed you can do that.
or it would be better if redo the tutorial again since it does not take more time.
and yes you can work on Mac

**Comment by skynard** [comment]
yes i just have a hard time making sure the sdks are loaded properly and
versions.  So I need to make sure xrsdk doesn't load in the package
manager?  I think it automatically loaded last time.  If that is the case
how would I prevent that from happening when I set up the new project?
[image: Screen Shot 2021-05-06 at 10.11.06 AM.png]

**Comment by veeruby-developer** [comment]
i dont think XRSDK packages will be automatically loaded.
please redo the tutorial. may be you are following the XRSDK tab in the tutorials, please follow the Legacy WSA tab.
![image](https://user-images.githubusercontent.com/61759322/117404934-7287ff00-af28-11eb-9953-4e17f52eafbe.png)

**Comment by skynard** [comment]
Thank you.  Will do

**Comment by skynard** [comment]
In Legacy WSA it says to switch to Universal Windows Platform.  Is this
correct?  I am deploying to ios.  dont i switch platform to ios build?

**Comment by skynard** [comment]
Would I load legacy xr via the package manager?

**Comment by veeruby-developer** [comment]
Follow this [Tutorial](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-asa-02) with unity 2019 LTS, please follow the order as present in the tutorial. only thing you need to Ignore is Building the project to HoloLens.
following this tutorial you would be able to build to IOS in ch5.
