### ISSUE TITLE
Unity Android: SaveCurrentObjectAnchorToCloud exception when running sample

### ISSUE THREAD

**Issue by bertt** [Azure/azure-spatial-anchors-samples#26]
We try to run the Unity3D basic demo (code build from master) on Android (Asus_A002 Android 7.0), but got an exception when saving anchors to cloud: 

![Screenshot_20190521-152513](https://user-images.githubusercontent.com/538812/58100246-8cb26080-7bdd-11e9-9de5-8cbc156f1f5f.jpg)

In a previous version of the samples (about 2 months ago) same trick did work with same setup.

**Comment by darax** [comment]
@bertt, thanks for the report. If you attach android studio to the phone and look in logcat, I think you can get a more meaningful error message. Make sure that your account information is configured correctly and your device is connected to the internet. If everything is configured correctly, post the output from logcat in android studio and hopefully we'll get a better idea of what's going on.

**Comment by bertt** [comment]
Hi Patrick, ok thanks, I've traced it down to setting a wrong SA Account Id... problem fixed!
The error reporting could be improved though :-)

**Comment by darax** [comment]
@bertt you can blame me for the awful error output.  glad you are working again!

**Comment by StarWardo** [comment]
@bertt I seem to have the same error. You mentioned that the SA Account Id was wrong. I filled in the account ID and key in the SpatialAnchorsConfig and in the Spatial Anchor Manager in the scene which are correct. Anything you can think if that I could have missed ?

**Comment by bertt** [comment]
@StarWardo no, only triple check the correct id's are used

**Comment by StarWardo** [comment]
@bertt I fixed the error by creating a new SA resource inside a different resource group.
