### ISSUE TITLE
error CS4008: Cannot await 'void'

### ISSUE THREAD

**Issue by GuoweiST** [Azure/azure-spatial-anchors-samples#260]
After importing this into a fresh Unity Poject, Unity shows the below error:
_Assets\AzureSpatialAnchors.Examples\Scripts\DemoScriptBase.cs(445,17): error CS4008: Cannot await 'void'_

I was following the steps provided [here]( https://docs.microsoft.com/en-us/azure/spatial-anchors/how-tos/setup-unity-project?tabs=unity-package-mixed-reality-feature-tool#download-asa-packages)

Currently using Unity 2019.4.21f1 LTS.

**Comment by willyeo** [comment]
I suspect while you're using ver 2.9.0 samples project here, but downloaded old ASA packages. 
Please follow [this download section](https://docs.microsoft.com/en-us/azure/spatial-anchors/how-tos/setup-unity-project?tabs=unity-package-mixed-reality-feature-tool#download-asa-packages) again with the matching version (2.9.0).

**Comment by GuoweiST** [comment]
Hi thanks for the reply.
I can't seems to find version 2.9.0 but able to get dismiss the error with 2.10.0-preview.1. 
Thanks for your help!

**Comment by GuoweiST** [comment]
Hi sorry but I faced another issue. 
I am currently stuck at the "Deploy the HoloLens application" step.

When I click on Start Debugging on VS, it loads the app on my Hololens 2 but I am not able to see the UI on the "AnchorsDemoLauncher" scene. I tried deploying the build and run it on the Hololens itself but still face the same issue.

**Comment by willyeo** [comment]
Is the scene checked in the Build Settings?
![image](https://user-images.githubusercontent.com/29989947/116460135-8c845c00-a81b-11eb-8825-767332d0b0d7.png)

Also, version mismatch might cause issues later. Looks like "Download with web browser" has a problem now and only shows 2.10.0-preview.1 as you mentioned. While this waits for the fix, please try with "Download with NPM" approach to get the correct version.

**Comment by GuoweiST** [comment]
Yes all the scene are checked.

After changing the SDK to 2.9.0, I am still facing the same issue. 

But when I tried to make a new build and start debugging, VS prompted me a that WindowsMRXRSDK.pdb not loaded. 
![image](https://user-images.githubusercontent.com/83278844/116501230-e0a64380-a8e2-11eb-8a60-8b3a8c7a5ca5.png)

**Comment by willyeo** [comment]
Because this is different issue than the original post (Cannot await 'void'), could you close this issue and open a new one? 
In the new issue, please include more information - Unity version, your device (HL 1 or 2?), OS version for the HoloLens, ASA SDK version (I assume it's 2.9.0).
