### ISSUE TITLE
Unable to fetch Azure packages from UPM

### ISSUE THREAD

**Issue by ian-phoria** [Azure/azure-spatial-anchors-samples#262]
**Description**

I am unable to fetch the Azure packages directly through the Unity Package Manager. Is the package server currently down?

**Steps to reproduce the issue**

- Attempt to update or fetch one of the azure packages from the Unity Package Manager
- OR attempt to run a Unity Cloud Build with azure packages in your manifest.json

**Screenshots**
![AzurePackageManager01](https://user-images.githubusercontent.com/69895079/116837456-dd29f980-ac0d-11eb-8c72-8fbec25701bc.PNG)
![AzureAccessDenied](https://user-images.githubusercontent.com/69895079/116837457-def3bd00-ac0d-11eb-841e-1ddc66af1e89.PNG)

**Additional context**

Project has been working correctly with Azure Spatial Anchors for about a year now. Issue only presented itself this morning (Monday) after working correctly on Friday.

**Comment by ian-phoria** [comment]
I've also noticed that your recommendation for [importing the Azure packages into Unity ](https://docs.microsoft.com/en-gb/azure/spatial-anchors/how-tos/setup-unity-project?tabs=unity-package-web-ui#configuring-a-project) has changed recently.

I initially had the Azure packages downloaded manually and locally included in the project but changed that to meet the ASA SDK v2.5.0 release requirements.

Have the requirements changed again? Is there no longer a way to pull the ASA packages directly using a scoped registry in the manifest.json as indicated: 
![image](https://user-images.githubusercontent.com/69895079/116841505-c4751000-ac1c-11eb-8bb1-f4b752a38406.png)

If so, what's the reason for the change? ..and what's the recommended way to keep Unity projects up-to-date with the latest ASA SDK version?

**Comment by ian-phoria** [comment]
My mistake. I've just noticed that in a previous [issue ](https://github.com/Azure/azure-spatial-anchors-samples/issues/254) you  announced that you are deprecating my way of pulling the packages and that issues may arise after May 1st. Fair enough.

I've reopened the issue to ask where I should be looking for breaking Azure changes like this in future. Did I miss a more obvious and clear announcement of this change? ..or am I supposed to trawl the issues page every day in the hope I catch something like this earlier?

**Comment by willyeo** [comment]
Code breaking changes are announced in a couple of different ways: pinned post in the "Issues" channel here and direct emails if your email address is up-to-date in the azure portal where you created the ASA account. 

This particular issue was a change to project configuration and not a code breaking change, therefore it was deemed sufficient to just have a pinned post in the channel which you mention. You can be made aware of this type of issue by "watching" (signing up for notifications) the this repo.

**Comment by ian-phoria** [comment]
Ah yep of course, I'll start watching the repo. Thank you for the quick response.

**Comment by StephenHodgson** [comment]
Yeah moving away from a scoped registry was a bad decision imho. I'm pretty sure that it breaks the TOS for package providers
