### ISSUE TITLE
Unity Android: Anchors not located accurately

### ISSUE THREAD

**Issue by feko006** [Azure/azure-spatial-anchors-samples#264]
**Description**

Hi, we've been experiencing an issue where anchors are not located at the exact position where they were created. We initially noticed it in a project we were working on that has ASA integrated in it, but were able to reproduce it with the samples app for Android with some small modifications. The anchors themselves are located very quickly, but usually have an offset of a few centimeters in a random direction.

**Steps to reproduce the issue**

Sample app:
We have created a modified version of the AzureSpatialAnchorsBasicDemo scene and script in order to be able to test and reproduce the issue.
The changes can be found in the following forked repo and branch: https://github.com/feko006/azure-spatial-anchors-samples/tree/android-locate-precision-issue

Setting up the sample app:
While testing, the ASA libraries (core and android, 2.9.0) were imported via tarballs and the credentials were added in the Assets/AzureSpatialAnchors.SDK/Resources/SpatialAnchorConfig.asset file.
Once the libraries are added and the credentials filled, the app should be built and run. The platform should be Android and all scenes should be included.

Preconditions:
To verify the issue, we need an anchor ID from a previous session. This can be extracted from the original non-modified samples app, after the create anchor step. We had an anchor ID recorded from our own app which we used when trying to reproduce the issue with the customized sample app.

Reproduction steps:
1. Once the app is built and deployed, the "BasicDemo" should be selected from the launcher.
2. Next would need to be pressed exactly 3 times.
3. When the "Look for Anchor" text is shown on the screen, enter the anchor ID in the text field in the center of the screen and press the Add Anchor Id button. This adds the anchor ID to the anchorIdsToLocate list.
4. Press the "Next Step" button and locate the anchor.
5. Anchor is often not located at the correct position.

**Expected behavior**

Anchors are always located at the correct and accurate position, or their position is corrected as more of the environment is scanned.

**Screenshots**

Recorded anchor position
![image](https://user-images.githubusercontent.com/17888938/120816775-5c825400-c551-11eb-8344-0b314108efcd.png)

Located anchor position. You can notice that the center of the cube is not that close to the corner of the laptop. Anchor was located from approximately the same position it was captured in.
![inaccurate-location](https://user-images.githubusercontent.com/17888938/120816848-6efc8d80-c551-11eb-8fd7-bbc7ccc0ca2b.png)

**Development information (please complete the following information)**

 - OS: Windows 10
 - Development Platform\Version: Visual Studio 2019, Unity 2020.3.11f1
 - Azure Spatial Anchors SDK version: 2.9.0 (was also noticed on previous versions such as 2.7.0)

**AR Device information (please complete the following information):**

 - Device: Pixel 2 XL, Asus Zenfone AR
 - OS: Android 9, Android 7.0

**Additional context**

Dependency versions:
- AR Foundation: 4.0.12
- ARCore XR Plugin 4.0.12

The anchors were also created from the same custom Android app they are not accurately located in. Some of the created anchors were tested on another HoloLens 2 app of ours and were located properly / accurately, which means that they were recorded properly in the Android app. This leads us to think that it is an issue with the locating, not the recording of the anchors. An additional point here is that this does not happen 100% of the time. Sometimes (but somehow rarely) anchors are located properly.

For the purposes of this issue, tests were made and behavior was reproduced on a Google Pixel 2XL device. 
Was also experienced previously on an Asus Zenfone AR device.

I would be more than happy to provide more relevant info about this issue if needed.

**Comment by phamqduc** [comment]
Thank you for reporting the issue with such level of details, @feko006.
We have a few questions for clarification of the issue:
1/ Is the level of in-accuracy always a few centimeters? Do you **often** see offset being several tens of centimeters?

2/ Does the accuracy level improve when you place more objects with texture into the scene and capture more environment data during both the anchor creation time and anchor querying time?

3/ Is it always the case that anchor created on your Android app are located _correctly_ by your HoloLens 2 app but most often _incorrectly_ on your Android app?

4/ If you also used previous ASA versions before, did you observe the same problem?

5/ Could you please share the recorded anchor ID (and session ID if possible) for the anchor that has low location accuracy? We also want to inspect on our server side operations for that anchor.

**Comment by feko006** [comment]
Hi @phamqduc, thanks for the quick response!

I am able to answer a few of the questions now, but would have to get back to you again on Monday for some of them.

1/ Yes, the observed inaccuracy is always a matter of, I would say, up to 10 centimeters.

2/ We have tried different scenes and environments and it did not appear to improve the situation. It gives the impression that it is somewhat random. We have also noticed this behavior when having scanned a significant amount of environment data. Most of these observations are from within our app,

3/ With the limited number of tests that we did, that was the case.

4/ We have had ASA integrated even before version 2.7.0. We didn't get to use and test it much before we upgraded to 2.7.0, so this is the version where we first noticed this behavior. Next we upgraded to 2.9.0, which is the version we used for reproducing the issue and documenting this report.

I will provide more info about questions 3/ and 5/ early on Monday.

**Comment by feko006** [comment]
Hi, I did a few more tests in order to answer some of the questions in the previous comment.

3/ Ran a few more tests on the HL2 and it seems that locating the anchors is a lot more precise there. It locates the anchors exactly where they were placed / created in the Android app. When locating the anchors in the Android app, we get an offset.

5/ I wrote down a couple of sets of session and anchor IDs where the issue was noticed:

Anchor set 1:
- Session ID: 2f26d1ed-83bd-454b-9044-0c3655e933eb
- Anchor IDs: 6e33c59c-1f0f-431c-9a39-e388abcb13ea, cc2f5197-ee5a-49f1-97a7-e3427c49a9b2

Anchor set 2 (similar points):
- Session IDs: cefb7409-fa53-4ec8-8932-688bc5df4621, fab4482f-dbbd-47c6-91e0-ca1571f488e8
- Anchor IDs: 5d6e4929-3bc6-41bb-b53e-d793b98ceefc, f4e32deb-5f6f-427a-b225-528f0ad71830

Regarding the last question. If I understood correctly. We do not place the virtual object until the anchor is found and then we instantiate it, parent it under the located anchor and set its local coordinates to (0, 0, 0). Additionally, we do some calculations based on the anchor positions (not the visual's positions) in order to display other virtual objects and the effect of the inaccurate positioning can be noticed here as well. So I would say that there is no position offset that could affect what we are experiencing. Please let me know if I somehow misunderstood the question and you had something else in mind and I will be more than glad to try to provide a more meaningful answer.

**Comment by phamqduc** [comment]
hi @feko006, thank you so much for providing us more details on the session and anchor IDs.
Upon inspection, we notice that those anchor IDs were located using HL and Pixel 2 XL devices as you mentioned.
However, there is an important difference:
- on HL, those anchors were located using locate strategy with "Visual Information" where their poses were computed individually and based on visual matching.
- on Pixel 2, they were located using "AnyStrategy" and indeed their poses were computed based on relationship to the other anchor.

The strategy "Visual Information" can deliver more accurate anchor position especially _if_ the link between anchors (their relative 3D transformation) is not highly accurate as expected. Such link could be formed when anchors were created using mobile phones, as compared to using HLs (where tracking is more accurate).
Further information on locate strategy can be found on this [documentation page](https://docs.microsoft.com/en-us/azure/spatial-anchors/concepts/anchor-locate-strategy).

For the purpose of troubleshooting, please using locate strategy of "Visual Information" for the app running on Pixel 2 device as well and kindly let us know if it helps to improve the anchor location accuracy.

**Comment by feko006** [comment]
Hi @phamqduc, thanks a lot for the continuous support and interest in this issue! 

We did more tests, this time with the "VisualInformation" strategy instead of the default "AnyStrategy". It did appear that the anchors were placed a bit better, but looking around we still noticed some small offsets (not larger than 5cm).

Should small offsets such as these be expected? Is there maybe a known expected precision when recording and locating anchors on Android?

Following are two more sets of session and anchor IDs where the offset issue was noticed, with the "VisualInformation" strategy being used:
Set 1:
- Session ID: 148eff88-61aa-4a61-bd16-44b7c6bf50d8
- Anchor IDs: 55c20364-d23c-4512-bf37-2c55834646cd, 151f8ff9-64f8-4803-ac3b-f5bd44878c6f

Set 2:
- Session ID: 9f1e3932-3a39-46bb-877c-c3a9622fc730
- Anchor IDs: 25dce77b-b39a-4ba5-b311-c6ced13843f5, 918229b8-a711-49e0-94e7-7bd6e1d3e44e

**Comment by feko006** [comment]
Hi, are there maybe any updates regarding this issue?

**Comment by msftradford** [comment]
Hi @feko006, thanks for the update! Errors on the order of a few centimeters are not uncommon in certain environments, especially on mobile devices. Unfortunately, we cannot give a specific expected precision because many factors affect the accuracy of locating anchors--lighting conditions, the objects in the environment, and even the surface on which the anchor is placed. We are working on providing better guidance around anchor accuracy (internal #34098672).

**Comment by feko006** [comment]
Hi @msftradford, thanks a lot for the reply and clarification!

Taking what you said into consideration, I would say that the behavior that we experienced falls in the expected category. 
Since that's the case, I would even say this issue can be closed.

Looking forward to the additional guidance regarding anchor accuracy!

**Comment by oafolabi-msft** [comment]
Closing issue for now, as recommended by @feko006
