### ISSUE TITLE
Saving anchors on iOS occasionally fails

### ISSUE THREAD

**Issue by snowyao** [Azure/azure-spatial-anchors-samples#265]
Working on unity(iOS) and SDK Version(2.9.0).
When internet is not stable, it will likely fail to save, in order to reproduce it, tester can
1, Disconnect internet then try to save, it will fail for sure
2, Reconnect to internet, it will fail to save since then
I would like to know what can I do after user's internet is not stable and fail to save since then. Is it restart the scene the only choice we have?

Here is the similar log:
`
RestClient::CreateNeighborhoodAnchorAndSpatialAnchorAsync - Exception 'HRESULT: 80004005 Platform error code: fffffc04'
Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)

(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

CreateNeighborhoodAnchorAndSpatialAnchor failed with HTTP error 0. ReqCV: BiumpZ8nRl67xwbHJ7myGw. ResCV: . JSON Error:
Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)

(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

OnError - Service unavailable or unspecified error found
Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
Microsoft.Azure.SpatialAnchors.<>c__DisplayClass88_0:b__0()
System.Action:Invoke()
System.Threading.Tasks.Task:Execute()
System.Threading.ContextCallback:Invoke(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.Tasks.Task:ExecuteWithThreadLocal(Task&)
System.Threading.Tasks.Task:ExecuteEntry(Boolean)
System.Threading.ThreadPoolWorkQueue:Dispatch()

(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

CloudManager_Error Service unavailable or unspecified error found
Microsoft.Azure.SpatialAnchors.Unity.Examples.DemoScriptBase:CloudManager_Error(Object, SessionErrorEventArgs)
Microsoft.Azure.SpatialAnchors.SessionErrorDelegate:Invoke(Object, SessionErrorEventArgs)
Microsoft.Azure.SpatialAnchors.SessionErrorDelegate:Invoke(Object, SessionErrorEventArgs)
Microsoft.Azure.SpatialAnchors.<>c__DisplayClass88_0:b__0()
System.Action:Invoke()
System.Threading.Tasks.Task:Execute()
System.Threading.ContextCallback:Invoke(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.Tasks.Task:ExecuteWithThreadLocal(Task&)
System.Threading.Tasks.Task:ExecuteEntry(Boolean)
System.Threading.ThreadPoolWorkQueue:Dispatch()

(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

Failed to save catch exception:
Microsoft.Azure.SpatialAnchors.Unity.Examples.<>c__DisplayClass64_0:<CloudManager_Error>b__0()
System.Threading.ContextCallback:Invoke(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Runtime.CompilerServices.MoveNextRunner:Run()
System.Action:Invoke()
System.Threading.ContextCallback:Invoke(Object)
System.Threading.Tasks.AwaitTaskContinuation:RunCallback(ContextCallback, Object, Task&)
System.Threading.Tasks.Task:FinishContinuations()
System.Threading.Tasks.Task:Finish(Boolean)
System.Threading.Tasks.Task1:TrySetException(Object) System.Runtime.CompilerServices.AsyncTaskMethodBuilder1:Create()
Microsoft.Azure.SpatialAnchors.Unity.UnityDispatcher:.cctor()
System.Threading.ContextCallback:Invoke(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Runtime.CompilerServices.MoveNextRunner:Run()
System.Action:Invoke()
System.Threading.ContextCallback:Invoke(Object)
System.Threading.Tasks.AwaitTaskContinuation:RunCallback(ContextCallback, Object, Task&)
System.Threading.Tasks.Task:FinishContinuations()
System.Threading.Tasks.Task:Finish(Boolean)
System.Threading.Tasks.Task1:TrySetException(Object) System.Runtime.CompilerServices.AsyncTaskMethodBuilder1:Create()
Microsoft.Azure.SpatialAnchors.<>c__DisplayClass95_0:b__0()
System.Threading.ContextCallback:Invoke(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Runtime.CompilerServices.MoveNextRunner:Run()
System.Action:Invoke()
System.Threading.SendOrPostCallback:Invoke(Object)
UnityEngine.Enumerator:Reset()
UnityEngine.UnitySynchronizationContext:Exec()

(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

**Comment by phamqduc** [comment]
Hi @snowyao. Thank you for letting us know the issue of concern. We'll investigate and get back to you.

**Comment by phamqduc** [comment]
Hi @snowyao, 
I've tried out a simpler ASA sample app (Swift) regarding the connection instability concern. When a connection can not be made to ASA services, the call to create anchor fails. If the app makes the call to create anchor again in the same CloudSpatialAnchorSession, when internet is back, it will succeed.
So, In order for us to understand the issue you are facing, please kindly let us know:
1/ what does it mean by "restart the scene" ? Do you mean having to restart CloudSpatialAnchorSession?
2/ Do you also observe the same issue in the ASA Unity sample app? Can you share the sequence of steps to re-produce the issue in the sample app, for example,
- at which ASA stage/API call does the app disconnect?
- which API calls does it make during the disconnection and when the internet is back?

Thank you and we are looking forward to hearing further from you.

**Comment by somepablo** [comment]
Hi,

We are also experiencing issues when saving anchors on both Android & iOS from Unity using mobile data (didn't try on WiFi)

Apparently there are not any network disconnects during the session as other API services work well.

When saving an anchor we randomly receive a "CloudManager_Error Service unavailable or unspecified error found".

Looking deep into the Android log, it prints the following errors:

`"log":"CreateNeighborhoodAnchorAndSpatialAnchor failed with HTTP error 0.`
`"log":"PoseQueryProcessorStream - Error Response: gRPC code [14] gRPC Message [Software caused connection abort] Spatial Code 6! ReqCV [ruW2yGQSS9yiTi65iRPpIg]`

Hope this helps.

**Comment by msftradford** [comment]
@somepablo thanks for reaching out. If you don't mind, can you please [file a separate bug report](https://github.com/Azure/azure-spatial-anchors-samples/issues/new?assignees=&labels=&template=bug_report.md&title=). Thanks!
