### ISSUE TITLE
Instantiated object changes are not reflecting while viewing the created cloud anchor (UNITY)

### ISSUE THREAD

**Issue by KanagaDavid** [Azure/azure-spatial-anchors-samples#267]
**Instantiated object changes are not reflecting while viewing the created cloud anchor (UNITY)**

I have an prefab of inputfield which will be the instantiating object at runtime. After created that object by clicking on detected plane it will be the spawnedObject, before saving it I'm entering text into the spawnedObject inputfield then saving it in azure spatial cloud. When viewing that object after cloud save it's showing the inputfield object without entered text.

Is there any way to store the changed value too?

**Steps to reproduce the issue**

1. Use any inputfield gameobject as prefab to instantiate.
2. After placing that prefab at runtime enter some words in it, (eg: Hi, How are You?).
3. Save that placed object.
4. Now try to view the placed object from view mode, there entered text (Hi, How are You?) will be missed.

**Expected behavior**

Entered text "Hi, How are You?" also need to be there when viewing the saved object.

**Development information:**

 - OS: Windows
 - Development Platform\Version: Unity 2019.4.16f1
 - Azure Spatial Anchors SDK version: 2.7.2

**AR Device information:**

 - Device: Samsung S9 Plus.
 - OS: Android 10.

**Comment by gllebede** [comment]
You can use [AppProperties](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.spatialanchors.cloudspatialanchor.appproperties?view=spatialanchors-dotnet) to store any app-specific information with the anchor.

If I understand the issue correctly you can store the text into AppProperties and retrieve it back when anchor is discovered.

**Comment by KanagaDavid** [comment]
@gllebede Thank you, that's what I'm looking. Closing this issue.
