### ISSUE TITLE
Looking for a .NET version of ASA

### ISSUE THREAD

**Issue by StephenHodgson** [Azure/azure-spatial-anchors-samples#270]
Is there a version of ASA without Unity for .NET?

**Comment by gllebede** [comment]
There is no ASA nuget package that would work across multiple platforms. You can find nuget packages here: https://www.nuget.org/packages?q=Microsoft.Azure.SpatialAnchors

This one is for HoloLens: https://www.nuget.org/packages/Microsoft.Azure.SpatialAnchors.WinRT/

And this one is for Android and iOS: https://www.nuget.org/packages/Microsoft.Azure.SpatialAnchors.Xamarin/

**Comment by StephenHodgson** [comment]
Any plans to add one? You guys have the unity packages, I suspect it is just a matter of using the base implementation of that library.

**Comment by gllebede** [comment]
@msftradford may know if any work to unify .net API is scheduled.

**Comment by gllebede** [comment]
@StephenHodgson may I ask you to leave a feature request here https://feedback.azure.com/forums/919252-azure-spatial-anchors ?

**Comment by StephenHodgson** [comment]
Sure thing

**Comment by StephenHodgson** [comment]
Done https://feedback.azure.com/forums/919252-azure-spatial-anchors/suggestions/43722831-a-net-offering-of-asa-without-unity-dependency

**Comment by StephenHodgson** [comment]
To be honest I'm surprised you guys didn't just make the .net version and then build the unity stuff on top of that. Would have been a lot easier imho

**Comment by StephenHodgson** [comment]
Guessing this isn't gonna happen
