### ISSUE TITLE
Ask for a Unity Android app with Azure Spatial Anchors

### ISSUE THREAD

**Issue by HappyBoy-pengpengc** [Azure/azure-spatial-anchors-samples#271]
Hello, I have recently ran into issues when attempting to complete the tutorial "Quickstart: Create a Unity Android app with Azure Spatial Anchors(https://docs.microsoft.com/en-us/azure/spatial-anchors/quickstarts/get-started-unity-android?tabs=azure-portal)" .When I deployed it to the Android phone, the application failed to open normally. I don't know why, so I would like to ask if you could share an Android application that was deployed through Unity, thank you very much.
I just want to see how spatial anchors are used so that I can write my own code for creating and locating spatial anchors,

**Comment by HappyBoy-pengpengc** [comment]
If possible, please send the application to my email："m202070460@hust.edu.cn", thank you

**Comment by msftradford** [comment]
Hi @HappyBoy-pengpengc, thanks for reaching out! The quickstart link that you've provided is for our ASA sample application on Unity. I would expect that it should be deployable out-of-the-box. To figure out what went wrong, can you please [enable logging](https://docs.microsoft.com/en-us/azure/spatial-anchors/concepts/logging-diagnostics) and send us the resulting logs of a session where the application failed to open normally? Thanks!
