### ISSUE TITLE
Spatial anchor service not available 

### ISSUE THREAD

**Issue by anirudharpatil** [Azure/azure-spatial-anchors-samples#279]
Spatial anchor service not available,
Location: East US
"Account domain" is not reachable using Azure Spatial Anchors SDK for Windows Version 2.9.0
developing HoloLens 2 application with Unity 2021.1.14f1 (64-bit)
the "Account Domain" DNS is not getting resolved, Tried from a different geographical location but the service is not available. 
Resulting in "SpatialAnchorManager is improperly configured" error.

**Comment by oafolabi-msft** [comment]
Hi @anirudharpatil , are you still running into this issue? If so, can you please [turn on the debug logging](https://docs.microsoft.com/en-us/azure/spatial-anchors/concepts/logging-diagnostics#standard-logging) and provide us with more information so we can understand the problem better? In addition are you able to get the [samples](https://github.com/Azure/azure-spatial-anchors-samples) working?

**Comment by anirudharpatil** [comment]
Hello @oafolabi-msft,
Thanks for your response,
Yes, We are able to get the sample working successfully, attaching the screenshots. 
Yes, we are still running into this issue, As per your suggestion, I have enabled the debug logging. attached is output
[Exact_error_Logs.txt](https://github.com/Azure/azure-spatial-anchors-samples/files/6930499/Exact_error_Logs.txt)
[Full_Dig_Log.txt](https://github.com/Azure/azure-spatial-anchors-samples/files/6930501/Full_Dig_Log.txt)
![screen](https://user-images.githubusercontent.com/9820284/128165723-aaecea44-7498-4f68-8f5f-a9342b9f3501.PNG)
![Error](https://user-images.githubusercontent.com/9820284/128165733-eca008ef-d3a9-4ace-863e-d62c9e545569.PNG)
  
1. Exact error logs file when we click on create a session (Exact_error_Logs.txt)
2. Full logs from the begining.  (Full_Dig_Log.txt)

Please note that we are testing/running this in the "HoloLens 2 Emulator (10.0.20348.1010)"

Please help.

Many thanks
Regards

**Comment by anirudharpatil** [comment]
Please help on this.

**Comment by msftradford** [comment]
Hi @anirudharpatil! Please be aware that ASA only [added support for MROpenXR](https://github.com/Azure/azure-spatial-anchors-samples/releases) starting with ASA SDK 2.10.0 and we currently target Unity 2020.3 (LTS). Can you explain what you mean when you say that the "Account Domain DNS is not getting resolved"? Is there an error message somewhere that mentions the account domain? What account domain url are you using to configure the SpatialAnchorManager?

**Comment by anirudharpatil** [comment]
Hello @msftradford  Many Thanks for response,

Ok Sure I will try with ASA SDK 2.10.0 currently I am using 2.9

But currently I am using Unity 2021.1.14f1 (64-bit). Shall I downgrade it to Unity 2020.3 (LTS) ? 

And for that account domain DNS, I mean "Account Domain" we mention in the spatial anchor manager script. Attached is screen shot with yellow mark.
![view-resource-accountid~3](https://user-images.githubusercontent.com/9820284/128410740-f1045916-c58a-4b8c-a328-9d45f27afe7c.png)

 i.e "eastus.mixedreality.azure.com " I tried to ping this domain using cmd prompt when I got improperly configured error. By ping command.

**Comment by anirudharpatil** [comment]
Sorry that was accidentally closed

**Comment by chwarr** [comment]
There are no interesting DNS records on eastus.mixedreality.azure.com. It's expected that "eastus.mixedreality.azure.com" won't resolve to a A, AAAA, or CNAME record. You won't be able to ping it.

Think of the Account Domain property as a base domain name that the ASA SDK uses to build DNS names for the various endpoints it needs to connect to.

-------------------------

⚠⚠⚠ Here be current implementation details. All of this is subject to change. ⚠⚠⚠

One of the current subdomains is "query.sa". When I resolve "query.sa.eastus.mixedreality.azure.com", I get a CNAME record. If I chase that all the way to an A record, I can establish a TLS connection on port 443.

The service is not configured to accept ICMP packets from the Internet, so you won't be able to ping it anyway.

```
PS> resolve-dnsname query.sa.eastus.mixedreality.azure.com

Name                           Type   TTL   Section    NameHost
----                           ----   ---   -------    --------
query.sa.eastus.mixedreality.a CNAME  30    Answer     mrc-asa-pqp-prod-usea.trafficmanager.net
zure.com
mrc-asa-pqp-prod-usea.trafficm CNAME  30    Answer     asa-pqp-prod-usea-2.eastus.cloudapp.azure.com
anager.net

Name       : asa-pqp-prod-usea-2.eastus.cloudapp.azure.com
QueryType  : A
TTL        : 10
Section    : Answer
IP4Address : 52.170.169.46


Name                   : eastus.cloudapp.azure.com
QueryType              : SOA
TTL                    : 60
Section                : Authority
NameAdministrator      : msnhst.microsoft.com
SerialNumber           : 10001
TimeToZoneRefresh      : 900
TimeToZoneFailureRetry : 300
TimeToExpiration       : 604800
DefaultTTL             : 60


PS> openssl s_client -connect 52.170.169.46:443 -servername query.sa.eastus.mixedreality.azure.com
CONNECTED(00000160)
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root G2
verify return:1
depth=1 C = US, O = Microsoft Corporation, CN = Microsoft Azure TLS Issuing CA 06
verify return:1
depth=0 C = US, ST = WA, L = Redmond, O = Microsoft Corporation, CN = query.sa.eastus.mixedreality.azure.com
verify return:1
---
Certificate chain
 0 s:/C=US/ST=WA/L=Redmond/O=Microsoft Corporation/CN=query.sa.eastus.mixedreality.azure.com
   i:/C=US/O=Microsoft Corporation/CN=Microsoft Azure TLS Issuing CA 06
 1 s:/C=US/O=Microsoft Corporation/CN=Microsoft Azure TLS Issuing CA 06
   i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root G2
 2 s:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root G2
   i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root G2
---
Server certificate
-----BEGIN CERTIFICATE-----
<elided>
-----END CERTIFICATE-----
subject=/C=US/ST=WA/L=Redmond/O=Microsoft Corporation/CN=query.sa.eastus.mixedreality.azure.com
issuer=/C=US/O=Microsoft Corporation/CN=Microsoft Azure TLS Issuing CA 06
---
No client certificate CA names sent
Peer signing digest: SHA256
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 5629 bytes and written 481 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
<elided>
---
read:errno=0
```

**Comment by anirudharpatil** [comment]
Hello @chwarr ,

Thanks for the response,

As suggested by  @msftradford  I have switched to ASA SDK 2.10.0. (Version 2.10.0-preview.1)

but still using the latest unity version as the downgrading to it to Unity 2020.3 (LTS) gives me some issues i am not able to run the sample.

I am able to run the sample with Unity 2021.1.1.14f but it is giving me the attached errors 

tried with x64 build and then x86 build.
![Access_Violation_Error_when used_64bit](https://user-images.githubusercontent.com/9820284/128695395-e5858d1e-b0db-4bf2-a226-ab61d3cb1b93.PNG)
[Full_Logs after 2_10_SDK_Dig_Log_build_x64.txt](https://github.com/Azure/azure-spatial-anchors-samples/files/6953847/Full_Logs.after.2_10_SDK_Dig_Log_build_x64.txt)
[Full_Logs after 2_10_SDK_Dig_Log_built_x86.txt](https://github.com/Azure/azure-spatial-anchors-samples/files/6953848/Full_Logs.after.2_10_SDK_Dig_Log_built_x86.txt)
![SDK_2_10](https://user-images.githubusercontent.com/9820284/128695406-972e549e-de74-4942-8f20-f89d06c370fd.PNG)

Thanks
Regards
Anirudha

**Comment by anirudharpatil** [comment]
Please help

**Comment by anirudharpatil** [comment]
Hello @chwarr  Please help on this.

**Comment by msftradford** [comment]
@anirudharpatil we strongly recommend using the supported HL stack that is [reflected in our sample code](https://github.com/Azure/azure-spatial-anchors-samples/tree/master/Unity):
- Unity 2020.3 (LTS)
- ASA SDK 2.10.2
- build for [ARM64](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/porting-apps/porting-hl1-hl2#compile-dependenciesplugins-for-arm-processor)

The issue of SpatialAnchorManager being improperly configured usually means that something is wrong with the ASA account credentials or that the required ARFoundation objects are missing (or disabled) from the scene. Starting with our working sample code and then slowly adding on components would be a good way to figure out what might be going wrong.

**Comment by anirudharpatil** [comment]
Hello @msftradford,

Many thanks for your input I will try as per the given versions and combination.

One doubt we are using HoloLons 2 emulator to test the application as mentioned above and I am running it on Windows 10
and ARM64 may not be supported I guess, but still, let me give it a try.

Regards
Anirudha

**Comment by anirudharpatil** [comment]
Dear @chwarr and @msftradford,

Thank you very much for all your efforts this was really helpful to understand the details about ASA SDK.
I appreciate the quick response and support given by you.

For now, Closing this issue as I am trying to use Emulator which is not a feasible case for ASA SDK, I will keep you updated in case of any additional findings from my end.  
Thanks Again
Regards
Anirudha
