### ISSUE TITLE
Many Namespaces are missing when Importing to unity 2020.3.12

### ISSUE THREAD

**Issue by nouraaan** [Azure/azure-spatial-anchors-samples#280]
I tried to import this sample project to unity 2020.3.12f1 but there're many missing references/types.
Any help please ?

**Comment by nouraaan** [comment]
I tried to import this sample project to unity 2020.3.12f1 but there're many missing references/types.
Any help ,please ?

**Comment by oafolabi-msft** [comment]
Hi @nouraaan, thank you for reaching out.  Can you please describe the exact steps you took, so that we can reproduce the issue?

**Comment by msftradford** [comment]
@nouraaan, we're going to go ahead and close this issue. Please let us know if you need additional help.
