### ISSUE TITLE
[HoloLens][GPS] External GPS device advices

### ISSUE THREAD

**Issue by Kent1LG** [Azure/azure-spatial-anchors-samples#281]
Hello, 

First, that not a bug issue.

I'm actually studying ASA on HoloLens (and android but more by curiosity) for a next potential project.
I already know that HoloLens can't use a native GPS sensor, and it totally makes sense. On the Coarse relocalization documentation it says that it's possible to use an external GPS devices with the HL, and for more information to contact the support, I tried and that didn't help.

So I just want to ask a couple of questions if you don't mind : 

- What are the technical specs required by a GPS device to be usable? 
- Do you have a list of compatible devices? Recommended ones?
- Do you know the precision per price range or per device?

Thank you very much,

Quentin Louet Guérin

**Comment by msftradford** [comment]
Hi @Kent1LG, thanks for reaching out! I'll work with the team to try and get answers to these questions.

**Comment by msftradford** [comment]
Hey @Kent1LG, here is some info from the team:

There are a number of GPS devices that you can buy off-the-shelf that provide you with a stream of GPS readings. Internally, we've experimented with connecting [these devices](https://emlid.com/reach/) to an Android phone via bluetooth. It should be  possible to connect similar devices to a HoloLens as well. You'll just need something that the HL can connect to and parse a stream of GPS readings. In terms of compatibility, you would want a device that emits data in a format that we can understand. The above device supports several different formats that are easy to parse. In terms of precision, it is much more accurate than a regular smart phone and for additional accuracy you can buy an RTK subscription, which can give you ~10 cm accuracy (which is more than enough). To implement this with our current SDK, you'll establish a connection with the device, parse the stream, and then give the SDK the current GPS coordinates using the [GeoLocation APIs](https://docs.microsoft.com/en-us/cpp/api/spatial-anchors/winrt/geolocation). For more info, please check out our [coarse relocalization concept page](https://docs.microsoft.com/en-us/azure/spatial-anchors/concepts/coarse-reloc).

**Comment by oafolabi-msft** [comment]
Hi @Kent1LG, this sounds like a feature you would be interested in. I would encourage you to add it to as a suggestion on our [feedback forum](https://feedback.azure.com/forums/919252-azure-spatial-anchors) and upvote it.

**Comment by Kent1LG** [comment]
This is a good idea, I will do that. Thank you
