### ISSUE TITLE
How can I delete the Cloud Anchor only through CloudAnchorID ?

### ISSUE THREAD

**Issue by Davidwang007** [Azure/azure-spatial-anchors-samples#282]
Thank you first !
    In my project ,I bind the Cloud Anchor ID to my object and  stored it in the database. We have lots of these binding relations data, so ,the question is : How can I delete the Cloud Anchor only through CloudAnchorID, NOT after Instantiated the object into the scene.
    I only found CloudManager.DeleteAnchorAsync(CloudSpatialAnchor anchor) method which NOT meet the require we need . do you have any suggestion ?
    thanks !

**Comment by oafolabi-msft** [comment]
Hi @Davidwang007, you can attempt to delete an anchor by first obtaining the anchor using 

`CloudManager.GetAnchorPropertiesAsync(anchorId)`
and then deleting the anchor using  
`DeleteAnchorAsync(anchor)`


while this is not a simple as just having one function, you are able to delete the anchor even if it has not been located yet. 
You can wrap this functionality in a simple function and use that in the rest of your code. Please let us know if this addresses you issue.

**Comment by Davidwang007** [comment]
@oafolabi-msft  Thank you , I will try it .

**Comment by Davidwang007** [comment]
Yes ,it's works, the script I used as bellow:
               foreach (string id in ids)
                {
                    CloudSpatialAnchor csa = await CloudManager.Session.GetAnchorPropertiesAsync(id);
                    if (csa != null)
                        await CloudManager.DeleteAnchorAsync(csa);
                }

**Comment by oafolabi-msft** [comment]
Great to hear @Davidwang007 ! I will be closing this issue since it now resolved.

**Comment by oafolabi-msft** [comment]
@Davidwang007, is there a particular reason you want to delete the anchors using only the anchor Ids?

**Comment by Davidwang007** [comment]
> @Davidwang007, is there a particular reason you want to delete the anchors using only the anchor Ids?

I bind the Anchor id with my 3D model and store the relationship into the database,so ,i can only get the Anchor id. if i want to delete the 3D model,for clear resource reason ,also need to delete the Cloud Anchor .

**Comment by Davidwang007** [comment]
> @Davidwang007, is there a particular reason you want to delete the anchors using only the anchor Ids?

I bind the Anchor id with my 3D model and store the relationship into the database,so ,i can only get the Anchor id. if i want to delete the 3D model,for clear resource reason ,also need to delete the Cloud Anchor .
