### ISSUE TITLE
How to cancel or set the timeout after start a watcher 

### ISSUE THREAD

**Issue by Davidwang007** [Azure/azure-spatial-anchors-samples#285]
I am sorry to ask this question but i have not found any useful information on the documents . My question is how to cancel the finding Spatial Anchor processing after started a Watcher use:
 CloudManager.Session.CreateWatcher(anchorLocateCriteria);

Because after created the Watcher in another place where the Cloud Anchor not in , the Cloud Anchor matching processing hangs indefinitely without any result ( always in the finding processing because no visual points match ). I have searched the documents for something such as "timeout" setting or "cancel" function but no good news .

yes ,I have used the watcher.stop() function but it's seems like no help because the matching processing does not really stop and still hangs on .

so ,my question is how to cancel or set the timeout when start a watcher ?

**Comment by wyliefoxxx** [comment]
currentWatcher.Stop() has worked well in stopping the watcher for us on mobile platforms, although I've not probed the process deep enough to ensure all related processes and threads are terminated completely

**Comment by Davidwang007** [comment]
@wyliefoxxx  Yes,you are right ,my mistake,huhu,i will close this issue.
