### ISSUE TITLE
MBP 13 M1, Try open added ASA sample unity project failed

### ISSUE THREAD

**Issue by AShtanev** [Azure/azure-spatial-anchors-samples#286]
**Description**

Can't add ASA sample project to Unity. After adding and trying to launch editor get this message:
"The project you are opening contains compilation errors.

Entering Safe Mode allows you to resolve these errors without waiting for the rest of your project to import.

If you select Ignore (not recommended), your project will continue to import, but it may be in a broken or unusable state."

Try Unity versions 2020.3.15f2 and 2021.1.16f1
Try SDK Versions 2.9.0 and 2.10.2
OSX 11.5.1

At this point project opening is stopped

<img width="423" alt="Снимок экрана 2021-08-15 в 15 25 33" src="https://user-images.githubusercontent.com/88971438/129478653-cc3a4287-10c8-434b-b2f4-65b6a2b0a7f1.png">

And then a get this message
<img width="246" alt="Снимок экрана 2021-08-15 в 15 30 57" src="https://user-images.githubusercontent.com/88971438/129478690-abece6fc-a95f-4e12-813f-6a0948319051.png">

**Comment by oafolabi-msft** [comment]
Hi @AShtanev , were you able to successfully follow the instructions on how to [configure your project in unity](https://docs.microsoft.com/en-us/azure/spatial-anchors/how-tos/setup-unity-project?tabs=unity-package-web-ui#configuring-a-project)? It looks like you may be missing some packages.

**Comment by AShtanev** [comment]
But how could I add packages to project before I open it?
And if I try to open demo project in safe mode all required packages already in, because packages belong to project project. Or I miss something?

This is after open in safe mode. 
<img width="1156" alt="Снимок экрана 2021-08-17 в 22 49 30" src="https://user-images.githubusercontent.com/88971438/129791006-57499dc0-b2cc-4381-9735-17ea6bcd4c96.png">

<img width="795" alt="Снимок экрана 2021-08-17 в 22 49 26" src="https://user-images.githubusercontent.com/88971438/129790990-29ea1eb9-6e27-4c54-8ae0-2c1edd39e328.png">

**Comment by oafolabi-msft** [comment]
Hi @AShtanev, you can open the project in safe mode, follow the [instructions](https://docs.microsoft.com/en-us/azure/spatial-anchors/how-tos/setup-unity-project?tabs=unity-package-web-ui#configuring-a-project) I shared earlier to download the asa packages as tarballs, and then follow the instruction [here](https://docs.unity3d.com/Manual/upm-ui-tarball.html) to see how to add the packages as tarballs. Please let us know if this resolves your issue.

**Comment by AShtanev** [comment]
@oafolabi-msft, thank you for response. If you look to images I attached in previous message ( they are from ASA project opened in safe mode ) .tgz packages already added to Package Manager. I also try to add .tgz packages for android and windows ( which I don't need ) - no result, all errors the same in console

**Comment by msftradford** [comment]
Hi @AShtanev! The `CloudSpatialAnchor` object is a part of the platform-specific ASA SDK package. It looks like you have installed the ASA SDK for iOS, so you should be good there. Another thing to check would be the build platform. Can you confirm that you've selected the iOS platform from the Build Settings menu?

**Comment by AShtanev** [comment]
@msftradford, you are my savior! The problem was in target platform. When I download the project it was set to tvOS, after switching to iOS all compile errors gone. Tank you for response.

**Comment by msftradford** [comment]
That is great news! I'm going to go ahead and close this issue. Enjoy!
