### ISSUE TITLE
Mapping area size limitation while creating spatial anchor.

### ISSUE THREAD

**Issue by nikhilsawlani** [Azure/azure-spatial-anchors-samples#290]
Hi,

I have been using azure spatial anchors for a year now, and recently I feel that mapping area while creating an azure spatial anchor had been reduced. for example, While creating an anchor in a large room I can notice now that the anchor is only localized near the area where I stop anchor creation. even though I cover full room while mapping, the anchor is only localized in a small area.

A few weeks back in the same process, I was able to localize in the complete room where I used to Map, so my question is there any limitations that have been introduced to size of area where we can create the anchors? and in general, is there any area size recommendations while creating spatial anchors ?

**Comment by shreya-sharma** [comment]
Hello @nikhilsawlani, thanks for your question. We will need a little bit more information to be able to help you with this issue. Could you us know which platform and device are you facing this issue in?

**Comment by nikhilsawlani** [comment]
Hi @ShreeyaSharma5.

We are facing issues in both Andoird and iOS, we tested in the previous version of ASA 2.8.1 which was working fine then. but it seems something changed from Cloud/server-side which has limited localization 

We're using:
Unity 2020.1.17f1
ASA 2.10.2 and ASA 2.8.1
For iOS iPhone 11  and iPhone 12 and Android Oneplus 8

**Comment by willyeo** [comment]
@nikhilsawlani 
To find issues, could you share some more info about your scenario?
* How many anchors do you create the map the room?
* What's the approximate size of the room?
* What kind of [locate criteria ](https://docs.microsoft.com/en-us/azure/spatial-anchors/concepts/anchor-locate-strategy)do you use? 
* If you use NearAnchor criteria, is the mapping behavior same as before? For example, you do "Connecting anchors" described [here ](https://docs.microsoft.com/en-us/azure/spatial-anchors/concepts/anchor-relationships-way-finding)in the same way you did before?

**Comment by nikhilsawlani** [comment]
Hi @willyeo 

1- We are creating a single anchor to Map the room.
2- the size of the room is around 25 sq. meters.
3- We are using NearAnchor criteria.
4- Yes mapping process is the same as previous, but we don’t do connect anchors, as we only create a single anchor in a session. and during localization time we pass all the identifiers of anchors from which we want to get the Pose.

Code which we use to locate anchors, I tried to change anchors finding distance but that did not help either.

`protected void SetAnchorIdsToLocate(IEnumerable<string> anchorIds)
       
         {
            if (anchorIds == null)
            {
                throw new ArgumentNullException(nameof(anchorIds));
            }
            anchorLocateCriteria.NearAnchor = new NearAnchorCriteria();
            anchorLocateCriteria.NearAnchor.DistanceInMeters = 50;
            anchorIdsToLocate.Clear();
            anchorIdsToLocate.AddRange(anchorIds);
            string[] anchoriden = anchorIdsToLocate.ToArray();
            anchorLocateCriteria.Identifiers = anchoriden;
        }`

**Comment by willyeo** [comment]
@nikhilsawlani 
Thanks for the info. We don't see any immediate changes leading to this kind of behaviors, but we will spend some time to see if we can repro the issue on our side. In the mean time, if you have any further context around your scenario, please share. Thanks for your patience.

**Comment by nikhilsawlani** [comment]
@willyeo 
Thanks for the update, in the meantime, is there any area size recommendation while creating a single anchor in a session. that will be helpful

**Comment by willyeo** [comment]
@nikhilsawlani 
I checked with the team, and 5m x 5m area seems a bit bigger to cover with a single anchor in general as a single anchor can contain only certain amount of visual information, and it starts kicking out earlier info when it overflows. This behavior didn't change between 2.8 and 2.10, so I suspect the scanning behavior (either creating the anchor or querying for the anchor) has changed between the experiment. 

There was a change though to improve the accuracy of the query. This might have consumed more resources on the device itself and degrade the tracking quality (hypothetically) which in turn could affect the query performance.

Regardless, 3-4 anchors seem more appropriate for 25 m^2 area. Let us know how it goes.

**Comment by nikhilsawlani** [comment]
@willyeo 
Thanks for the details,
Although getting the most accuracy was not a concern for us in our use-case, individual anchor area size is, so it there way or in the future, we can choose between anchor accuracy or anchor size during mapping or during query time. (since we would like to capture an area with the least amount of anchors and sufficient accuracy.)

It will be a handy option/feature considering the vast amount of use-cases possible with Spatial Anchors.

**Comment by willyeo** [comment]
@nikhilsawlani
Thanks for the feedback. Yes, we realized this is very cumbersome for our customers, and supporting the scenario for the large area is actually one of the top priorities we're working on, and we really want to prevent our customers thinking about anchor density in their area while scanning.

**Comment by nikhilsawlani** [comment]
@willyeo 
Thanks for the update,

Is there any way we can revert/avoid those changes that improve accuracy during query time? since we have deployed Spatial Anchors in production, and after those changes, most anchors are not localizing from all the desired locations where they used to work.
Otherwise, we have to do all the remapping of the areas again.

**Comment by msftradford** [comment]
Hi @nikhilsawlani! I just took a look at your anchorLocateCriteria and noticed a couple of things that are worth calling out. 

When creating your [anchor location strategy](https://docs.microsoft.com/en-us/azure/spatial-anchors/concepts/anchor-locate-strategy), keep in mind that you can use exactly one of the following properties: Identifiers, NearAnchor, or NearDevice. It appears that you would like to query by specific identifiers, so you should not need to set anchorLocateCriteria.NearAnchor.

When using just AnchorLocateCriteria.Identifiers, you should also consider setting AnchorLocateCriteria.Strategy and AnchorLocateCriteria.BypassCache, depending on your implementation. If none of this code has changed on your end between the upgrade from 2.8.1 to 2.10.2, then feel free to ignore these suggestions.

If you are looking for a way to "disable" the recent changes related to improved accuracy on mobile devices, then you could revert to [ASA SDK 2.9.0 ](https://github.com/Azure/azure-spatial-anchors-samples/releases/tag/v2.9.0). Please keep us updated and we'll continue to try to repro this on our end.

**Comment by nikhilsawlani** [comment]
Hi @msftradford,

I have tested apps with the above-mentioned changes, we are also using BypassCache = true since we want to localize to the same anchor multiple times in the same session.

ASA packages 2.9.0 have increased anchor localizing area slightly but not like the original previous version.

For now will keep version 2.9.0 until future updates
