### ISSUE TITLE
Unable to find Azure Spatial Anchor on another HoloLens 2

### ISSUE THREAD

**Issue by MarkoXR** [Azure/azure-spatial-anchors-samples#291]
**Description**

Hi, I am having trouble implementing shared experience using Azure Spatial Anchors. I followed the Microsoft tutorial (https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-sharing-05) and it is working locally on one HoloLens 2. But when I try to share anchor from one HoloLens 2 and get it from another HoloLens 2 in the same room the watcher can't seem to find it. No error is thrown and last debug message I get is "Watcher created" and "Looking for Azure anchor... please wait...". I tried going to different rooms multiple times but that didn't help.

**Steps to reproduce the issue**

Follow Microsoft Multi-user capabilities tutorial (https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-sharing-01)

**Expected behavior**

Locating Anchor either succeeds or fails.

**Screenshots**

Finding Azure Anchor locally: 
![localAnchor](https://user-images.githubusercontent.com/87175945/131347226-3910ea5f-4947-4da6-8fa8-b9f01fd9ab92.png)
Finding Azure Anchor cross device:
![crossDeviceAnchor](https://user-images.githubusercontent.com/87175945/131347278-0d56c6a1-5ef3-4207-86f4-da7941164de6.png)

**Development information (please complete the following information)**

 - OS: Windows
 - Development Platform\Version: Visual Studio 2019, Unity 2020.3.12f1 LTS
 - MRTK version: MRTK 2.7.2
 - OpenXR version: 1.0.0
 - Azure Spatial Anchors SDK version: 2.10.0-preview1

**AR Device information (please complete the following information):**

 - Device: HoloLens 2
 - OS Version and build: 21H1, 20348.1010

**Additional context**

Players are in the same Photon Room
There is activity in the Azure Portal

**Comment by willyeo** [comment]
@MarkoXR, sorry to hear that you have this problem. Let's check some basic component first:
1) Did you look around scanning the room while you're wearing the second HL device trying to find the anchor?
2) Did you make sure you installed the same version of SDKs for core and Hololens/windows packages? ([SDK installation page](https://docs.microsoft.com/en-us/azure/spatial-anchors/how-tos/setup-unity-project?tabs=unity-package-npm#download-asa-packages))
3) Could you try the stable version for the SDK which is 2.10.2 (not the preview version)?

**Comment by MarkoXR** [comment]
@willyeo Thank you!!! I had this issue for quite some time. 
The ASA SDK version was the problem. Since the 2.10.0-preview1 was the latest at the time I installed MR Feature Tool and Discover Features has to be manually refreshed I didn't realize there were newer versions.
