### ISSUE TITLE
ASA service does not offer backup and restore

### ISSUE THREAD

**Issue by franklanganke** [Azure/azure-spatial-anchors-samples#292]
**Description**

Azure Spatial anchors does not offer backup and restore. As a service user there is currently no scenario to recover from accidental anchor or account writes/deletions (by application or human error). This creates an unmitigated business risk for us.

**Expected behavior**

A backup and restore policy like provided by [Azure Cosmos DB](https://docs.microsoft.com/en-us/azure/cosmos-db/continuous-backup-restore-introduction) in order to:

* restore an ASA account/anchors to a point in time up to 30 days
* restore an ASA account to a different region to be able to move data for compliance reasons.

**Additional context**

If today my ASA account would be deleted by accident would Microsoft support be able to restore it?

**Comment by chwarr** [comment]
> If today my ASA account would be deleted by accident would Microsoft support be able to restore it?

Yes, support can restore an accidentally deleted ASA account for about 28 days. Contact [Azure Support via the Azure portal](https://docs.microsoft.com/en-us/azure/spatial-anchors/spatial-anchor-support) to start this process.

Support can also recover individual anchors.

As you've found, as of September 2021, there are no APIs or Azure portal UI to do these restores. You currently have to go through Azure Support. I cannot speak to whether/when self-service support for account or individual anchor restoration will be made available, nor can I speak to backup/restore policies or region movement.

**Comment by franklanganke** [comment]
Thanks for the clarification!
