### ISSUE TITLE
Latest Demos not working without ARFoundationSessionStack

### ISSUE THREAD

**Issue by EVOsparkLP** [Azure/azure-spatial-anchors-samples#294]
I noticed that the ARFoundationSessionStack was removed from the demo scenes. Without this prefab the demo scenes will not work and show only a black screen. In some former versions of the demo scenes, the ARFoundationSessionStack was in the hierarchy and everything worked fine.
For someone who does not know the old demos, this might be very hard to find out.
Is there a reason why the stack was removed, or was it a mistake?

**Comment by msftradford** [comment]
Hey @EVOsparkLP, thanks for reaching out! We haven't modified our consumption of the ARFoundationSessionStack recently. You should still see it referenced in the AzureSpatialAnchorsDemoLauncher scene inside of the XRCameraPicker script under CameraParent. If you have a clean check-out of the samples repo and do not see this scene or entry, let us know. If everything in the scene hierarchy matches what I've described, then perhaps there is another issue leading to the black screen? Would you mind sending over the information requested in [our bug report template](https://github.com/Azure/azure-spatial-anchors-samples/issues/new?assignees=&labels=&template=bug_report.md&title=)?

**Comment by EVOsparkLP** [comment]
Hi @msftradford,
thanks for you feedback! Indeed the whole project with the AzureSpatialAnchorsDemoLauncher scene as a starting point works fine.

The issue in my case was that I built a project only with the "BasicDemo" and without the "Launcher" scene. In this case there is no XRCameraPicker script that loads the ARFoundationSessionStack. That's why the screen kept black.
