### ISSUE TITLE
Spatial Anchors SDK generates unneeded `SpatialAnchorsConfig.asset` and cannot be stopped

### ISSUE THREAD

**Issue by johannesvollmer** [Azure/azure-spatial-anchors-samples#296]
**Description**

In Unity, adding the dependency clutters the project structure.

**Steps to reproduce the issue**

1. Open Unity Editor `2021.1.21f1`
2. Observe the perfectly clean an elegand asset folder structure
2. Install the azure spatial anchors tarball dependencies `com.microsoft.azure.spatial-anchors-sdk.android-2.10.2.tgz`, `com.microsoft.azure.spatial-anchors-sdk.core-2.10.2.tgz` and `com.microsoft.azure.spatial-anchors-sdk.ios-2.10.2.tgz`
3. Build and Launch the Unity Project for a connected device, for example a recent Android Smartphone
4. Observe the unneeded `AzureSpatialAnchors.SDK/Resources/SpatialAnchorConfig` file cluttering the perfectly clean Asset folder
5. Observe that deleting and renaming the folder is ineffective, as it will result in the aforementioned folder being generated again

__Note:__

The file and folder seems to be generated within a script called in the unity package `com.microsoft.azure.spatial-anchors-sdk.core/Editor/SpatialAnchorConfigInitializer.cs`. The file is generated in the `Editor.update` callback.

**Expected behavior**

The folder should not be generated. Hard-Coded file paths are not the professional way to approach Unity development. The information from the `SpatialAnchorConfig.asset` can already be entered in the `SpatialAnchorManager.cs` component. There is not need for another asset. If a user wants to have an asset, they can easily create it themselves, without this script. I would expect this kind of code in an example project, but not in a serious Unity package.

**Development information (please complete the following information)**

 - OS: Windows (the aforementioned script does not depend on any platform though)
 - Development Platform\Version: `Unity 2021.1.21f1`
 - Azure Spatial Anchors SDK version: `2.10.2`

**AR Device information (please complete the following information):**

 - Device: Samsung Galaxy A40 (this is not a device-related problem though)
 - OS: Android (this is not a device-related problem)

**Comment by pamistel** [comment]
Thank you for your feedback! The team will review possible options to mitigate a cluttered asset folder

**Comment by johannesvollmer** [comment]
Thank you :)
