### ISSUE TITLE
Documentation Unclear: `RecommendedForCreateProgress` Lifetime (for multiple anchors)

### ISSUE THREAD

**Issue by johannesvollmer** [Azure/azure-spatial-anchors-samples#298]
The purpose of the `RecommendedForCreateProgress` field is clearly described in the documentation: While smaller than one, it is discouraged to upload anchor. However, I couldn't find some important details anywhere. Maybe you can help me out?

For example, `RecommendedForCreateProgress` is part of the `Session` object. This means that it behaves basically like a global variable. Inevitably, this raises the question of Context. 

 When an anchor is in progress, and a new anchor is added to the session, what does the global variable do? When all the anchors are replaced by other anchors within one operation, what does the global variable do? When multiple anchors are in progress, and all of them are removed, what does the global variable do? Is it even safe to have more than one anchor in progress at the same time? Which anchor needs more progress, and which anchor doesn't need more progress? Does `SpatialAnchorManager.CreateAnchorAsync` in Unity for the first anchor, will it automatically reset the progress of all the other pending anchors to zero?

This is important, not only for me, but also for the user to know, in case multiple anchors exist.

**Comment by pamistel** [comment]
Hi @johannesvollmer 

It is correct, that `RecommendedForCreateProgress` should be at least 1 to create the Anchor. You cannot create multiple anchors in parallel, hence the `RecommendedForCreateProgress` will always be refering to the one you are currently creating. You can create multiple anchors sequentially and then query them all at the same time (for example using their AnchorIDs)

**Comment by mrwellmann** [comment]
There is also #268 with some more explanations on Microsoft.Azure.SpatialAnchors.SessionStatus.

**Comment by johannesvollmer** [comment]
Thank you for your giving these insights on the underlying mechanics :)

Is this currently mentioned somewhere in the documentation?

**Comment by pamistel** [comment]
We have a small section [here](https://docs.microsoft.com/en-us/azure/spatial-anchors/how-tos/create-locate-anchors-unity#provide-feedback-to-the-user)

I've added an internal ticket to elaborate in more depth about these mechanics

**Comment by johannesvollmer** [comment]
Excellent, thank you :)
