### ISSUE TITLE
Azure Spatial Anchor sample has no anchorID

### ISSUE THREAD

**Issue by cPtz0** [Azure/azure-spatial-anchors-samples#299]
I'm following the tutorial [Here](https://docs.microsoft.com/en-us/azure/spatial-anchors/tutorials/tutorial-share-anchors-across-devices?tabs=azure-portal%2CVS%2CAndroid).I do every step in the tutorial successfully.But When I run it on my android device.The third function(The Shared one) can't show the ID of my anchor.[like this](https://imgur.com/a/P0Lmqiz).Don't know where is wrong because I follow every step on the web page.Do I miss something or there are more task need to be finish?

**Comment by pamistel** [comment]
Hi @cPtz0 

What Android device are you using?

**Comment by ian-phoria** [comment]
I apologise heavily in advance because this information may be unrelated (and it is somewhat anecdotal) but I've had two clients yesterday and today utilising an application built on Azure Spatial Anchors that are having issues **hosting** anchors in our custom application.

They are both on Samsung devices. A **Samsung Note 20 5G** and a **Samsung Galaxy Tab S6 Lite Wi-Fi 64gb edition**. 

I'm unable to access a Samsung device to test with - so don't have enough information to provide a formal bug report. I will submit a formal bug report if we find this issue is unrelated.

Could this be a recent Samsung specific issue?


**Additional Information:**
Both devices were able to successfully host anchors prior to yesterday (not sure how long ago their last attempt was so this issue may have occurred earlier than yesterday) - but both devices appear now to be receiving errors when hosting anchors. There have been no changes to our host anchor logic and the same process works successfully on Google Pixels and iOS devices.

I was able to get one client to send me some short debug logs - and they appear to be getting the following error:

`CreateNeighborhoodAnchorAndSpatialAnchor failed with HTTP error 0. ReqCV: 1wFnrja8Tdm7HK9claKG8A. ResCV: . JSON Error:`

I believe that error is being logged by the Azure SpatialAnchorManager but I cannot confirm. The devices definitely have solid internet connectivity and active AR sessions (as there's no way to get to the hosting part of our application's logic without a ready AR session and contact with our company API).

Once again, apologies if this is unrelated / useless and for my inability to further test.

**Comment by cPtz0** [comment]
@ian-phoria Thank you for your info.Maybe someone else had this kind of trouble.I didn't counter any error log,so I guess maybe I need to wait for a deeper fix or something.Still thanks for telling me your situation.

**Comment by mrwellmann** [comment]
@ian-phoria We are using an A71 and an S20+ and both work as usual for creating and finding anchors with our app.

**Comment by cPtz0** [comment]
@ian-phoria Really?Then there must have problems on my program setting.Can you tell me how you set the SharingAnchorsServiceUrl(Which will set a web page to store the anchor info,maybe)?

**Comment by mrwellmann** [comment]
@ian-howell Here is how we set it up:

```
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.
using UnityEngine;

namespace Microsoft.Azure.SpatialAnchors.Unity
{
    /// <summary>
    /// This menu item generates an optional configuration file which can be
    /// excluded from source control to avoid committing credentials there.
    /// </summary>
    [CreateAssetMenu(fileName = "SpatialAnchorConfig", menuName = "Azure Spatial Anchors/Configuration")]
    public class SpatialAnchorConfig : ScriptableObject
    {
        [Header("Authentication")]
        [SerializeField]
        [Tooltip("The method to use for authentication.")]
        protected AuthenticationMode authenticationMode = AuthenticationMode.ApiKey;
        public AuthenticationMode AuthenticationMode => authenticationMode;

        [Header("Credentials")]
        [SerializeField]
        [Tooltip("The Account ID provided by the Spatial Anchors service portal.")]
        protected string spatialAnchorsAccountId = "";
        public string SpatialAnchorsAccountId => spatialAnchorsAccountId;

        [SerializeField]
        [Tooltip("The Account Key provided by the Spatial Anchors service portal.")]
        protected string spatialAnchorsAccountKey = "";
        public string SpatialAnchorsAccountKey => spatialAnchorsAccountKey;

        [SerializeField]
        [Tooltip("The Account Domain to use when connecting to the Azure Spatial Anchors services.")]
        protected string spatialAnchorsAccountDomain = "";
        public string SpatialAnchorsAccountDomain => spatialAnchorsAccountDomain;

        [Header("Credentials")]
        [SerializeField]
        [Tooltip("The Client ID to use when authenticating using Azure Active Directory.")]
        protected string clientId = "";
        public string ClientId => clientId;

        [SerializeField]
        [Tooltip("The Tenant ID to use when authenticating using Azure Active Directory.")]
        protected string tenantId = "";
        public string TenantId => tenantId;
    }
}
```
![image](https://user-images.githubusercontent.com/247111/135621716-60c071a3-e9fa-4044-9e33-beaa732bffd1.png)

```
namespace VRTX.Azure.SpatialAnchors
{
    public class AzureAnchorManager : SpatialAnchorManager
    {

        /// <summary>
        /// We load the configuration for the Spacial Anchor Backend. 
        /// From the references it looks like this is not called but it is by it's parent
        /// SpatialAnchorManager.Awake() { LoadConfiguration();}
        /// </summary>
        protected override void LoadConfiguration()
        {
            // Attempt to load configuration from config resource if present.
            SpatialAnchorConfig config = null;

            if (DistributionSettings.Instance.CurrentDistributionMode ==
                DistributionSettings.DistributionMode.Staging)
            {
                config = Resources.Load<SpatialAnchorConfig>("Staging");
            }
            if (DistributionSettings.Instance.CurrentDistributionMode ==
                DistributionSettings.DistributionMode.Production)
            {
                config = Resources.Load<SpatialAnchorConfig>("Production");
            }

            if (config != null)
            {
                // Apply Authentication Mode
                authenticationMode = config.AuthenticationMode;

                if (string.IsNullOrWhiteSpace(spatialAnchorsAccountId))
                {
                    spatialAnchorsAccountId = config.SpatialAnchorsAccountId;
                }
                // Apply Authentication Mode
                if (string.IsNullOrWhiteSpace(spatialAnchorsAccountDomain))
                {
                    spatialAnchorsAccountDomain = config.SpatialAnchorsAccountDomain;
                }
                if (string.IsNullOrWhiteSpace(spatialAnchorsAccountKey))
                {
                    spatialAnchorsAccountKey = config.SpatialAnchorsAccountKey;
                }
                if (string.IsNullOrWhiteSpace(clientId))
                {
                    clientId = config.ClientId;
                }
                if (string.IsNullOrWhiteSpace(tenantId))
                {
                    tenantId = config.TenantId;
                }
            }
        }

    }
}
```

**Comment by cPtz0** [comment]
After few days tring trouble shooting,still can't get the anchor ID.But there's something I found.
1.My anchor is surely being put on the place I want,and my azure spatial anchor website shows that there's really an anchor being created.So the main problem is how should I get the anchor ID?Can I get it on the official tutorial(the android studio project) or should I get it on the azure website?

**Comment by pamistel** [comment]
Hi @cPtz0 

Good to hear we're making progress :)
The AnchorID is created after you have created the Anchor and will be sent to you via callback

Following [this Section](https://docs.microsoft.com/en-us/azure/spatial-anchors/tutorials/tutorial-new-android-app?tabs=azure-portal#upload-your-local-anchor-into-the-cloud) you should be able to get the AnchorID using

`
String anchorId;

 uploadCloudAnchorAsync(cloudAnchor)
            .thenAccept(id -> {
                this.anchorId = id;
                Log.i("ASAInfo", String.format("Cloud Anchor created: %s", this.anchorId));
                runOnUiThread(() -> {
                    MaterialFactory.makeOpaqueWithColor(this, new Color(android.graphics.Color.BLUE))
                            .thenAccept(blueMaterial -> {
                                this.nodeRenderable.setMaterial(blueMaterial);
                                synchronized (this.syncTaps) {
                                    this.tapExecuted = false;
                                }
                            });
                });
            });`
