### ISSUE TITLE
App property not available in shared anchor demo

### ISSUE THREAD

**Issue by nallaperumal** [Azure/azure-spatial-anchors-samples#30]
When trying to run the IOS sample program, it runs successfully. I set the app property for the anchor and fetched the anchor from azure, the property is retrieved properly.

However, when I try to fetch the nearby anchors, the anchor is fetched but the app property is empty. The property that was set is not available.

**Comment by darax** [comment]
Hi @nallaperumal, 

The shared anchor demo and the nearby anchor demo are separate demos.  You should not expect to be able to find nearby anchors from the shared demo.  If you've modified the shared sample to add 'nearby' support then you do need to make sure that the anchors were either created or recalled without resetting or recreating the session.

**Comment by nallaperumal** [comment]
Thanks for the response. I will check the session and get back to you.
