### ISSUE TITLE
Download Previous Version?

### ISSUE THREAD

**Issue by johannesvollmer** [Azure/azure-spatial-anchors-samples#300]
We can't get the newest version working. I want to try to use an older version, maybe `2.10.1`. 

We can download the newest version [azure.com/mixed-reality-packages](https://dev.azure.com/aipmr/MixedReality-Unity-Packages/_packaging?_a=feed&feed=Unity-packages). Is it possible to download a previous version there too? Couldn't find any links. I'm not talking about the samples, but the tarball library for Unity

**Comment by oafolabi-msft** [comment]
Hi @johannesvollmer, you should be able to click on the package and then select the versions tab.
![package_version_images](https://user-images.githubusercontent.com/77306179/135529041-881db968-ad2e-48cb-98d9-cd91f56df060.png)

**Comment by mrwellmann** [comment]
You can add a scoped registry to the your Unity Package Manger. With this you can switch directly inside Unity between versions.
![image](https://user-images.githubusercontent.com/247111/135617230-bc9f968d-62a3-495a-8f3a-5b2ac3a5d655.png)
![image](https://user-images.githubusercontent.com/247111/135617243-bb03d719-33b6-4feb-baab-be9d33e995a3.png)

**Comment by johannesvollmer** [comment]
Thanks for the quick answers and the patience for this reply :)

This is how it looks for me, I can't see the button you mentioned, @oafolabi-msft, are we on a different website?

![grafik](https://user-images.githubusercontent.com/32042925/135859585-563752c0-72cb-4e4b-a092-ad34bba1a57e.png)

I don't need to install an older version as it turns out, but I am curious as to why I can't see that button

**Comment by johannesvollmer** [comment]
@mrwellmann Thank you for this hint, that's a neat feature :)

**Comment by johannesvollmer** [comment]
Ah, how could I not see this, of course I had to click on a specific dependency first, to see the older versions of that specific dependency, haha how embarassing oh no
