### ISSUE TITLE
Cannot collect environment data with Azure Spatial Anchors Unity sample android app

### ISSUE THREAD

**Issue by laurencecliffe** [Azure/azure-spatial-anchors-samples#306]
I am using the following example to create the Azure spatial Anchors (ASA) demo app here:

https://docs.microsoft.com/en-gb/azure/spatial-anchors/quickstarts/get-started-unity-android?tabs=azure-portal

Using the following SDK and Unity versions I cannot get the app to collect the environment data in order to save the data and anchor to my Azure Portal. I have successfully built an iOS version of the app, but the Android version fails to collect any environment data and gets stuck at 0%.

Unity: 2020.3.12f1 
ARFoundation: 4.0.12 
ARCore XR Plugin: 4.0.12 
ARKit XR Plugin: 4.0.12 
Azure Spatial Anchors SDK Core: 2.10.2 
Azure Spatial Anchors SDK for Android: 2.10.2 
Azure Spatial Anchors SDK for iOS: 2.10.2
OS: macOS 11.6
Android Mobile test device: moto g (50), Android 11
iOs test device: iPhone SE (1st generation) iOS 14.4.2

 I've tried updating ARFoundation and the XR plugins to 4.1.7 but no luck...

**Comment by virtualxmy** [comment]
any new update for this matter? waiting for new release?
thank you

**Comment by msftradford** [comment]
Hi @virtualxmy! Yes, this fix will be included in the next release, ASA SDK 2.11.0. If you click the "watch" button at the top of this page, you'll be automatically notified when the release is out.

**Comment by virtualxmy** [comment]
> Hi @virtualxmy! Yes, this fix will be included in the next release, ASA SDK 2.11.0. If you click the "watch" button at the top of this page, you'll be automatically notified when the release is out.

May, i know when does SDK 2.11.0 will be released? Thank you

**Comment by MehranAzimi-msft** [comment]
@virtualxmy and @laurencecliffe ASA SDK 2.11.0 was released yesterday, and the Android issue reported here is fixed in this release. Please give SDK 2.11 a try and let us know if you had any issues. Thanks.
