### ISSUE TITLE
Anchors not consistently found with OpenXR Unity plugin

### ISSUE THREAD

**Issue by robbbbbb** [Azure/azure-spatial-anchors-samples#312]
**Description**

When running the 2.10.2 SDK with the OpenXR plugin, the `SpatialAnchorManager.AnchorLocated` callback is often just never received for a valid anchor in situations where it should be. Shutting down the session and restarting it (without killing the app, changing environmental conditions, or moving the device in any significant way) will often result in the same anchor being found immediately. Subsequent repetitions of the same cycle of stop/starting the ASA session show non-deterministic results, with the anchor sometimes being found immediately and other times never being found.

When the anchor is not located, no errors are reported by the `LogDebug `or `Error` event, the `AnchorLocated` event simple never fires.

**Note:** I reported this as [an issue on the OpenXR-Unity-MixedReality-Samples](https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/issues/51) repo, but since I can repro it in our app (see environment setup below) I believe there's a pretty good chance it not an issue with those samples, but with either the ASA SDK, or with the OpenXR plugin or runtime.

**Steps to reproduce the issue**

1. Build and run [this OpenXR ASA Sample](https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/tree/main/AzureSpatialAnchorsSample)
2. Tap 'Start Session'
3. Place 2 anchors by air tapping
4. Save both anchors by air tapping in their boxes
5. Confirm both have been saved
6. Tap 'Stop Session'
7. Tap 'Start Session'
8. Observe that both anchors were located and appear as green boxes
9. Tap 'Stop Session'
10. Tap 'Start Session'
11. Observe that (usually) at least one, or both of the anchors are never located
12. Repeat steps 9-11 several times (varying the wait between stopping and restarting the session if you want to), and observe that the ability of the SDK to locate the anchors is seemingly random (and usually fails).

**Expected behavior**

Under reasonable environmental conditions an ASA anchor in a given location should always be found, or at least some error logging should happen against the SpatialAnchorManager's `Error` callback.

**Development information (please complete the following information)**
- Unity Version: 2020.3.19f1
- MRTK Version: 2.7.2
- Unity OpenXR Plugin Version: 1.2.8
- Mixed Reality OpenXR Plugin Version: 1.0.3.0
- Windows Mixed Reality Runtime: 107.2109.10010
- Azure Spatial Anchors SDK Version: 2.10.0-beta0014

**AR Device information (please complete the following information):**
- HoloLens
- Device OS Version: 10.0.20348.1018

**Comment by msftradford** [comment]
Hi @robbbbbb, thanks for reaching out! FYI 2.10.0-beta0014 was a prerelease version of the SDK. I recommend upgrading to the latest official release, 2.10.2. Please let us know if you have similar issues after the upgrade. Thanks!

**Comment by robbbbbb** [comment]
Hi @msftradford, thanks for the reply. 

I used 2.10.0-beta0014 because that was the version that the sample project in that repo was set to use (so I assumed it would work). I have also upgraded that sample project to 2.10.2 and tried our project with both 2.10.0-beta0014 and with 2.10.2 and the results are identical in all 4 cases. So it seems there's nothing improved in the official release. 

Can you confirm whether you can repro the issue with the sample project?

**Comment by msftradford** [comment]
Hey @robbbbbb we're working to root cause this (#36910921) so it is hard to say if we can provide a fix at the ASA or MROpenXR level yet. We'll keep this thread updated as we learn more. Thanks!

**Comment by phamqduc** [comment]
Hi @robbbbbb , we want to share with you further updates that ASA SDK 2.11.0 was released recently and it addresses the bug #36539781 and #36808186 mentioned above. We will let you know when updates on other issues are available. Thanks for your patience.

**Comment by phamqduc** [comment]
Closing the issue due to a lack of response. If you have other related questions, please kindly let us know or re-open the issue, @robbbbbb. Thank you.
