### ISSUE TITLE
Link to feedback is broken

### ISSUE THREAD

**Issue by snakex2000** [Azure/azure-spatial-anchors-samples#313]
Repro:
   1)   Go to this page:
          https://github.com/Azure/azure-spatial-anchors-samples

   2)   Click the "feedback" link at bottom of page to give feedback  
           Support

           "Have an idea or suggestion? Give us your feedback"

Expected:
   feedback page to load

Results:
    404 error returned with page not found

Link needs to be updated to following for feedback requests on ASA:
    https://feedback.azure.com/d365community/forum/f47d9b25-0725-ec11-b6e6-000d3a4f07b8#

**Comment by phamqduc** [comment]
Thanks @snakex2000 for providing us with suggestion to improve our documentation. The broken link is now fixed.
