### ISSUE TITLE
iPhone SE (2020) blurry camera on iOS 15.1.x

### ISSUE THREAD

**Issue by Silloty1** [Azure/azure-spatial-anchors-samples#314]
**Description**

I currently have an issue only appearing on iPhone SE (2020). When I am building an ASA Project, even from the Sample project, I have a blurry camera issue. Indeed, the camera cannot focus or refocus on different objects 
The problem only appears on iPhone SE which has made the iOS 15 update, regardless of the version of iOS 15.
The problem doesn't appear on the sample of AR Foundation

**Development information (please complete the following information)**

 - OS: [e.g. Windows\macOS\Linux]
 - Development Platform\Version: Xcode 13, Visual Studio 2019, Unity 2020.3.12f1
 - Azure Spatial Anchors SDK version: 2.9.0

**AR Device information (please complete the following information):**

 - Device: Iphone SE2 (2020)
 - OS: iOS 15.1

Do you have any idea why this is occurring ?

**Comment by ashishash** [comment]
can u explain the process when I was trying to open sample project in unity 
I was facing this errors, I was running on IOS 2020.3.18F1 
<img width="1440" alt="Screenshot 2021-10-31 at 1 46 38 AM" src="https://user-images.githubusercontent.com/10698763/139566178-405cd8d0-3f44-48dc-8cb0-136f4fa89c60.png">

**Comment by VipulKakkad-MSFT** [comment]
@Silloty1 and @mrwellmann, thank for your the detailed post. We haven't seen this type of issue before - we're working on getting a repro on this specific model.
Is it consistent even with no other applications running on the device?

**Comment by Silloty1** [comment]
@VipulKakkad-MSFT Thank you for your answer.
We cannot reproduce that bug with other applications on the iPhone SE unfortunately.
We tried to build differents projects as explained (AR Foundation Samples, ASA Samples), every time with separate Unity Projects and the bug only appears on projects which contain the ASA SDK.
Other AR features or even apps which are using the camera doesn't have the bug

**Comment by Silloty1** [comment]
Hello @VipulKakkad-MSFT 
Did you manage to reproduce the issue on a specific device? Do you need more information from our side ?

Thank you

**Comment by mrwellmann** [comment]
@Silloty1 can be closed as it is a ARFoundation / ARKit issue for updates see https://github.com/Unity-Technologies/arfoundation-samples/issues/909

**Comment by msftradford** [comment]
Awesome find @mrwellmann, thanks very much for the update!
