### ISSUE TITLE
After downloading the git repo with terminal command and opening in unity 

### ISSUE THREAD

**Issue by ashishash** [Azure/azure-spatial-anchors-samples#315]
<img width="1440" alt="Screenshot 2021-10-31 at 1 46 38 AM" src="https://user-images.githubusercontent.com/10698763/139566066-e782f63a-4400-4083-b000-f05750d26153.png">

the dowloaded folder opened in unity  ver  2020.3.18 1f1 and switch the build platform to iOS. 

it throws these errors like spatialanchor does not contain spatialanchorAccountdomain

**Comment by VipulKakkad-MSFT** [comment]
Hey @ashishash, could you verify that you've downloaded both the core package, as well as the iOS package?
[This page](https://docs.microsoft.com/en-us/azure/spatial-anchors/how-tos/setup-unity-project?tabs=unity-package-web-ui#download-asa-packages) describes how to identify the packages you need.
