### ISSUE TITLE
"InvalidOperationException: Couldn't obtain a native anchor pointer" saving anchors on Cloud

### ISSUE THREAD

**Issue by fafux** [Azure/azure-spatial-anchors-samples#316]
**Description**
I am working on Hololens 2 and having problem creating anchors with CloudSpatialAnchor. I both followed the tutorial on [how to create an anchor with Unity](https://docs.microsoft.com/en-us/azure/spatial-anchors/how-tos/create-locate-anchors-unity) and the tutorial on [getting started with azure spatial anchors](https://docs.microsoft.com/en-us/learn/modules/azure-spatial-anchors-tutorials/3-exercise-get-started-with-azure-spatial-anchors?tabs=openxr). In both cases, I get the `InvalidOperationException: Couldn't obtain a native anchor pointer` error in the code line `await cloudNativeAnchor.NativeToCloud();`.
As suggested by @msftradford in #269, I tried to use the [WinXR-based official ASA sample](https://github.com/Azure/azure-spatial-anchors-samples/tree/master/Unity) and the [official MROpenXR+ASA sample](https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/tree/main/AzureSpatialAnchorsSample) on my device and both the tutorials worked without any error. I notice that: 
- in the tutorials in which the prefab is already in the scene and I just have to move it and save it, I get the error.
- in the tutorials in which the prefab is instantiated later and then saved, I don't get any error. 

**Development information (please complete the following information)**
 - OS: Windows 10
 - Unity Version: 2020.3.15f2
 - MRTK Version: 2.7.2
 - Unity OpenXR Plugin Version: 1.2.8
 - Mixed Reality OpenXR Plugin Version: 1.0.1
 - Azure Spatial Anchors SDK Version: 2.10.2

**AR Device information (please complete the following information):**
 - Device: HoloLens 2
 - Device OS Version: 10.0.20348.1432

**Additional context**
The error appears when I try to create a spatial anchor.

**Comment by pamistel** [comment]
Hi @fafux

Could you please clarify a couple of things:
1. You mention in both tutorials [WinXR](https://github.com/Azure/azure-spatial-anchors-samples/tree/master/Unity) & [OpenXR](https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/tree/main/AzureSpatialAnchorsSample) it works, but you mention that there are tutorials - where the prefab is not in the scene - it doesn't work. Could you link to these tutorials?

2. We are currently working on updating the [Tutorial for Unity HL2](https://docs.microsoft.com/en-us/azure/spatial-anchors/tutorials/tutorial-new-unity-hololens-app?tabs=unity-package-web-ui%2Cazure-portal) where it should become clear how to avoid this

**Comment by fafux** [comment]
Hi @pamistel

The two tutorials in which appears the error are the ones in the description: [how to create an anchor with Unity](https://docs.microsoft.com/en-us/azure/spatial-anchors/how-tos/create-locate-anchors-unity) and[getting started with azure spatial anchors](https://docs.microsoft.com/en-us/learn/modules/azure-spatial-anchors-tutorials/3-exercise-get-started-with-azure-spatial-anchors?tabs=openxr). Moreover, I noticed that, if I change the prefab, also [official MROpenXR+ASA sample tutorial](https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/tree/main/AzureSpatialAnchorsSample) does not work getting the same error.

**Comment by msftradford** [comment]
Hey @fafux! I'm not sure that I understand how to repro the issue. It looks like the MROpenXR+ASA sample [first instantiates the prefab](https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/blob/e127cd11d01bf42d23a78e68322bcb6572e7fb61/AzureSpatialAnchorsSample/Assets/Scripts/SpatialAnchorsSample.cs#L269) and then at some time later (after the prefab is already in the scene) [calls NativeToCloud](https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/blob/e127cd11d01bf42d23a78e68322bcb6572e7fb61/AzureSpatialAnchorsSample/Assets/Scripts/SpatialAnchorsSample.cs#L294). It seem that is working for you, is that right? Can you help us understand how you have modified that sample to produce the issue? Is there anything special about the prefabs that you are using? Do they happen to already have ARAnchors attached to them with you call NativeToCloud? Thanks!

**Comment by fafux** [comment]
Hi @msftradford! Yes, it's right. I just used the demo changing the spawned prefab. I created a simple 3D object (a sphere) and I assigned to the `AR Session Origin` GameObject in the `Spatial Anchors Sample (Script)` component the sphere as prefab (image attached below).
![image](https://user-images.githubusercontent.com/36882135/141087929-b6ca0d43-abba-4ad9-82b2-be3abe8feeac.png)
In this case, after creating the local anchor, when the code tries to save to the Cloud the anchor, the app gives me the error.
Instead, if in the sphere I add a component as the standard prefab (`Sample Spatial Anchor`, as in the image below), specifically the `Sample Spatial Anchor (Script)`  with the same exact properties, it works.
![image](https://user-images.githubusercontent.com/36882135/141089170-ef36f2ec-f44f-43bf-bb26-57e646dd6cf9.png)
I cannot understand why I should add also this component to the prefab and why, if I did not, the app gives me the error as in the others tutorials. Thanks!

**Comment by fafux** [comment]
Hi @msftradford! I solved the issue. The sphere is a simple 3D Object->Sphere with attached just the SampleSpatialAnchor.cs script. I removed the dependencies from `text`, `meshRenderer`, `persistentAnchorMaterial` and `transientAnchorMaterial` in this script. Thanks for your time.
