### ISSUE TITLE
Anchor locations are set to the world origin when saved and located on HoloLens

### ISSUE THREAD

**Issue by Adrian-Wennberg** [Azure/azure-spatial-anchors-samples#318]
**Description**

I have recently started running into this issue in an app we have been working on, and I am getting the same issue with the Demo app. When an anchor is being saved, the native anchor seems to move to the world origin position (0, 0, 0). In other words, the position that the HoloLens had when the app started. The anchor also has the same position when the it is loaded. 

**Steps to reproduce the issue**

I managed to reproduce the issue when following the [Unity ASA quickstart guide](https://docs.microsoft.com/en-us/azure/spatial-anchors/quickstarts/get-started-unity-hololens?tabs=azure-portal) using the Windows XR plugin. 

**Expected behavior**

When you save and locate an anchor, it is placed in the correct position according to the local coordinate system and not at the origin. 

**Development information (please complete the following information)**

 - OS: Windows
 - Development Platform\Version: Unity 2020.3.22f1 LTS, Visual Studio Professional 2019
 - Azure Spatial Anchors SDK version: 2.10.2

**AR Device information (please complete the following information):**

 - Device: HoloLens 2
 - OS: 20348.1438.arm64fre.fe_release_svc_sydney_rel_prod.211103-1741

**Comment by Adrian-Wennberg** [comment]
Adding log from the demo project:
[UnityPlayer (DemoProject).log](https://github.com/Azure/azure-spatial-anchors-samples/files/7538556/UnityPlayer.DemoProject.log)

**Comment by msftradford** [comment]
Hi @Adrian-Wennberg, thanks for reaching out! Any chance that you are using Windows XR version 4.5.1+? Is it possible for you to downgrade to version 4.5.0? You may need to downgrade your Unity version so that you can access Windows XR 4.5.0. Thanks a bunch!

**Comment by Adrian-Wennberg** [comment]
That might very well be the issue as I am on Windows XR 4.6. Is there a documented issue with the newer versions? I will try reverting the version tomorrow and get back to you.

**Comment by msftradford** [comment]
@Adrian-Wennberg, we're working to understand a behavior change that started around the 4.5.1/4.6.0 releases and will plan to provide a fix (#36765846) and a documentation update. Please do let us know the result of your experiment. Thanks!

**Comment by Adrian-Wennberg** [comment]
I just tested with version 4.5.0 and everything seems to be working as expected! I downgraded the version by changing it manually in `Packages/manifest.josn` and restarted Unity to make sure it didn't complain. It worked fine on Unity 2020.3.22 with Windows XR version 4.5.0. 

We will move our revert our own app back to 4.5.0 as well for now and probably move over to OpenXR as that seems to be the preferred XR plugin nowadays, especially once we move over to Unity 2021. Thank you so much for the help!

**Comment by maisylam99** [comment]
Hello! I am having the exact issue. I copied code to locate anchors from the LocalSharedDemo to my personal project and anchors are being "found" by their identifier but spawned at the origin. I am using

Unity 2020.3
Windows XR Plugin [4.5]([url](url))
ASA SDK 2.10.0 Preview 1
MRTK 2.7.0

Dependencies
ARCore 4.1.7
ARKit 4.1.7

I also seems to have OpenXR 1.2.3. 

Any ideas what could be the issue? I am not sure if I should remove MRTK and downgrade my ASA SDK or how/if my plugins are conflicting and causing this issue. Any help would be truly appreciated. Thank you!
![Packages](https://user-images.githubusercontent.com/68020322/142262175-f1d1390a-906a-4afa-94cf-1e6ea6cb3b32.PNG)

**Comment by maisylam99** [comment]
Hello! I am having the exact issue. I copied code to locate anchors from the LocalSharedDemo to my personal project and anchors are being "found" by their identifier but spawned at the origin. I am using
Unity 2020.3
Windows XR Plugin 4.5
ASA SDK 2.10.0 Preview 1
MRTK 2.7.0

Dependencies
ARCore 4.1.7
ARKit 4.1.7

I also seems to have OpenXR 1.2.3. 

Any ideas what could be the issue? I am not sure if I should remove MRTK and downgrade my ASA SDK or how/if my plugins are conflicting. Any help would be greatly appreciated thank you!
![PackagesProj](https://user-images.githubusercontent.com/68020322/142262683-3cb20b01-5cf3-4caf-b545-ec0a3f2375ca.PNG)

**Comment by phamqduc** [comment]
@maisylam99 , ASA SDK 2.11.0 was just released recently that addresses the _original_ reported concern about "native anchor seems to move to the world origin position". Please give SDK 2.11 a try and let us know if you still experience the issue. Thanks.

**Comment by maisylam99** [comment]
Hi @phamqduc thank you for the suggestion! This does not seem to resolve my issue. Now when I try to locate an anchor by providing an identifier, my code cannot make it past the anchor.GetPose() function. I am wondering if I am querying incorrectly? Any help would be appreciated thank you
![LocateAnchor](https://user-images.githubusercontent.com/68020322/143088094-c20541cc-3601-4172-b4ad-b945e3416baf.PNG)
!!

**Comment by msftradford** [comment]
Hi @maisylam99, thanks for reaching out. Is it possible for you to test [the Unity sample app](https://github.com/Azure/azure-spatial-anchors-samples/tree/master/Unity) out-of-the-box to make sure that everything is working with the device/network? I suspect that you might not be using the SpatialAnchorManager and are instead calling directly into CloudSpatialAnchorSession. For GetPose() to work, you'll need to use SpatialAnchorManager and have an enabled ARAnchorManager in the scene. You can see how that works in [DemoScriptBase ](https://github.com/Azure/azure-spatial-anchors-samples/blob/master/Unity/Assets/AzureSpatialAnchors.Examples/Scripts/DemoScriptBase.cs) which is the base class for the [SharedAnchorDemoScript](https://github.com/Azure/azure-spatial-anchors-samples/blob/master/Unity/Assets/AzureSpatialAnchors.Examples/Scripts/AzureSpatialAnchorsSharedAnchorDemoScript.cs).
