### ISSUE TITLE
Multiple anchor detection

### ISSUE THREAD

**Issue by alt95** [Azure/azure-spatial-anchors-samples#32]
It seems like if i try and create a watcher with more than 10 identifiers in it, the AnchorLocated event never fires. Using anything below 10 will work as intended. Is this just an arbitrary cap or is there something else to it?

**Comment by nallaperumal** [comment]
Hi @alt95 I also faced the same issue. It seems that azure spatial anchors is in preview stage and hence, it is a limit enforced by azure team.

**Comment by alt95** [comment]
Yea, would be nice if it was documented somewhere. I was trying to reset a session and then trying to detect more anchors in the next session. Thanks for the reply.

> Hi @alt95 I also faced the same issue. It seems that azure spatial anchors is in preview stage and hence, it is a limit enforced by azure team. However, you can create multiple 3d game objects around a single anchor in your program.

**Comment by julianparismorgan** [comment]
Hey @alt95, right now we have a max limit of 10 anchors per watcher. Thanks for the suggestion on adding this to the docs, will look into it!

**Comment by Merichbier** [comment]
This limit of 10 anchors exists, but you can always queue your watcher to find more anchors. If you are not sure that a watcher will end, you could do something like "context switch"

**Comment by vriveras** [comment]
Yes this cap is to control the amount of data we are looking for in given area. This number is now 35 instead of 10.
