### ISSUE TITLE
AsaPreProcessBuildForAndroid.cs still requires AppCenter dependency in 2.11.0 

### ISSUE THREAD

**Issue by mrwellmann** [Azure/azure-spatial-anchors-samples#321]
**Description**
I've updated to 2.11.0 and removed the AppCenter dependencies from the mainTemplate.gradle
AsaPreProcessBuildForAndroid.cs still requires AppCenter dependency and throws get a `Error building Player: BuildFailedException: Missing dependency: com.microsoft.appcenter:appcenter-analytics ...` on build.

**Comment by phamqduc** [comment]
Hi @mrwellmann , thank you for sharing with us your concern.
Please be noted that this SDK release 2.11.0 does not remove the dependency on App Center for telemetry on Android platform. We consider replacing it in a future release.
However, we add a new `CloudSpatialAnchorSession::EnableTelemetry` to SDK API which allows apps to disable telemetry by calling `CloudSpatialAnchorSession::EnableTelemetry(false` before calling `CloudSpatialAnchorSession::Start()`.
Please see a full version of the release notes [here ](https://github.com/Azure/azure-spatial-anchors-samples/releases/tag/v2.11.0) for further details.

**Comment by mrwellmann** [comment]
Thanks I for the clarification. I should have read the release notes with more attention.
