### ISSUE TITLE
System.InvalidOperationException: . Request CV: . Response CV: .   at Microsoft.Azure.SpatialAnchors.NativeLibraryHelpers.CheckStatus

### ISSUE THREAD

**Issue by AnandMulay** [Azure/azure-spatial-anchors-samples#324]
I don't know what I'm doing wrong, I have multiple scenes where my ASA setup runs and set anchor for the scene, but when i get back to the main menu and load another scene with the same setup i get this error - 
------------------------------------------------------------------
System.InvalidOperationException: . Request CV: . Response CV: .
  at Microsoft.Azure.SpatialAnchors.NativeLibraryHelpers.CheckStatus (System.IntPtr handle, Microsoft.Azure.SpatialAnchors.status value) [0x00000] in <00000000000000000000000000000000>:0 
  at AnchorModuleScript+FindAnchorDelegate.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.Tasks.Task.InnerInvoke () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.Tasks.Task.Execute () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.TimerCallback.Invoke (System.Object state) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.ExecutionContext.RunInternal

---------------------------------------------------------------------------

on this line public async void CreateAzureAnchor(GameObject theObject)
    {
        CreateLocalAnchor(theObject);

        bool success;

        try
        {
            Debug.Log("Creating Azure anchor... please wait...");

            // Actually save
            await cloudManager.CreateAnchorAsync(localCloudAnchor);    ----- here

i believe it is possible to create a new session and place an anchor multiple times in different unity scenes in a single app.

Unity 2019.4.28
ASA SDK 2.8.1 
Hololens 2

**Comment by msftradford** [comment]
Hi @AnandMulay, thanks for reaching out! Yes, you should be able to load a new scene and create an anchor in the new scene. You can see an example of this with [our Unity sample](https://github.com/Azure/azure-spatial-anchors-samples/tree/master/Unity). Can you try that sample on your device, change between scenes, and create an anchor in a new scene? You can see how we clean-up in-between scenes [here](https://github.com/Azure/azure-spatial-anchors-samples/blob/dec2392ceed364f020bfaa1bee8b205ebeccbe78/Unity/Assets/AzureSpatialAnchors.Examples/Scripts/DemoScriptBase.cs#L42). Let us know how it goes. Thanks!
