### ISSUE TITLE
Azure Spatial Anchors - How to get multiple Anchors.

### ISSUE THREAD

**Issue by RohitJoshi03** [Azure/azure-spatial-anchors-samples#325]
I tried the Azure Spatial Anchor for iOS (Swift) and it worked fine. I can add and retrieve single Anchor but now I want to retrieve multiple Anchors.

**Comment by msftradford** [comment]
Hey @RohitJoshi03, thanks for reaching out! There are few ways to retrieve anchors and you can read more about them [here](https://docs.microsoft.com/en-us/azure/spatial-anchors/concepts/anchor-locate-strategy). Assuming that you just want to retrieve multiple anchors using their identifiers, then you would modify [this function](https://github.com/Azure/azure-spatial-anchors-samples/blob/dec2392ceed364f020bfaa1bee8b205ebeccbe78/iOS/Swift/SampleSwift/ViewControllers/BaseViewController.swift#L307) to add multiple identifiers to `ids`.
