### ISSUE TITLE
'Next' button missing in create session

### ISSUE THREAD

**Issue by nallaperumal** [Azure/azure-spatial-anchors-samples#33]
Hi there, I tried to run the azure spatial anchors unity project with scene 'Local shared Demo' in Hololens v1. When I try to create an anchor, after couple of clicks the 'Next' button got vanished. However, the clicks were still working (though button not there).

Device used: Hololens v1
Unity version: 2018.3.14f
Visual Studio: 2017 (community edition)

**Comment by darax** [comment]
this is intentional. Aside from the first part of the sharing sample where we needed buttons to know the user's intent, we don't use buttons in the HoloLens samples.

**Comment by nallaperumal** [comment]
Thanks for the quick response
