### ISSUE TITLE
Best practices on the CloudSpatialAnchorWatcher and anchor realignment

### ISSUE THREAD

**Issue by mrwellmann** [Azure/azure-spatial-anchors-samples#332]
1. We stop and recreate a watcher every time we find an anchor to reduce the number of anchors in the watcher. Would you suggest this as best practice, or would you suggest leaving found anchors in the watcher if the limit of 35 is not reached? Here is our specific context:
   - We create the watcher with the criteria LocateStrategy.AnyStrategy and bypassCache = false.
   - Usually, we have about 5-20 Anchors. 
   - All anchors have been created in one session. After finding the initial anchor by visual information all other are found by relationship.
2. Is there any reason that anchors created in one session will not be found by relationship?
   - I have not encountered this. So, at his point I think it is not.
3. If a user notice a to big misalignment of an anchor found by relationship. Is there a best practice you can suggest realigning them?
   - We have sometimes more than 15 Meter distances between the anchor found by visual information and others found by relationship. So, a rotational error can happen.
   - We are looking for a realignment if the misalignment is more than 1/2 Meter.
   - We are walking along a route, and we would only realign the anchors which continue to be further away.
   - My only idea would be to create a new watcher with the misaligned anchor and any other further away from the anchor found by visual information.

**Comment by Varnauld** [comment]
Tracking via work item 37789223, thank you!

**Comment by msftradford** [comment]
Hello @mrwellmann!
1. Are you configuring the watcher to use Identifiers or NearDeviceCriteria? If NearDeviceCriteria, are you setting the [MaxResultCount](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.spatialanchors.nearanchorcriteria.maxresultcount?view=spatialanchors-dotnet)? Is the intention of restarting the watcher to minimize cost, query time, or something else?
2. If all anchors are created in one session and the device tracker has not been interrupted during the session, each of the anchors should be connected via relationship
3. Once an anchor has been created, there is no way to update the associated environment information or the pose wrt to other anchors. To address an issue with a specific anchor relationship, I would recommend either:
  a. offset the content from the anchor, move the content to the correct spot, then store the new pose offset to the existing anchor
  b. delete the existing incorrect anchor, find the other anchors (to re-establish the relationships), and recreate a new anchor at the correct pose (taking care to check the pose accuracy of the other anchors, as controlled by the device tracker, before creating the new anchor)

**Comment by mrwellmann** [comment]
1. We are using Identifiers. It is a bit embarrassing but I don't know what the original intention was. This part of the code was written more then 1 1/2 years ago and the creator is not longer in the company. The git history does not help here. Also ASA changed since then as well so it might be possible that time it was a good idea and know it is not. I'm now trying to figure out if this is a good idea or not.

**Comment by msftradford** [comment]
@mrwellmann, thanks for the info! I do not believe that there is a benefit to restarting the watcher on each found anchor. Either way, you are still finding the same number of anchors and using the same amount of ALR. I can imagine that stopping and restarting the watcher may end up taking longer than just waiting for the initial watcher to complete.

**Comment by mrwellmann** [comment]
By coincidence in the HoloDevelopers developer slack was a similar question. So for anybody comming here in the future
![image](https://user-images.githubusercontent.com/247111/156311740-4b93e3ba-d206-4065-8e83-401be4d20aab.png)
