### ISSUE TITLE
Is AR Core Depth Required necessary?

### ISSUE THREAD

**Issue by mrwellmann** [Azure/azure-spatial-anchors-samples#334]
The Unity sample project has set AR Core Depth Required. Which will translate to `<uses-feature android:name="com.google.ar.core.depth" />.`

Is this really necessary for ASA to work properly or is it just suggested to have a optimal experience.
We have a Samsung A71 (not a71x or a71xq) which does not support com.google.ar.core.depth and it seems to work fine.

**Comment by Varnauld** [comment]
Tracking via work item [38060572] assigned to @MehranAzimi-msft

**Comment by mrwellmann** [comment]
Updated my original comment as `<uses-feature android:name="com.google.ar.core.depth" />` was hidden beause of some markup issues.

**Comment by MehranAzimi-msft** [comment]
@mrwellmann ASA on Android does not use ARCore depth APIs and so com.google.ar.core.depth is not needed.

**Comment by mrwellmann** [comment]
> @mrwellmann ASA on Android does not use ARCore depth APIs and so com.google.ar.core.depth is not needed.

In this case I suggest to disable Project Settings->AR Core-> Depth = Required in the Unity sample of this repository as it is misleading that it used.

**Comment by Varnauld** [comment]
Thanks for the follow-up, tagging @pamistel for us to track this for our next updates (work item: 38060572)
