### ISSUE TITLE
"Type exists in both" console errors when installing Core SDK and Windows SDK

### ISSUE THREAD

**Issue by StefanNikolovXR** [Azure/azure-spatial-anchors-samples#335]
Hello, I'm getting "type exists in both" errors after I install the Windows SDK. My Unity version is 2020.3.28f, ASA SDK core and Windows are both version 2.12.0. I'm using the Open XR Plugin and that one is version 1.2.0. Thank you very much in advance for any assistance you can give me!
![asa error](https://user-images.githubusercontent.com/99468787/153553009-36d465f8-9191-446e-8110-26e0c4b08f50.png)

**Comment by Varnauld** [comment]
Hello @ChefoSLR - tracking this action item 38186708, assigned to @pamistel

**Comment by pamistel** [comment]
Hi @StefanNikolovXR 
Could you please let us know which instructions you followed?

Following [this](https://docs.microsoft.com/en-us/azure/spatial-anchors/quickstarts/get-started-unity-hololens?tabs=azure-portal) including the import section should not yield the error you are experiencing.

Feel free to also give the [Open XR Sample](https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples) a try. Instructions on how to run can be found [here](https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/tree/main/AzureSpatialAnchorsSample
)

**Comment by StefanNikolovXR** [comment]
Hello, I repeated the process on Unity 2021.3.1f1 and I was able to run the Spatial Anchors SDK with no console errors.  I followed the instructions here  - https://docs.microsoft.com/en-us/azure/spatial-anchors/how-tos/setup-unity-project?tabs=xr-plugin-framework%2Cunity-2020%2Cunity-package-web-ui%2CExtraConfigurationsHoloLens#project-requirements
