### ISSUE TITLE
SpatialAnchorManager property IsReadyForCreate tests sessionStatus.RecommendedForCreateProgress

### ISSUE THREAD

**Issue by TangarTomas** [Azure/azure-spatial-anchors-samples#337]
**Description**

The implementation of (public) property IsReadyForCreate tests SessionStatus.RecommendedForCreateProgress >= 1, but it should test SessionStatus.ReadyForCreateProgress >= 1.

This makes it impossible to eg. create anchors using SpatialAnchorManager.CreateAnchorAsync before RecommendedForCreateProgress reach 1, even though ReadyForCreateProgress is over 1.

**Steps to reproduce the issue**

1. Wait for SessionStatus.ReadyForCreateProgress to reach 1
2. Check value of SpatialAnchorManager.IsReadyForCreate, it will indicate false

**Expected behavior**

SpatialAnchorManager.IsReadyForCreate should be true when SessionStatus.ReadyForCreateProgress >= 1

**Development information (please complete the following information)**

 - OS: macOS
 - Development Platform\Version: Unity 2020.3.26f1
 - Azure Spatial Anchors SDK version: 2.12.0

**AR Device information (please complete the following information):**

 - Device: iPhone 12 Pro
 - OS: iOS 15.2.1

**Comment by phamqduc** [comment]
Hi @TangarTomas, thank you for bringing to our attention your observation of the issue. We'll investigate and check the implementation details as mentioned and get back to you.

**Comment by Varnauld** [comment]
Hello @TangarTomas - apologies for the delay. We believe we have addressed this in our release last July - could you confirm whether this is resolved please? Or alternatively, provide some further insights into the issues encountered,. Thank you 
https://github.com/Azure/azure-spatial-anchors-samples/releases

**Comment by TangarTomas** [comment]
It's resolved per [v2.13.0](https://github.com/Azure/azure-spatial-anchors-samples/releases/tag/v2.13.0), thank you.
