### ISSUE TITLE
UserFeedback for Maximum limit during creating an Anchor

### ISSUE THREAD

**Issue by nikhilsawlani** [Azure/azure-spatial-anchors-samples#338]
Hi,

I know there is class `UserFeedback`  which shows `RecommendedForCreateProgress` [here in doc](https://docs.microsoft.com/en-in/azure/spatial-anchors/how-tos/create-locate-anchors-unity#provide-feedback-to-the-user), but I wanted to check if we have a MaximumForCreateProgress' method? as in our case users sometime croses the limit of RecommendedForCreateProgress and when they save an Anchor the session gets Reset (dumping all captured features) and users have to start again.

So if we have MaximumForCreateProgress method we can show users upfront how max they can go while creating an anchor instead they saving it and then returning that it is out of limit

**Comment by mrwellmann** [comment]
As far as in know there is currently no 'MaximumForCreateProgress' we are using internally 2 as maximum value.
If you haven not seen this, here are some more insight on this topic https://github.com/Azure/azure-spatial-anchors-samples/issues/268

**Comment by nikhilsawlani** [comment]
As mentioned in #268 there is no hard limit on the amount of environmental data that is uploaded to the service during anchor creation. but that's not the case here it seems as if users capture larger space it doesn't create an anchor. 
there should some indicator to give users hard limit feedback

**Comment by nikhilsawlani** [comment]
Hi @pamistel could be please tell me ifs possible to find how much environment an anchor can capture.

**Comment by Varnauld** [comment]
Hello, 
There is no correlation between a session resetting and the system reaching any maximum limit for environment data. As part of saving the anchor, the SDK uploads some environment data that it has been collecting in the background. The "recommended for create progress" and "ready for create progress" values reflect if enough data has been collected for successfully saving an anchor and saturate at 1.0. Even after they saturate the system keeps collecting data as the device scans the space further.
There is an upper limit on how much environment data the SDK uploads with each anchor. However, that is not something we currently surface through an API (if that limit has been reached for saving an anchor). If this is a feature you believe would be valuable, could you submit the idea [here](https://feedback.azure.com/d365community/forum/f47d9b25-0725-ec11-b6e6-000d3a4f07b8) please (we review and consider these for future iterations). Thank you!

**Comment by nikhilsawlani** [comment]
Thanks, I have submitted the idea

**Comment by Varnauld** [comment]
Thank you @nikhilsawlani !
