### ISSUE TITLE
Order of Anchors retrieved by relationship

### ISSUE THREAD

**Issue by mrwellmann** [Azure/azure-spatial-anchors-samples#341]
Wehen in Low connection settings, it takes some time until all anchors found by relation ship are received.
Is there an order on how ASA Service sends them?
E.g:
- Order of how the are in the watcher
- Order when they have been originally created
- Distance to the anchor found by relation ship

**Comment by chwarr** [comment]
No, there is no meaning you can ascribe to the order the anchors are returned.
