### ISSUE TITLE
Unity - Android ,cloudManager.SessionStatus.RecommendedForCreateProgress gets null reference exception 

### ISSUE THREAD

**Issue by AnandMulay** [Azure/azure-spatial-anchors-samples#344]
**Description**
my app is working fine on Hololens and ios, same code works all good on these platforms, the issue only occurs for the android platform, it doesn't scan the room well , and I tried to debug using android logcat
 and i get null reference exception on this line -
float createProgress = cloudManager.SessionStatus.RecommendedForCreateProgress;

 - OS: [Android]
 - Development Platform\Version:[ Unity 2019.4.28 ]
 - Azure Spatial Anchors SDK version: [e.g. `2.8.1`]
-    com.unity.xr.arcore": "3.1.10",   - updated from 2.1.19 to solve blackscreen issue on Android 11
    "com.unity.xr.arfoundation": "2.1.18",
    "com.unity.xr.arkit": "2.1.19",
**AR Device information (please complete the following information):**

 - Device: [Samsung S20, oneplus 5 , and many others]
 - OS: [Android10 & Android 11]

**Additional context**
`        theObject.CreateNativeAnchor();
             
        localCloudAnchor = new CloudSpatialAnchor();
        
        localCloudAnchor.LocalAnchor = theObject.FindNativeAnchor().GetPointer();
        
        if (localCloudAnchor.LocalAnchor == IntPtr.Zero)
        {
            Debug.Log("Didn't get the local anchor...");
            return;
        }
        else
        {
            Debug.Log("Local anchor created");
        }

        localCloudAnchor.Expiration = DateTimeOffset.Now.AddDays(7);
        Debug.Log("expiration set. cloud manager is: " + cloudManager.ToString());

        // Save anchor to cloud
        while (!cloudManager.IsReadyForCreate)
        {
            await Task.Delay(330);
            float createProgress = cloudManager.SessionStatus.RecommendedForCreateProgress;
            QueueOnUpdate(new Action(() => Prgresstext.text = $"Move your device to capture more environment data: {createProgress:0%}"));;
        }`

**Comment by Varnauld** [comment]
Thank you for reaching out! (tracking task n# 38687865)

**Comment by darax** [comment]
@AnandMulay  
Hi AnandMulay, this could happen if SessionStatus was null. SessionStatus can be null until the ASA SDK processes a few frames. 

It might help to make a change like:
` float createProgress = cloudManager.SessionStatus == null ? 0 : cloudManager.SessionStatus.RecommendedForCreateProgress;
        QueueOnUpdate(new Action(() => Prgresstext.text = $"Move your device to capture more environment data: {createProgress:0%}"));`

If you want to know deterministically that the SessionStatus is ready, you can subscribe to the cloudManager.SessionStarted event before calling cloudManager.StartSessionAsync().

**Comment by Varnauld** [comment]
Hello @AnandMulay - if you believe your question has been answered, please let us know if we can close this issue. If not, please let us know how we can be of further help, thank you!

**Comment by Varnauld** [comment]
@AnandMulay I will go ahead and close this item, thank you!
