### ISSUE TITLE
Crash when stopping an Azure Session while some anchors are not found

### ISSUE THREAD

**Issue by the-mad** [Azure/azure-spatial-anchors-samples#346]
**Description**

Using the **azure-spatial-anchors-samples** project (iOS/Swift), I experienced a crash if I "quit" a session whereas anchors have not yet been found.

**Steps to reproduce the issue**

1) `git clone https://github.com/Azure/azure-spatial-anchors-samples.git`
2) `cd azure-spatial-anchors-samples/iOS/Swift && pod install`
3) Open the .xcworkspace with Xcode, set the `accountId`, `accountKey`, `accountDomain`, etc. and launch the app on an iOS device
4) Start the **Coarse Reloc Demo** and follow the steps :
        - Tap to start session
        - Tap to place an anchor 
        - Wait until it's saved to the cloud (scan over 100%)
5) At this very moment, **turn around or simply go into another room, where there is no anchors** and start the step **Tap to start next Session & look for anchors near device**
6) The app should show **Looking for anchors near device...**. Now simply press **Exit demo**
7) The app crashes with a `Thread 1: EXC_BAD_ACCESS (code=1, address=0x...)`

**Expected behavior**

I think the expected behavior would be exiting the demo and going back to the main menu without crashing.
I'm working on an application which uses ASA, and *it can happen* that a user exits a session without finding any anchors (which crashes the entire app).

**Development information (please complete the following information)**

 - OS: macOS Monterey (version 12.0.1)
 - Development Platform\Version: Xcode 13.0 (13A233)
 - Azure Spatial Anchors SDK version: 2.12.0

**AR Device information (please complete the following information):**

 - Device: iPhone 8
 - OS: iOS 15.2.1

**Additional informations**

Stack trace when the crash happens :

```
Thread 1 Queue : com.apple.main-thread (serial)
#0	0x0000000101ed69fc in CoarseRelocalization::RawSensorFingerprintProvider::Stop() ()
#1	0x0000000101ed6414 in CoarseRelocalization::RawSensorFingerprintProvider::SetActiveImpl(bool) ()
#2	0x0000000101ed5e38 in CoarseRelocalization::RawSensorFingerprintProvider::~RawSensorFingerprintProvider() ()
#3	0x0000000101ed6000 in CoarseRelocalization::RawSensorFingerprintProvider::~RawSensorFingerprintProvider() ()
#4	0x0000000107c78a74 in std::__1::unique_ptr<CoarseRelocalization::SensorFingerprintProviderBase, CoarseRelocalization::TypeDeleter<CoarseRelocalization::SensorFingerprintProviderBase> >::reset(CoarseRelocalization::SensorFingerprintProviderBase*) ()
#5	0x0000000107c78b14 in CoarseRelocalization::SensorFingerprintProvider::~SensorFingerprintProvider() ()
#6	0x0000000107b1e330 in std::__1::shared_ptr<pplx::details::_Task_impl<TokenLib::GetTokenAsyncContext> >::~shared_ptr() ()
#7	0x0000000107c02bfc in ssc_platform_location_provider::~ssc_platform_location_provider() ()
#8	0x0000000107c02c78 in ssc_platform_location_provider::~ssc_platform_location_provider() ()
#9	0x0000000107c02b54 in boost::intrusive_ptr<ssc_sensor_capabilities>::~intrusive_ptr() ()
#10	0x0000000107c05d3c in ssc_cloud_spatial_anchor_session::~ssc_cloud_spatial_anchor_session() ()
#11	0x0000000107c05e30 in ssc_cloud_spatial_anchor_session::~ssc_cloud_spatial_anchor_session() ()
#12	0x0000000107b004f4 in ssc_cloud_spatial_anchor_session_release ()
#13	0x0000000107c8f078 in -[ASACloudSpatialAnchorSession dealloc] ()
#14	0x0000000100fa8528 in outlined destroy of ASACloudSpatialAnchorSession? ()
#15	0x0000000100fa7300 in @objc BaseViewController.__ivar_destroyer ()
#16	0x0000000199d18f50 in object_cxxDestructFromClass(objc_object*, objc_class*) ()
#17	0x0000000199d15f48 in objc_destructInstance ()
#18	0x0000000199d1edfc in _objc_rootDealloc ()
#19	0x0000000184f7ca1c in -[UIResponder dealloc] ()
#20	0x0000000184e4eea8 in -[UIViewController dealloc] ()
#21	0x0000000199d185c8 in AutoreleasePoolPage::releaseUntil(objc_object**) ()
#22	0x0000000199d14e30 in objc_autoreleasePoolPop ()
#23	0x000000018294406c in _CFAutoreleasePoolPop ()
#24	0x000000018293d3f0 in __CFRunLoopPerCalloutARPEnd ()
#25	0x000000018293c1cc in __CFRunLoopRun ()
#26	0x000000018294ee1c in CFRunLoopRunSpecific ()
#27	0x00000001a2cc99a0 in GSEventRunModal ()
#28	0x0000000185182600 in -[UIApplication _run] ()
#29	0x0000000184f17b08 in UIApplicationMain ()
#30	0x0000000100fa9f7c in main at /Users/XXX/azure-spatial-anchors-samples/iOS/Swift/SampleSwift/AppDelegate.swift:7
#31	0x00000001010b4250 in start ()
```

**Comment by the-mad** [comment]
Any news about an update regarding this ?

**Comment by darax** [comment]
Hi @the-mad, We're working through some other issues in our internal branch so I cannot say exactly when we'll be releasing, but I would guess our next release is 2-3 weeks out.

**Comment by darax** [comment]
hi @the-mad, I wanted to update you. We are still 2-3 weeks out, but I am much more confident now. (we have worked through the internal issues and are preparing to start testing for the release)

**Comment by the-mad** [comment]
Thank you @darax can't wait for this release 👍

**Comment by the-mad** [comment]
Hello @darax ,
I just tested the new SDK version (2.13.0) and it seems the issue is still there (or a similar one)...
Here is the steps I made : 
1. I cloned the repo;
2. cd iOS/Swift && pod install --repo-update;
3. I set my project's credentials in BaseViewController.swift;
4. Here, no matter which demo I start, the following steps produce a crash : 
    a. Start the demo and place an anchor;
    b. Move the device around until the anchor is saved to the cloud;
    c. Start the new session and look around for the anchor;
    d. **At this point**, if you tap the **Exit** button **before the anchor is found**, the app still crashes !

Sadly, the stack trace isn't very helpful here... I will try my best to get a "usable" stack trace.

**Comment by XiangyuL-Microsoft** [comment]
@the-mad 

We just released a new version of SDK [2.13.0](https://github.com/Azure/azure-spatial-anchors-samples/releases/tag/v2.13.0).
Could you try this new version of SDK to see if the problem still persists please?
Thank you very much.

**Comment by the-mad** [comment]
> Hello @darax , I just tested the new SDK version (2.13.0) and it seems the issue is still there (or a similar one)... Here is the steps I made :
> 
> 1. I cloned the repo;
> 2. cd iOS/Swift && pod install --repo-update;
> 3. I set my project's credentials in BaseViewController.swift;
> 4. Here, no matter which demo I start, the following steps produce a crash :
>    a. Start the demo and place an anchor;
>    b. Move the device around until the anchor is saved to the cloud;
>    c. Start the new session and look around for the anchor;
>    d. **At this point**, if you tap the **Exit** button **before the anchor is found**, the app still crashes ! Maybe is there a _**trick**_ to make this work I'm not aware of ?
> 
> Sadly, the stack trace isn't very helpful here... I will try my best to get a "usable" stack trace.
> 
> I think the bug relates to **ASACloudSpatialAnchorWatcher** still. In the app I work on, I create a watcher like so :
> 
> ```
> func getAnchorLocateCriteria(_ anchorIds: Array<String>) -> ASAAnchorLocateCriteria? {
>     guard let criteria = ASAAnchorLocateCriteria() else {
>       return nil
>     }
>     
>     criteria.identifiers = anchorIds
>     criteria.strategy = .anyStrategy
>     criteria.requestedCategories = .spatial
>     return criteria
> }
> 
> // ... somewhere else, I create it this way (anchorIds is an array containing the IDs of the anchors I'm looking for)
> guard let criteria = getAnchorLocateCriteria(anchorIds) else {
>     return
> }
> watcher = cloudSession.createWatcher(criteria)
> ```
> 
> and when I dismiss the view, I stop the session and the watcher by doing something like :
> 
> ```
> func stop() {
>     if let watcher = watcher {
>         watcher.stop() // <--- When the app crahes, it crashes here (Thread 1: EXC_BAD_ACCESS (code=1, address=0x10c74898))
>     }
>     watcher = nil
>     
>     if let cloudSession = cloudSession  {
>         cloudSession.stop()
>         cloudSession.dispose()
>     }
>     cloudSession = nil
> }
> 
> deinit {
>     stop()
> }
> ```
> 
> Hope this helps...

Hello ! I tested it already and my issue is still there, as I said in my last comment.

**Comment by darax** [comment]
@the-mad thanks for following up.  There was definitely an issue fixed in 2.13 (the coarse reloc SensorFingerprint classes didn't have proper destructors in the iOS codebase, and the first stack corroborates), so this probably is separate but similar. I'll check to see what is still wrong. Before the fix I think I was able to crash the app without starting a watcher (step 4a), so I wasn't trying as far into the sample as possible.

**Comment by the-mad** [comment]
Hello @darax and thank you for your answer !
Let me know if you need some extra informations/tests from me 👌

**Comment by the-mad** [comment]
Hello @darax 
I wanted to know how you see things concerning this issue. Will there be a fix for the v2.13 coming soon or will this be part of the next update ? How many time until the update ?

**Comment by darax** [comment]
hey @the-mad 
Apologies for taking so long to get back to you.  I have been able to reproduce this in the sample; I'll work on root causing and see if there is a workaround.

**Comment by darax** [comment]
hello @the-mad,
I need to see what we can do about this to prevent the crash. I suspect what is happening is some ARKit state that the ASA runtime is using has been cleaned up, and memory is being corrupted. I was able to work around this in the sample by adding a call to  StopSession() before calling self.dismiss() in moveToMainMenu(). Could you implement the same workaround in your application? In 2.12 I believe the call to StopSession() would crash when using coarse reloc.

**Comment by the-mad** [comment]
Hello @darax thanks for reaching out !
If I understand correctly, the ASA Session must be stopped **before** ARKit is freed when dismissing the view.
Indeed, I our project (in Swift) the StopSession() is called in `deinit { ... }`.
I will see to integrate the workaround you have suggested and let you know if it works 👌

**Comment by the-mad** [comment]
It's working like a charm !!! 🎉  Thank you for the intel ;)

**Comment by darax** [comment]
@the-mad glad to hear.  This has been digging at the back of my mind for a month. :)
