### ISSUE TITLE
Collect environmental information

### ISSUE THREAD

**Issue by shoukailiang** [Azure/azure-spatial-anchors-samples#349]
**Description**

I don't quite understand why this demo doesn't need to collect environment information when creating anchors in hololens2.

**Comment by Varnauld** [comment]
Hello @shoukailiang, could you provide some further information on what you're trying to do and what issues you may be seeing or concerns you have? Thank you!

**Comment by shoukailiang** [comment]
Thank you for your reply @Varnauld . I'm just curious. I've run this demo on both iPad and hololens 2. On the iPad, I need to move my device to collect environmental information before I can create a successful anchor. However, on hololens 2, I can successfully create the anchor without collecting environmental information.

**Comment by Varnauld** [comment]
It is actually collecting information as you are walking around in your space - it may seem more "natural" though as you are glancing around your space as opposed to pointing a device in one direction or another. Is that helpful? Our documentation does have a few links around these concepts if you want to read further information : https://docs.microsoft.com/en-us/windows/mixed-reality/design/core-concepts-landingpage
