### ISSUE TITLE
App not launching (Hololens)

### ISSUE THREAD

**Issue by nallaperumal** [Azure/azure-spatial-anchors-samples#35]
Hi there,

I tried to launch the 'local shared demo' scene from the Unity via VIsual studio 2017 in HoloLens v1.
The app is not at all launching. I made various attempts and sometimes it launches (with some issues like button not visible etc) but mostly the app is blank. Even 'made with Unity' too is not appearing, the app is just blank.
Please help. I have attached the debug log of Visual studio 2017

Unity version: 2018.3.
Visual studio community 2017

[log.txt](https://github.com/Azure/azure-spatial-anchors-samples/files/3247550/log.txt)

**Comment by darax** [comment]
WebException: Error: NameResolutionFailure
and
HttpRequestException: 500 (Internal Server Error)
 makes me think that perhaps there is a typo in the sharing service URL. 

Did you include /api/anchors/ in the URL?

**Comment by nallaperumal** [comment]
We used the same URL in iOS and it worked fine.
I am using Windows 10 Home edition, should I change it to professional?

**Comment by darax** [comment]
By home edition you mean your PC that's building to the HoloLens?  I don't think that matters.  The network configuration of the HoloLens could matter. Is the HoloLens connecting to the same wi-fi as your iOS device?

**Comment by nallaperumal** [comment]
Yes, of course, the hololens is connected to the same network. Also, the HttpRequestException: 500 (Internal Server Error) also appears in iOS app debug log also but the app runs.

**Comment by nallaperumal** [comment]
I finally resolved the issue by using a different windows 10 professional edition laptop. Again reinstalling all the components mentioned in https://docs.microsoft.com/en-in/azure/spatial-anchors/tutorials/tutorial-new-unity-hololens-app#prerequisites
The windows 10 SDK should be properly set to 10.0.17763.0 during the build phase. Probably that could have solved the issue.
