### ISSUE TITLE
Activation of the Windows Store app failed with error 'Access is denied'.

### ISSUE THREAD

**Issue by jimmy12day** [Azure/azure-spatial-anchors-samples#36]
I load the SampleHololens.sln solution in Visual Studio 2017 and it was built successively.
But when I start debugging, it has an error message as below which stop me from deploy the sample app to Hololens1, I followed the exact tutorial from[ GetStartFromHololens](https://docs.microsoft.com/en-us/azure/spatial-anchors/quickstarts/get-started-hololens):
Activation of the Windows Store app 'd1c3b0c0-33f2-48b3-82f8-19844d285be0_0erf857dqbjaw!App' failed with error 'Access is denied'.

**Comment by darax** [comment]
Can you follow the tutorial here: https://docs.microsoft.com/en-us/windows/mixed-reality/creating-a-holographic-directx-project

**Comment by Dugyu** [comment]
You can try debugging on the same built app for a 2nd time even if it shows "Access is denied" and the problem will be fixed.

**Comment by craigktreasure** [comment]
Haven't seen a response. Closing this for now. @jimmy12day, feel free to re-open if you need further help.
