### ISSUE TITLE
IL2CPP azure storage table deprecated

### ISSUE THREAD

**Issue by MirageRTM** [Azure/azure-spatial-anchors-samples#364]
**Description**

Hi everyone ! I'm trying to deploy an app into an Hololens 2 headset. In MRTK2 I used to play with Microsoft.WindowsAzure.Storage.Table for retrieve object and update their status. Now with MRTK3 I wanted to play with the new Azure.Data.table library because Microsoft.WindowsAzure.Storage is officially deprecated. 
With the new library (Azure.data.table), after the deployment and because of IL2CPP the app crash for some AOT error : "Azure.monitor.query.typebinder etc...." and with the old library (Microsoft.WindowsAzure.Storage) you can't compile because of a conflict with the version 12 of Newtonsoft.json library of unity. My question is simple : What do you personnaly use to exchange data with table in MRTK3 and did i make a mistake wanted to use table ? Maybe I should give up ?

**Steps to reproduce the issue**

1. Install the azure.data.table dll in a Asset/Plugins/
2. Create any script an use a method of Azure.data.table such as tableClient.GetEntityAsync<T>();
3. Deploy on an Hololens 2 Headset
4. Run the app

**Development information (please complete the following information)**

 - OS: Windows 10 pro
 - Development Platform\Version: Visual Studio 2022, Unity 2020.3.36f1, MRTK3 prev7

**AR Device information (please complete the following information):**

 Hololens 2

**Comment by Varnauld** [comment]
Hello - thank you for submitting this issue. Tracking this issue (n#40768868) and will assign it shortly, thank you

**Comment by davidkline-ms** [comment]
@Eytos, if you deploy an MRTK3 application without using azure.data.table, do you experience any issues?

Can you also post the details of the error?

Thanks!

**Comment by MirageRTM** [comment]
Hi, thank for both of you answer. I work on MRTK3 and never had issues like that. Here is the error :
`ExecutionEngineException: Attempting to call method 'Azure.Monitor.Query.TypeBinder`1+BoundMemberInfo`1[[System.Collections.Generic.IDictionnary`2[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.Object, mscorlib, Version=4.0.0.0, Culture=neutral,PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.Nullable`1[[System.DateTimeOffSet, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]::.cctor` for which np aheand of time (AOT) code was generated`

Like I said I understand that it is a AOT issue and a generics problem due to IL2CPP. It's just that without azure.data.table and Microsoft.WindowsAzure.Storage I can't see how we are supposed to work with table.
Have a great day.

**Comment by davidkline-ms** [comment]
Not sure if this is going to work, but here is something you might try....

If you add a link.xml file referencing the azure dll you are using, it should prevent Unity's code stripper from removing any code from that library. You _might_ be experiencing an issue related to code stripping and runtime binding.

Please let us know so that we can document guidance and investigate with Unity as needed.

**Comment by MirageRTM** [comment]
Good evening @davidkline-ms, I'm sorry, I forgot to mention that I had already done this by following this link : [https://docs.unity3d.com/Manual/PluginInspector.html](https://docs.unity3d.com/Manual/PluginInspector.html) . 
Here are the contents of my link.xml :
[`<linker>
  <assembly fullname="Azure.Core" />
  <assembly fullname="Azure.Data.Tables" />
  <assembly fullname="Azure.Storage.Blobs" />
  <assembly fullname="Azure.Storage.Common" />
  <assembly fullname="Microsoft.Bcl.AsyncInterfaces" />
  <assembly fullname="System.Buffers" />
  <assembly fullname="System.Core">
    <type fullname="System.Linq.Expressions.Interpreter.LightLambda" preserve="all" />
  </assembly>
  <assembly fullname="System.Diagnostics.DiagnosticSource" />
  <assembly fullname="System.IO.Hashing" />
  <assembly fullname="System.Memory.Data" />
  <assembly fullname="System.Memory" />
  <assembly fullname="System.Runtime.CompilerServices.Unsafe" />
  <assembly fullname="System.Text.Encodings.Web" />
  <assembly fullname="System.Text.Json" />
  <assembly fullname="System.Threading.Tasks.Extensions" />
</linker>`]

**Comment by Varnauld** [comment]
@MirageRTM were you able to resolve this or would you need some further support from @davidkline-ms ? thank you

**Comment by MirageRTM** [comment]
> @MirageRTM were you able to resolve this or would you need some further support from @davidkline-ms ? thank you

Good morning, I workaround the issue by converting tables I needed into collection of objects and serialize it all in json files. I haven't had the opportunity to work with azure data tables so I couldn't say if the bug persists.

**Comment by Varnauld** [comment]
I will close it now - if you do have the opportunity to try again and run into that same bug, please do let us know (we can start a new thread) thank you! Have a great weekend
