### ISSUE TITLE
GetAnchorProperties throws an exception when called with an invalid id

### ISSUE THREAD

**Issue by EVOsparkLP** [Azure/azure-spatial-anchors-samples#367]
**Description**

My app crashes when CloudManager.Session.GetAnchorProperties is called with an anchor ID that does not exist.
According to the docs this method can be used to get anchors that were not located before. In my case I want to get these anchors to delete them.

**Steps to reproduce the issue**

1. Use the ASA demo scene "AzureSpatialAnchorsBasicDemo"
2. In the AdvanceDemoAsync method add the following code to the "DemoStepDeleteFoundAnchor":
```
                case AppState.DemoStepDeleteFoundAnchor:
                    currentAppState = AppState.DemoStepBusy;

                    string anchorId = currentCloudAnchor.Identifier;
                    Debug.Log("Trying to find previously generated anchor with ID " + anchorId);
                    // this line works:
                    currentCloudAnchor = await CloudManager.Session.GetAnchorPropertiesAsync(anchorId);

                    if (currentCloudAnchor != null)
                    {
                        Debug.Log("Anchor found - deleting");
                        // this is what I want to do with the anchor but it has nothing to do with the issue:
                        // await CloudManager.DeleteAnchorAsync(currentCloudAnchor);
                    }
                    else
                        Debug.Log("Anchor not found");

                    anchorId = Guid.NewGuid().ToString();
                    Debug.Log("Trying to find anchor with random ID " + anchorId);
                    // this line crashes the app:
                    currentCloudAnchor = await CloudManager.Session.GetAnchorPropertiesAsync(anchorId);

```
3. Run the app
4. Watch the crash

**Expected behavior**

The GetAnchorPropertiesAsync Method should return null in case the anchor could not be found, instead of throwing an exception

**Development information (please complete the following information)**

 - OS: Windows
 - Unity 2020.3.34f1]
 - ASA-Version 2.13.0

**AR Device information (please complete the following information):**

 - Device: iPad Pro 2020

**Comment by Varnauld** [comment]
Hello, thank you for submitting this issue. Assigned to @darax  (tracking ID [41155293])

**Comment by darax** [comment]
Hi @EVOsparkLP, 
you should wrap the call in a try/catch. generally if an error occurs, a [CloudSpatialException](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.spatialanchors.cloudspatialexception?view=spatialanchors-dotnet ) is thrown, which contains a [CloudSpatialErrorCode ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.spatialanchors.cloudspatialerrorcode?view=spatialanchors-dotnet) to help diganose the issue.
