### ISSUE TITLE
Azure Spatial Anchor with Holographic remote

### ISSUE THREAD

**Issue by almoga296** [Azure/azure-spatial-anchors-samples#371]
**Describe the bug**
I've opened Azure account and enabling the spatial anchors service to build spatially aware mixed reality application.
Clone Azure Spatial Anchors [github](https://github.com/Azure/azure-spatial-anchors-samples) sample.
Can't run azure spatial anchors with holographic remoting (store edition) on windows standalone x64, probably because lack of dll.

**Error:**
DllNotFoundException: AzureSpatialAnchors assembly: type: member:(null)
Microsoft.Azure.SpatialAnchors.AnchorLocateCriteria..ctor () (at Library/PackageCache/com.microsoft.azure.spatial-anchors-sdk.core@bd79930953e8/Runtime/Plugins/Standalone/AzureSpatialAnchorsBridge_Standalone.cs:1928)
Microsoft.Azure.SpatialAnchors.Unity.Examples.DemoScriptBase.Start () (at Assets/AzureSpatialAnchors.Examples/Scripts/DemoScriptBase.cs:112)
Microsoft.Azure.SpatialAnchors.Unity.Examples.AzureSpatialAnchorsSharedAnchorDemoScript.Start () (at Assets/AzureSpatialAnchors.Examples/Scripts/AzureSpatialAnchorsSharedAnchorDemoScript.cs:139)

It looks like Azure spatial anchors doesn't have the compatible .dll file for targeting WindowsStandalone build.

**Remote side - Laptop:**

OS version: WIN10 21H2, build 19044
Using Unity 2021.3.9f1 with MRTK holographic remote for play mode
Nvidia RTX 3070 with driver version 30.0.15.1236

**Player side - HoloLens 2**

OS version: 20348.1513.arm64fre.fe_release_svc_sydney_rel_prod.220802-1135
Store player

Do you familiar with a way to achieve azure spatial anchor to work with holographic remote at all?
Do you familiar with other co-location sharing solution that can work with holographic remote & hololens2?

Almog

**Comment by Varnauld** [comment]
Hello - thank you for submitting this issue. Assigning to @XiangyuL-Microsoft (Tracking n#41323140), thanks!

**Comment by cheles** [comment]
@almoga296  ASA is not supported in Unity Editor, which above error might be related to. You need to switch your Unity build to UWP. https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk2/features/tools/holographic-remoting?view=mrtkunity-2022-05#connecting-to-the-hololens-with-wi-fi

**Comment by yixun** [comment]
@almoga296, Hi I saw your answer about Unity support for Holographic remoting and Azure saptial anchor.  I am using UE5 to do Holographic remoting, do you know if UE5 support both Holographic remoting and Azure spatial anchor?
Thank you so much!

**Comment by cheles** [comment]
@yixun  initial question was in regards of Unity/ASA/HRemoting, where yours is Unreal/ASA/HRemoting. would you mind opening a new Github issue with your question, so any answer to it be helpful for other developers?

**Comment by Varnauld** [comment]
@almoga296 Did the guidance provided by @cheles resolve your issue ? (if yes we can close this but I did want to check whether you had any further questions for us. Thank you!
