### ISSUE TITLE
Unreal sample needed for ASA to be posted, https://learn.microsoft.com/en-us/windows/mixed-reality/develop/unreal/unreal-azure-spatial-anchors

### ISSUE THREAD

**Issue by snakex2000** [Azure/azure-spatial-anchors-samples#373]
Go to following URL:
   https://learn.microsoft.com/en-us/windows/mixed-reality/develop/unreal/unreal-azure-spatial-anchors

A clear and concise description of what the issue is.

**Steps to reproduce the issue**
1)   No sample on GitHub, cannot complete the walkthrough easily  and cannot search text since it is lot of pictures

**Additional context**
Forum posts on not able to find information needed from only text and images provided:
    https://learn.microsoft.com/en-us/answers/questions/1013458/locating-pre-existing-anchors.html

**Comment by Varnauld** [comment]
Hello, thank you for the feedback! It looks like my colleague Nathan made a request for [documentation update]([[url](https://github.com/MicrosoftDocs/mixed-reality/issues/655)]. If you have any further feedback you would like to submit to the team, please do share [here](https://feedback.azure.com/d365community/forum/f47d9b25-0725-ec11-b6e6-000d3a4f07b8?filter=top)

**Comment by snakex2000** [comment]
Thanks!!  

Forums are getting some more Unreal questions & the completed sample would be great to help review + test with reports like this one:

https://learn.microsoft.com/en-us/answers/questions/1034019/using-azure-spatial-anchors-makes-project-crashed.html?childToView=1034978#answer-1034978

**Comment by Varnauld** [comment]
Tagging @pamistel for visibility too, thank you for highlighting this

**Comment by fieldsJacksonG** [comment]
You can find a sample using Azure spatial anchors here:
https://github.com/microsoft/Microsoft-OpenXR-Unreal

The ASA for Unreal doc was mostly based on this sample

**Comment by Varnauld** [comment]
Thanks @fieldsJacksonG for the update here. @snakex2000 I will close this issue out, but if you have any follow-up questions, do let us know, 
thank you,
