### ISSUE TITLE
"Could not establish Pose Query Processor Stream" Error

### ISSUE THREAD

**Issue by thomaswester** [Azure/azure-spatial-anchors-samples#377]
**Description**

Starting October 12, 2022 we are seeing the following error when trying to locate anchors on Hololens2, anchors are not able to be found after this.

` ProcessPoseQueryStreamingEvents - OnError: gRPC error code [1] - msg [Could not establish Pose Query Processor Stream] - ReqCV [r89o1ltbRyq72H9j4vc4NA] - ResCV []`

Anchor location had been working reliable over the last 12 months. 

**Development information (please complete the following information)**

 - Azure Spatial Anchors SDK version: 2.10.2, 2.13.2
 - Unity 2020.3 LTS

**AR Device information (please complete the following information):**

 - Device: Hololens2
 - OS: Windows 20348.1522 and 20348.1518

**Additional context**

Thing we tried so far:
- Deploy on OS 1522, 1518
- Deploy using SDK 2.10.2 and 2.13.2
- Test against new / fresh ASA databsae 
- Test across 4 different devices
- Delete mapping data on devices

**Comment by cheles** [comment]
@thomaswester would you mind opening a Microsoft developer support case here: https://developer.microsoft.com/en-us/windows/support/?tabs=Contact-us and use Mixed Reality Dev topic? I am interested in following this internally and I might need some information about your HL2 and subscription.

**Comment by thomaswester** [comment]
@cheles Thank you. See support request 2210240030001181.
