### ISSUE TITLE
 AnchorModuleScript

### ISSUE THREAD

**Issue by BlackLi-J** [Azure/azure-spatial-anchors-samples#379]
**Description**
 private void CloudManager_AnchorLocated(object sender, AnchorLocatedEventArgs args)
    {
        QueueOnUpdate(new Action(() => Debug.Log($"Anchor recognized as a possible Azure anchor")));

        if (args.Status == LocateAnchorStatus.Located || args.Status == LocateAnchorStatus.AlreadyTracked)
        {
            currentCloudAnchor = args.Anchor;

            QueueOnUpdate(() =>
            {
                Debug.Log($"Azure anchor located successfully");

                // Notify AnchorFeedbackScript
                OnASAAnchorLocated?.Invoke();

#if WINDOWS_UWP || UNITY_WSA
                // HoloLens: The position will be set based on the unityARUserAnchor that was located.

                // Create a local anchor at the location of the object in question
                gameObject.CreateNativeAnchor();

                // Notify AnchorFeedbackScript
                OnCreateLocalAnchor?.Invoke();

                // On HoloLens, if we do not have a cloudAnchor already, we will have already positioned the
                // object based on the passed in worldPos/worldRot and attached a new world anchor,
                // so we are ready to commit the anchor to the cloud if requested.
                // If we do have a cloudAnchor, we will use it's pointer to setup the world anchor,
                // which will position the object automatically.
                if (currentCloudAnchor != null)
                {
                    Debug.Log("Local anchor position successfully set to Azure anchor position");
                   // gameObject.GetComponent<UnityEngine.XR.WSA.WorldAnchor>().SetNativeSpatialAnchorPtr(currentCloudAnchor.LocalAnchor);
                }

A clear and concise description of what the issue is.
Is there any code missing in this script that finds an anchor but has no synchronization location? The following Android method synchronizes in a different place than the first time
**Steps to reproduce the issue**

If the issue occurs in one of the ASA sample apps, please detail the steps required to reproduce it. Otherwise, provide details on how to reproduce it in your custom app.

**Expected behavior**

![a559ccc8882d5c1ac489adee13e1ad1](https://user-images.githubusercontent.com/39038383/197990171-36ee0754-7685-4f7b-8644-9181bdcf5b6f.jpg)

**Development information (please complete the following information)**

 - OS: [e.g. Windows\macOS\Linux]
 - Development Platform\Version: [e.g. Xcode 12.4, Android Studio 4.1.2, Visual Studio 2019, Unity 2020.3.0f1]
 - Azure Spatial Anchors SDK version: [e.g. `2.9.0`]

**AR Device information (please complete the following information):**

 - Device: [e.g. iPhone 12, Samsung S20]
 - OS: [e.g. iOS 14.4, Android 11]

**Additional context**

**Comment by Varnauld** [comment]
Hello, thank you for submitting this issue. @darax would you be available to review please?

**Comment by Varnauld** [comment]
(tracking n# for this issue - 42109963)

**Comment by darax** [comment]
This should be handled by the folks who made that tutorial over here: https://github.com/microsoft/MixedRealityLearning/issues
