### ISSUE TITLE
Sharing in Unity locks up at camera step on iPad

### ISSUE THREAD

**Issue by Alberto-Vega-MSFT** [Azure/azure-spatial-anchors-samples#38]
Moving issue from docs since this is a sample application issue: https://github.com/MicrosoftDocs/azure-docs/issues/33058

Environment: MacBook Pro Mojave 10.14.5; Unity 2019.1.5f1; Visual Studio 2019 for Mac; .NET 2.2.107; Xcode 10.2.1; Build goes fine in unity. cocoa pods installed successfully in App directory. Opened xcworkspace in App directory from terminal. App deploys successfully to iPad and starts to run. Menu functional. When I select the button to allow access to the camera, the application locks. Recurrent message in Xcode window monitoring the running app:(Filename: currently not available on il2cpp Line: -1)

NullReferenceException: Object reference not set to an instance of an object.
at UnityEngine.XR.iOS.UnityARVideo.OnPreRender () [0x00000] in <00000000000000000000000000000000>:0

**Comment by Alberto-Vega-MSFT** [comment]
@ggorby Would you please try to do assets->reimport all  from unity, and then rebuild?

**Comment by ggorby** [comment]
Hi Alberto,
I reimported all with same results...lock up at camera access step.
Gary

Sent from my iPad

On Jun 21, 2019, at 1:31 PM, Alberto Vega <notifications@github.com<mailto:notifications@github.com>> wrote:


@ggorby<https://github.com/ggorby> Would you please try to do assets->reimport all from unity, and then rebuild?

**Comment by ggorby** [comment]
Additional info after reimport:
Repeated build time issues ‘ARWorldMap’ is only available on iOS 12.0 or newer
Single runtime issue: GPU Frame Capture
Shader performance data maybe unavailable due to deployment target older than device version
My iPad is running iOS 12.3.1


Sent from my iPad

On Jun 21, 2019, at 1:31 PM, Alberto Vega <notifications@github.com<mailto:notifications@github.com>> wrote:


@ggorby<https://github.com/ggorby> Would you please try to do assets->reimport all from unity, and then rebuild?

**Comment by darax** [comment]
@ggorby, this isn't an issue I've seen before. I want to figure this out.  Can you confirm that the sample ARKit scene (without ASA) works properly?  Also, can you try Unity 2018? I'll get 2019.1.5f1 installed on my Mac and see if I can reproduce the issue on my end.

**Comment by ggorby** [comment]
Hi Patrick,
I don’t understand what you mean by “...confirm that the sample ARKit scene (without ASA) works properly?” Can you clarify the scene to which you are referring? I will try with an earlier version of Unity. Which release of 2018 worked for you? I did read today in documentation about Mixed Reality Toolkit that .NET was deprecated in Unity 2018 and removed from 2019. Not totally sure if that is relevant but I recall that The .NET Core 2.2 SDK has to be installed as a prerequisite for the ASA tutorial.
Take care,
Gary

Sent from my iPhone

On Jul 1, 2019, at 3:35 PM, Patrick Cook <notifications@github.com<mailto:notifications@github.com>> wrote:


@ggorby<https://github.com/ggorby>, this isn't an issue I've seen before. I want to figure this out. Can you confirm that the sample ARKit scene (without ASA) works properly? Also, can you try Unity 2018? I'll get 2019.1.5f1 installed on my Mac and see if I can reproduce the issue on my end.

**Comment by darax** [comment]
I meant a scene like UnityARKitPlugin\Examples\UnityARKitScene\UnityARKitScene.unity.

2018.3.6f1 is a version that is known to work.

**Comment by andreidevloper** [comment]
@Alberto-Vega-MSFT I have exactly the same issue too. 
@darax I tried to run UnityARKitScene in Unity 2018.3.6f1 and still the recurrent message is got in Xcode 
```
NullReferenceException: Object reference not set to an instance of an object.
  at UnityEngine.XR.iOS.UnityARVideo.OnPreRender () [0x00000] in <00000000000000000000000000000000>:0 
 
(Filename: currently not available on il2cpp Line: -1)
```

**Comment by darax** [comment]
I got my Mac setup to match the original post, and the sample is working built form 2019.1.5f1. If the UnityARKitScene isn't working, then that's a signal that Arkit is also not working.  What iPad do you have?

**Comment by ggorby** [comment]
IPad (6th generation) Model MR7F2LL/A; iOS 12.3.1
32 GB; 18.33 GB Available

Sent from my iPhone

On Jul 5, 2019, at 3:11 PM, Patrick Cook <notifications@github.com<mailto:notifications@github.com>> wrote:


I got my Mac setup to match the original post, and the sample is working built form 2019.1.5f1. If the UnityARKitScene isn't working, then that's a signal that Arkit is also not working. What iPad do you have?

**Comment by darax** [comment]
Just realized that I haven't installed vs 2019 on my mac.  I'll give that a go and double check the .NET version.

**Comment by darax** [comment]
After installing VS 2019 and .NET 2.2.107 the sample still works on my end. 
Since the built in ARkit Plugin sample isn't working, lets double check to see if the ARFoundation sample works.  Can you try out 
https://github.com/Unity-Technologies/arfoundation-samples/tree/2.1
and see if the Assets/Scenes/SimpleAR.unity works on your iPad?
Note that we don't have Azure Spatial Anchors support for AR Foundation yet, I just want to know if it would work on your device.

**Comment by Alberto-Vega-MSFT** [comment]
Hi @ggorby do you have any updates?
