### ISSUE TITLE
Lagging on iOS 16.1

### ISSUE THREAD

**Issue by DinethD-VM** [Azure/azure-spatial-anchors-samples#380]
Trying to test the provided samples and running into heavy lag on iOS 16.1 soon as it starts capturing the environment.

Is this a known issue and if there is any solution to this?

Tested on
- iPad Pro 5th gen running iPadOS 16.1
- Unity 2020.3.1f1
- Azure Spatial Anchors SDK Core v2.13.0
- Azure Spatial Anchors SDK for Android v2.13.0
- Azure Spatial Anchors SDK for iOS v2.13.0
- AR Foundation v4.1.12
- AR Subsystems v4.1.12
- ARCore XR Plugin v4.1.12
- ARKit XR Plugin v4.1.12

Note: Exact same project but running on a Google Pixel XL Gen 1 running Android 10, which works flawlessly.

**Comment by snakex2000** [comment]
Thanks for filing this report.  Adding the comment from the forum too stating this is working prior without lag with iOS 15.6 on the same iPad.

**Comment by mrwellmann** [comment]
There is an in progress issue with iOS 16 and ARKit XR Plugin see https://github.com/Unity-Technologies/arfoundation-samples/issues/988 and https://issuetracker.unity3d.com/issues/ios-fps-in-the-player-is-very-low-when-using-xrcamerasubsystem-dot-trygetlatestframe.

Our solution for now is 4.2.3 without multi-threaded rendering as this does not issues.

**Comment by DinethD-VM** [comment]
Many thanks. That worked.

**Comment by Varnauld** [comment]
Thank you for the awareness @mrwellmann!

(@XiangyuL-Microsoft tracking for this item is n#42109628)

**Comment by cheles** [comment]
@Varnauld @XiangyuL-Microsoft  https://github.com/Unity-Technologies/arfoundation-samples/issues/988 has been marked as Resolved with fixes in AR Foundation/ARKit packages 4.13, 4.2.7, 5.0.3 as covered here https://github.com/Unity-Technologies/arfoundation-samples/issues/988
<5.0 versions are designed to be used in 2020.3 LTS so I've tested our sample with 4.2.7. 
I can't see any camera jitter or holograms drift w/o multi-thread rendering.
