### ISSUE TITLE
Can't select any button in ASA BasicDemo

### ISSUE THREAD

**Issue by thisiszy** [Azure/azure-spatial-anchors-samples#384]
I follow [this tutorial](https://learn.microsoft.com/en-us/azure/spatial-anchors/quickstarts/get-started-unity-hololens?tabs=azure-portal) and compiled the ASA BasicDemo in this repository successfully. When I open the app in HoloLens 2, I can see the button and welcome page, however, I can't press any botton to trigger the next step.

Windows version: 22H2 19045.2251
Device: HoloLens 2
Unity version: 2020.3.40f1

![view](https://user-images.githubusercontent.com/43633145/203435473-f36ca4c7-a807-4b1d-a7bd-165b1da45a7f.jpg)

**Comment by Varnauld** [comment]
Assigning to @pamistel  tracking n#42358297

**Comment by darax** [comment]
fixed in 2.14.1
