### ISSUE TITLE
Can't find release notes for 2.13.3

### ISSUE THREAD

**Issue by mrwellmann** [Azure/azure-spatial-anchors-samples#385]
I'm missing something or are there just no release notes for [2.13.3](https://dev.azure.com/aipmr/MixedReality-Unity-Packages/_artifacts/feed/Unity-packages/Npm/com.microsoft.azure.spatial-anchors-sdk.core/overview/2.13.3)?

**Comment by darax** [comment]
My mistake, I need to figure out where to edit them. :)
until then:
- On HoloLens using the OpenXR runtime, ASA was only issuing queries once per watcher.
- There is a rare crash that was fixed.

**Comment by darax** [comment]
I've updated the 2.13.0 release notes to include the hotfix information.
