### ISSUE TITLE
How to get CloudSpatialAnchor?

### ISSUE THREAD

**Issue by jelmerS2** [Azure/azure-spatial-anchors-samples#391]
I want to update an anchor's AppProperties and for this I need a reference to the CloudSpatialAnchor.
However, anchors in the scene only get a CloudNativeAnchor and ARAnchor component.

How do I get a reference to CloudSpatialAnchor from an earlier retrieved anchor?

**Comment by Varnauld** [comment]
Happy New Year @jelmerS2 
Thank you for your question (tracking 42852602) - assigning to @darax !

**Comment by darax** [comment]
Hi @jelmerS2 
In Unity SpatialAnchorManager provides access to the underlying [CloudSpatialAnchorSession](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.spatialanchors.cloudspatialanchorsession?view=spatialanchors-dotnet). CloudSpatialAnchorSession provides APIs to get and

What I think you need to do is something like:
`
CloudSpatialAnchor spa = await CloudManager.Session.GetAnchorPropertiesAsync(Guid.Empty.ToString());.

spa.AppProperties.Add("new", "entry");

await CloudManager.Session.UpdateAnchorPropertiesAsync(spa);
`

this method will also enable you to delete anchors without first locating them.

**Comment by Varnauld** [comment]
Hi @jelmerS2 - was this helpful for you? May I close this topic if so? Thank you for confirming

**Comment by jelmerS2** [comment]
Yes thanks! You can close this one :)
________________________________
