### ISSUE TITLE
Unity Asset Package or Usage in my Own Project

### ISSUE THREAD

**Issue by jbienzms** [Azure/azure-spatial-anchors-samples#4]
I would really like to see Azure Spatial Anchors available as a stand alone Unity Asset Package. Or at least I would like to see some clear instructions on how to add it to my own project.

Right now it seems the only way to locate the files I need to use ASA in my own Unity projects is by cloning this sample repository. But looking at the sample project it's a little confusing to me which files are needed by ASA itself vs. which ones are only needed for this sample project.

For example, it appears the native API wrapper logic is found in the file **AzureSpatialAnchorsDemoWrapper.cs** which is located in the **Examples** folder. But I wouldn't have known that without searching for it. Since most of the code seems to be put in **Examples**, I don't know which parts I need for my own projects vs. which parts are just for this demo.

Another example is that there seem to be two different sets of plugin folders:

- \Plugins\Android

and

- AzureSpatialAnchors\Plugins\Common
- AzureSpatialAnchors\Plugins\Editor
- AzureSpatialAnchors\Plugins\HoloLens
- AzureSpatialAnchors\Plugins\iOS

The one in the root contains a .gradle file which appears to add a maven reference (among other things). Could this be merged into the other AzureSpatialAnchors\Plugins folder, or does it need to be in the root?

Any guidance on gathering just the parts I need would be greatly appreciated. And I'd love to see an actual Unity Asset Package.

Thanks!

**Comment by vriveras** [comment]
@jbienzms Thank you for the feedback. We are currently working on documenting and creating artifacts to improve the start from scratch scenario. We also want to have this in the Asset store but we have that work scheduled but its not available yet. 

You can still use the unity package we release [here](https://github.com/Azure/azure-spatial-anchors-samples/releases). If you only care about the core minimum to get the API integrated you can just select the following when importing the package. 

![corerequierementsforasa](https://user-images.githubusercontent.com/4194864/53905794-4c8c0a80-3ffe-11e9-9de3-97d4976c410a.png)

The rest of the code is specific to the samples and you can reuse pieces if you want. 

To answer the question for the gradle template plugin on the root we need this to be in the top plugin of the project to make sure our build works properly for Android it cannot be in the AzureSpatialAnchors plugin.

Please let me know if you need any more help getting this integrated.

**Comment by jbienzms** [comment]
Thank you for the update @vriveras. I'm very curious about **AzureSpatialAnchorsDemoWrapper.cs** not being selected in your screenshot above. And actually, this does raise an important question for me. **AzureSpatialAnchorsDemoWrapper.cs** seems significant in the following ways:

- It's used in all of the examples scenes
- It appears to be the primary MonoBehaviour class that "brings the service into the scene"
- It acts as the singleton (.Instance property) for the service
- It provides a way of specifying the **Account ID** and **Account Key** in the Unity Editor
- It provides a way of starting and stopping the service in the Unity Editor (**EnableProcessing** property)
- It provides _significant_ logic such as **EnoughDataToCreate**, **ResetSession**, **CreateNewCloudSession**, etc.
- It deals with background threads vs Unity main thread (via **dispatchQueue**)
- It handles ARCore and ARKit message pumping (**ProcessFrame**, **ARFrameUpdatedEvent**, etc.)
- It handles ARKit matrix transformation (**GetMatrix4x4FromUnityAr4x4**)

Should **AzureSpatialAnchorsDemoWrapper.cs** be considered part of the core Azure Spatial Anchor SDK or should it be considered part of the examples? If it's part of the core, the name and namespace of the class should probably be changed. If it's part of examples, the significant logic in this class really should probably be included somewhere in the core SDK.

If you could please let me know the designed intent for this class, maybe we can open a separate issue to address the design and usage of the logic within?

**Comment by jbienzms** [comment]
Oh, back to the original reason for this issue. Thank you for the screenshot above showing which components are core vs example. This does highlight my reason for opening this issue. Without finding this issue and your screnshot, developers won't be able to determine which components are Core vs. Example. 

It seems there is a Unity build requirement for the .gradle file to be in the root. Other than that file, would it be possible to reorganize the layout of the asset package to better clarify what is core and what is example? Our own MRTK does a great [job of this](https://github.com/Microsoft/MixedRealityToolkit-Unity/tree/mrtk_release/Assets), and it makes it really clear when importing the package which pieces are needed. As an added bonus, having a folder structure that clearly separates Core from Example helps avoid "fuzzy" situations like **AzureSpatialAnchorsDemoWrapper.cs** which appear to be both Example and Core.

**Comment by VincentGuigui** [comment]
I agree that the Wrapper should be moved outside the sample folder as it is a very good bootstrap.

The demoscriptbase contains also some useful ASA logic base which could be extracted from the actual sample logic.

**Comment by vriveras** [comment]
Thanks for your feedback. We are currently working on improvements for the unitypackage and starting a unity project from scratch tutorial which we will be releasing soon.

**Comment by dylandepass** [comment]
Just want to add my support for this. The examples are great but they are very much tied to the samples. It would be great to have a controller class that allows us to easily create, find, load and remove anchors for existing projects. Typically dev's are already dealing with placement on our own and just need a way to persist and load these anchors.

Trying to rip apart the samples to just get what you need is a bit of a tedious and error prone task.

Loving these anchors though, great job to the teams involved in making this!
