### ISSUE TITLE
[iOS] Anchors load in wrong location when app/ARKitsession is restarted

### ISSUE THREAD

**Issue by jelmerS2** [Azure/azure-spatial-anchors-samples#40]
I've implemented Azure Anchors based on the examples and concepts in the docs:

```    
private void OnAnchorLocated(object sender, AnchorLocatedEventArgs args)
    {
        switch (args.Status)
        {
            case LocateAnchorStatus.Located:
                Debug.Log("anchor found, adding to the scene");
                textFeedback.Feedback("anchor found, adding to the scene");
                CloudSpatialAnchor foundAnchor = args.Anchor;

                Pose anchorPose = Pose.identity;
#if UNITY_ANDROID || UNITY_IOS
                anchorPose = foundAnchor.GetAnchorPose();
#endif
                SpawnNewAnchoredObject(anchorPose.position, anchorPose.rotation, foundAnchor);
                break;

            case LocateAnchorStatus.AlreadyTracked:
                // This anchor has already been reported and is being tracked
                Debug.Log("This anchor has already been reported and is being tracked");
                break;

            case LocateAnchorStatus.NotLocatedAnchorDoesNotExist:
                // The anchor was deleted or never exited in the first place
                // Drop it, or show UI to ask user to anchor the content anew
                Debug.Log("Drop it, or show UI to ask user to anchor the content anew");
                break;

            case LocateAnchorStatus.NotLocated:
                // The anchor hasn't been found given the location data
                // The user might in the wrong location, or maybe more data will help
                // Show UI to tell user to keep looking around
                Debug.Log("Not found yet! Keep looking around");
                break;
        }

        GameObject SpawnNewAnchoredObject(Vector3 worldPos, Quaternion worldRot, CloudSpatialAnchor cloudSpatialAnchor)
        {
            GameObject newGameObject = GameObject.Instantiate(anchorPrefab, worldPos, worldRot);
            spawnedAnchors.Add(newGameObject);
            return newGameObject;
        }
    }
```

To me it looks like found anchors are spawned relative to the world origin. 
So let's say I save an anchor
I restart the app while holding my phone in the same physical location as when I started it the first time, then the anchor spawns in roughly the same place

However, when I start the app in a different physical location, move to the area where I expect the anchor, the anchor get's loaded successfully, then the location is completely wrong. 

Maybe `GetAnchorPose()` is broken?

Unity 2019.1.5
XCode 12.x
running on iOS12.3.1
Using the latest (deprecated!) [UnityARKitPlugin](https://bitbucket.org/Unity-Technologies/unity-arkit-plugin/src/default/).

**Comment by cbutzke** [comment]
I've got the exact same problem. Doesn't matter which lighting conditions or if ARKit is able to find Feature Points easily. The anchor gets located but GetAnchorPose() gives me a wrong location. Any update on this?

**Comment by RamonArguelles** [comment]
The code needs to run on the UI thread to be able to retrieve the native anchor pose. OnAnchorLocated doesn't run on the UI thread. Once you receive LocateAnchorStatus.Located, schedule work on the UI thread to retrieve the native anchor pose, and spawn your game object with it.

From https://github.com/Azure/azure-spatial-anchors-samples/blob/master/Unity/Assets/AzureSpatialAnchors.Examples/Scripts/AzureSpatialAnchorsBasicDemoScript.cs:

        protected override void OnCloudAnchorLocated(AnchorLocatedEventArgs args)
        {
            base.OnCloudAnchorLocated(args);
            if (args.Status == LocateAnchorStatus.Located)
            {
                currentCloudAnchor = args.Anchor;
                UnityDispatcher.InvokeOnAppThread(() =>
                {
                    currentAppState = AppState.DemoStepDeleteFoundAnchor;
                    Pose anchorPose = Pose.identity;
#if UNITY_ANDROID || UNITY_IOS
                    anchorPose = currentCloudAnchor.GetPose();
#endif
                    // HoloLens: The position will be set based on the unityARUserAnchor that was located.
                    SpawnOrMoveCurrentAnchoredObject(anchorPose.position, anchorPose.rotation);
                });
            }
        }

**Comment by julianparismorgan** [comment]
Hi @jelmerS2 / @cbutzke, checking in to see if you were able to get it working? If you update to the latest SDK, do things work?

**Comment by jelmerS2** [comment]
Hi thanks, however I haven’t worked with spatial anchors lately. I’ll try the updated SDK some time!

Sent from a mobile device
________________________________
