### ISSUE TITLE
Multi-user capabilities - coordinate system of the different players dosen't line up

### ISSUE THREAD

**Issue by mikkeline-elleby** [Azure/azure-spatial-anchors-samples#403]
Hi, 

I'm using unity 2020.3.42f1, I'm running it with a PUN app and have 2 different hololens where I deploy the application (+my computer) 

I'm doing my bachelor project on the multi-user capabilities of the Hololens. I have tried to follow this tutorial: https://learn.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-sharing-01 

Everything is working fine with the pun app, and I am able to view the players inside of the Room. The only thing missing for making it a shared experience is to have the coordinate system of all the different players to be the same. I have tried to introduce an azure spatial anchor to to share the location of the table (the object in the SharedPlayGround that defines the coordinate system of the position of the players) to the players so that their coordinate system lines up.  The anchor is shared with the Sharing Module script and the Anchor Module. 
But whenever I deploy the application on two different hololens the position dosen't match up. (the player is also represented with a sphere and it dosen't coincide with the real position of the player.

How to run the app: 
wearer A: 
- start an azure session
- creates a local anchor 
- shares this anchor 
(these steps seem to work as the have the correct logs) 

wearer B: 
- start an azure session
- get the anchor
And here the issue occurs, the anchors seems to move a bit but it's position dosen't coincide with the position of anchor A -- here you can see the logs: 

![20230426_103216_HoloLens](https://user-images.githubusercontent.com/83402800/234674914-2a12da70-6be8-4723-875c-5081a2033399.jpg)

![20230426_103315_HoloLens](https://user-images.githubusercontent.com/83402800/234674796-0c9f4726-c3b3-44df-b1ec-0685c9c316c4.jpg)

I don't know if the null reference is the root of my issue. Another idea I have, is that maybe the environment isn't scanned enough before creating the achor (but I have a log telling me if that was the case - and it dosen't get printed so are we fine ?) 

It would help me so much if you could help me, I have been struggling with this problems for weeks.

**Comment by darax** [comment]
Hi @mikkeline-elleby  Are you rendering something (like a cube) where the anchor is being detected on both devices?  That null reference might be photon trying to spawn an object, so it would be good to figure it out. You can get a full log in the device portal in the application's 'TempState' folder.

**Comment by mikkeline-elleby** [comment]
I just put my project on a repo so you can have a look at it : 
[https://github.com/mikkeline-elleby/multiUser-Capabilities](url)

(and also I was just wondering if I'm just starting out with the hololens, and I spend so much time on this project - can I get it to work ? As this is fundemental for all of the rest of my project)

**Comment by darax** [comment]
I'm not seeing your repo.  The link seems to link back here.  

You don't need to put the anchors on surfaces to get a multi user experience to work.  It does look like something in 'AnchorModuleScript' is causing an issue.

I'm somewhat concerned about entries like:
```
Unable to register IMixedRealitySpatialAwarenessObserver data provider (Windows Mixed Reality Spatial Mesh Observer) because the value of concreteType is null.
This may be caused by code being stripped during linking. The link.xml file in the MixedRealityToolkit.Generated folder is used to control code preservation.
More information can be found at https://docs.unity3d.com/Manual/ManagedCodeStripping.html.
```

**Comment by mikkeline-elleby** [comment]
I updated the link, which should work now (I hope) : https://github.com/mikkeline-elleby/multiUser-Capabilities

**Comment by mikkeline-elleby** [comment]
Hi I have tested your idea and tried different things but none worked. 

Maybe it's that the anchors is not being kept correctly in memory, or maybe it's the sharing bit as I get the NullPointerException when I want to share it and when I try to get it back. I can see also that the feedback getting printed to the log that the ID is getting shared and created could be wrong according to this : https://learn.microsoft.com/en-us/answers/questions/850617/(unity-hololens2)-spatial-anchor-id-could-not-be-i

What should I try to do ? Is there another ready to use sharing module for azure anchors I could try out ? Or do you see other issues I could try to corrrect ?

**Comment by mikkeline-elleby** [comment]
I found a solution. The error was due to the Table Anchor. I used this tutorial: https://learn.microsoft.com/en-us/training/modules/azure-spatial-anchors-tutorials/3-exercise-get-started-with-azure-spatial-anchors and implemented photon on it and adding the sharing module from the multi-user capabibilities. Here is my repo : https://github.com/mikkeline-elleby/Multi-user-Hololens-PUN-and-ASA- 
I have tested it out and it works really great (even with 3 hololens). I will write a report on everything as this is my bachelor project. If you need anymore details or a step-by-step of how I solved the issue then just reach out (I can also help update the tutorial if needed)

**Comment by darax** [comment]
Hey @mikkeline-elleby , I'm glad to hear you figured it out. I wish I had the time to have provided more guidance.  Back in the day  getting multiple users in an AR/VR environment was my favorite thing to do. :)   https://learn.microsoft.com/en-us/windows/mixed-reality/deprecated/mixed-reality-250.
