### ISSUE TITLE
Questions about the Anchor models

### ISSUE THREAD

**Issue by jznling** [Azure/azure-spatial-anchors-samples#41]
My friend and I are each working on Android and iOS version of Spatial anchors. We get confused when trying to change the anchor model. 

We find the code generate sphere or box and know how to change it to torus or other simple 3d objects. But we don't know how the object is positioned. I have done some WebGL and OpenGL 3D modeling, but not AR. When we do the text anchor, the text image is often out of our expected position. 

I am confused with how the 3D coordinate axis is set in this project. Where is the origin of the coordinate and how objects are created with respect to the anchor position? I did not find any explanation in the docs website. Could you explain it or show me a web link that explains the mechanism about the graphics model generation?

Moreover, is there an official way to import models? How did you set the sphere tags and distance meters in the demo video( https://www.youtube.com/watch?v=CVmfP8TaqNU )? By Unity? Or is there a Sceneform method to achieve the same goal?

Finally, my friend is curious about the overall mechanism of spatial anchors. We did not find any explanation document and mainly understand the project by guessing. Could you provide a brief explanation about the overall mechanism? It is fine if specific.

**Comment by darax** [comment]
Here is the Unity document regarding how transforms are handled: https://docs.unity3d.com/Manual/Transforms.html

The origin of the scene in AR depends, but is typically wherever the device happened to be when it started tracking. 

Documentation for importing assets is here:
https://docs.unity3d.com/Manual/ImportingAssets.html

Usually you can just drag them into your assets folder and Unity pulls them in.  Note that the interpretation of coordinates varies greatly between software packages. My default I beleive that Maya and Blender use different axes for 'up', with blender using Y (as does unity) and Maya using Z. The size of a unit also varies, not just package by package, but sometimes artist by artist, and for some artists  project by project.   By this I mean the different between x,y,z 0,1,0 and 0,2,0 could be 1 meter on the y axis, or 1 centimeter on the y axis, or anything else. A challenge when pulling assets together from mulitple sources is getting everything oriented and scaled in a consistent manner. 

To get an object with a text label over it involves creating a compound object.  In the object hierarchy you use the create dropdown and create a new game object. Then right click on that new object, select 3d object, and cube.  Then right click on the new object again and select 3d object and 3d text.  Then select the 3d text obejct that got created and set it's 'y' component in the transform to 1.  That will cause the local position of the text to be 1 meter above the cube.   You'll have something like:
![image](https://user-images.githubusercontent.com/15933792/60746948-d9a48900-9f36-11e9-941c-b17d3d8cea91.png) 

![image](https://user-images.githubusercontent.com/15933792/60747186-6865d580-9f38-11e9-8570-e3dd99af4121.png)

given all that, you'll want to check the transform of the parent (FancyObject in the screen shots.)  If your object has a transform that isn't Position 0,0,0, Rotation 0,0,0, then things are going to behave out of position as you've described.
