### ISSUE TITLE
iOS does not build on macOS Catalan Xcode 11

### ISSUE THREAD

**Issue by Badboyabout** [Azure/azure-spatial-anchors-samples#44]
I’m pretty certain it’s not using SwiftUI, and migration to swift5 doesn’t happen.

But the sample’s build seems Brocken !

**Comment by vriveras** [comment]
We are currently working on getting the support for XCode 11 its not ready yet.

**Comment by doubl3p** [comment]
What are the supported versions of Xcode?

**Comment by vriveras** [comment]
This should be supported in the latest version of the SDK.
