### ISSUE TITLE
Useless Without ARFoundation

### ISSUE THREAD

**Issue by shawmakesmusic** [Azure/azure-spatial-anchors-samples#45]
Frankly, very few if any people are going to adopt this for serious applications without ARFoundation support. I'd be happy to roll my own with native pointers but cannot because ASA does not support the latest ARKit/Core versions that ARFoundation supports.
Every day this repo sits without an update for the latest ARKit/Core plugins is a day that you might as well have literally not created this product. 10000% more people -- not an exaggeration -- would be pulling from this repo if you supported ARFoundation.
Don't blow it.

**Comment by vriveras** [comment]
We are currently working on ARFoundation It will be part of the SDK supported platforms.

**Comment by shawmakesmusic** [comment]
Cool. Any update on this? We're in a Catch 22- Unity's old open source ARKit/Core plugins are deprecated and not working with the latest Unity. The ARKit and ARCore plugins provided in their packages system are not compatible with the current version of the Spatial Anchors stuff. Since everything is wrapped in managed plugins, the community has no recourse to fix any of it.

**Comment by craigktreasure** [comment]
@shawmakesmusic We just release Azure Spatial Anchors 1.3.0 and the Unity sample now uses ARFoundation.
