### ISSUE TITLE
Authentication with AAD v2.0

### ISSUE THREAD

**Issue by ashikns** [Azure/azure-spatial-anchors-samples#46]
The docs specify instructions for usage with ADAL. Is there any way to authenticate with AAD v2.0 using MSAL? I tried specifying https://sts.mixedreality.azure.com//.default as a scope to msal but it doesn't work.

**Comment by ashikns** [comment]
Okay so to clarify, this is something that has to come from the AAD team rather than the ASA team?

**Comment by RamonArguelles** [comment]
Correct, @ashikns. We'll be closing this issue now, but do feel free to re-open for further discussion.
