### ISSUE TITLE
Relocate anchors by finding any of the anchors placed in area

### ISSUE THREAD

**Issue by aurangzaibumer777** [Azure/azure-spatial-anchors-samples#47]
I did use the sample app and tried the second demo, i created two anchors in my area and save them on cloud. then it asked me to find the **last anchor** which was saved and hence found the other two with respect to the last one. **Is it possible to find any of the anchors, but not the last one. It is mandatory??** like if i place 10 anchors in my office and try to find any of the anchors, will it display all the anchors if i just find any one of them? Just like the **placenote** does in iOS

**Comment by aurangzaibumer777** [comment]
Moreover, the documentation is so poor that you cannot even start writing a new project on your own, it should be updated

**Comment by aurangzaibumer777** [comment]
been 5 days and no one bats an eye

**Comment by vriveras** [comment]
@aurangzaibumer777, you need to manage the ids of the anchors to initiate the lookup. You will need to pass the ids that you want to relocate for this you will need to change the sample. The sample is only having simple logic to show this process and it only works with the last anchor you placed. The sharing sample has more complicate logic and it will allow to on-demand query anchors based on an id that you will store in CosmosDb.
