### ISSUE TITLE
Can't get AccessToken

### ISSUE THREAD

**Issue by ChangweiZhang** [Azure/azure-spatial-anchors-samples#5]
After I open the SharingServiceSample project, I find the SpatialAnchorsTokenService.cs file and configure out I need fill it with my credentials info as below:
![image](https://user-images.githubusercontent.com/4610610/53710542-b5497a80-3e78-11e9-828a-c84e2918e606.png)

When I get the AAD token successfully and try get the spatial service access token, there is a error response as below:

![image](https://user-images.githubusercontent.com/4610610/53708664-76fb8d80-3e6f-11e9-9335-62c4a9c904e6.png)
bad response:
``````
{StatusCode: 500, ReasonPhrase: 'Internal Server Error', Version: 1.1, Content: System.Net.Http.HttpConnection+HttpConnectionResponseContent, Headers:
{
  Date: Mon, 04 Mar 2019 03:20:20 GMT
  MS-CV: u1xrmlrgwkSkBL2Fugk2IQ.0
  X-Content-Type-Options: nosniff
  Content-Length: 0
}}
``````

How can I get the access token successfully?

**Comment by vriveras** [comment]
@ChangweiZhang , If your are running any of the samples you will need to follow the section for configuring the **AccountId** and **AccountKey** to get the AuthToken properly. 

The AuthToken is automatically gathered for you after you configure the AccountId and AccountKey in the [SessionConfiguration](https://docs.microsoft.com/en-us/objectivec/api/spatial-anchors/asasessionconfiguration) object in the API. There is no need to configure a custom token service or application unless you have a specific scenario for it.

* Unity [configuration](https://docs.microsoft.com/en-us/azure/spatial-anchors/quickstarts/get-started-unity-android#configure-account-identifier-and-key) in the scene
* Non-Unity iOS [configuration](https://docs.microsoft.com/en-us/azure/spatial-anchors/quickstarts/get-started-ios?tabs=openproject-swift#configure-account-identifier-and-key).

* Non-Unity Android [configuration](https://docs.microsoft.com/en-us/azure/spatial-anchors/quickstarts/get-started-android?tabs=openproject-java#configure-account-identifier-and-key)

Please let me know if you still are not able to get the API working after following the configuration sections.

**Comment by PradeepHGK** [comment]
![image](https://user-images.githubusercontent.com/22808627/107361962-27fc0f80-6afe-11eb-8b55-e80464af074b.png)
I have done this but still getting this exception while saving the anchors, also verified the documentation still the same there also, not know why it's showing the same error, can someone help me on this?

**Comment by pamistel** [comment]
Hi @PradeepHGK 

1. Is this from the sample code or your own app?
2. If it's your own, were you able to successfully run the Unity Sample? 
3. Do you have a minimum repro or code that you can share?
