### ISSUE TITLE
Missing return on NDK example

### ISSUE THREAD

**Issue by JaimeIvanCervantes** [Azure/azure-spatial-anchors-samples#52]
There is a missing `return` on this line of the NDK example: https://github.com/Azure/azure-spatial-anchors-samples/blob/master/Android/NDK/app/src/main/cpp/AzureSpatialAnchorsApplication.cpp#L118

**Comment by craigktreasure** [comment]
Thanks! We've fixed this internally and will update the sample in our next sample update.

**Comment by craigktreasure** [comment]
We've fixed this in the samples update for 1.3.1.
