### ISSUE TITLE
Misleading Method Names ( InitializeXYZ )

### ISSUE THREAD

**Issue by TiNovTec** [Azure/azure-spatial-anchors-samples#55]
I use the demo version from **August 6th**.

I think you should **rename** the method names of the methods in the demo script _AzureSpatialAnchorsSharedAnchorDemoScript.cs_
- InitializeLocateFlowDemo
- InitializeLocateFlowDemoAsync
- InitializeCreateFlowDemo
- InitializeCreateFlowDemoAsync

These methods are called multiple times from the same ( generic ) button and should be called e.g. ProcessLocateFlowDemo because they not only initialize ( only the first time they are called ) but they also do other tasks like to create anchors etc.

**Comment by RamonArguelles** [comment]
Great suggestion, @TiNovTec. Thanks for providing it. I've filed a bug in our backlog to take a look at this.

**Comment by Varnauld** [comment]
Hello,
I closed this item as this was originally submitted close to two years ago. Our latest release is available [here](https://github.com/Azure/azure-spatial-anchors-samples/releases/tag/v2.12.0) – please re-open this item should you have further feedback for the team.
Alternatively, if you have any ideas or requests for new features or capabilities, or should you wish to upvote an existing idea, please visit our [Feedback hub](https://feedback.azure.com/d365community/forum/f47d9b25-0725-ec11-b6e6-000d3a4f07b8)

Thank you
