### ISSUE TITLE
Xamarin IOS fail at launch, missing Main storyboard

### ISSUE THREAD

**Issue by mgomar** [Azure/azure-spatial-anchors-samples#56]
https://github.com/Azure/azure-spatial-anchors-samples/blob/adcbe8fbb15d8bdb346cd835531d57ef255bc5c3/Xamarin/SampleXamarin.iOS/Info.plist#L24

https://github.com/Azure/azure-spatial-anchors-samples/blob/adcbe8fbb15d8bdb346cd835531d57ef255bc5c3/Xamarin/SampleXamarin.iOS/Info.plist#L25

Looks like there is a (missing but not required storyboard file) at this two lines,  Please remove them and the app will launch.

thanks.

**Comment by craigktreasure** [comment]
Oh interesting. I haven't encountered the launch failure you're referring to, but we'll take a look. @Sweekriti91, any thoughts?

**Comment by Sweekriti91** [comment]
Even I haven't hit this issue. Let me take a look too. @mgomar do you see the error when deploying to an iPhone or iPad?

**Comment by mgomar** [comment]
Hi @craigktreasure and @Sweekriti91, thanks for your reply!.

> Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: Could not find a storyboard named 'Main' in bundle NSBundle </var/containers/Bundle/Application/9E620236-005E-453F-A69D-214236C124E0/SampleXamarin.iOS.app> (loaded)

this is the exception, and I think they are related with the two lines in the info.plist, maybe this files are missing from this repo?.

thx!.

**Comment by Sweekriti91** [comment]
@mgomar I cloned the sample repo and tried a build from scratch and I am unable to repro the issue. What device type are you deploying to?

**Comment by mgomar** [comment]
@Sweekriti91 the device is an apple-ipad-pro-2018-11, and running from an Mackbook pro with the latest xamarin and latest visual studio for mac.

thx!

**Comment by mgomar** [comment]
@Sweekriti91 any update?

**Comment by bertt** [comment]
Why is this issue closed? Looks like every IPad user gets this cryptic error :-(

**Comment by mgomar** [comment]
¯\_(ツ)_/¯ 

Same thought here.

**Comment by vriveras** [comment]
This one was closed by mistake.

**Comment by craigktreasure** [comment]
Sorry for the delay on this issue. We'll try to get to the bottom of this one today.

**Comment by craigktreasure** [comment]
We'll have an update for this hopefully sometime next week.

**Comment by craigktreasure** [comment]
This has now been addressed in our 2.0.0 release. Feel free to re-open if you have further related issues.
