### ISSUE TITLE
Sometimes the whole coordinate system gets rotated

### ISSUE THREAD

**Issue by marklinmao** [Azure/azure-spatial-anchors-samples#57]
Hi,

Step 1: Create an anchor on the ground
Step 2: locate it, then move around, walk away and back, sometimes the located anchor is ROTATED, comparing to what it was placed. I found that actually not only the anchor but the whole coordinate system is rotated.

This problem makes Azure spatial anchor not reliable.
Please refer to the link that I posted in StackOverflow, there are two pictures describing this problem.

wrong:
![YvnYP](https://user-images.githubusercontent.com/4719869/63114288-2e5b0b00-bf9d-11e9-8566-b7eb954c2077.png)

it should be:
![bjUbR](https://user-images.githubusercontent.com/4719869/63114280-2ac78400-bf9d-11e9-9535-0cf3f75c7027.png)

**Comment by craigktreasure** [comment]
Thanks for the report. @darax to take a look.

**Comment by darax** [comment]
hi @marklinmao,  
I'm going through old issues and I noticed this one.  I'm going to close this, but if you are still having this issue feel free to reopen.  What would be really helpful is a short video of the capture you are taking that creates your described result.

**Comment by craigktreasure** [comment]
It would also help to know what platform: Android, iOS, or HoloLens. It looks like the AR platform is losing tracking and not restoring it accurately.
