### ISSUE TITLE
Event Names in AzureSpatialAnchorsDemoWrapper

### ISSUE THREAD

**Issue by jbienzms** [Azure/azure-spatial-anchors-samples#6]
AzureSpatialAnchorsDemoWrapper contains the following events:

- OnAnchorLocated
- OnLocateAnchorsCompleted
- OnSessionError
- OnSessionUpdated
- OnLogDebug

However, per [Event Design](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/event) and [Standard .Net event patterns](https://docs.microsoft.com/en-us/dotnet/csharp/event-pattern),  "On" should only be used to name a protected method that raises the event.

> ✓ DO use a protected virtual method to raise each event. This is only applicable to nonstatic events on unsealed classes, not to structs, sealed classes, or static events.
> 
> The purpose of the method is to provide a way for a derived class to handle the event using an override. Overriding is a more flexible, faster, and more natural way to handle base class events in derived classes. By convention, the name of the method should start with "On" and be followed with the name of the event.

**Comment by vriveras** [comment]
@jbienzms Thanks for the feedback. We will incorporate this change in the next refresh of the samples.
