### ISSUE TITLE
Web and ARFoundation recommended version 

### ISSUE THREAD

**Issue by ghus86** [Azure/azure-spatial-anchors-samples#60]
Hi All
two questions:

1) I don't think its possible at the moment but to make sure I am not providing a wrong information to a client is there any to run azure spatial anchors in browser ? 
will that be possible in the future ?

2 ) about ar foundation I have seen in the closed issues that is already supported
the sample is using unity 2019.1.10
but ar foundation have several versions what is the recommend ? 
does run with ar foundation 2.0 ?

@craigktreasure @vriveras if you could clarify that I would appreciate it 
thanks in advance

**Comment by craigktreasure** [comment]
Here's a bit of info:

1. I don't know about being possible, but it's certainly not supported. Do you have a scenario that requires this? If so, can you tell us more?
2. We documented the package versions of AR Foundation in our [1.3.0](https://github.com/Azure/azure-spatial-anchors-samples/releases/tag/v1.3.0) release notes. Essentially:
    * ARFoundation 2.2.0
    * ARCore XR Plugin 2.1.0
    * ARKit XR Plugin 2.1.0

**Comment by ghus86** [comment]
thanks for the info @craigktreasure (missed that page about ar foundation)

about the web scenario sure the client have a web solution for indoor navigation but its only a 2d map and wanted to include an AR option to guide the user

we already developed a prototype in app format but in the ideal scenario it would be nice to have an web solution that runs both systems and doesn't require the install

**Comment by craigktreasure** [comment]
Thanks for the additional info on the web scenario. We'll consider this as we discuss our plans for the future.

**Comment by ghus86** [comment]
Cool, thanks for your time and feedback.
