### ISSUE TITLE
How to delete Azure Spatial Anchor after detected

### ISSUE THREAD

**Issue by doubl3p** [Azure/azure-spatial-anchors-samples#61]
I develop an unity application and I am working with azure spatial anchors. I found no possibility to delete a detected cloudAnchor. I tried this:

        protected void OnCloudAnchorLocated(AnchorLocatedEventArgs args)
        {
            CloudSpatialAnchor nextCsa = args.Anchor;
  

            ...
            if (nextCsa != null)
            {
                Debug.Log("BEFORE DELETE");
                await CloudManager.DeleteAnchorAsync(nextCsa);
                Debug.Log("AFTER DELETE");
            }
        }

I get this in the console:

> StoreAndWatcherTrackedState::TryRemoveAsync for SpatialAnchor:
> 6b77de6e-d8ba-44ce-b7cc-1f1d09bcc7a5

And this error:

>  OnError - The specified spatial anchor is already associated with a different store

So I have three questions:

**1. What is the meaning of the error?**

**2. Is it possible to delte detected anchors from azure?**

**3. If yes what is the correct approach?**

**Comment by cheles** [comment]
https://docs.microsoft.com/en-us/azure/spatial-anchors/how-tos/create-locate-anchors-unity#delete-anchors 
```
  await this.cloudSession.DeleteAnchorAsync(cloudAnchor);
    // Perform any processing you may want when delete finishes

```
Our[ sample code](https://github.com/Azure/azure-spatial-anchors-samples/blob/bd662ab192cd92b53296e163ddc8d30efc650f11/Unity/Assets/AzureSpatialAnchors.SDK/Scripts/SpatialAnchorManager.cs) shows something like:
```
  public async Task DeleteAnchorAsync(CloudSpatialAnchor anchor)
        {
            // Validate
            if (anchor == null) throw new ArgumentNullException(nameof(anchor));
            EnsureSessionStarted();

            // Actually delete
            await session.DeleteAnchorAsync(anchor);
        }
```

There is also another solution purposed [here](https://stackoverflow.com/questions/57614734/how-to-delete-azure-spatial-anchor-after-detected)

**Comment by RamonArguelles** [comment]
Hi @doubl3p,

Do not attempt to delete the anchor from within the OnCloudAnchorLocated callback. This method is being called from an internal thread owned by the Azure Spatial Anchors Session. If you call DeleteAnchorAsync from here, and await on it, you'll hold the current thread, and the delete operation will be scheduled on a different thread. The delete operation is detecting that the anchor is still being held in the OnCloudAnchorLocated callback thread by the watcher, so it's not allowing it to be deleted.

As others have posted, you should be able to delete the anchor once the locate operation has completed, and the watcher has been stopped.

**Comment by craigktreasure** [comment]
Thanks @RamonArguelles! Closing this for now. Feel free to reopen for further discussion if necessary.
