### ISSUE TITLE
Updating from version 1.2 to 1.3.0

### ISSUE THREAD

**Issue by DalonV** [Azure/azure-spatial-anchors-samples#62]
I am a little lost with this update. So far, I have been using Spatial Anchors and the ARCore add-on for Unity. But with this update, when linking it to ARFoundation, it is impossible to have the ARCore plug-in enabled since ** has ** to be disabled for ARFoundation to work.

Am I missing something? Is there any way to facilitate this transition? The documentation is outdated, it even recommends previous versions of ARCore ...

**Comment by craigktreasure** [comment]
Sorry for the late response. Have you tried our latest [quickstart](https://docs.microsoft.com/en-us/azure/spatial-anchors/quickstarts/get-started-unity-android) for Unity on Android? We have migrated to using ARFoundation since the ARCore and ARKit plugins for Unity have been deprecated.

**Comment by craigktreasure** [comment]
Closing this as we haven't had a recent response. Feel free to reopen for further discussion.
