### ISSUE TITLE
Adding auto configured NuGet for Unity

### ISSUE THREAD

**Issue by adityosnrost** [Azure/azure-spatial-anchors-samples#65]
## Overview

Azure Spatial Anchors NuGet package will not be automatically installed or added if we build Unity project that also contain other Unity Package that utilized NuGet For Unity. It is because the post build script will not add the needed package list into NuGet package list to be installed when opening VS or build it. And, we need manually add Microsoft.Azure.SpatialAnchors.WinCPP into package list later in build folder.

## Expected Behavior

Includes NuGet for Unity, to automatically configured the ASA NuGet package after build.

**Comment by craigktreasure** [comment]
Thanks for the suggestion. We are considering this work and will have more to share in a future release.
