### ISSUE TITLE
HoloLens Error Report

### ISSUE THREAD

**Issue by czgorge** [Azure/azure-spatial-anchors-samples#68]
I used the demo from:

[https://docs.microsoft.com/zh-cn/azure/spatial-anchors/tutorials/tutorial-new-unity-hololens-app](url)

the AzureSpatialAnchorsScript has a error when it comes to this step: 
![20190909144148](https://user-images.githubusercontent.com/55077085/64508434-0185e380-d310-11e9-80ec-09ba71b09d0e.png)

The HoloLens app just crash and quit.
The VS shows this:

![20190909143529](https://user-images.githubusercontent.com/55077085/64508688-a0aadb00-d310-11e9-92fc-bfcc245e114a.png)

Btw I am using Unity3D 2018.4 and Visual Studio 2017.

**Comment by ashikns** [comment]
Could you please provide a translated version of the second screenshot :) I'm still new to this stuff but iirc I saw an error like this too.

**Comment by czgorge** [comment]
[cid:6353ffb3-78f3-43a9-92b9-3b9809f727a3]
 The Visual Studio can't be debugged when it is switched to English, do you think this translation is ok?

________________________________
发件人: Ashik Salim <notifications@github.com>
发送时间: 2019年9月16日 21:46
收件人: Azure/azure-spatial-anchors-samples <azure-spatial-anchors-samples@noreply.github.com>
抄送: Zhen Chen 陈震 <zhenchen@datamesh.com>; Author <author@noreply.github.com>
主题: Re: [Azure/azure-spatial-anchors-samples] HoloLens Error Report (#68)


Could you please provide a translated version of the second screenshot :) I'm still new to this stuff but iirc I saw an error like this too.

―
