### ISSUE TITLE
Object Created Not Anchored by Spatial Anchor on iOS/android Device in Azure Spatial Anchor Unity Demo

### ISSUE THREAD

**Issue by lingchun** [Azure/azure-spatial-anchors-samples#72]
I’m not sure if there’s some bug when spawning a new spatial-anchored game object in iOS/android device. When creating a game object with NativeAnchor on iOS/android device. The following statements is called,

![snapshot1](https://user-images.githubusercontent.com/17996334/65245715-a928c000-db1f-11e9-9555-c55621271640.png)

Actually the real anchored object is the game object (for short, I call it G1) of this.WorldAnchor(i.e. a game object with ARRefrencePoint) instead of the game object (for short, I call it G2) of a NativeAnchor(i.e. UnityARFoundationAnchorComponent) instance. And also G1(with ARRefrencePoint) is a newly created game object that has nothing to do with G2(with NativeAnchor) which is not also a child of G1. Since G1 is anchored according to the document(https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@1.0/api/UnityEngine.XR.ARFoundation.ARReferencePoint.html), the only way to anchor G2 is to make G2 a child game object of G1.

![snapshot3](https://user-images.githubusercontent.com/17996334/65245869-fad14a80-db1f-11e9-96ec-531ca49b29e2.png)
 
So I add the following code changes when Spawning a new anchored game object in DemoScriptBase.cs, and I’d like  to confirm if the following changes is right or not.

![snapshot2](https://user-images.githubusercontent.com/17996334/65245808-decda900-db1f-11e9-927b-87a922f88d31.png)

Or by the following way to anchor G2,

![snapshot4](https://user-images.githubusercontent.com/17996334/65245998-408e1300-db20-11e9-851f-d649429958e6.png)

**Comment by craigktreasure** [comment]
Sorry for the delay and thanks for the detailed report. @darax to take a look.

**Comment by darax** [comment]
@lingchun you are correct.  We will integrate a fix in the next release using the change you've recommended in the UnityARFoundationAnchorComponent.  One thing to watch out for is if the ArFoundationReference point gets destroyed the GameObject being anchored will also be destroyed.

**Comment by julianparismorgan** [comment]
Hi @lingchun, this should be fixed now, so I'm going to go ahead and close it. Thanks for helping us find issues in ASA!
