### ISSUE TITLE
Reality Composer and RealityKit support ?

### ISSUE THREAD

**Issue by skypu3** [Azure/azure-spatial-anchors-samples#73]
Hi Team,

I wonder if spatial anchor supports realityKit anchor system, that we can use aranchor to init AnchorEntity, then add model directly on it. 
The difference between aranchor and anchorentity
https://stackoverflow.com/questions/57593960/whats-the-difference-between-aranchor-and-anchorentity

**Comment by vriveras** [comment]
@skypu3 , No azure spatial anchors does not support RealityKit and RealityComposer at the moment.

**Comment by chyzhang** [comment]
Hey, just wondering if there is any update on the usage with spatial anchor and RealityKit?

**Comment by willyeo** [comment]
@chyzhang 
Azure Spatial Anchor (ASA) doesn't support AnchorEntity directly, but you can create the ASA from ARAnchor, and when you find ASA it will have ARAnchor (localAnchor property in ASA Swift SDK). You can do whatever you want with ARAnchor including attaching it to AnchorEntity but ASA doesn't provide any further support on that.

**Comment by chyzhang** [comment]
@willyeo
Wow, thanks! Will try it!
