### ISSUE TITLE
How to disable the flat surface detection shader?

### ISSUE THREAD

**Issue by sangadji** [Azure/azure-spatial-anchors-samples#77]
Hi,

Is there any way to disable the flat surface detection shader?
I mean the kind of red texture bordered with black lines that the app draws every time the app detects a flat surface.
Image : https://drive.google.com/file/d/10Y6oZgeVCBvX2MpwMrUCVbMGmh61JrFX/view?usp=sharing

**Comment by darax** [comment]
Hi sangadji, 
You can disable the effect by setting the Plane Prefab to none on the AR Plane Manager component on the ARFoundationSessionStack prefab.

![image](https://user-images.githubusercontent.com/15933792/67701273-e5e0a600-f96c-11e9-8953-c64c41627034.png)
