### ISSUE TITLE
Poor Performance on Samsung Devices

### ISSUE THREAD

**Issue by Redslaya** [Azure/azure-spatial-anchors-samples#78]
When building the sample via Unity to a Samsung device (S10, Note 10+) the camera framerate suffers significantly (~5fps) when placing, uploading, or finding a spatial anchor. The framerate is fine in the steps leading up to placing it. The same project runs fine on a pixel 3XL, iPhone XR, iPhone XS, and Hololens devices. Other ARCore based projects run fine on the Samsung devices. 

this occurs with all versions of the sample application and does not fix itself with time. 

I have no idea what would be causing this, but if I can provide any further information to assist in fixing this bug I am more than happy to.

**Comment by darax** [comment]
Hey @redslaya,

We are aware of this issue and have sent it to Unity to investigate.  We can reproduce this behavior without Azure Spatial Anchors.  All you have to do to reproduce this is call arCameraManager.subsystem.TryGetLatestImage to experience the stuttering behavior.

  Unity doesn't have a fix yet, but they have suggested a somewhat surprising workaround: add a couple objects to your scene that cast shadows. I tried this, and it worked.

**Comment by Redslaya** [comment]
Thank you Darax. will mark this closed.
