### ISSUE TITLE
Build on IOS not working with Xcode 11.1 (pods installed)

### ISSUE THREAD

**Issue by H-man** [Azure/azure-spatial-anchors-samples#79]
I have a problem building samples with XCode 11.1. I've run pod install --repo-update and it generated the xcworkspace project.

When building the xcworkspace, I get lot of errors like:
Undefined symbol: _ssc_get_error_details
Undefined symbol: _ssc_near_anchor_criteria_set_distance_in_meters
etc..

**Comment by s-r-jones** [comment]
Same here. Running: 

MacOS: 10.15
Unity: 2019.3.0b6
Xcode: 11.1

**Comment by darax** [comment]
Are you both running 2019.3? 

For 2019.3, we have had a couple of reports of this. You can update the podfile to look like:
platform :ios, '11.0'
use_frameworks!

target 'Unity-iPhone' do
  target 'UnityFramework' do
    # Pods for UnityFramework
    pod 'AzureSpatialAnchors', '1.3.0'
  end
end

**Comment by H-man** [comment]
> Are you both running 2019.3?
> 
> For 2019.3, we have had a couple of reports of this. You can update the podfile to look like:
> platform :ios, '11.0'
> use_frameworks!
> 
> target 'Unity-iPhone' do
> target 'UnityFramework' do
> # Pods for UnityFramework
> pod 'AzureSpatialAnchors', '1.3.0'
> end
> end

Yes, I'm running 2019.3 also. Should have mentioned that.. Anyways, updated podfile and it works perfectly. Thanks!

**Comment by SpencerIO** [comment]
I am having issues getting to the point in 2019.3 when I would be able to publish to xcode. How did you overcome the Migration issues in Unity?

@H-man @darax @s-r-jones 

I have opened a separate issue
https://github.com/Azure/azure-spatial-anchors-samples/issues/116

**Comment by craigktreasure** [comment]
For those that find this in the future, take a look at #149.
