### ISSUE TITLE
System.InvalidOperationException: Unexpected response code!

### ISSUE THREAD

**Issue by efsjouw** [Azure/azure-spatial-anchors-samples#81]
Hello I have based my own code on the example code but in essence anchor creation should still work the same as far I I know, I get this error most of the time when trying to create an anchor.

`Debug.Log("Creating anchor " + managedAnchor.anchorName + "...");

managedAnchor.anchorObject.AddARAnchor(); //First we create a local anchor at the location of the object in question
        CloudSpatialAnchor localCloudAnchor = new CloudSpatialAnchor();                     //Then we create a new local cloud anchor        
        localCloudAnchor.LocalAnchor = managedAnchor.anchorObject.GetNativeAnchorPointer(); //Now we set the local cloud anchor's position to the local anchor's position`

        //Check to see if we got the local anchor pointer
        if (localCloudAnchor.LocalAnchor == IntPtr.Zero) {
            Debug.Log("Didn't get the local XR anchor pointer...");
            return;
        }
        
        // In this sample app we delete the cloud anchor explicitly, but here we show how to set an anchor to expire automatically
        localCloudAnchor.Expiration = DateTimeOffset.Now.AddDays(managedAnchor.expirationInDays);       
        Debug.Log("Start saving " + managedAnchor.anchorName + " to cloud...");
        
        Task.Run(async () => { //Save anchor to cloud

            while (!cloudManager.EnoughDataToCreate) {
                QueueOnUpdate(new Action(() => { Debug.Log("Waiting for cloud manager data..."); }));
                await Task.Delay(330);
            }            

            try {
                QueueOnUpdate(new Action(() => { Debug.Log("Try store anchor in cloud..."); }));

                if(localCloudAnchor != null) {
                    managedAnchor.currentCloudAnchor = await cloudManager.StoreAnchorInCloud(localCloudAnchor);
                    managedAnchor.azureAnchorId = managedAnchor.currentCloudAnchor.Identifier; //Save the Azure Anchor ID                    
                    localCloudAnchor = null;

                    if (managedAnchor.currentCloudAnchor != null) { //Success
                        QueueOnUpdate(new Action(() => {
                            Debug.Log("Successfully created anchor");
                            onAnchorCreated(managedAnchor);
                        }));
                    } else {
                        QueueOnUpdate(new Action(() => { Debug.Log("Could not create anchor : managedAnchor.currentCloudAnchor is null!"); }));
                    }
                }
                else {
                    QueueOnUpdate(new Action(() => { Debug.Log("Could not create anchor : localCloudAnchor is null!"); }));
                }

            } catch (Exception ex) {
                QueueOnUpdate(new Action(() => { Debug.Log(ex); }));                
            }
        });`

Error:

`Try store anchor in cloud...UnityEngine.Debug:Log(Object)`
`<>c:<createAnchor>b__44_2()`
`AnchorManager:Update()`
`System.InvalidOperationException: Unexpected response code! Likely bug in the SDK!. Request CV: V/BNlOunR/qCfUW+LJvoVg. Response CV: .
  at Microsoft.Azure.SpatialAnchors.NativeLibraryHelpers.CheckStatus (System.IntPtr handle, Microsoft.Azure.SpatialAnchors.status value) [0x00000] in <00000000000000000000000000000000>:0 
  at Microsoft.Azure.SpatialAnchors.CloudSpatialAnchorSession+<>c__DisplayClass68_0.<CreateAnchorAsync>b__0 () [0x00000] in <00000000000000000000000000000000>:0 
  at AnchorModuleScript+EndASASessionDelegate.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.Tasks.Task.Execute () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Action 1[T].Invoke (T obj) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.Tasks.Task.ExecuteWithThreadLocal (System.Threading.Tasks.Task& currentTaskSlot) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.Tasks.Task.ExecuteEntry (System.Boolean bPreventDoubleExecution) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <00000000000000000000000000000000>:0 
--- End of stack trace from previous location where exception was thrown ---
`

There is more, but it just sort of repeats the same kind of message, is this a nullpointer?

I have tried going back to builds that I could be certain of that they should work, but they appear to throw the same exception. I have also stashed my changes and tried again to no avail, they should not be breaking either way as I only changed my gameobject names that are placed on the anchor and added some debug logs etc.

**Comment by efsjouw** [comment]
After some testing/debugging we found out that out of the three anchors we have in our application only the third one cannot be created right now, even though this is the exact same process.

**Comment by darax** [comment]
Hi efsjouw,

Would it be possible to try moving your SDK forward to 1.3.2?

**Comment by efsjouw** [comment]
Alright that appears to work however now I get the message that the expiration time of the anchor is invalid, in the example I used (from the Microsoft tutorial page) this was set to 7 days?

**Comment by darax** [comment]
Interesting.  Do you have any log output from this?  The CV entries are very useful for use triaging.
(like System.InvalidOperationException: Unexpected response code! Likely bug in the SDK!. Request CV: V/BNlOunR/qCfUW+LJvoVg. Response CV: . at )

**Comment by RamonArguelles** [comment]
Hi efsjouw,

As darax pointed out, do you happen to have log output from your issues after upgrading the SDK to 1.3.2?

**Comment by efsjouw** [comment]
Hello, I was working on a different project for a while as this was only R&D.

Sadly I cannot reproduce the error anymore, I will keep an eye out for it if I or anyone else encounters it again.

**Comment by yosun** [comment]
Hi! Just sanity checked with the latest github unity iOS repo / empty Unity project, getting the same errors on trying to save anchor 
 
System.Threading.ExecutionContext.RunInternal
ComiplerServices
.SendOrPost
etc

**Comment by craigktreasure** [comment]
Closing this since the original issue seem to be resolved.

Hey @yosun, would you mind opening a new issue with more information (ASA version, platform, etc.) for us to give you a hand?
