### ISSUE TITLE
Unable to locate anchors by passing empty list to watcher criteria

### ISSUE THREAD

**Issue by kforshier** [Azure/azure-spatial-anchors-samples#82]
The documentation for ASAAnchorLocateCriteria.identifiers states  `Cloud anchor identifiers to locate. If empty, any anchors can be located.`

However, when I pass an empty list to this field I am unable to locate any anchors. There are less than five anchors total in the account I am using, so I should be under the max limit of 35 (as mentioned here https://github.com/Azure/azure-spatial-anchors-samples/issues/32). I am able to locate the anchors fine if I pass in the specific id. 

Is the documentation wrong here, or am I not setting the criteria properly?

I am using the iOS SDK, version 1.3.2

**Comment by Nanoodle** [comment]
Hey Kforshier, it isn't actually possible but the documentation hasn't been changed yet.
I'll reference this issue regarding the docs: https://github.com/MicrosoftDocs/azure-docs/issues/26617

**Alberto-Vega-MSFT commented on Mar 19**
"This text: "If empty, any anchors can be located". It's wrong. You can't pass an empty list of identifiers. So, we need to fix it."

**Comment by RamonArguelles** [comment]
Thanks, @kforshier. I've filed a bug in our backlog to take a look at this documentation bug.

**Comment by julianparismorgan** [comment]
Thanks @Nanoodle. This docs bug was fixed in our 2.2.0 release. 

https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.spatialanchors.anchorlocatecriteria.identifiers#Microsoft_Azure_SpatialAnchors_AnchorLocateCriteria_Identifiers
