### ISSUE TITLE
Unity, Android - DllNotFoundException: azurespatialanchorsndk

### ISSUE THREAD

**Issue by MikeChemi** [Azure/azure-spatial-anchors-samples#84]
I'm trying to integrate the Azure Spatial Anchors SDK into my own app, instead of starting from the sample. I have it working on a HoloLens, but when I deploy to Android I get this error:
AndroidPlayer(ADB@127.0.0.1:34999) DllNotFoundException: azurespatialanchorsndk
  at (wrapper managed-to-native) Microsoft.Azure.SpatialAnchors.NativeLibrary.ssc_anchor_locate_criteria_create(intptr&)
  at Microsoft.Azure.SpatialAnchors.AnchorLocateCriteria..ctor () [0x00008] in K:\undock\proto2\GAMApp\Assets\AzureSpatialAnchors.SDK\Plugins\Common\AzureSpatialAnchorsBridge.cs:6419

I assume I am missing something that is configured in the sample, but not in my own application. Where can I find azurespatialanchorsndk?

**Comment by craigktreasure** [comment]
Hey @MikeChemi! Based on your folder structure it looks like you're building a Unity app. Is that correct? If so, you'll need to setup the `mainTemplate.gradle` file in `Assets/Plugins/Android/mainTemplate.gradle`. Here's the [Unity docs](https://docs.unity3d.com/Manual/android-gradle-overview.html) for that file and our usage in our [sample](https://github.com/Azure/azure-spatial-anchors-samples/blob/master/Unity/Assets/Plugins/Android/mainTemplate.gradle). That file instructs Gradle (which Unity delegates to) to include our Maven packages when it builds the app.

I hope that helps. Let me know.

**Comment by craigktreasure** [comment]
Also, as part of our 2.0.0 release, our Unity package now only includes the scripts you need to add Azure Spatial Anchors to an existing project, so that should be more helpful. You might give that a try.

**Comment by MikeChemi** [comment]
I have added the gradle template, but that didn't work for me. I will try the 2.0.0 release and let you know how it goes.

**Comment by MikeChemi** [comment]
I'm getting a different error now:
<i>AndroidPlayer(ADB@127.0.0.1:34999)</i> Unable to load library '/data/app/com.Microsoft.GAMApp-cosXchAGh9IqWPCSaaY7Xg==/lib/arm/libazurespatialanchorsndk.so', native render plugin support disabled: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "ArCamera_getTrackingFailureReason" referenced by "/data/app/com.Microsoft.GAMApp-cosXchAGh9IqWPCSaaY7Xg==/lib/arm/libazurespatialanchorsndk.so"...

This then seems to cause:
<i>AndroidPlayer(ADB@127.0.0.1:34999)</i> DllNotFoundException: azurespatialanchorsndk
  at (wrapper managed-to-native) Microsoft.Azure.SpatialAnchors.NativeLibrary.ssc_anchor_locate_criteria_create(intptr&)
  at Microsoft.Azure.SpatialAnchors.AnchorLocateCriteria..ctor () [0x00008] in K:\undock\proto2\GAMApp\Assets\AzureSpatialAnchors.SDK\Plugins\Common\AzureSpatialAnchorsBridge.cs:8388

**Comment by craigktreasure** [comment]
You'll also need to make sure you have enabled the following Unity packages if you haven't already:
* AR Foundation: 2.1.4
* ARCore XR Plugin: 2.2.0

**Comment by MikeChemi** [comment]
Ah, ok. I was still on version 2.0.2 for both of those. If I try to use AR Foundation 2.1.4 with ARCore XR Plugin 2.2.0, I get build errors.

Version 2.2.0 for both packages are marked as preview packages (I'm using Unity 2019.2.1f1). I picked preview.6. This combination worked, and I'm no longer getting the DllNotFoundException. Thanks for the help!

**Comment by Pycorax** [comment]
I think it would be helpful to have this information specified somewhere. I understand that there is already a page on how to set up this project here: https://docs.microsoft.com/en-us/azure/spatial-anchors/quickstarts/get-started-unity-android

However, some of us are creating applications from scratch or integrating with an existing MRTK solution and I was struggling to figure out why I kept getting this error. It would be good if this can be shown on the repo's readme.md file or some other page to indicate the basic set up.

**Comment by craigktreasure** [comment]
We've added the info to the latest release page and will try to do so in the future per #122.
