### ISSUE TITLE
Performance issues with Unity on Android

### ISSUE THREAD

**Issue by craigktreasure** [Azure/azure-spatial-anchors-samples#86]
We are aware of a performance issue in Unity that affects certain Android devices (Samsung Galaxy S10 for certain). We're waiting on a fix from Unity, but a workaround you can try in the meantime is to add a couple of objects to your scene that cast shadows. We've had success on a few devices with this workaround. It's worth a try if you feel you may be hitting the same issue.

We'll update this issue when we have a more concrete solution.

**Comment by darax** [comment]
Unity has fixed this in ARFoundation 3.0.0-preview.6 and above.

**Comment by RamonArguelles** [comment]
As a temporary workaround, if you don't need to run your code on HoloLens devices, you can upgrade your app to both Unity 2019.3+ and ARCore 3.0+, and this issue will go away. Instructions for doing so are posted here: https://github.com/Azure/azure-spatial-anchors-samples/issues/149

Bear in mind, though, that this configuration is still unsupported by Azure Spatial Anchors. As the link above mentions, we are working to find a solution. Until then, the configuration hasn't been heavily tested, so even without using HoloLens devices, there might be other issues lurking around.

**Comment by craigktreasure** [comment]
This has been resolved by moving to Unity 2019.4 with [2.4.0](https://github.com/Azure/azure-spatial-anchors-samples/releases/tag/v2.4.0).
