### ISSUE TITLE
CoarseReloc Sample fails with NearDeviceCriteria 

### ISSUE THREAD

**Issue by reneschulte** [Azure/azure-spatial-anchors-samples#87]
I've tried the latest sample commit a4e5e3a34d88f33775b4f5bb3024e0d20162b44b and all samples work fine except the Coarse Reloc one which seems to have some issue when trying to reloc the anchor.

See the screenshots when I was in Berlin it was a little cloudy and overcast but GPS with Maps worked fine.

For this one I created an anchor on the bench and tried to reloc it for a minute moving my phone (Samsung S8) around but no luck. Reloc with ID worked fine at that location, so I guess it is rather related to anchor Geo reloc.
![Screenshot_20191118-111322_ASA HelloAR U3D](https://user-images.githubusercontent.com/7439129/69050169-bd931700-0a01-11ea-9023-a92b9e1583a3.jpg)

This looks like an even worse issue that it might send too mnay requests under the hood and somehow causes an exception with throttling. 
I also tried increasing the value to 50 for nearDeviceCriteria.DistanceInMeters but it was still not able to use that. 
![Screenshot_20191118-112157_ASA HelloAR U3D](https://user-images.githubusercontent.com/7439129/69050280-f7fcb400-0a01-11ea-9afc-25e0c3e99e60.jpg)

**Comment by reneschulte** [comment]
Quick update. It seems to e related to the WiFi as LocationProvider which might be conflicting with the GPS. I disabled WiFi, so it's only using GPS and then it seems to work. 
locationProvider.Sensors.WifiEnabled = false;

**Comment by TobiasPott** [comment]
I can confirm that there seem to be an issue when GPS and Bluetooth are both enabled on the location provider. Doing so let both appear as missing provider on my Pixel XL 2 whereas when only GeoLocation is enabled the sensor state for GeoLocation is correct (green color)

When I try to confirm the same behaviour for WiFi only I cannot get it to report a valid state for WiFi sensor.

**Comment by pabusse** [comment]
We have deployed a fix for the first issue mentioned by @reneschulte. Thank you for your detailed report!

@TobiasPott Your issue appears to be separate and we will continue to track it in #88.

**Comment by reneschulte** [comment]
Thanks @pabusse 
I think this solved my issue! Tried it 5 times and it was smooth. 🙌
