### ISSUE TITLE
Android 7.0 support?

### ISSUE THREAD

**Issue by bertt** [Azure/azure-spatial-anchors-samples#89]
I'm trying to run the 2.0 Xamarin Android samples on Asus_002, Android 7.0, but get runtime error when hitting one of the buttons on main screen (basic demo/nearby demo/sharing/coarse reloc):

Java.Lang.NoSuchMethodError
  Message=No virtual method requireActivity()Landroid/support/v4/app/FragmentActivity; in class Lcom/google/ar/sceneform/ux/BaseArFragment; or its super classes (declaration of 'com.google.ar.sceneform.ux.BaseArFragment' appears in /data/app/SampleXamarin.Android-1/base.apk)

Before 2.0 the Xamarin Android demo did run fine on this phone. Google Play Services for AR is installed (version 1.13.xx).

The Unity3D samples for Android do work, only got a runtime crash on coarse relocation demo. 

Q: Is there a trick to get the Xamarin/Android demo working?

**Comment by bucurb** [comment]
It's probably [this](https://github.com/google-ar/sceneform-android-sdk/issues/129#issuecomment-415151687) issue. We're working on a fix and will get back to you ASAP.

**Comment by gllebede** [comment]
Hi @bertt 
I'm currently investigating the issue.

Unfortunately I didn't find an Android 7 phone to reproduce and fix the issue. I've tried an Android 7 emulator but if fails to show even the first menu with a different exception and it doesn't support OpenGL ES 3.0 so I can't test the coarse relocation demo on it at all.

> Before 2.0 the Xamarin Android demo did run fine on this phone
It looks to me that the uses-sdk android:minSdkVersion property of the sample was always set to "26". Did you change it to 24 to make the sample work with your device? Please tell me if you did any other tweaks to the sample so I can accurately reproduce the issue.

Cheers.

**Comment by bertt** [comment]
Hi @gllebede , I've tested it with latest release 2.1.1, now 3 demo's work only the last one (coarse reloc) crashes with message:

```
'12-17 16:19:34.302 F/art     (10935): art/runtime/runtime.cc:403]   (no managed stack frames)
12-17 16:19:34.304 F/libc    (10935): Fatal signal 6 (SIGABRT), code -6 in tid 10935 (Xamarin.Android)
 ```
In order to run the demo I've only changed the Minimum Android version to 24 (and of course changed AccountDetails.cs)

**Comment by darax** [comment]
hi @bertt, it sounds like the issue is resolved. If the the coarse reloc is still crashing in the latest release, please open a new issue.  Thanks!
