### ISSUE TITLE
NativeLibrary.ssc_cloud_spatial_anchor_session_create_anchor_async fails with unknown exception

### ISSUE THREAD

**Issue by Rufus1123** [Azure/azure-spatial-anchors-samples#90]
We are trying to run the HoloLens demo of the [SmartHotel360 demo](https://github.com/microsoft/SmartHotel360-MixedReality), but when trying to save a new anchor to Azure spatial anchors, it fails.
**Update** Also fails following the Android demo

The code:
```
    string message;
    string requestCorrelationVector;
    string responseCorrelationVector;

    status code = NativeLibrary.ssc_get_error_details(handle, out message, out requestCorrelationVector, out responseCorrelationVector);

    string fullMessage;
    if (code == status.Failed)
    {
        throw new InvalidOperationException("Unexpected error in exception handling.");
    }
    else if (code != status.OK)
    {
        fullMessage = "Exception thrown and an unexpected error in exception handling.";
    }
    else
    {
        fullMessage = message + ". Request CV: " + requestCorrelationVector + ". Response CV: " + responseCorrelationVector + ".";
    }

    switch (value)
    {
        case status.OK:
            return;
        case status.Failed:
            throw new InvalidOperationException(fullMessage);
        ...
    }
```
The code throws an exception at status.Failed with `fullMessage = 'Unknown exception. Request CV: . Response CV: .'`

We tried changing the SDK version to 10.0.17763.0, as recommended by https://github.com/Azure/azure-spatial-anchors-samples/issues/21, but that did not help.

Logging output from Visual Studio:
> DeviceChooserBinding::OnItemSelected - Room
>  
> (Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)
> 
> 
> DigitalTwinsChooser::OnDeviceChooserItemSelected
>  
> (Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)
> 
> 
> Starting the observer.
>  
> (Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)
> 
> 
> 'SmartHotel360 Facility Management.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\Microsoft.SmartHotelMRVS.Debug_x86.MyUserName\System.Collections.NonGeneric.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
> Input device 8 removed
> 
> 'SmartHotel360 Facility Management.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\Microsoft.SmartHotelMRVS.Debug_x86.MyUserName\System.Diagnostics.Tracing.dll'. Module was built without symbols.
> New input device (9): {"interface":"XRInputV1","type":"","product":"Spatial Controller - Left","manufacturer":"Microsoft","serial":"","version":"","capabilities":"{\"deviceName\":\"Spatial Controller - Left\",\"manufacturer\":\"Microsoft\",\"serialNumber\":\"\",\"deviceRole\":2,\"deviceId\":2,\"inputFeatures\":[{\"name\":\"CombinedTrigger\",\"usageHints\":[{\"content\":\"CombinedTrigger\",\"id\":2001351222}],\"featureType\":3,\"customSize\":4294967295},{\"name\":\"Joystick\",\"usageHints\":[{\"content\":\"Primary2DAxis\",\"id\":2655220405}],\"featureType\":4,\"customSize\":4294967295},{\"name\":\"Trigger\",\"usageHints\":[{\"content\":\"Trigger\",\"id\":2448783467}],\"featureType\":3,\"customSize\":4294967295},{\"name\":\"Grip\",\"usageHints\":[{\"content\":\"Grip\",\"id\":1590085501}],\"featureType\":3,\"customSize\":4294967295},{\"name\":\"Touchpad\",\"usageHints\":[{\"content\":\"Secondary2DAxis\",\"id\":708289259}],\"featureType\":4,\"customSize\":4294967295},{\"name\":\"Grip - Pressed\",\"usageHints\":[{\"content\":\"GripButton\",\"id\":518426673}],\"featureType\":1,\"customSize\":4294967295},{\"name\":\"Menu\",\"usageHints\":[{\"content\":\"MenuButton\",\"id\":2565854125}],\"featureType\":1,\"customSize\":4294967295},{\"name\":\"Joystick - Clicked\",\"usageHints\":[{\"content\":\"2DAxisClick\",\"id\":1986533019}],\"featureType\":1,\"customSize\":4294967295},{\"name\":\"Trigger - Pressed\",\"usageHints\":[{\"content\":\"TriggerButton\",\"id\":3798928494}],\"featureType\":1,\"customSize\":4294967295},{\"name\":\"Touchpad - Clicked\",\"usageHints\":[{\"content\":\"2DAxisTouch\",\"id\":2065899303}],\"featureType\":1,\"customSize\":4294967295},{\"name\":\"Touchpad - Touched\",\"usageHints\":[{\"content\":\"Thumbrest\",\"id\":4040714719}],\"featureType\":1,\"customSize\":4294967295},{\"name\":\"TrackingState\",\"usageHints\":[{\"content\":\"TrackingState\",\"id\":1636970542}],\"featureType\":2,\"customSize\":4294967295},{\"name\":\"IsTracked\",\"usageHints\":[{\"content\":\"IsTracked\",\"id\":1429429695}],\"featureType\":1,\"customSize\":4294967295},{\"name\":\"Device - Position\",\"usageHints\":[{\"content\":\"DevicePosition\",\"id\":3323297731}],\"featureType\":5,\"customSize\":4294967295},{\"name\":\"Device - Rotation\",\"usageHints\":[{\"content\":\"DeviceRotation\",\"id\":3528255621}],\"featureType\":6,\"customSize\":4294967295},{\"name\":\"Device - Velocity\",\"usageHints\":[{\"content\":\"DeviceVelocity\",\"id\":1066346694}],\"featureType\":5,\"customSize\":4294967295},{\"name\":\"Device - AngularVelocity\",\"usageHints\":[{\"content\":\"DeviceAngularVelocity\",\"id\":2550892527}],\"featureType\":5,\"customSize\":4294967295}]}"}
> 
> The thread 0x15b0 has exited with code 0 (0x0).
> The thread 0x11d0 has exited with code 0 (0x0).
> Exception thrown: 'System.InvalidOperationException' in Assembly-CSharp.dll
> An exception of type 'System.InvalidOperationException' occurred in Assembly-CSharp.dll but was not handled in user code
> Unknown exception. Request CV: . Response CV: .

**Update 2**
We have verified that the mixed reality appservice in Azure receives calls from the HoloLens/Android app and that it returns a valid token. 
Android Studio logs below:

> I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
>     (HTTPLog)-Static: isSBSettingEnabled false
> W/ft.SmartHotelM: Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (light greylist, reflection)
>     Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (light greylist, reflection)
>     Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (light greylist, reflection)
> W/ft.SmartHotelM: Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setAlpnProtocols([B)V (light greylist, reflection)
> W/ft.SmartHotelM: Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->getAlpnSelectedProtocol()[B (light greylist, reflection)
> D/CBindingAutoGen: exception causing failure: std::exception
> E/Unity: AnchorManager::AddPhysicalVisualizerAnchor - Failed to save anchor std::exception. Request CV: . Response CV: .
>      
>     (Filename: ./Runtime/Export/Debug.bindings.h Line: 45) 
> I/native: cloud_anchor_manager.cc:372 Anchor Hosting is not configured.
> I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
>     (HTTPLog)-Static: isSBSettingEnabled false
> I/native: viwls_optimization.cc:987 Run Lite-COM for the map optimization.
> I/native: viwls_optimization.cc:833 MAP SOLVE: USER_SUCCESS
> I/native: visual_inertial_wls.cc:250 online_viwls_solve_time in seconds = 0.295026 solve_time_counter_ = 0
> I/native: vio_fault_detector.cc:393 VIO did not use vision constraints.

**Comment by Rufus1123** [comment]
We have identified one possible issue in our sample. The sample was still pointing to an old api:
`https://mrc-auth-prod.trafficmanager.net/Accounts/{spatialAnchorsAccountId}/token`
whereas this should be:
`https://sts.mixedreality.azure.com/Accounts/{spatialAnchorsAccountId}/token`
The former is very unreliable. It only responded with a token three times out of many requests.
Unfortunately, we still get the same error. We're investigating if our Spatial Anchors SDK in the sample project is just out-dated. From the looks of it, the Spatial Anchors 1.x.x is not compatible with 2.0.0.

**Comment by julianparismorgan** [comment]
Hi @Rufus1123, is everything working if you move to the latest SDK?
