### ISSUE TITLE
Buttons not visible on Xamarin IOS

### ISSUE THREAD

**Issue by bertt** [Azure/azure-spatial-anchors-samples#91]
I'm trying to run the samples Xamarin IOS samples (on IPad Pro), but the buttons are not visible when camera is visible (only buttons 'exit demo' on top left). See attached (bit vague) screenshot.
![P_20191126_100139](https://user-images.githubusercontent.com/538812/69615126-afae4900-1034-11ea-9e49-29decae60d7b.jpg)

**Comment by weinanshen** [comment]
Hi @bertt, it should be a UI bug in the sample. We will get back to you when we have a fix. Thanks!

**Comment by craigktreasure** [comment]
This issue should be resolved with the 2.4.0 samples.
