### ISSUE TITLE
get ASAWifiStatusResult.noAccessPointsFound on iOS 13

### ISSUE THREAD

**Issue by skypu3** [Azure/azure-spatial-anchors-samples#96]
Hi,

I enabled the wifi capability, and can get SSID from the code
`guard let ssid = info[kCNNetworkInfoKeySSID as String] as? String else {
                return nil
            }`

But I still get unavailable status from wifiSignalStatus, do you know the reason ?

**Comment by bucurb** [comment]
Yes, unfortunately WiFi signal strength cannot be recovered on iOS so I'm afraid you won't be able to use WiFi as sensor data on that platform. You're right that you can retrieve the SSID you're connected to but that is not enough for us to place and recover anchors with WiFi. You might consider trying out Bluetooth beacons if you're targeting indoor scenarios with iOS.

**Comment by yosun** [comment]
Which bluetooth beacon devices have you tried it with for Unity/iOS

**Comment by bucurb** [comment]
It should just work with iBeacons and Eddystone UIDs regardless of manufacturer. Have you tried a specific manufacturer and were not able to get it working?
