### ISSUE TITLE
All the images under 'android-logos' folders are broken

### ISSUE THREAD

**Issue by clifflinmao** [Azure/azure-spatial-anchors-samples#97]
In the lasted version, all the images under 'android-logos' folders are broken, which results in error in Unity (but can be ignored).

**Comment by weinanshen** [comment]
Hi @clifflinmao, what version of Unity are you using?

Options to try:
1. Reimport the asset
2. Reclone the sample repo

Thanks!

**Comment by clifflinmao** [comment]
It 's not about Unity, just try cloning or downloading the sample project, open the images under \azure-spatial-anchors-samples\Unity\Assets\android-logos, all of them are broken.

**Comment by clifflinmao** [comment]
even from the size it obviously much smaller than before.

**Comment by clifflinmao** [comment]
![image_error](https://user-images.githubusercontent.com/57075803/70128229-2c6ca300-1685-11ea-98e2-436433258c4d.png)

**Comment by GooDtoLivE** [comment]
The same issue occurred in my unity project developed by MRTK2.0, Did you fix that?

**Comment by craigktreasure** [comment]
Sorry about this everyone. We're now using Git LFS for a few more file types in our sample repo.

Follow these instructions to get fixed up:
  - Install [Git LFS](https://git-lfs.github.com/)
  - Run `git lfs install`.
  - If you previously cloned the samples repository before installing and configure Git LFS, you'll also need to run the following from the repository:
    - `git lfs pull`

**Comment by craigktreasure** [comment]
Closing this now. Feel free to re-open for further related discussion.

**Comment by ibsusu** [comment]
Can you please put this in the readme?

**Comment by msftradford** [comment]
Thanks for the feedback @ibsusu! This change be included in the next samples update.
