### ISSUE TITLE
Public Development? 

### ISSUE THREAD

**Issue by bertt** [Azure/azure-spatial-anchors-samples#99]
Why are you developing these samples on some private repository and do public releases only? Let's develop it here in public, its more fun for everyone.

**Comment by Alberto-Vega-MSFT** [comment]
Adding @julianparismorgan @vriveras @craigktreasure

**Comment by craigktreasure** [comment]
Hey @bertt. Thanks for the feedback. We like the idea and will consider it in the future. Likely not until after ASA goes GA as it is now public preview. That being said, we're happy to consider PRs from the public on this repository now. Don't let our private repository get in the way of you having fun 😉.
